### ISSUE TITLE
GENIVI git repos out of sync

### ISSUE THREAD

**Issue by jeremiah** [smartdevicelink/sdl_core#10]
Hi,

The last commit I have from the smartdevicelink repo in GENIVI is from June; http://git.projects.genivi.org/?p=smartdevicelink.git;a=summary

This seems to imply that the GENIVI git repos for SDL have gone out of sync. This might mean that if there are people only following the GENIVI repos, then they will be following an older code base which might contain bugs and likely won't contain the latest and greatest. Also, there may be licenses and other collateral that might be out of date or inaccurate.

I think we should either sync up the GENIVI repos so that they are a mirror of what is pushed to github, or we should deprecate the GENIVI repos altogether. The current situation is confusing for SDL users and for GENIVI since we get questions about SDL that we can't really answer.

What do you folks think?

**Comment by justinjdickow** [comment]
As of today, the GENIVI repos are now mirrored from GitHub - Refs included. Still working on a way of automating the mirror, but I will keep them up to date for now and I believe this warrants closing this issue.

For reference the genivi repos are:

  * [Core](http://git.projects.genivi.org/?p=smartdevicelink.git;a=summary)
  * [Android](http://git.projects.genivi.org/?p=smartdevicelink_android.git;a=summary)
  * [iOS](http://git.projects.genivi.org/?p=smartdevicelink_ios.git;a=summary)
