### ISSUE TITLE
[SDL4.0]SDL does not create icons folder in case it was removed after SDL start

### ISSUE THREAD

**Issue by DrachenkoAnastasiia** [smartdevicelink/sdl_core#1003]
## Occurrence
Always

## Preconditions
SDL4.0 feature is enabled in .ini file, ' Icons' values is set as AppIconsFolder value, SDL and HMI are started. Icons folder is created.

## Steps to reproduce
1. Remove Icons folder.
2. Register app via 4th protocol, app is set icon.

## Actual result
SDL does not create Icons folder.

## Expected result
SDL creates Icons folder to save icon for registered app.

# Environment
SDL:
Repository: https://github.com/smartdevicelink/sdl_core/
Tag: 4.2.0
commit: a6c32b45832653d6b851be9b19355fa35f377e07
ATF version: 2.2 / 962e1eff8664d97a 

# Attachments:
[att_issue#1003.zip](https://github.com/smartdevicelink/sdl_core/files/576156/att_issue.1003.zip)

# Expected delivery   
- [ ] Source code updates 
- [ ] Code comments 
- [ ] UTs add/update 
- [x] ATF tests add/update ***(not required)***  
- [x] Manual tests ***(not required)*** 
- [x] Add/update CI plans/jobs ***(not required)***  
- [x] SDD updates ***(not required)***  
- [x] Guidelines update ([sdl_core_guides](https://github.com/smartdevicelink/sdl_core_guides)) ***(not required)***  
- [x] Guidelines update ([sdl_hmi_integration_guidelines](https://github.com/smartdevicelink/sdl_hmi_integration_guidelines))  ***(not required)***

**Comment by vvvakulenko** [comment]
**Reproducible**
SDL: HEAD of https://github.com/smartdevicelink/sdl_core/tree/feature/extended_policy_functionality 
(commit d5f63b4f66d9ab945d452dfb1c07bf7ee3ca781e)
ATF: HEAD of https://github.com/smartdevicelink/sdl_atf/tree/develop
(commit aa5beae6ab1726a9b43ed2fa15f66c20d7f7883f)

**Comment by LitvinenkoIra** [comment]
Priority Low.
Loss of functionality in specific case.

**Comment by iCollin** [comment]
Closed via #3359
