### ISSUE TITLE
[Policies] Ford-specific keys are present in Genivi Policy DB - DeviceData

### ISSUE THREAD

**Issue by DrachenkoAnastasiia** [smartdevicelink/sdl_core#1007]
## Occurrence
Always

## Preconditions
1. Policy DB is absent on FS.

## Steps to reproduce
1. Start SDL

## Actual result
SDL creates DB, table "device" contains Ford-specific keys like "hardware", "firmware_rev" etc.

## Expected result
"DeviceData" secition is Ford-specific.

_**Note:**_ device_consent_group and consent_group also are present in the Genivi Policy DB.

# Environment
SDL repo: https://github.com/smartdevicelink/sdl_core.git
SDL branch: master
SDL commit: a6c32b4
HMI: https://github.com/LuxoftSDL/sdl_hmi: 01cb5b49883ed6288e34fcf7db24fd0439d08312
OS: Ubuntu 14.04 LTS

# Attachments
[att_issue#1007.zip](https://github.com/smartdevicelink/sdl_core/files/576181/att_issue.1007.zip).

# Expected delivery   
- [ ] Source code updates 
- [ ] Code comments 
- [ ] UTs add/update 
- [x] ATF tests add/update ***(not required)***  
- [x] Manual tests ***(not required)*** 
- [x] Add/update CI plans/jobs ***(not required)***  
- [x] SDD updates ***(not required)***  
- [x] Guidelines update ([sdl_core_guides](https://github.com/smartdevicelink/sdl_core_guides)) ***(not required)***  
- [x] Guidelines update ([sdl_hmi_integration_guidelines](https://github.com/smartdevicelink/sdl_hmi_integration_guidelines))  ***(not required)***

**Comment by jacobkeeler** [comment]
@DrachenkoAnastasiia @LuxoftAKutsan The issue that this describes still occurs, but I'm not certain that it was ever incorrect behavior in the first place.

**Comment by dboltovskyi** [comment]
@jacobkeeler 
The defect was raised a quite a long time ago - in Dec-2015.
And at that date SDL had own PTU flow, but anyway Policy database contained redundand Ford-specific fields.
However in Feb-2017 SDL was extended with new EXTERNAL_PROPRIETARY flow functionality.
And this supposes presence of Ford-specific keys in Policy database.

So for now this issue is not actual.

**Comment by LuxoftAKutsan** [comment]
```SDL creates DB, table "device" contains Ford-specific keys like "hardware", "firmware_rev" etc.```
When Extended policy was not in open source , keys "hardware", "firmware_rev" etc...  shouldn't be there.
But extended policy functionality is actually adding this keys.
Thats why this defect is not actual after merging Extended policy functionality
