### ISSUE TITLE
SDL doesn't add device identifier to Policy DB and not present in the snapshot

### ISSUE THREAD

**Issue by DrachenkoAnastasiia** [smartdevicelink/sdl_core#1008]
**Occurrence:**
Always

**Steps to reproduce:**
1. Start SDL

**Actual result:**
SDL created redundant table in Policy DB (data_consent) and device
{device identifier} is not present in the Snapshot

**Expected result:**
SDL shloud create only needed tables and device{device identifier}
is present in the Snapshot

**Environment:**
SDL:
sdl_repository = "https://github.com/smartdevicelink/sdl_core/"
sdl_branch = "release/4.2.0", commit fc832c7a7ae
SDL created redundant table in Policy DB (data_consent) - NOK, redundant table device_consent_group present now
device
{device identifier}
is present in the Snapshot -OK
Files added:
policy.sqlite and sdl_snapshot.json (15 kB)

**Attachments:**
[att_issue#1008.zip](https://github.com/smartdevicelink/sdl_core/files/576186/att_issue.1008.zip)

**Comment by JackLivio** [comment]
Non reproducible on master
