### ISSUE TITLE
Communication is not saved in SmartDeviceLinkCore.log after adding persistent data after SUSPEND

### ISSUE THREAD

**Issue by DrachenkoAnastasiia** [smartdevicelink/sdl_core#1011]
## Occurrence
Always

## Preconditions
1. Core, HMI started.
2. Application is registered, HMI level = FULL.

## Steps to reproduce
1. Add some data, e.g. AddCommand.
2. Send OnExitAllApplications(SUSPEND).
3. Add persistent data. 
4. Send OnExitAllApplications(IGNITION_OFF).

## Actual result
In SmartDeviceLinkCore.log times after BasicCommunication.OnExitAllApplications("SUSPEND") has 1 sec difference.

See in attached logs DifferentTimestamps.7z:
ATF_No_Resumption_PersistentData_20161107162718.txt:
HMI->SDL(16:27:55) : {"params":
{"reason":"IGNITION_OFF"}
,"method":"BasicCommunication.OnExitAllApplications","jsonrpc":"2.0"}
SDL->HMI(16:27:55) : {"id":119,"jsonrpc":"2.0","method":"BasicCommunication.UpdateAppList","params":{"applications":[]}}
SDL->HMI(16:27:55) : {"jsonrpc":"2.0","method":"BasicCommunication.OnAppUnregistered","params":{"appID":813718822,"unexpectedDisconnect":true}}
SDL->HMI(16:27:55) : {"jsonrpc":"2.0","method":"BasicCommunication.OnSDLClose","params":{}}

SmartDeviceLinkCore.log:
**BasicCommunication.OnExitAllApplications(IGNITION_OFF) - Not observed at all**
16:27:54,241: BasicCommunication.UpdateAppList
16:27:54,242: BasicCommunication.OnAppUnregistered
16:27:54,270: BasicCommunication.OnSDLClose

Can be reproduced with:
[test script](https://github.com/CustomSDL/sdl_atf_test_scripts/blob/develop/test_scripts/Resumption/ATF_No_Resumption_PersistentData.lua).

## Expected result
1. In log of SmartDeviceLinkCore.log and in ATF log timestamps should be equal

# Environment

SDL repo: https://github.com/smartdevicelink/sdl_core/
SDL branch: a6c32b45832653d6b851be9b19355fa35f377e07
HMI: HTML5
ATF version: 2.2
ATF repo: https://github.com/smartdevicelink/sdl_atf/
ATF branch: 962e1eff8664d97af5e59ec4e22f39b9ea76f5eb
Scripts repo: https://github.com/CustomSDL/sdl_atf_test_scripts/tree/OS_DRAFT
Scripts branch: 18cce42
OS: Ubuntu 14.04.01
Transport: Wi-Fi
Mobile device: -
Mobile OS: -
Mobile App version: -
Mobile App type (media/non-media/navi/any): any
Virtual Machine using (yes/no): no

# Attachments
[att_issue#1011.zip](https://github.com/smartdevicelink/sdl_core/files/576203/att_issue.1011.zip)

# Expected delivery   
- [ ] Source code updates 
- [ ] Code comments 
- [ ] UTs add/update 
- [x] ATF tests add/update ***(not required)***  
- [x] Manual tests ***(not required)*** 
- [x] Add/update CI plans/jobs ***(not required)***  
- [x] SDD updates ***(not required)***  
- [x] Guidelines update ([sdl_core_guides](https://github.com/smartdevicelink/sdl_core_guides)) ***(not required)***  
- [x] Guidelines update ([sdl_hmi_integration_guidelines](https://github.com/smartdevicelink/sdl_hmi_integration_guidelines))  ***(not required)***

**Comment by JackLivio** [comment]
I don't think this is a bug?
