### ISSUE TITLE
Response to UI.ScrollableMessage is sent twice to app if no HMI response HMI during <DefaultTimeout> 

### ISSUE THREAD

**Issue by DrachenkoAnastasiia** [smartdevicelink/sdl_core#1014]
## Occurrence
Always

## Preconditions
1. SDL and HMI are started
2. HMI is initialized and didn't respond on UI.IsReady:
SDL -> HMI: UI.IsReady
HMI -> SDL: HMI didn't repond to UI.IsReady 

## Steps to reproduce
1. App is registered
2. App sends to SDL single UI.Slider => SDL resends it, but no HMI response comes.
```
    ===== TC_ScrollableMessage_Only__Case_1_IsReady_HMI_Does_Not_Respond :
    MOB->SDL (14:33:54) [version: 2, frameType: 1, encryption: false, serviceType: 7, frameInfo: 0, messageId: 17] : {"scrollableMessageBody":"abc","softButtons":[{"text":"Button1","isHighlighted":false,"type":"IMAGE","softButtonID":1,"image":
    Unknown macro: {"value"}

    ,"systemAction":"DEFAULT_ACTION"}],"timeout":5000}
    SDL->HMI(14:33:54) : {"id":43,"jsonrpc":"2.0","method":"UI.ScrollableMessage","params":{"appID":118713057,"messageText":
    Unknown macro: {"fieldName"}

    ,"softButtons":[{"image":
    Unknown macro: {"imageType"}
    ,"isHighlighted":false,"softButtonID":1,"systemAction":"DEFAULT_ACTION","type":"IMAGE"}],"timeout":5000}}

    SDL->MOB(14:33:59) [version: 2, frameType: 1, encryption: false, serviceType: 7, frameInfo: 0, messageId: 18] :
    Unknown macro: {"success"}

    SDL->MOB(14:33:59) [version: 2, frameType: 1, encryption: false, serviceType: 7, frameInfo: 0, messageId: 19] :
    Unknown macro: {"success"} 
```
## Actual result
SDL sends respons twice to App for this RPC.

## Expected result
SDL must respond with "GENERIC_ERROR, success:false" in case HMI does NOT respond during `<DefaultTimeout>`.

_**Note:**_ Issue could be reproduced by ATF:
1. Put to user_modules in test_run folder of ATF build attached files: ATF_Interface_IsReady_missing_SingleRPC_Template.lua, Interfaces_RPC.lua, isReady.lua.
2. In test_scripts folder in sdl_atf_test_scripts folder of ATF build put ATF_UI_IsReady_missing_SingleRPC_empty.lua.

# Environment
SDL repo: https://github.com/smartdevicelink/sdl_core.git
SDL branch: master
SDL commit: a6c32b4
HMI: https://github.com/LuxoftSDL/sdl_hmi: 01cb5b49883ed6288e34fcf7db24fd0439d08312
OS: Ubuntu 14.04 LTS

# Attachments
[att_issue#1014.zip](https://github.com/smartdevicelink/sdl_core/files/576217/att_issue.1014.zip).

# Expected delivery   
- [ ] Source code updates 
- [ ] Code comments 
- [ ] UTs add/update 
- [x] ATF tests add/update ***(not required)***  
- [x] Manual tests ***(not required)*** 
- [x] Add/update CI plans/jobs ***(not required)***  
- [x] SDD updates ***(not required)***  
- [x] Guidelines update ([sdl_core_guides](https://github.com/smartdevicelink/sdl_core_guides)) ***(not required)***  
- [x] Guidelines update ([sdl_hmi_integration_guidelines](https://github.com/smartdevicelink/sdl_hmi_integration_guidelines))  ***(not required)***

**Comment by VVeremjova** [comment]
Updated script ATF_Interface_IsReady_missing_SingleRPC_Template.lua 
[ATF_Interface_IsReady_missing_SingleRPC_Template.lua.tar.gz](https://github.com/smartdevicelink/sdl_core/files/852279/ATF_Interface_IsReady_missing_SingleRPC_Template.lua.tar.gz)
After updating defect is not reproduced on commit 65ade78808a37560c1a55de058201a10296f14d1, branch feature/extended_policy_functionality
