### ISSUE TITLE
SDL doesn't send info parameter when result of ResetGlobalProperties is GENERIC_ERROR

### ISSUE THREAD

**Issue by KhrystynaDubovyk** [smartdevicelink/sdl_core#1016]
## Occurrence
Always.

## Preconditions
1. HMI and SDL are running.
2. Register a new application.
3. Send ResetGlobalProperties from mobile:
-> SDL sends to HMI UI.SetGlobalProperties request - OK
-> SDL sends to HMI TTS.SetGlobalProperties request - OK

## Steps to reproduce
1. Do not send HMI response of UI.SetGlobalProperties OR TTS.SetGlobalProperties OR to both.
2. Wait timeout of RPC to expire.

## Expected result
According to requirement:

>In case SDL splits the request from mobile app to one and/or more HMI interfaces
and at least one of the interfaces does not respond during SDL`s watchdog (important note: this component is working and has responded to previous RPCs),
SDL must:
return "GENERIC_ERROR, success: false" result to mobile app
include appropriate description into "info" parameter.
Information: template for "info" parameter in terms of the requirement: "'%interface-name%' component does not respond". (interface - UI, TTS, VR, Navigation, Buttons)

SDL shall return to mobile "GENERIC_ERROR, success: false" with "info" parameter in terms of the requirement: "'%component-name%' component does not respond".

## Actual result
SDL returns to mobile "GENERIC_ERROR, success: false" WITHOUT "info parameter".

# Environment
SDL branch: a6c32b45832653d6b851be9b19355fa35f377e07
HMI: HTML5
ATF version: 2.2
ATF repo: https://github.com/smartdevicelink/sdl_atf/
ATF branch: 962e1eff8664d97af5e59ec4e22f39b9ea76f5eb
Scripts repo: https://github.com/CustomSDL/sdl_atf_test_scripts/tree/OS_DRAFT
Scripts branch: 18cce42
OS: Ubuntu 14.04.01
Transport: Wi-Fi
Mobile device: -
Mobile OS: -
Mobile App version: -
Mobile App type (media/non-media/navi/any): any
Virtual Machine using (yes/no): no

# Attachments
[ayy_issue#1016.zip](https://github.com/smartdevicelink/sdl_core/files/576253/ayy_issue.1016.zip)

# Expected delivery   
- [ ] Source code updates 
- [ ] Code comments 
- [ ] UTs add/update 
- [x] ATF tests add/update ***(not required)***  
- [x] Manual tests ***(not required)*** 
- [x] Add/update CI plans/jobs ***(not required)***  
- [x] SDD updates ***(not required)***  
- [x] Guidelines update ([sdl_core_guides](https://github.com/smartdevicelink/sdl_core_guides)) ***(not required)***  
- [x] Guidelines update ([sdl_hmi_integration_guidelines](https://github.com/smartdevicelink/sdl_hmi_integration_guidelines))  ***(not required)***

**Comment by jacobkeeler** [comment]
Fixed with the merge of #1640
