### ISSUE TITLE
[API] SDL sends BC.UpdateDeviceList with out of upper bound size of deviceList

### ISSUE THREAD

**Issue by OVikhrov** [smartdevicelink/sdl_core#1019]
## Occurrence
Always.

## Preconditions
SDL and HMI are started.

## Steps to reproduce
1. Connect 101 device

## Expected result
SDL sends BC.UpdateDeviceList with 100 devices

## Actual result 
SDL sends BC.UpdateDeviceList with 101 devices

**Note:** 
To reproduce defect using ATF extract attached files in 'ATF_build' and execute updateDeviceList_with_101_device.lua script.

# Environment
Release: 4.2.0 (master marge)
Repository: https://github.com/smartdevicelink/sdl_core
Commit: a6c32b45832653d6b851be9b19355fa35f377e07

# Attachments
[att_issue#1019.zip](https://github.com/smartdevicelink/sdl_core/files/576402/att_issue.1019.zip).

# Expected delivery   
- [ ] Source code updates 
- [ ] Code comments 
- [ ] UTs add/update 
- [x] ATF tests add/update ***(not required)***  
- [x] Manual tests ***(not required)*** 
- [x] Add/update CI plans/jobs ***(not required)***  
- [x] SDD updates ***(not required)***  
- [x] Guidelines update ([sdl_core_guides](https://github.com/smartdevicelink/sdl_core_guides)) ***(not required)***  
- [x] Guidelines update ([sdl_hmi_integration_guidelines](https://github.com/smartdevicelink/sdl_hmi_integration_guidelines))  ***(not required)***

**Comment by jacobkeeler** [comment]
Fixed with the merge of #1634
