### ISSUE TITLE
[Policy]: SDL does not set "timeout" for OnSystemRequest with url

### ISSUE THREAD

**Issue by OVikhrov** [smartdevicelink/sdl_core#1021]
## Occurrence
Always.

## Preconditions
1. SDL built with DEXTENDED_POLICY: OFF
2. Core, HMI started.
3. SPT is configured to send attached PTU - PTFromCloud_smoke%20test__2.json.

## Steps to reproduce
1. Register App with appID "584421907".

## Actual result
After Registration app SDL triger PTU and send to mobile OnSystemRequest
{ "fileType" : "BINARY", "requestType" : "HTTP", "url" : "http://policies.telematics.*.com/api/policies" }
without timeout parameter.

## Expected result
timeout parameter is required if a URL is provided.

# Environment
Release: 4.2.0 (master marge)
Repository: https://github.com/smartdevicelink/sdl_core
Commit: a6c32b45832653d6b851be9b19355fa35f377e07
OS: Ubuntu 14.04 
Transport: WiFi 
App type: navi
App: Luxoft SPT
Device: HTC One

# Attachments
[att_issue#1021.zip](https://github.com/smartdevicelink/sdl_core/files/576419/att_issue.1021.zip)

# Expected delivery   
- [ ] Source code updates 
- [ ] Code comments 
- [ ] UTs add/update 
- [x] ATF tests add/update ***(not required)***  
- [x] Manual tests ***(not required)*** 
- [x] Add/update CI plans/jobs ***(not required)***  
- [x] SDD updates ***(not required)***  
- [x] Guidelines update ([sdl_core_guides](https://github.com/smartdevicelink/sdl_core_guides)) ***(not required)***  
- [x] Guidelines update ([sdl_hmi_integration_guidelines](https://github.com/smartdevicelink/sdl_hmi_integration_guidelines))  ***(not required)***

**Comment by JackLivio** [comment]
@mghiumiusliu If this issue is scoped to be fixed as part of an upcoming release could you please add the appropriate milestone?
