### ISSUE TITLE
Incorrect Version of API in MOBILE_API.xml

### ISSUE THREAD

**Issue by Itileda** [smartdevicelink/sdl_core#1022]
**Precondition**
build SDL

**Actions**
look through MOBILE_API.xml

**Actual result**
"Ford Sync RAPI" version="4.1"

**Expected result**
due to CRQ "Ford Sync RAPI" version should be "4.2"

**Environment**
SDL branch: release/4.2.0
SDL commit: fa05b5f5b1af6fae7d684a5cc156ec2e68dbc197

**Comment by JackLivio** [comment]
This has been fixed on master
