### ISSUE TITLE
[Policies] SDL doesn't exclude messages from snapshot

### ISSUE THREAD

**Issue by Itileda** [smartdevicelink/sdl_core#1023]
## Occurrence
Always.

## Preconditions
SDL is built with Flag ENABLE_EXTENDED_POLICY = ON. SDL and HMI are started.
SPT is configured to send PTFromCloud_smoke test.json (attached) as reply to SDL's OnsyustemRequest. To do it
1. Place PTFromCloud_smoke test.json to sdcard
2. Start SPT (SDL is not started), click AddSession
3. Goto Menu > Set up Policy files
4. in case of Ubuntu SDL is under testing, check the checkbox "Override Policy Table Update data" and provide path to uploaded json on sdcard.
in case of HeadUnit SDL is under testing, uncheck allcheckboxes

## Steps to reproduce
Register App:
appName: SyncProxyTester Null
appID: 584421907

## Expected result
After registration SDL starts PTU sequence and creates snapshot of policies database with removed "messages" sub-section from "consumer_friendly_messages".

## Actual result
SDL does not remove "messages" sub-section

# Environment
SDL branch: release/4.2.0
SDL commit: fa05b5f5b1af6fae7d684a5cc156ec2e68dbc197
HMI: HTML5
ATF version: commit 962e1e
OS: Ubuntu 14.04 LTS
App version: - 2.1.73
App type: - SPT

# Attachments
[att_iss#1023.zip](https://github.com/smartdevicelink/sdl_core/files/576425/att_iss.1023.zip)
[PTFromCloud_smoke_test_json.zip](https://github.com/smartdevicelink/sdl_core/files/933059/PTFromCloud_smoke_test_json.zip)

# Expected delivery   
- [ ] Source code updates 
- [ ] Code comments 
- [ ] UTs add/update 
- [x] ATF tests add/update ***(not required)***  
- [x] Manual tests ***(not required)*** 
- [x] Add/update CI plans/jobs ***(not required)***  
- [x] SDD updates ***(not required)***  
- [x] Guidelines update ([sdl_core_guides](https://github.com/smartdevicelink/sdl_core_guides)) ***(not required)***  
- [x] Guidelines update ([sdl_hmi_integration_guidelines](https://github.com/smartdevicelink/sdl_hmi_integration_guidelines))  ***(not required)***

**Comment by JackLivio** [comment]
@mghiumiusliu If this issue is scoped to be fixed as part of an upcoming release could you please add the appropriate milestone?
