### ISSUE TITLE
Policies Manager does not revert the Local Policy Table to the Preload Policy Table upon FACTORY Reset

### ISSUE THREAD

**Issue by Itileda** [smartdevicelink/sdl_core#1024]
## Occurrence
Always.

## Preconditions
SDL is built with Flag ENABLE_EXTENDED_POLICY = ON. SDL and HMI are started.

## Steps to reproduce
1. Select FACTORY _DEFAULT in ExitApplication on HMI.

## Expected result
Policies Manager reverts the Local Policy Table to the Preload Policy Table upon FACTORY Reset

## Actual result
PT is not reverted.

# Environment
SDL repo: https://github.com/smartdevicelink/sdl_core.git
SDL branch: master
SDL commit: a6c32b4
HMI: https://github.com/LuxoftSDL/sdl_hmi: 01cb5b49883ed6288e34fcf7db24fd0439d08312
OS: Ubuntu 14.04 LTS

# Attachments
[att_iss#1024.zip](https://github.com/smartdevicelink/sdl_core/files/576428/att_iss.1024.zip)

# Expected delivery   
- [ ] Source code updates 
- [ ] Code comments 
- [ ] UTs add/update 
- [x] ATF tests add/update ***(not required)***  
- [x] Manual tests ***(not required)*** 
- [x] Add/update CI plans/jobs ***(not required)***  
- [x] SDD updates ***(not required)***  
- [x] Guidelines update ([sdl_core_guides](https://github.com/smartdevicelink/sdl_core_guides)) ***(not required)***  
- [x] Guidelines update ([sdl_hmi_integration_guidelines](https://github.com/smartdevicelink/sdl_hmi_integration_guidelines))  ***(not required)***

**Comment by JackLivio** [comment]
@mghiumiusliu If this issue is scoped to be fixed as part of an upcoming release could you please add the appropriate milestone?
