### ISSUE TITLE
[Genivi] SDL do not disallow API of revoked App.

### ISSUE THREAD

**Issue by OVikhrov** [smartdevicelink/sdl_core#1025]
## Occurrence
Always.

## Preconditions
1. Core, HMI started 1st time.

## Steps to reproduce
1. Register App.
2. Initiate PTU, after which App will be revoked (<appID>:null).
3. Reregister App, send Show request.

## Actual result
API processed correctly to HMI.

## Expected result
SDL should disallow all APIs for revoked App.

# Environment
Release: 4.2.0 (master marge)
Repository: https://github.com/smartdevicelink/sdl_core
Commit: a6c32b45832653d6b851be9b19355fa35f377e07
OS: Ubuntu 14.04 
Transport: WiFi 
App type: navi
App: Luxoft SPT
Device: HTC One

# Expected delivery   
- [ ] Source code updates 
- [ ] Code comments 
- [ ] UTs add/update 
- [x] ATF tests add/update ***(not required)***  
- [x] Manual tests ***(not required)*** 
- [x] Add/update CI plans/jobs ***(not required)***  
- [x] SDD updates ***(not required)***  
- [x] Guidelines update ([sdl_core_guides](https://github.com/smartdevicelink/sdl_core_guides)) ***(not required)***  
- [x] Guidelines update ([sdl_hmi_integration_guidelines](https://github.com/smartdevicelink/sdl_hmi_integration_guidelines))  ***(not required)***

**Comment by JackLivio** [comment]
@mghiumiusliu If this issue is scoped to be fixed as part of an upcoming release could you please add the appropriate milestone?
