### ISSUE TITLE
[Policy]: SDL does not write UserFriendlyMessages to DB

### ISSUE THREAD

**Issue by OVikhrov** [smartdevicelink/sdl_core#1027]
## Occurrence
Always.

## Preconditions
1. SDL built with DEXTENDED_POLICY: ON.
2. First SDL life cycle.

## Steps to reproduce
1. Start SDL.
2. Register app and perform PTU.

## Actual result
During PTU HMI sends GetUserFriendlyMessage to SDL but SDL responds "messages":[
{"messageCode":"StatusPending"}
] where "messages" is re-sent part of request. UserFriendlyMessage are absent in DB.

## Expected result
SDL should write UserFriendlyMessage to DB and correctly respond to HMI GetUserFriendlyMessage request.

# Environment
SDL: https://github.com/smartdevicelink/sdl_core.git: a6c32b45832653d6b851be9b19355fa35f377e07
ATF: https://github.com/smartdevicelink/sdl_atf.git: 962e1eff8664d97af5e59ec4e22f39b9ea76f5eb
OS: Ubuntu 14.04 LTS

# Attachments
[att_issue#1027.zip](https://github.com/smartdevicelink/sdl_core/files/576436/att_issue.1027.zip).

# Expected delivery   
- [ ] Source code updates 
- [ ] Code comments 
- [ ] UTs add/update 
- [x] ATF tests add/update ***(not required)***  
- [x] Manual tests ***(not required)*** 
- [x] Add/update CI plans/jobs ***(not required)***  
- [x] SDD updates ***(not required)***  
- [x] Guidelines update ([sdl_core_guides](https://github.com/smartdevicelink/sdl_core_guides)) ***(not required)***  
- [x] Guidelines update ([sdl_hmi_integration_guidelines](https://github.com/smartdevicelink/sdl_hmi_integration_guidelines))  ***(not required)***

**Comment by JackLivio** [comment]
@mghiumiusliu If this issue is scoped to be fixed as part of an upcoming release could you please add the appropriate milestone?

**Comment by jacobkeeler** [comment]
Fixed with the merge of #1615
