### ISSUE TITLE
[Memory leaks]: SDL does not release memory after sending AddCommand limit exhausted

### ISSUE THREAD

**Issue by Itileda** [smartdevicelink/sdl_core#1029]
## Occurrence
Always.

## Preconditions
1. Core, HMI started.

## Steps to reproduce
1. Register and activate app.
2. Execute AddCommand_limitExhausted.xml (attached).

## Actual result
After finishing test SDL does not release memory (see screenshots).

## Expected result
SDL should release memory.

# Environment
Branch: Repository: https://github.com/smartdevicelink/sdl_core/ Tag: 4.2.0
HMI: 3acad9e9673fb479a
SDL: a6c32b45832653d6b851be9b19355fa35f377e07
ATF version: N/A
OS: Ubuntu 14.04 TTS x64
Transport: USB
Mobile device: Acer B1-710
Mobile OS: Android 4.1.2
Mobile App version: SPT ver 2.1.84 code 242
Mobile App type: Navi
Virtual machine using: N/A

# Attachments
[att_iss#1029.zip](https://github.com/smartdevicelink/sdl_core/files/576450/att_iss.1029.zip)

# Expected delivery   
- [ ] Source code updates 
- [ ] Code comments 
- [ ] UTs add/update 
- [x] ATF tests add/update ***(not required)***  
- [x] Manual tests ***(not required)*** 
- [x] Add/update CI plans/jobs ***(not required)***  
- [x] SDD updates ***(not required)***  
- [x] Guidelines update ([sdl_core_guides](https://github.com/smartdevicelink/sdl_core_guides)) ***(not required)***  
- [x] Guidelines update ([sdl_hmi_integration_guidelines](https://github.com/smartdevicelink/sdl_hmi_integration_guidelines))  ***(not required)***

**Comment by JackLivio** [comment]
@mghiumiusliu I see this one doesn't have a project associated with it so I'm not sure if there is a milestone related to this fix, or if it is just a general issue. Please place milestone if it is related to a release.

**Comment by mghiumiusliu** [comment]
@JackLivio This is part of stabilization fixes we provided in June.

**Comment by jacobkeeler** [comment]
Closing with the merge of #1626
