### ISSUE TITLE
SDL forwards OnButtonPress notification of CUSTOM_BUTTON to BACKGROUND App.

### ISSUE THREAD

**Issue by Itileda** [smartdevicelink/sdl_core#1033]
**Occurrence:** 
Always

**Preconditions:** 
1. Core, HMI started. 
2. App is registered on HM and has HMIlevel BACKGROUND

**Steps to reproduce:**
1. Send from HMI OnButtonEvent(CUSTOM_BUTTON, SHORT/LONG)

**Actual result:**
SDL resend it to BACKGROUND App.

**Expected result:**
SDL should resend OnButtonEvent notification to either FULL non-media App or FULL/LIMITED media App 

**Environment**
Repository: https://github.com/smartdevicelink/sdl_core/
Tag: 4.2.0
commit: a6c32b45832653d6b851be9b19355fa35f377e07
ATF version: 2.2 / 962e1eff8664d97a
NOTE: In order for the script to run please change line
from <<Test = require('user_modules/OnButtonPress_connecttest') >>
to <<Test = require('connecttest')>>

**Comment by JackLivio** [comment]
@mghiumiusliu Can you please add the appropriate milestone? Not sure if it is still 4.4.1

**Comment by LitvinenkoIra** [comment]
Priority is hight: significant loss of functionality on SDL side with standard use-case

**Comment by LitvinenkoIra** [comment]
Already fixed in develop 7836d78b7f28ec7c54bef420f90449583a4e18d5

**Comment by jacobkeeler** [comment]
Fixed with the merge of https://github.com/smartdevicelink/sdl_core/issues/1111
