### ISSUE TITLE
[Protocol] SDL respond ACK with protocol version 4 for video and audio services if send start service with 2 or 3 protocol version

### ISSUE THREAD

**Issue by Itileda** [smartdevicelink/sdl_core#1034]
**Occurrence:** 
Sometimes (1/5)

**Precondition:** 
1. SDL and HMI are started
2. SPT is registered using v2 or v3 protocol
3. Video and Audio services are allowed to be unsecure
4. Wireshark is configured to listen SDL protocol

**Steps:**
1. Start VIdeoService.
2. Accept with pop-up on HMI.
3. Start Audio service.
4. Accept with pop-up on HMI.
5. Start RPC service.

**Actual result:** 
SDL respond ACK with protocol version 4.

**Expected result:** 
SDL should respond ACK with the same protocol as start service was come - version 2.

**Note:**
The same behavior if start secure audio/video services.

[att_iss#1034.zip](https://github.com/smartdevicelink/sdl_core/files/576474/att_iss.1034.zip)

**Comment by JackLivio** [comment]
Duplicate Issue https://github.com/smartdevicelink/sdl_core/issues/1365
