### ISSUE TITLE
[Policies] SDL doesn't reject PT if the consumer_friendly_message section contains messaging without “en-us” language key

### ISSUE THREAD

**Issue by OVikhrov** [smartdevicelink/sdl_core#1036]
## Occurrence
Always.

## Preconditions
Ensure that "en-us" of "AppPermissions" message is erased from the sdl_prealoaded_pt.json

## Steps to reproduce
Start SDL

## Expected result
If “en-us” is not present for any message, the table shall be rejected, PM should log error and shut SDL down

## Actual result
SDl continue working, no errors in log observed

# Environment
Release: 4.2.0 (master marge)
Repository: https://github.com/smartdevicelink/sdl_core
Commit: a6c32b45832653d6b851be9b19355fa35f377e07
OS: Ubuntu 14.04 
Transport: WiFi 
App type: navi
App: Luxoft SPT
Device: HTC One

# Attachments
[att_issue#1036.zip](https://github.com/smartdevicelink/sdl_core/files/576485/att_issue.1036.zip)

# Expected delivery   
- [ ] Source code updates 
- [ ] Code comments 
- [ ] UTs add/update 
- [x] ATF tests add/update ***(not required)***  
- [x] Manual tests ***(not required)*** 
- [x] Add/update CI plans/jobs ***(not required)***  
- [x] SDD updates ***(not required)***  
- [x] Guidelines update ([sdl_core_guides](https://github.com/smartdevicelink/sdl_core_guides)) ***(not required)***  
- [x] Guidelines update ([sdl_hmi_integration_guidelines](https://github.com/smartdevicelink/sdl_hmi_integration_guidelines))  ***(not required)***

**Comment by jacobkeeler** [comment]
Fixed with the merge of #1624
