### ISSUE TITLE
[Policies] External UCS: informing HMI

### ISSUE THREAD

**Issue by TMelnyk** [smartdevicelink/sdl_core#1047]
**_Description:_** 
Upon GetListOfPermissions_request, SDL must inform "externalConsentStatus" setting to HMI

**_Impact:_** 
SDL 
HTML5 HMI 
TestCases 
Requirements

**Comment by DrachenkoAnastasiia** [comment]
**_Description:_** 
Upon GetListOfPermissions_request, SDL must inform "CCS status" setting to HMI

**_Impact:_** 
SDL 
HTML5 HMI 
TestCases 
Requirements

**Comment by JackLivio** [comment]
@TMelnyk Closing since this is a requirement and not an issue. If this CRQ is still being worked on please relocate to https://github.com/smartdevicelink/sdl_requirements
