### ISSUE TITLE
[ResultCodes] SDL must send WARNINGS (success:true) to mobile app in case HMI respond WARNINGS at least to one component of RPC

### ISSUE THREAD

**Issue by mghiumiusliu** [smartdevicelink/sdl_core#1061]
**Description**
Covered cases:
->SDL must send WARNINGS (success:true) to mobile app in case HMI respond WARNINGS to at least one HMI-portions

**Impact**
SDL
SPT
TestCases
Requirements

**Comment by JackLivio** [comment]
@mghiumiusliu Closing since this is a requirement and not an issue. If this CRQ is still being worked on please relocate to https://github.com/smartdevicelink/sdl_requirements

**Comment by LevchenkoS** [comment]
PR #1505
