### ISSUE TITLE
Perform Interaction Manual Mode Still Requires Vr Response

### ISSUE THREAD

**Issue by JackLivio** [smartdevicelink/sdl_core#1096]
### Description

Core does not send Perform Interaction Response to Mobile when using manual mode (i.e. only using ui.performinteraction). Core will not send the response to mobile unless it receives a response for both ui and vr perform interaction. 

### Information
This image shows the implemented flow for manual only. Why does the HMI HAVE to respond to VR.PerformInteraction in manual only mode?
![performinteractionmanualonly](https://cloud.githubusercontent.com/assets/12038416/20982815/03a57208-bc88-11e6-8562-e0448315a212.png)

### Impact
Modules that do not have VR implemented and will not be able to respond to VR.PerformInteraction.

**Comment by jacobkeeler** [comment]
Seems that the issue here is that TTS information is included in the `VR.PerformInteraction` request, so I believe that there would need to be a change of the design of these RPCs in order to fix this issue.

**Comment by chinlin0924** [comment]
Hi, when will this be fixed?

**Comment by jacobkeeler** [comment]
Closing, because a proposal would be needed to change this behavior at this point
