### ISSUE TITLE
after running 'cmake' command getting following error

### ISSUE THREAD

**Issue by mohammadfarooque** [smartdevicelink/sdl_core#1111]
Hi ,
I am installing sdlcore on my linux OS , getting following error while running 'cmake' command.
any help will be appreciated 

errore massege:-

[  0%] Built target jsoncpp
 Need to build logger. 
[ 50%] Built target expat
[100%] Built target libapr-1
[100%] Built target apr-util
running CONFIG_SHELL=/bin/bash /bin/bash /sdl_core/src/3rd_party/apache-log4cxx-cmake/../apache-log4cxx-0.10.0/configure --with-apr=../apr-build --with-apr-util=../apr-util-build LDFLAGS=-L/sdl_core/src/3rd_party/expat-2.1.0 CC=/usr/bin/cc CXX=/usr/bin/c++ --no-create --no-recursion
configure: WARNING: unrecognized options: --with-apr, --with-apr-util
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking how to print strings... printf
checking for style of include used by make... GNU
checking for gcc... /usr/bin/cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether /usr/bin/cc accepts -g... yes
checking for /usr/bin/cc option to accept ISO C89... none needed
checking dependency style of /usr/bin/cc... gcc3
checking for a sed that does not truncate output... /bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking for ld used by /usr/bin/cc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 3458764513820540925
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from /usr/bin/cc object... ok
checking for sysroot... no
checking for mt... mt
checking if mt is a manifest tool... no
checking how to run the C preprocessor... /usr/bin/cc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if /usr/bin/cc supports -fno-rtti -fno-exceptions... no
checking for /usr/bin/cc option to produce PIC... -fPIC -DPIC
checking if /usr/bin/cc PIC flag -fPIC -DPIC works... yes
checking if /usr/bin/cc static flag -static works... yes
checking if /usr/bin/cc supports -c -o file.o... yes
checking if /usr/bin/cc supports -c -o file.o... (cached) yes
checking whether the /usr/bin/cc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking whether make sets $(MAKE)... (cached) yes
checking whether we are using the GNU C++ compiler... yes
checking whether /usr/bin/c++ accepts -g... yes
checking dependency style of /usr/bin/c++... gcc3
checking how to run the C++ preprocessor... /usr/bin/c++ -E
checking for ld used by /usr/bin/c++... /usr/bin/ld -m elf_x86_64
checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
checking whether the /usr/bin/c++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking for /usr/bin/c++ option to produce PIC... -fPIC -DPIC
checking if /usr/bin/c++ PIC flag -fPIC -DPIC works... yes
checking if /usr/bin/c++ static flag -static works... yes
checking if /usr/bin/c++ supports -c -o file.o... yes
checking if /usr/bin/c++ supports -c -o file.o... (cached) yes
checking whether the /usr/bin/c++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking how to run the C++ preprocessor... /usr/bin/c++ -E
checking for doxygen... /usr/bin/doxygen
checking for dot... no
/sdl_core/src/3rd_party/apache-log4cxx-cmake/../apache-log4cxx-0.10.0/configure: line 15462: syntax error near unexpected token `,'
/sdl_core/src/3rd_party/apache-log4cxx-cmake/../apache-log4cxx-0.10.0/configure: line 15462: `APR_FIND_APR( , , 1, 1)'
make[6]: *** [config.status] Error 2
make[5]: *** [src/3rd_party/apache-log4cxx-cmake/CMakeFiles/liblog4cxx] Error 2
make[4]: *** [src/3rd_party/apache-log4cxx-cmake/CMakeFiles/liblog4cxx.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [CMakeFiles/3rd_party_logger] Error 2
make[1]: *** [CMakeFiles/3rd_party_logger.dir/all] Error 2
make: *** [all] Error 2

**Comment by jacobkeeler** [comment]
@mohammadfarooque Are you still experiencing this on the latest release? If you are, what OS are you building for?
