### ISSUE TITLE
OnHMIStatus notification should contain the 'trigger source'

### ISSUE THREAD

**Issue by justinjdickow** [smartdevicelink/sdl_core#12]
The trigger source defines whether or not the application is being brought into HMI FULL via a selection on the head unit or by voice recognition.

**Comment by justinjdickow** [comment]
Need use cases for whether or not the application or HMI needs to know if an app was activated via voice or HMI

**Comment by JackLivio** [comment]
If this proposal is still valid please consider submitting a proposal to the sdl evolution repository
https://github.com/smartdevicelink/sdl_evolution
