### ISSUE TITLE
DISALLOWED instead of USER_DISALLOWED in case getting negative user consent from HMI

### ISSUE THREAD

**Issue by KhrystynaDubovyk** [smartdevicelink/sdl_core#1207]
## Occurrence:
Sometimes

## Preconditions:
1. SDL is built with EXTERNAL_PROPRIETARY flag
2. SDL and HMI are started. First ignition cycle
3. Device is connected to SDL and consented by the User, App is running on that device.
4. App is registered with SDL and is present in HMI list of registered aps.
5. Local PT has permissions for App that require User`s consent.

## Steps to reproduce:
1. User choose App in the list of registered aps on HMI.
2. The User disallows definite permissions.
3. Send RPC to sure that it USER_DISALLOWED
--
Or run script [App_Permissions/004_ATF_HP_User_Consent_NO.lua](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Policies/App_Permissions/004_ATF_HP_User_Consent_NO.lua) 

## Expected result:
SDL-> App: Response: { success = false, resultCode = "USER_DISALLOWED"}.
Scenario is failed.

## Actual result:
SDL-> App: Response: { success = false, resultCode = "DISALLOWED"}.
Scenario is passed.

## Environment
repo: https://github.com/smartdevicelink/sdl_core/
branch: feature/external_proprietary_policy (head of branch)
ATF version: 2.2, commit 752d9aec810ccb2a30ab6b53c587f8bb8ef1c545

## Expected delivery
- [ ] Source code updates
- [ ] Code comments
- [ ]  UTs add/update
- [ ]  ATF tests add/update
- [ ]  Add/update CI plans/jobs
- [ ]  SDD updates
- [ ]  Guidelines update (sdl_core_guides)
- [ ]  Guidelines update (sdl_hmi_integration_guidelines)

**Comment by JackLivio** [comment]
Issue is not reproducible or it is fixed in develop.

**Comment by JackLivio** [comment]
@KhrystynaDubovyk the title of the issue and the actual/expected outcomes seem to be conflicting. What is the correct behavior supposed to be in this case?

**Comment by JackLivio** [comment]
When testing Develop manually, mobile is receiving "DISALLOWED"

**Comment by dboltovskyi** [comment]
@JackLivio, Thank you for such finding, - actual and expected results were confused.
Description is updated and now it is correct.

**Comment by LuxoftAKutsan** [comment]
Priority is Medium
Wrong result code received from SDL

**Comment by GetmanetsIrina** [comment]
Defect is not reproduced.
SDL: develop branch(ba1da7bc2ff3fd37638620f6bea526384646ab0e)
ATF: develop branch
Script: https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Policies/App_Permissions/004_ATF_HP_User_Consent_NO.lua
