### ISSUE TITLE
SDL sends BC.ActivateApp twice in specific case

### ISSUE THREAD

**Issue by DrachenkoAnastasiia** [smartdevicelink/sdl_core#1208]
## Occurrence:
Always

## Preconditions:
1. SDL is built with External Proprietary flag.
2. SDL and HMI are started. First ignition cycle.
3. Connect device
4. Register new application.

## Steps to reproduce:
1. Activate application. 
HMI->SDL: SDL.ActivateApp
SDL->HMI: SDL.ActivateApp(isSDLAllowed: false)
2. HMI->SDL: SDL.GetUserFriendlyMessage(messageCodes : ["DataConsent"])
SDL->HMI: SUCCESS
3. HMI->SDL: SDL.OnAllowSDLFunctionality (allowed: true)
--
Or run script [175_ATF_OnAllowSDLFunctionality_allowed_true_without_device.lua](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Policies/Related_HMI_API/175_ATF_OnAllowSDLFunctionality_allowed_true_without_device.lua)

## Actual result:
SDL sends: 
1) BasicCommunication.ActivateApp (level: <default_hmi>)
2) BasicCommunication.ActivateApp (level: ).
Scenario is failed.

## Expected result:
SDL sends only one BasicCommunication.ActivateApp() request.
Scenario is passed.

## Environment
repo: https://github.com/smartdevicelink/sdl_core/
branch: feature/external_proprietary_policy (head of branch)
ATF version: 2.2, commit 752d9aec810ccb2a30ab6b53c587f8bb8ef1c545

## Expected delivery
- [ ] Source code updates
- [ ] Code comments
- [ ]  UTs add/update
- [ ]  ATF tests add/update
- [ ]  Add/update CI plans/jobs
- [ ]  SDD updates
- [ ]  Guidelines update (sdl_core_guides)
- [ ]  Guidelines update (sdl_hmi_integration_guidelines)

**Comment by LuxoftAKutsan** [comment]
Priority is low
Redundant not critical SDL activity

**Comment by APipko** [comment]
sdl_core commit 406f491b7db0123351e3851d130bb334cf275023 : not reproduced

**Comment by IGapchuk** [comment]
SDL (develop): commit - 28235f88a6733106a7e8a0d490dfb16a5f374a33.
ATF: (feature/script_runner): commit - 6d7161a86825dd75ae5ae9ac6bae9d9ee824880e.
Status: not reproduce.

**Comment by iCollin** [comment]
Closed as not reproducible.
Please let me know if you believe this issue is still actual.
