### ISSUE TITLE
PROPRIETARY: BC.PolicyUpdate is sent during retry sequence

### ISSUE THREAD

**Issue by KhrystynaDubovyk** [smartdevicelink/sdl_core#1210]
## Occurrence:
Always

## Preconditions:
1. SDL is built with PROPRIEATRY flag.
2. SDL and HMI are started. First ignition cycle.
3. Connect device.
4. Register new application --> PTU sequence is triggered.

## Steps to reproduce:
1. Do not send PolicyTableUpdate within defined 'timeout' (60s).
--
Or run script [ATF_Start_PTU_retry_sequence.lua](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Polices/build_options/ATF_Start_PTU_retry_sequence.lua) 

## Actual result;
SDL re-starts PTU:
1) SDL->HMI: SDL.OnStatusUpdate(UPDATE_NEEDED) - OK
2) SDL->HMI: BC.PolicyUpdate - NOK.
Scenario is failed.

## Expected result:
SDL starts retry sequence:
1) SDL->HMI: SDL.OnStatusUpdate(UPDATE_NEEDED).
2) SDL->HMI: BC.PolicyUpdate is not send.
Scenario is passed.

## Environment
repo: https://github.com/smartdevicelink/sdl_core/
branch: feature/external_proprietary_policy (head of branch)
ATF version: 2.2, commit 752d9aec810ccb2a30ab6b53c587f8bb8ef1c545

## Expected delivery

- [ ]  Source code updates
- [ ]  Code comments
- [ ]  UTs add/update
- [ ]  ATF tests add/update
- [ ]  Add/update CI plans/jobs
- [ ]  SDD updates
- [ ]  Guidelines update (sdl_core_guides)
- [ ]  Guidelines update (sdl_hmi_integration_guidelines)

**Comment by jacobkeeler** [comment]
It appears that this OnStatusUpdate message is sent as part of the `OnAppRegisteredOnMobile` function (eventually leading to the `OnUpdateStatusChanged`, where this message is sent from). 

This function call was moved in this commit (although it was part of the `RegisterAppInterface` response originally): https://github.com/smartdevicelink/sdl_core/commit/088bc6dbd4a59b4bcea423accef081cb7beae889

**Comment by Itileda** [comment]
Actually SDL sends OnStatusUpdate(UPDATE_NEEDED) to HMI as expected, but issue here is that there is a redundant PolicyUpdate request to HMI.
Initially snapshot was created during first BasicCommunication.PolicyUpdate.
Accordinf to retry sequence diagram, in case mobile App doesn't reply within timeout, SDL should inform HMI that status was changed from UPDATING to UPDATE_NEEDED, and send again to the App OnSystemRequest. Next behavior is the same. Right after sending OnSystemRequest state is changed to UPDATING.

**Comment by jacobkeeler** [comment]
@Itileda I don't know how this comment ended up here, it was originally posted on #1215, and for some reason a duplicate was posted here as well. Sorry about that.

**Comment by jacobkeeler** [comment]
@Itileda Could you please link the retry sequence diagram? I'm not finding it on the Dev Portal. 

Based off of the "Proprietary flow" diagram for [PolicyUpdate](https://smartdevicelink.com/en/docs/hmi/master/basiccommunication/policyupdate/), this message is supposed to start off the PTU, is this not supposed to initiate the sequence on retry?

**Comment by LuxoftAKutsan** [comment]
Priority is low.
Redundant SDL activity that may trigger significant effect on HMI

**Comment by jacobkeeler** [comment]
Closing with the merge of #3329
