### ISSUE TITLE
SDL shut down due to SIGSEGV

### ISSUE THREAD

**Issue by DrachenkoAnastasiia** [smartdevicelink/sdl_core#1211]
## Occurrence:
Sometimes
## Steps to reproduce:
1. Make sure SDL is built with EXTERNAL_PROPRIETARY flag
2. Change values of the following parameters in SDL .INI file:
* 'AppHMILevelNoneTimeScaleMaxRequests' = 10
* 'AppHMILevelNoneRequestsTimeScale' = 30000
3. Start SDL
4. Start HMI
5. Connect mobile device
6. Register new application
7. Send ‘AddCommand’ RPC more than 10 times
8. Check the value of ‘count_of_removals_for_bad_behavior’ parameter in ‘app_level’ table of Local Policy DB

## Expected result:
The value of parameter is incremented

## Actual result:
The value of parameter is not incremented and SDL is shutdown due to SIGSEGV signal

## Test script:
[1211_ATF_Check_count_of_removals_for_bad_behavior_REQUEST_WHILE_IN_NONE_HMI_LEVEL.lua](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Defects/4_5/1211_ATF_Check_count_of_removals_for_bad_behavior_REQUEST_WHILE_IN_NONE_HMI_LEVEL.lua)

## Environment
repo: https://github.com/smartdevicelink/sdl_core/
branch: feature/external_proprietary_policy (head of branch)
ATF version: 2.2, commit 752d9aec810ccb2a30ab6b53c587f8bb8ef1c545

## Expected delivery
- [ ] Source code updates
- [ ] Code comments
- [ ]  UTs add/update
- [ ]  ATF tests add/update
- [ ]  Add/update CI plans/jobs
- [ ]  SDD updates
- [ ]  Guidelines update (sdl_core_guides)
- [ ]  Guidelines update (sdl_hmi_integration_guidelines)

**Comment by jacobkeeler** [comment]
PR: #1519

**Comment by LuxoftAKutsan** [comment]
@jacobkeeler @JackLivio I can see merged PR related to this issue. Should it be closed?

**Comment by LuxoftAKutsan** [comment]
Priority is high
Segmentation fault in a trivial use case

**Comment by LitvinenkoIra** [comment]
Works correctly on current develop (9e95f67178c575ca5a537f9ef3a69653219b073d)
Script for verifying and testing report [1211.tar.gz](https://github.com/smartdevicelink/sdl_core/files/1535131/1211.tar.gz)

**Comment by dboltovskyi** [comment]
For the information: issue was reproducible on https://github.com/smartdevicelink/sdl_core/commit/22ed9b1 commit

**Comment by LuxoftAKutsan** [comment]
Issue was in invalidation iterator of the application during checking allowed parameters. Fix available in  https://github.com/smartdevicelink/sdl_core/pull/1519

**Comment by mrapitis** [comment]
Reviewed ATF script and ran successfully.  Successfully reproduced issue with provided commit.

**Comment by jacobkeeler** [comment]
Fixed with the merge of #1519
