### ISSUE TITLE
SDL does not increment "count_of_sync_reboots" section value of Local Policy Table on getting SDL.OnSystemError("SYNC_REBOOTED")

### ISSUE THREAD

**Issue by KhrystynaDubovyk** [smartdevicelink/sdl_core#1213]
## Occurrence:
Always.

## Preconditions:
1. SDL is built with External Proprietary flag.
2. Start SDL and HMI
Note: SDL is starting first time LocalPT has "count_of_sync_reboots" = 0

## Steps to reproduce:
1. Send SDL.OnSystemError("SYNC_REBOOTED") from HMI to SDL 3 times
2. Stop SDL
3. Start SDL and HMI
4. Send SDL.OnSystemError("SYNC_REBOOTED") from HMI to SDL 4 times
5. Stop SDL
--
Or run script [074_ATF_usage_and_error_counts_update_count_of_sync_reboots.lua](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Polices/Validation_of_PolicyTables/074_ATF_usage_and_error_counts_update_count_of_sync_reboots.lua) 

## Actual result:
LocalPT has "count_of_sync_reboots" = 4.
Scenario is failed.

## Expected result:
SDL must increment "count_of_sync_reboots" section value of Local Policy Table on each SDL.OnSystemError("SYNC_REBOOTED")
So LocalPT has "count_of_sync_reboots" = 7.
Scenario is passed.

## Environment
repo: https://github.com/smartdevicelink/sdl_core/
branch: feature/external_proprietary_policy (head of branch)
ATF version: 2.2, commit 752d9aec810ccb2a30ab6b53c587f8bb8ef1c545

## Expected delivery

- [ ]  Source code updates
- [ ]  Code comments
- [ ]  UTs add/update
- [ ]  ATF tests add/update
- [ ]  Add/update CI plans/jobs
- [ ]  SDD updates
- [ ]  Guidelines update (sdl_core_guides)
- [ ]  Guidelines update (sdl_hmi_integration_guidelines)

**Comment by LuxoftAKutsan** [comment]
Priority is low
Sometimes SDL does not increment an internal counter.

**Comment by iCollin** [comment]
Closed as not reproducible against the first 7.1 release candidate. The mentioned ATF test has been renamed (228) but it is passing.

Please let me know if you believe this issue is still actual.
