### ISSUE TITLE
UPDATE_NEEDED is sent if user requested PTU from HMI

### ISSUE THREAD

**Issue by DrachenkoAnastasiia** [smartdevicelink/sdl_core#1214]
## Occurrence:
Always

## Preconditions:
1. SDL is built with EXTERNAL_PROPRIETARY flag
2. SDL and HMI are started. First ignition cycle
3. Connect device
4. Register new application
5. Activate app => PTU is triggered
6. Finish PTU with UP_TO_DATE status

## Steps to reproduce:
1. Request PTU from HMI by user (via SDL.UpdateSDL request)
--
Or run script [007_ATF_P_TC_OnStatusUpdate_UPDATE_NEEDED_new_PTU_request.lua](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Polices/Policy_Table_Update/007_ATF_P_TC_OnStatusUpdate_UPDATE_NEEDED_new_PTU_request.lua)

## Actual result: 
SDL->HMI: SDL.OnStatusUpdate(UPDATE_NEEDED) is sent.
Scenario is failed.

## Expected result:
SDL->HMI: SDL.OnStatusUpdate(UPDATE_NEEDED) is NOT sent.
Scenario is passed.

## Environment
repo: https://github.com/smartdevicelink/sdl_core/
branch: feature/external_proprietary_policy (head of branch)
ATF version: 2.2, commit 752d9aec810ccb2a30ab6b53c587f8bb8ef1c545

## Expected delivery
- [ ] Source code updates
- [ ] Code comments
- [ ]  UTs add/update
- [ ]  ATF tests add/update
- [ ]  Add/update CI plans/jobs
- [ ]  SDD updates
- [ ]  Guidelines update (sdl_core_guides)
- [ ]  Guidelines update (sdl_hmi_integration_guidelines)

**Comment by jacobkeeler** [comment]
PR: #1491

**Comment by LuxoftAKutsan** [comment]
Priority is low.
Redundant SDL activity. But this activity may trigger significant effects on HMI.
@jacobkeeler @JackLivio I can see merged PR related to this issue. Should it be closed?

**Comment by LuxoftAKutsan** [comment]
Priority is low.
Redundant SDL activity. But this activity may trigger significant effects on HMI.
@jacobkeeler @JackLivio I can see merged PR related to this issue. Should it be closed?

**Comment by JackLivio** [comment]
Yes issue is fixed by pr #1491. Closing issue
