### ISSUE TITLE
HTTP: OnSystemRequest is sent twice

### ISSUE THREAD

**Issue by DrachenkoAnastasiia** [smartdevicelink/sdl_core#1216]
## Occurrence:
Always

## Preconditions:
1. SDL is built with HTTP flag.
2. SDL and HMI are started. First ignition cycle.
3. Connect device.

## Steps to reproduce:
1. Register new application => PTU is triggered.
--
Or run script [025_ATF_P_TC_PTU_Local_PT_Start_Retry_Sequence_HTTP.lua](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Polices/build_options/025_ATF_P_TC_PTU_Local_PT_Start_Retry_Sequence_HTTP.lua)

## Actual result:
SDL->App: OnSystemRequest(requestType = 'HTTP') 2 times.
Scenario is failed.

## Expected result:
SDL->App: OnSystemRequest(requestType = 'HTTP').
Scenario is passed.

## Environment
repo: https://github.com/smartdevicelink/sdl_core/
branch: feature/external_proprietary_policy (head of branch)
ATF version: 2.2, commit 752d9aec810ccb2a30ab6b53c587f8bb8ef1c545

## Expected delivery
- [ ] Source code updates
- [ ] Code comments
- [ ]  UTs add/update
- [ ]  ATF tests add/update
- [ ]  Add/update CI plans/jobs
- [ ]  SDD updates
- [ ]  Guidelines update (sdl_core_guides)
- [ ]  Guidelines update (sdl_hmi_integration_guidelines)

**Comment by LitvinenkoIra** [comment]
Priority : Medium
Redundant request to mobile

**Comment by JackLivio** [comment]
Issue no longer reproducible. Closing
