### ISSUE TITLE
OnHMIStatus is not sent in case app gets 'null' while PTU

### ISSUE THREAD

**Issue by DrachenkoAnastasiia** [smartdevicelink/sdl_core#1217]
## Occurrence:
Always

## Preconditions:
1. SDL is built with EXTERNAL_PROPRIETARY flag.
2. SDL and HMI are started. First ignition cycle.
4. Connect device
5. Register new application
6. Activate application

## Steps to reproduce:
1. Perform PTU where application gets 'null' policies
--
Or run script [162_ATF_P_TC_HMI_Status_Appid_Gets_Null_In_Case_Of_PTU.lua](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Polices/appID_Management/162_ATF_P_TC_HMI_Status_Appid_Gets_Null_In_Case_Of_PTU.lua)
[163_ATF_P_TC_HMI_Status_Value_Of_AppId_In_PT_Is_Null.lua](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Polices/appID_Management/163_ATF_P_TC_HMI_Status_Value_Of_AppId_In_PT_Is_Null.lua)

## Actual result
Notification is not sent.
Scenario of script is failed.

## Expected result
SDL -> app: OnHMiStatus (NONE, NOT_AUDIBLE, MAIN).
Scenario of script is passed.

## Environment
repo: https://github.com/smartdevicelink/sdl_core/
branch: feature/external_proprietary_policy (head of branch)
ATF version: 2.2, commit 752d9aec810ccb2a30ab6b53c587f8bb8ef1c545

## Expected delivery
- [ ] Source code updates
- [ ] Code comments
- [ ]  UTs add/update
- [ ]  ATF tests add/update
- [ ]  Add/update CI plans/jobs
- [ ]  SDD updates
- [ ]  Guidelines update (sdl_core_guides)
- [ ]  Guidelines update (sdl_hmi_integration_guidelines)

**Comment by jacobkeeler** [comment]
PR: #1513

**Comment by LitvinenkoIra** [comment]
@jacobkeeler is this issue shouldn't be closed? I see PR related to this Issue.

**Comment by LitvinenkoIra** [comment]
Priority : minor
Not critical redundant notification to mobile

**Comment by JackLivio** [comment]
Fixed by #1513
