### ISSUE TITLE
Mandatory parameter 'spaceAvailable' is not provided in response for PutFile request

### ISSUE THREAD

**Issue by DrachenkoAnastasiia** [smartdevicelink/sdl_core#1218]
## Occurrence:
Always

## Preconditions:
1. SDL is built with EXTERNAL_PROPRIETARY flag.
2. SDL and HMI are started. First ignition cycle.
3. Connect device
4. Register new application

## Steps to reproduce:
1. App -> SDL: Send valid "PutFile" request
--
Or run script [158_ATF_P_TC_Register_App_Interface_With_Data_Consent_Assign_Default_Policies.lua](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Polices/appID_Management/158_ATF_P_TC_Register_App_Interface_With_Data_Consent_Assign_Default_Policies.lua)

## Actual result:
{ success = true, resultCode = "SUCCESS"}.
Scenario is failed.

## Expected result:
{ success = true, resultCode = "SUCCESS", spaceAvailable=xxx}.
Scenario is passed.

## Environment
repo: https://github.com/smartdevicelink/sdl_core/
branch: feature/external_proprietary_policy (head of branch)
ATF version: 2.2, commit 752d9aec810ccb2a30ab6b53c587f8bb8ef1c545

## Expected delivery
- [ ] Source code updates
- [ ] Code comments
- [ ]  UTs add/update
- [ ]  ATF tests add/update
- [ ]  Add/update CI plans/jobs
- [ ]  SDD updates
- [ ]  Guidelines update (sdl_core_guides)
- [ ]  Guidelines update (sdl_hmi_integration_guidelines)

**Comment by jacobkeeler** [comment]
While it should likely be included in this case, it seems to me that the spaceAvailable parameter shouldn't be mandatory in the first place. 

Leaving this as mandatory requires it to be included even when sending an error response, which theoretically shouldn't include anything other than the `success`, `resultCode`, and possibly `info` parameters.

**Comment by jacobkeeler** [comment]
@DrachenkoAnastasiia Also, when I run the test myself, spaceAvailable is not missing in the SUCCESS case, just the DISALLOWED case. As I said before, this parameter should not be mandatory in error cases, but the API treats it as such.

**Comment by AStasiuk** [comment]
@jacobkeeler Earlier all changes in MOBILE_API.xml were threated as change requests. 
Need to clarify how such cases should be handled?For example to create sdl_evolution proposal for future discussion, or some other approach.
Looking forward you suggestion.

**Comment by LitvinenkoIra** [comment]
@jacobkeeler should we create proposal related to it?

**Comment by LitvinenkoIra** [comment]
Priority is High
Missed mandatory parameters

**Comment by LitvinenkoIra** [comment]
Works correctly on current develop (8c94933)
Script for verifying and test reports in attachments.
[1218.tar.gz](https://github.com/smartdevicelink/sdl_core/files/1530894/1218.tar.gz)

**Comment by LitvinenkoIra** [comment]
@jacobkeeler @JackLivio should we create proposal related to it? or just close this issue?

**Comment by JackLivio** [comment]
Leaving issue open until proposal is made for making parameter non mandatory in failed response

**Comment by HSavynetska** [comment]
Defect is not reproduce on current develop(91123c3cae83ad41e1f5f37d37e46e9f07264d1b)

Verified with script(Script under review ): https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/1923

**Comment by AStasiuk** [comment]
Closed as not reproducible.

**Comment by GetmanetsIrina** [comment]
Script for reproducing https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Defects/5_0/1218_Mandatory_parameter_spaceAvailable_is_not_provided_in_response_for_PutFile_request.lua
