### ISSUE TITLE
HTTP SDL doesn't respect retry timeout sequence

### ISSUE THREAD

**Issue by KhrystynaDubovyk** [smartdevicelink/sdl_core#1221]
## Occurrence:
Always

## Preconditions:
1. SDL is built with HTTP policy flag.
2. Update preloaded_pt.json with:
"timeout_after_x_seconds": 30,
"seconds_between_retries": [1, 2, 3, 4, 5], in script is named as sec_btw_ret[]
3. Start SDL and HMI.
4. Register new application. => PTU is triggered.
OnSystemRequest is received at time1

## Steps to reproduce
1. Wait 'total_time' calculated as:
time_wait[1] = timeout_after_x_seconds
time_wait[2] = sec_btw_ret[1] + timeout_after_x_seconds
time_wait[3] = sec_btw_ret[1] + sec_btw_ret[2] + timeout_after_x_seconds
time_wait[4] = sec_btw_ret[2] + sec_btw_ret[3] + timeout_after_x_seconds
time_wait[5] = sec_btw_ret[3] + sec_btw_ret[4] + timeout_after_x_seconds
time_wait[6] = sec_btw_ret[4] + sec_btw_ret[5] + timeout_after_x_seconds
total_time = (time_wait[1] + time_wait[2] + time_wait[3] + time_wait[4] + time_wait[5] + time_wait[6])*1000
--
Or run script [032_ATF_P_TC_PTU_Retry_Sequence_Retry_Timeout_Expiration_HTTP.lua](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Polices/build_options/032_ATF_P_TC_PTU_Retry_Sequence_Retry_Timeout_Expiration_HTTP.lua) 

## Actual result:
1. SDL sends each OnSystemRequest after timeout_after_x_seconds(30 sec)
2. Afrer each OnSystemRequest(PROPRIETARY). SDL sends OnSystemRequest(LOCK_SCREEN_ICON_URL). 
Scenario is failed.

## Expected result:
1. Second OnSystemRequest is received after (t1 + time_wait[1]) - OK
2. Difference between received OnSystemRequest and previous OnSystemRequest is equal to time_wait[occurence].
Scenario is passed.

## Environment
repo: https://github.com/smartdevicelink/sdl_core/
branch: feature/external_proprietary_policy (head of branch)
ATF version: 2.2, commit 752d9aec810ccb2a30ab6b53c587f8bb8ef1c545

## Expected delivery

- [ ]  Source code updates
- [ ]  Code comments
- [ ]  UTs add/update
- [ ]  ATF tests add/update
- [ ]  Add/update CI plans/jobs
- [ ]  SDD updates
- [ ]  Guidelines update (sdl_core_guides)
- [ ]  Guidelines update (sdl_hmi_integration_guidelines)

**Comment by jacobkeeler** [comment]
PR: #1483

**Comment by LitvinenkoIra** [comment]
@jacobkeeler shouldn't this issue be closed? I can see merged PR that is related to it.

**Comment by LitvinenkoIra** [comment]
Priority Medium
Loss of  functionality in standard use case. 
Retry timeouts should be increased between retries

**Comment by JackLivio** [comment]
fixed by #1483
