### ISSUE TITLE
HTTP: SDL sends OnSystemRequest "requestType":"LOCK_SCREEN_ICON_URL" on app registered

### ISSUE THREAD

**Issue by KhrystynaDubovyk** [smartdevicelink/sdl_core#1223]
## Occurrence:
Always

## Preconditions:
1. SDL is built with HTTP policy flag.
2. SDL and HMI are started. First ignition cycle.
3. Connect device.

## Steps to reproduce:
1. Register app.
--
Or run script [032_ATF_P_TC_PTU_Restarting_Policy_Table_Exchange_HTTP.lua](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Polices/build_options/032_ATF_P_TC_PTU_Restarting_Policy_Table_Exchange_HTTP.lua) 

## Actual result:
SDL sends OnSystemRequest "requestType":"LOCK_SCREEN_ICON_URL" to mobile app.
Scenario is failed.

## Expected result:
SDL should not send onSystemRequest "requestType":"LOCK_SCREEN_ICON_URL".
Scenario is passed.

## Environment
repo: https://github.com/smartdevicelink/sdl_core/
branch: feature/external_proprietary_policy (head of branch)
ATF version: 2.2, commit 752d9aec810ccb2a30ab6b53c587f8bb8ef1c545

## Expected delivery

- [ ]  Source code updates
- [ ]  Code comments
- [ ]  UTs add/update
- [ ]  ATF tests add/update
- [ ]  Add/update CI plans/jobs
- [ ]  SDD updates
- [ ]  Guidelines update (sdl_core_guides)
- [ ]  Guidelines update (sdl_hmi_integration_guidelines)

**Comment by jacobkeeler** [comment]
This behavior is correct as far as I can tell, even if it wasn't originally base on a requirement. There would likely need to be several changes to the ATF test scripts to match these expectations, however.

**Comment by jacobkeeler** [comment]
@LuxoftAKutsan

**Comment by LitvinenkoIra** [comment]
@JackLivio @jacobkeeler so is this behavior is expected? There should be changes in SDL code or in scripts? and it should be mentioned in requirements?

**Comment by LitvinenkoIra** [comment]
Priority is Medium.
Not critical redundant SDL activity.

**Comment by jacobkeeler** [comment]
Test scripts should be updated, this behavior is expected and was added in response to https://github.com/smartdevicelink/sdl_core/issues/3
