### ISSUE TITLE
SDL does not increment count_of_rejections_sync_out_of_memory counter after OUT_OF_MEMORY for RAI

### ISSUE THREAD

**Issue by KhrystynaDubovyk** [smartdevicelink/sdl_core#1229]
## Occurrence:
Always

## Preconditions
SDL is built with External Proprietary flag

## Steps to reproduce
1. Create ramdisk with restricted size: 
mkdir /mnt/ramdisk
mount -t tmpfs -o size=300m tmpfs /mnt/ramdisk
 2. Copy to /mnt/ramdisk "bin" folder with SDL.
 3. Start SDL, HMI.
 4. Register app.
 5. Fill app folder via PutFile fully.
 6. Register new App.

## Actual result
SDL Respond OUT_OF_MEMORY resultCode for RAI of new app.
Counter "count_of_rejections_sync_out_of_memory" is not incremented.

## Expected result
Counter "count_of_rejections_sync_out_of_memory" should incremented after every OUT_OF_MEMORY resultCode for RAI.

## Environment
repo: https://github.com/smartdevicelink/sdl_core/
branch: feature/external_proprietary_policy (head of branch)
ATF version: 2.2, commit 752d9aec810ccb2a30ab6b53c587f8bb8ef1c545

## Expected delivery

- [ ]  Source code updates
- [ ]  Code comments
- [ ]  UTs add/update
- [ ]  ATF tests add/update
- [ ]  Add/update CI plans/jobs
- [ ]  SDD updates
- [ ]  Guidelines update (sdl_core_guides)
- [ ]  Guidelines update (sdl_hmi_integration_guidelines)

**Comment by jacobkeeler** [comment]
PR: #1486

**Comment by LuxoftAKutsan** [comment]
@jacobkeeler shouldn't this issue be closed?

**Comment by LuxoftAKutsan** [comment]
Priority is medium:
request is not processed or returned response is wrong in non-standard use case.
Out of memory is not standard use case.

**Comment by JackLivio** [comment]
Fixed by#1486
