### ISSUE TITLE
[INI file changes] The default value of "VideoDataStoppedTimeout" and "AudioStoppedTimeout" must be increased to 3000 ms

### ISSUE THREAD

**Issue by TMelnyk** [smartdevicelink/sdl_core#1259]
**Description:**
1. The default value of "_VideoDataStoppedTimeout_" param must be **increased to 3000ms** at .ini file
2. The default value of "_AudioDataStoppedTimeout_" param must be **increased to 3000ms** at .ini file
3. The new "_iAPBufferSize_" param with 1048576 value **must be added** to [iAP] section of .ini file

**.ini file change:**
_[MEDIA MANAGER]_
...
_; Defines time in milliseconds for SDL to wait for the next package of raw data over audio service_
_AudioDataStoppedTimeout = 3000_
_; Defines time in milliseconds for SDL to wait for the next package of raw data over video service_
_VideoDataStoppedTimeout = 3000_

_[IAP]_
_: Defines size of iAP buffer in bytes_
_iAPBufferSize = 1048576_

**Impact**: 
SDL 
TestCases 
Requirements

**Comment by JackLivio** [comment]
@TMelnyk Is this just a proposal or is there a milestone related to this? If so could you please add the appropriate milestone? Thank you

**Comment by TMelnyk** [comment]
@JackLivio , this can be closed actually
.ini file is configurable, so any OEM can change valud of any param

**Comment by JackLivio** [comment]
@TMelnyk Thanks!
