### ISSUE TITLE
[SDL 0014] Adding Audio File Playback to TTSChunk

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_core#1277]
Proposal: [Adding Audio File Playback to TTSChunk](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0014-adding-audio-file-playback-to-ttschunk.md)

> More and more applications use sounds as a means to make a user feel more at home within their application, and allow the developer to have more customization of their User Experience. This proposal will allow developers to provide audio files uploaded to be played in conjunction with, or without, Text-to-Speech text, so that they may provide a more customized experience.

Review: smartdevicelink/sdl_evolution#42

Steering Committee Decision:

> This proposal was accepted. The committee feels it is a good feature to add to give apps some personality and to enable new features, and while the naming isn't ideal, it gives us the maximum amount of flexibility with the minimum extra development cost.  The implementation will have to be fleshed out on core to ensure backward compatibility.

**Comment by shoamano83** [comment]
Hi @jacobkeeler,
I think the branch https://github.com/smartdevicelink/sdl_core/tree/feature/audio_file_playback_tts_chunks is for this improvement. I guess this will not be included in SDL Core 4.3, but can I expect that it is included in 4.4 release?

**Comment by theresalech** [comment]
Hi @shoamano83, it's possible that this can be included in Core 4.4, but it isn't currently prioritized for the release.  SDLC Members have been tasked with providing prioritized items for the Core 4.4 release, so can include this proposal/issue if needed.

**Comment by shoamano83** [comment]
Thanks @theresalech, I understand the situation.

**Comment by jacobkeeler** [comment]
Closing with the merge of #1360
