### ISSUE TITLE
[SDL 0023] Update Mobile API to Include Mandatory Flag on Parameters

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_core#1278]
Proposal: [Update Mobile API to Include Mandatory Flag on Parameters](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0023-update-mobile-api-mandatory-flag.md)

> Currently within the spec that is used by core (MOBILE_API.xml ), there is a lack of consistency among structs and functions relating to their parameters not stating whether they are all mandatory or not.

Review: smartdevicelink/sdl_evolution#82

**Comment by jacobkeeler** [comment]
Closed via #1618
