### ISSUE TITLE
UTF-8: Core incorrect handles symbols of two or more bytes size

### ISSUE THREAD

**Issue by AStasiuk** [smartdevicelink/sdl_core#1364]
## Occurrence
Always
## Preconditions:
Core, HMI started HMI. First app activated on HMI. HMI level - FULL. 
## Steps to reproduce:
Start ATF_UTF-8_Genivi.lua (attached).
## Actual result: 
All PutFile request has INVALID_DATA response. Core processes symbols of two or more bytes size like several symbols with one byte size. That's why INVALID_DATA for 255 symbols size which more than two bytes.
## Expected result:
Correct handling large size symbols.
## Note:
 Also can use attached scripts for checking other APIs.

## Expected delivery

-  Source code updates 
-  Code comments 
-  UTs add/update 
-  ATF tests add/update (not required) 
-  Manual tests (not required) 
-  Add/update CI plans/jobs (not required) 
-  SDD updates (not required) 
-  Guidelines update (sdl_core_guides) (not required) 
-  Guidelines update (sdl_hmi_integration_guidelines) (not required)
[SmartDeviceLinkCore.txt](https://github.com/smartdevicelink/sdl_core/files/834436/SmartDeviceLinkCore.txt)
[ATF_UTF-8_Genivi.lua.txt](https://github.com/smartdevicelink/sdl_core/files/834438/ATF_UTF-8_Genivi.lua.txt)
[JSONWithdifferentLanguagesForApp_utf-8_Arabic.json.txt](https://github.com/smartdevicelink/sdl_core/files/834439/JSONWithdifferentLanguagesForApp_utf-8_Arabic.json.txt)

**Comment by AStasiuk** [comment]
[SmartDeviceLinkCore.txt](https://github.com/smartdevicelink/sdl_core/files/834428/SmartDeviceLinkCore.txt)

**Comment by vvvakulenko** [comment]
**Reproducible**
SDL: HEAD of https://github.com/smartdevicelink/sdl_core/tree/feature/extended_policy_functionality
(commit d5f63b4f66d9ab945d452dfb1c07bf7ee3ca781e)
ATF: HEAD of https://github.com/smartdevicelink/sdl_atf/tree/develop
(commit aa5beae6ab1726a9b43ed2fa15f66c20d7f7883f)

**Comment by LitvinenkoIra** [comment]
Priority is medium because Putfile functionality does not work in some specific cases like name of the file contains symbols of two or more bytes and length of file name is more than 255 symbols

**Comment by GetmanetsIrina** [comment]
Defect is reproduced on current develop branch(621080dafb543db973d15ba7415c1eb60833a8b0), but with resultCode "GENERIC_ERROR".
Script for reproducing https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/1950.
ATF: develop.
