### ISSUE TITLE
SDL do not attach binary data to OnSystemRequest notification during Policy update in EXTERNAL_PROPRIETARY mode

### ISSUE THREAD

**Issue by LuxoftAKutsan** [smartdevicelink/sdl_core#1376]
## Occurrence:
Always

## Steps to reproduce:
1. Make sure SDL is built with EXTERNAL_PROPRIETARY flag
2. Start SDL and HMI
3. Connect mobile device
4. Register mobile application => Policy Table Update sequence started
5. Check that SDL sends ‘OnSystemRequest’ notification to mobile application
6. Check binary data of this notification

## Expected result:
Policy Table Snapshot is attached as binary data for ‘OnSystemRequest’

## Actual result:
SDL send OnSystemRequest to Mobile without binary field 

## Test script:
[1376_PTU_all_flows.lua](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Defects/4_5/1376_PTU_all_flows.lua)

## Environment:
repo: https://github.com/smartdevicelink/sdl_core/
branch: release/4.3.0 (head of branch)
ATF version: 2.2, commit b91f4b89f0230c48c76da082432f61f6bac4a0d5

## Expected delivery

- [x]  Source code updates
- [x]  Code comments
- [x]  UTs add/update
- [x]  ATF tests add/update
- [ ]  Add/update CI plans/jobs
- [ ]  SDD updates
- [ ]  Guidelines update (sdl_core_guides)
- [ ]  Guidelines update (sdl_hmi_integration_guidelines)

**Comment by LuxoftAKutsan** [comment]
Priority high
Significant part of policy update functionality missed

**Comment by LitvinenkoIra** [comment]
Works correctly on current develop (9e95f67)
Script for verifying and testing report in attachments [1376.tar.gz](https://github.com/smartdevicelink/sdl_core/files/1538887/1376.tar.gz)

**Comment by dboltovskyi** [comment]
Issue is reproduced on commit 458fa67468b2c10a7f8eb18277a83eb90c2f8004 with 'EXTERNAL_PROPRIETARY' SDL flow.
Description changed accordingly.
Test script [1376_PTU_all_flows.lua](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Defects/4_5/1376_PTU_all_flows.lua) is updated

**Comment by mrapitis** [comment]
Current status: issue needs to be retest with updated test script using EXTERNAL_PROPRIETARY flow.

**Comment by JackLivio** [comment]
Manually performing policy table update with EXTERNAL_PROPRIETARY works on release 4.5.0. Binary data is attached. Closing issue.
