### ISSUE TITLE
Release Branch Fatal Error

### ISSUE THREAD

**Issue by JackLivio** [smartdevicelink/sdl_core#138]
I am trying to start the version of SDL Core on the release/4.0.0 branch and am getting a fatal error "HMI index.hml doesn't exist!" 

Is there any setup/configuration that is different from the version of SDL core on the develop branch that might cause this error?

**Comment by AGaliuzov** [comment]
There is another opensource project named WebHMI. 
Please find Readme here
https://github.com/LuxoftSDL/sdl_hmi

In short, you have to run HMI(index.html) to make SDL Core workable.

**Comment by justinjdickow** [comment]
If this is the new way of separating HMIs, can you please move the sdl_hmi repo into the smartdevicelink GitHub so that everything is in one place and update the sdl_core readme with new instructions...

**Comment by JackLivio** [comment]
HMI repo has been moved/merged to smart device link github. S'all goodman.
