### ISSUE TITLE
SDL doesn't deactivate app when receives BasicCommunication.OnEventChange(PHONE_CALL,true) from HMI

### ISSUE THREAD

**Issue by dboltovskyi** [smartdevicelink/sdl_core#1385]
**Occurrence:** Always

**Steps:**
1. Send BasicCommunication.OnEventChanged(Phone_Call,true) from HMI when apps are full 

**Expected result:**
When SDL received BasicCommunication.OnEventChanged(Phone_Call,true) from HMI:
- With Media/VOICE Com app: SDL should send OnHMIStatus(BACKGROUND, NOT_AUDIBLE,MAIN) to mobile app
- With the Navi app: SDL should send OnHMIStatus(LIMITED, NOT_AUDIBLE,MAIN) to mobile app

**Actual result:**
- For VOICE Com app: SDL sends OnHMIStatus(FULL)

**Environment:**
ATF: aa5beae6ab1726a9b43ed2fa15f66c20d7f7883f
SDL: 7bd5326e8a6f5127220bf938a5be3063bdbb4ab4
Parameters: EXTENDED_POLICY=PROPRIETARY

**Comment by dboltovskyi** [comment]
[2017-03-20.tar.gz](https://github.com/smartdevicelink/sdl_core/files/855196/2017-03-20.tar.gz)

**Comment by dboltovskyi** [comment]
Script&Logs: [2017-03-20_1.tar.gz](https://github.com/smartdevicelink/sdl_core/files/855200/2017-03-20_1.tar.gz)

**Comment by ValeriiMalkov** [comment]
ATF test scripts will update for this issue.

**Comment by dboltovskyi** [comment]
Issue is still applicable for `6.1` release.
Updated ATF script and logs: [2020-06-15_13-36-35_1385.tar.gz](https://github.com/smartdevicelink/sdl_core/files/4782528/2020-06-15_13-36-35_1385.tar.gz)

**Comment by JackLivio** [comment]
Fixed with merge of #2582
