### ISSUE TITLE
[Policies]: "application" table contains "certificate"

### ISSUE THREAD

**Issue by dboltovskyi** [smartdevicelink/sdl_core#1386]
**Occurrence:** Always
**Preconditions:**
1. sdl_preloaded is original after SDL was built

**Steps:**
1. Start SDL
2. Extract policy database and check "application" table

**Expected result:**
"certificate" column is present in "module_config" only

**Actual result:**
"certificate" column is present both in "module_config" and "application" tables

**Environment:**
ATF: aa5beae6ab1726a9b43ed2fa15f66c20d7f7883f
SDL: 7bd5326e8a6f5127220bf938a5be3063bdbb4ab4

**Comment by jacobkeeler** [comment]
Closing due to this field being used in the implementation of #2215
