### ISSUE TITLE
[Protocol] SDL sends UnregisterAppInterface response over v.4 while app is registered over v.3 protocol

### ISSUE THREAD

**Issue by dboltovskyi** [smartdevicelink/sdl_core#1388]
**Occurrence:** Always
**Preconditions:**
1. Core, HMI started.
2. App is registered over v.3 protocol (specify min=1 max=3 Protocol Version in RAI) and in FULL

**Steps:**
1. Send UnregisterAppInterface

**Expected result:**
SDL responds with success over v.3 protocol

**Actual result:**
SDL responds with success over v.4 protocol

**Environment:**
ATF: aa5beae6ab1726a9b43ed2fa15f66c20d7f7883f
SDL: 7bd5326e8a6f5127220bf938a5be3063bdbb4ab4

**Comment by dboltovskyi** [comment]
Script&Logs: [2017-03-20_1.tar.gz](https://github.com/smartdevicelink/sdl_core/files/855340/2017-03-20_1.tar.gz)

**Comment by jacobkeeler** [comment]
Duplicate of #1365
