### ISSUE TITLE
[Resumption] SDL sends redundant notification Buttons.OnButtonSubscription with subscribed "CUSTOM_BUTTON" during resumption

### ISSUE THREAD

**Issue by maria-mih** [smartdevicelink/sdl_core#1391]
**Occurrence:**
Always

**Precondition:**
Path to files:
Use SDL and ATF Build from environment details below. 
Remove storage folder in SDL_build/bin.

**Steps to reproduce:**
Run script https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/feature/extended_policy_functionality/test_scripts/Resumption/ATF_Resumption_PersistentData.lua 

**Actual result:**
SDL sends redundant notification Buttons.OnButtonSubscription with subscribed "CUSTOM_BUTTON" during resumption for step Resumption_data

**Expected result:**
Only one Buttons.OnButtonSubscription notification should be sent. 

**Environment**
Branch repository: https://github.com/smartdevicelink/sdl_core.git 
SDL branch: feature/extended_policy_functionality 
Commit: 7bd5326e8a6f5127220bf
HMI: HTML5 
OS: 14.04.01 
Virtual machine:no 
ATF repository: https://github.com/smartdevicelink/sdl_atf
ATF branch: develop 
ATF commit: aa5beae6ab1726a9b43ed

[Uploading SmartDeviceLinkCore_Resumption_Persistent_Data.zip…]()
[Uploading ATF_Resumption_PersistentData_20170320165553.txt…]()
[Uploading ATF_Resumption_PersistentData_20170320165553_xml.txt…]()

**Comment by iCollin** [comment]
Closed as not reproducible against the first 7.1 release candidate.
Please let me know if you believe this issue is still actual.
