### ISSUE TITLE
File Names Caching in SDL core

### ISSUE THREAD

**Issue by madhuy** [smartdevicelink/sdl_core#1393]
SDL core Caches the file names and responds to 'ListFiles' Request from [Cache](https://github.com/smartdevicelink/sdl_core/blob/master/src/components/application_manager/src/commands/mobile/list_files_request.cc#L80) instead of Enumerating through the file system.

Issue is, There is possibility that System(HU) delete files, in  that case 'ListFiles' response  is invalid.

**Comment by JackLivio** [comment]
@madhuy Is core deleting the file or is it some other part of the head unit deleting the file?

**Comment by madhuy** [comment]
@JackLivio NOT SDL core. other part of Head unit Native.

**Comment by madhuy** [comment]
@JackLivio Please let me know if you have any concerns to enumerating  through file system. 
GetFiles from Cache been called twice.
- from Listfiles
- from resumption apps.

other purpose of cache is to send file [removed notification ](https://github.com/smartdevicelink/sdl_core/blob/master/src/components/application_manager/src/commands/mobile/delete_file_request.cc#L84) .

**Comment by goelgoldi** [comment]
@theresalech this is high priority ticket for Xevo.

**Comment by madhuy** [comment]
PR is here https://github.com/smartdevicelink/sdl_core/pull/1484

**Comment by LitvinenkoIra** [comment]
@JackLivio is this issue shouldn't be closed? I see PR related to this Issue.

**Comment by LitvinenkoIra** [comment]
Works correctly on current develop (8c94933)
Script for verifying and testing report [1393.tar.gz](https://github.com/smartdevicelink/sdl_core/files/1527488/1393.tar.gz)
