### ISSUE TITLE
SDL doesn't apply sequence SUSPEND -> OnSDLAwake -> SUSPEND -> IGN_OFF for saving resumption data

### ISSUE THREAD

**Issue by istoimenova** [smartdevicelink/sdl_core#1395]
## Occurrence:
Always

## Steps to reproduce:
1. Make sure SDL is built with default flags
2. Start SDL and HMI
3. Connect mobile device
4. Register mobile application
5. Activate application in order to switch it to FULL HMI level
6. Add some data according to data resumption requirements, e.g. AddCommand
7. Send OnExitAllApplications(SUSPEND)
8. Send some resumption data again

## Expected result:
SDL does:
1. Store all applications resumption-related data on the file system
2. Send BC.OnSDLPersistenceComplete to HMI on data persistance complete
3. Continue remembering resumption related data (in case getting some from mobile application)
without sending OnHashChanged notification to mobile app. - OnHashChanged should be sent
only after OnSDLAwake notification.

## Actual result:
SDL does:
1. Save data in app_info.dat and send OnHashChanged notification

## Test script:
[1395_Resumption_data_IGN_OFF.lua](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Defects/4_5/1395_Resumption_data_IGN_OFF.lua)

## Environment:
SDL repo: https://github.com/smartdevicelink/sdl_core/tree/feature/extended_policy_functionality
SDL commit: 7bd5326
OS with SDL: Ubuntu 14.04
VM used for OS with SDL (yes/no): no
ATF version: aa5beae6ab1726a9b43ed2fa15f66c20d7f7883f
Transport: WiFi

## Attachments
[Uploading SmartDeviceLinkCore.log.zip…]()

Requirements:
[Data Resumption]:OnExitAllApplications(SUSPEND) in terms of resumption
[Data Resumption]:OnExitAllApplications(IGNITION_OFF) in terms of resumption

## Expected delivery
- [ ]  Source code updates
- [ ]  Code comments
- [ ]  UTs add/update
- [ ]  ATF tests add/update
- [ ]  Manual tests
- [ ]  Add/update CI plans/jobs
- [ ]  SDD updates
- [ ]  Guidelines update (sdl_core_guides)
- [ ]  Guidelines update (sdl_hmi_integration_guidelines)

**Comment by GetmanetsIrina** [comment]
Reproduced on develop (9e95f67178c575ca5a537f9ef3a69653219b073d)
Works correctly on https://github.com/AKalinich-Luxoft/sdl_core/tree/fix/fix_data_resumption_flow (1f59584)
Script for verifying is https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Defects/4_5/1395_Resumption_data_IGN_OFF.lua

**Comment by mrapitis** [comment]
Reviewed ATF script and ran successfully. Successfully reproduced issue with provided commit. Reviewed code with and requested any changes to public methods require appropriate deprecation.

**Comment by JackLivio** [comment]
fix merged
