### ISSUE TITLE
CCB: Fix wrong success code for ReadDID request truncated data 

### ISSUE THREAD

**Issue by aderiabin** [smartdevicelink/sdl_core#1399]
### Bug Report
SDL returns mobile CANCEL_ROUTE with success: false if it received TRUNCATED_DATA from HMI

##### Reproduction Steps
- Start SDL and HMI
- Connect mobile and create mobile session
- Register mobile App
- Activate mobile App
- Perform PTU sequence
- Send RPC "ReadDID" from mobile App 
- Send response on request "VehicleInfo.ReadDID" from HMI with resultCode = "TRUNCATED_DATA"

##### Expected Behavior
SDL sends TRUNCATED_DATA with success: true to mobile

##### Observed Behavior
SDL sends TRUNCATED_DATA with success: false to mobile

##### OS & Version Information
* OS/Version: Ubuntu 16.04
* SDL Core Version: 65ade78808a37560c1a55de058201a10296f14d1
* Testing Against: ATF

##### Test Case, Sample Code, and / or Example App
Script: [ATF_ReadDID_TRUNCATED_DATA.tar.gz](https://github.com/smartdevicelink/sdl_core/files/857446/ATF_ReadDID_TRUNCATED_DATA.tar.gz)

**Comment by robinmk** [comment]
The description makes a mention of CANCEL_ROUTE while there is no further mention of it in the steps or results.  Please ensure issue is accurate

**Comment by JackLivio** [comment]
@aderiabin  If there is a milestone related to this issue could you please add it?

**Comment by LitvinenkoIra** [comment]
Defect is reproduced.
SDL branch: develop(e137556)
ATF: develop
Script: smartdevicelink/sdl_atf_test_scripts#2137

**Comment by LitvinenkoIra** [comment]
#2370 - rebased to the latest develop
Fix is valid

**Comment by LitvinenkoIra** [comment]
Full regression successfully passed
SDL: fix/wrong_success_code_for_re 38f63bde
Scripts: develop 6f43bfd
ATF: develop 37da7aba

**Comment by LitvinenkoIra** [comment]
@theresalech Please triage this issue

**Comment by theresalech** [comment]
@LitvinenkoIra We are currently working on finalizing the roadmap with the Steering Committee, so will keep this issue in consideration for upcoming Core releases.

**Comment by iCollin** [comment]
Closed via #2370
