### ISSUE TITLE
[TM] SPT can't establish connection with SDL if bluetooth was activated on phone after SPT's start

### ISSUE THREAD

**Issue by maria-mih** [smartdevicelink/sdl_core#1400]
**Occurrence:** 
Always

**Preconditions:** 
1. Bluetooth is active on SDL's server.
2. App has started, bluetooth will be a transport

**Steps to reproduce:**
1. start SDL.
2. Turn on Bluetooth on the phone

**Actual result:**
Unable to register App via Bluetooth in current ignition cycle, even if exit App and start again with established bluetooth connection again.

**Expected result:**
SDL shoudl establish connection via BT

**Note**
If perform ignition off-on then App will be registered successfully

**Environment:**
Branch repository: https://github.com/smartdevicelink/sdl_core.git 
SDL branch: feature/extended_policy_functionality 
Commit: 7bd5326e8a6f5127220bf
HMI: HTML5 
OS: 14.04.01 
Virtual machine:no 
Transport: Bluetooth
Mobile device: Acer Iconia B1-710 
Mobile OS: Android
Mobile App version: Luxoft SPT, version 2.1.85 
Mobile App type (media/non-media/navi): Media

[HMI_log.zip](https://github.com/smartdevicelink/sdl_core/files/857451/HMI_log.zip)
[SmartDeviceLinkCore.zip](https://github.com/smartdevicelink/sdl_core/files/857452/SmartDeviceLinkCore.zip)
[TransportManager.zip](https://github.com/smartdevicelink/sdl_core/files/857453/TransportManager.zip)

**Comment by AByzhynar** [comment]
As issue is not SDL defect - it will be closed.
