### ISSUE TITLE
[SDL 0042] SDL must transfer RPC’s with invalid image reference parameters to the HMI

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_core#1428]
Proposal: [SDL must transfer RPC’s with invalid image reference parameters to the HMI](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0042-transfer-invalid-image-rpc.md)

> Update SDL Core behavior to more gracefully handle RPC requests that provide an invalid image reference. Any RPC that provides a reference to an image that is not located in the AppStoreFolder is considered invalid (the AppStoreFolder is specified in the SmartDeviceLink.ini.)

Review: https://github.com/smartdevicelink/sdl_evolution/issues/128

Steering Committee Decision:

> The Steering Committee has agreed to accept this proposal. They also recommended that an additional proposal be submitted for the additional post loading of content.

**Comment by jacobkeeler** [comment]
Closing with the merge of #2276
