### ISSUE TITLE
[SDL 0041] Provide AppIcon resumption across app registration requests

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_core#1456]
Proposal: [Provide AppIcon resumption across app registration requests](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0041-appicon-resumption.md)

> This proposal is to simplify (and speed up) the process of setting an app icon across app registration requests.

Review: https://github.com/smartdevicelink/sdl_evolution/issues/127

**Comment by askirk** [comment]
* Tested with SPT & Core branch (TCP)
* Reviewed Code
* Ran Smoke and Resumption ATF tests

**Comment by jacobkeeler** [comment]
Closing with the merge of #2126

**Comment by theresalech** [comment]
Proposal markdown file has been updated per the revisions included in accepted Evolution Proposal [Revise SDL-0041 - AppIcon Resumption](https://github.com/smartdevicelink/sdl_evolution/pull/560).  Implementation will need to be revised to change the `iconResumed` parameter to optional, and make some formatting fixes.

**Comment by JackLivio** [comment]
Closing. Fixed by #2487
