### ISSUE TITLE
[SDL 0040] DTLS encryption

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_core#1479]
Proposal: [DTLS encryption](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0040-DTLS-encryption.md)

> This proposal is to add DTLS (Datagram Transport Layer Security) to SDL core. SDL core will utilize the DTLS communications protocol as a preferred solution when sending encrypted data over protected services (such audio 0x0a and video 0x0b ) including the handshake, encryption and decryption processes.

Review: https://github.com/smartdevicelink/sdl_evolution/issues/126

Steering Committee Decision:

> The Steering Committee has agreed to accept this proposal. They've also agreed that we should target Android and iOS library changes as an additional proposal, as this cannot be tested without the library portion.

**Comment by theresalech** [comment]
Closed via #2068

**Comment by FStoikov** [comment]
Jira ticket created for current case: https://adc.luxoft.com/jira/browse/FORDTCN-810
