### ISSUE TITLE
[SDL 0046] Implement logger abstraction

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_core#1480]
Proposal: [Implement logger abstraction](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0046-implement-logger-abstraction.md)

> The good abstraction for the logger allows to easily substitute the logger library from one to another in the case of necessity. The different system has different logging mechanism and SDL has to be easily integrated to use any logger library as a background sink.

Review: https://github.com/smartdevicelink/sdl_evolution/issues/141

**Comment by ShobhitAd** [comment]
Closed via https://github.com/smartdevicelink/sdl_core/pull/3472
