### ISSUE TITLE
Mobile_Api has incorrect param and enum

### ISSUE THREAD

**Issue by joeygrover** [smartdevicelink/sdl_core#1503]
The current [MOBILE_API.xml](https://github.com/smartdevicelink/sdl_core/blob/master/src/components/interfaces/MOBILE_API.xml) file has an enum and param that were never approved.

[HmiZoneCapabilities](https://github.com/smartdevicelink/sdl_core/blob/master/src/components/interfaces/MOBILE_API.xml#L398)

RegisterAppInterface response uses [this as a param](https://github.com/smartdevicelink/sdl_core/blob/develop/src/components/interfaces/MOBILE_API.xml#L2536) and shouldn't. 

Mobile libraries never implemented this, however, we will still need to bump the minor version to fix.

**Comment by jacobkeeler** [comment]
Now that the mobile libraries use the Mobile API directly to generate their data types, I believe they are aligned with SDL Core and have this parameter implemented now. While the parameter isn't used, I'm thinking a proposal would need to be submitted to fix at this point. Closing this issue for now.
