### ISSUE TITLE
Media app switched Audio Source to FM, onHMIStatus gives wrong state

### ISSUE THREAD

**Issue by yang1070** [smartdevicelink/sdl_core#1507]
Media app switched Sources FM,onHMIStatus gives wrong state

**Occurrence:** 
Always

**PreConditions:**
[iPhone connected via USB
Vehicle ignition set to ON and RUN. 
SyncProxyTester (Media) App running on phone and SYNC with HMI Full and Audible 
]

**Reproduction Steps:**
[Step 1]:Change source to FM Radio
[Step 2]:Verify the OnHMIStatus notification on the Test App

**Expected Behavior**
[OnHMIStatus for the test app displays HMILevel=Background and Not_Audible]

**Observed Behavior**
[OnHMIStatus for the test app displays HMILevel=Limited and Audible]

**OS & Version Information**
Phone Type/Model and OS version: [iphone 6 with ios 10.2.1]
Mobile Application name and version: [Version of SPT3_resigned.ipa]
Connection Type: Wi-Fi/Bluetooth/USB: [Wi-Fi ]

Probably related to that DeactivateReason  is removed from OnAppDeactivated RPC, 
the same root cause as https://github.com/smartdevicelink/sdl_core/issues/1390

**Comment by dboltovskyi** [comment]
Issue is not reproduced within ATF script using `6.1` release.
Script and logs: [2020-06-15_16-36-13_1507.tar.gz](https://github.com/smartdevicelink/sdl_core/files/4782853/2020-06-15_16-36-13_1507.tar.gz)
