### ISSUE TITLE
LOG4cxx Crashes(SIGSEGV) while exit SDLcore by using SIGTERM 

### ISSUE THREAD

**Issue by madhuy** [smartdevicelink/sdl_core#1522]
Details for crash explained in https://issues.apache.org/jira/browse/LOGCXX-322
We experienced this crash in our HU's.

We might need to apply this patch https://issues.apache.org/jira/secure/attachment/12634687/130-bugfix-LOGCXX-322.dpatch to fix this issue.

**Comment by iCollin** [comment]
Closing as not reproducible on latest [develop](https://github.com/smartdevicelink/sdl_core/tree/develop).
