### ISSUE TITLE
Are "Long" and "Double" allowed in the API defintions in the xml files?

### ISSUE THREAD

**Issue by ojmakke** [smartdevicelink/sdl_core#154]
So far we have "Integer" and "Float" in HMI_API.xml and MOBILE_API.xml

Are "Long" and "Double" allowed? The intention is to define 64-bit length values.

Are "Integer" and "Float" assumed to be definitions for 32-bit values?

**Comment by genivi** [comment]
From Core's perspective, they're all just "numbers". They are translated on
the mobile side so you can check 64 bit compatibility and type conversions
for any of the RPCs

https://github.com/smartdevicelink/sdl_android/blob/develop/sdl_android_lib/src/com/smartdevicelink/proxy/rpc/OnVehicleData.java#L98-L101
https://github.com/smartdevicelink/sdl_android/blame/develop/sdl_android_lib/src/com/smartdevicelink/util/SdlDataTypeConverter.java

best,

justin


justin dickow, product development project manager

justin@livio.io

cell: 248-842-2836

office: 248-591-0333, ext 889.

skype: justin.dickow.livio


3136 Hilton, Ferndale, MI 48220
