### ISSUE TITLE
README should not reference "v4tester" application

### ISSUE THREAD

**Issue by joeljfischer** [smartdevicelink/sdl_core#1547]
In the README, it is recommended that people should use an iOS "v4tester" application that links to a random box account download. This is _absolutely not_ how people should get started. They should use the example app in the iOS library, or hello_android, or pretty much anything other than that. The "v4tester" application was never built for this purpose or even to be shared, is not supported or updated, and I have no idea how it got into distribution.

**Comment by jacobkeeler** [comment]
Fixed with the merge of https://github.com/smartdevicelink/sdl_core/pull/1780
