### ISSUE TITLE
SDL respond with UnregisterAppInterface using protocol version 4

### ISSUE THREAD

**Issue by dsmyrnov** [smartdevicelink/sdl_core#1580]
*Environment:*
OS: Ubuntu 16.04.
ARC: PC (x86)
SDL - Tag 4.2.1 commit e98cef9
*Occurrence:*
Always
*Preconditions:*
SDL is running and HMI is connected to SDL
App is registered with SDL using protocol version 2
*Steps to reproduce:*
Send UnregisterAppInterface
*Actual result:*
SDL respond using protocol version 4
*Expected result:*
SDL respond using protocol version 2

**Comment by jacobkeeler** [comment]
Unable to reproduce on [master branch](https://github.com/smartdevicelink/sdl_core/commit/6212599da217e95899d63d4b33088082489841bd), closing
