### ISSUE TITLE
PerformInteraction: SDL doesn't ignore ABORTED result code from VR.PerformIntercation in case of BOTH mode

### ISSUE THREAD

**Issue by DrachenkoAnastasiia** [smartdevicelink/sdl_core#1583]
## Occurrence
Always

## Preconditions
1. SDL is built with Proprietary flag.
2. SDL and HMI are started. First ignition cycle.
3. Connect device
4. Register new application.
5. Put icon.png file using PutFile RPC
6. Create a сhoiceSet with VR choices:interactionChoiceSetID1

## Steps to reproduce
1. PerfromInteraction with previously created choiceSet:
app -> SDL:PerfromInteracton(interactionChoiceSetID1, interactionMode = "BOTH")
2. SDL sends the both: VR and UI portion
SDL->HMI: VR.PerformInteraction()
SDL->HMI: UI.PerfrormInteraction()
3. Make the following choices:
HMI->SDL: VR.PerformInteraction(): SendError("ABORTED")
HMI->SDL: UI.PerformInteraction(): SendResponse("UNSUPPORTED_RESOURCE")
4. SDL->App: PerfromInteracton response --> check parameters

## Actual result
{ success = false, resultCode = "ABORTED" } 

## Expected result
{ success = true, resultCode = "UNSUPPORTED_RESOURCE"} 

# Environment
SDL: https://github.com/LuxoftAKutsan/sdl_core/tree/integration/4.3.1 (35344c8)
ATF: https://github.com/smartdevicelink/sdl_atf/tree/develop (fe002fb)
ATF Scripts: https://github.com/smartdevicelink/sdl_atf_test_scripts/tree/develop (4ba374c)
OS: Ubuntu 14.04 LTS x64

# Attachments
[SDLOPEN-2443.zip](https://github.com/smartdevicelink/sdl_core/files/1044867/SDLOPEN-2443.zip)

# Expected delivery   
- [ ] Source code updates 
- [ ] Code comments 
- [ ] UTs add/update 
- [ ] ATF tests add/update ***(not required)***  
- [x] Manual tests ***(not required)*** 
- [x] Add/update CI plans/jobs ***(not required)***  
- [x] SDD updates ***(not required)***  
- [x] Guidelines update ([sdl_core_guides](https://github.com/smartdevicelink/sdl_core_guides)) ***(not required)***  
- [x] Guidelines update ([sdl_hmi_integration_guidelines](https://github.com/smartdevicelink/sdl_hmi_integration_guidelines))  ***(not required)***

**Comment by jacobkeeler** [comment]
Closing with the merge of #3587
