### ISSUE TITLE
UnregisterAppInterface: SDL doesn't reply APPLICATION_NOT_REGISTERED for not registered application

### ISSUE THREAD

**Issue by DrachenkoAnastasiia** [smartdevicelink/sdl_core#1584]
## Occurrence
Always

## Preconditions
1. SDL is built with Proprietary flag.
2. SDL and HMI are started. First ignition cycle.
3. Connect device
4. Register new application.

## Steps to reproduce
1. Unregister application:
App->SDL: UnregisterAppInterface() --> SUCCESS
2. Register application
App->SDL: UnregisterAppInterface()

## Actual result
{ success = false, resultCode = "GENERIC_ERROR" } 

## Expected result
{ success = false, resultCode = "APPLICATION_NOT_REGISTERED"}

# Environment
SDL: https://github.com/LuxoftAKutsan/sdl_core/tree/integration/4.3.1 (35344c8)
ATF: https://github.com/smartdevicelink/sdl_atf/tree/develop (fe002fb)
ATF Scripts: https://github.com/smartdevicelink/sdl_atf_test_scripts/tree/develop (4ba374c)
OS: Ubuntu 14.04 LTS x64

# Attachments
[SDLOPEN-2444.zip](https://github.com/smartdevicelink/sdl_core/files/1044929/SDLOPEN-2444.zip)

# Expected delivery   
- [ ] Source code updates 
- [ ] Code comments 
- [ ] UTs add/update 
- [ ] ATF tests add/update ***(not required)***  
- [x] Manual tests ***(not required)*** 
- [x] Add/update CI plans/jobs ***(not required)***  
- [x] SDD updates ***(not required)***  
- [x] Guidelines update ([sdl_core_guides](https://github.com/smartdevicelink/sdl_core_guides)) ***(not required)***  
- [x] Guidelines update ([sdl_hmi_integration_guidelines](https://github.com/smartdevicelink/sdl_hmi_integration_guidelines))  ***(not required)***

**Comment by iCollin** [comment]
Closed via https://github.com/smartdevicelink/sdl_core/pull/3705
