### ISSUE TITLE
[SDL 0053] Connectivity via iAP-BT and Transport Switch

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_core#1587]
Proposal: [Connectivity via iAP-BT and Transport Switch](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0053-Connectivity-via-iAP-BT-and-Transport-Switch.md)

> This feature allows iOS devices to be connected with the Head Unit via Bluetooth without requiring a wired USB connection for registering media and non-media apps and also provides provision for transitioning to USB connection once the iOS device is also connected via USB.

Review: https://github.com/smartdevicelink/sdl_evolution/issues/158

Steering Committee Decision:

> With the inclusion of the diagram posted on this review on 2017-05-15, this proposal has been accepted by the Steering Committee. The Ford and Xevo teams have also discussed additional enhancements for this feature and will be entering separate proposals for such.

**Comment by jacobkeeler** [comment]
Closed with the merge of #1927
