### ISSUE TITLE
Build error with QT HMI

### ISSUE THREAD

**Issue by RayBloodworth** [smartdevicelink/sdl_core#159]
Error occurs building sdl core with qt hmi.

Generating files:
   /home/work/SDL/sdl_core-release-4.0.0/src/components/interfaces/QT_HMI_API.h;/home/work/SDL/sdl_core-release-4.0.0/src/components/interfaces/QT_HMI_API_schema.h
   /home/work/SDL/sdl_core-release-4.0.0/src/components/interfaces/QT_HMI_API_schema.cc
from:
   QT_HMI_API.xml ...

Generating interface source code with following parameters:
    Source xml      : /home/work/SDL/sdl_core-release-4.0.0/src/components/interfaces/QT_HMI_API.xml
    Namespace       : hmi_apis
    Output directory: /home/work/SDL/sdl_core-release-4.0.0/src/components/interfaces
    Parser type     : jsonrpc

Unknown type 'Common.DeviceInfo'

**Comment by justinjdickow** [comment]
See #151 for the hotfix to this issue.
