### ISSUE TITLE
Lock screen icon URL should be updated

### ISSUE THREAD

**Issue by joeljfischer** [smartdevicelink/sdl_core#1646]
Currently the default SDL Core icon that is sent to be used on the phone lock screens is [found here](https://github.com/smartdevicelink/sdl_core/blob/master/src/appMain/sdl_preloaded_pt.json#L25) which points to http://i.imgur.com/QwZ9uKG.png

![old sdl image](http://i.imgur.com/QwZ9uKG.png)

We should update it for the redesign and rebrand of SDL.

**Comment by jacobkeeler** [comment]
Fixed with the merge of #2055
