### ISSUE TITLE
build apache-log4cxx error

### ISSUE THREAD

**Issue by yafei323154** [smartdevicelink/sdl_core#1647]
*** Warning: inter-library dependencies are not known to be supported.
*** All declared inter-library dependencies are being dropped.
*** The inter-library dependencies that have been dropped here will be
*** automatically added whenever a program is linked with this library
*** or is declared to -dlopen it.
/home/jiyou/qnx660/host/linux/x86/usr/bin/CC -shared -nostdlib /home/jiyou/qnx660/target/qnx6/x86/lib/crti.o /home/jiyou/qnx660/host/linux/x86/usr/lib/gcc/i486-pc-nto-qnx6.6.0/4.7.3/pic/crtbegin.o  .libs/action.o .libs/appenderattachableimpl.o .libs/appenderskeleton.o .libs/aprinitializer.o .libs/asyncappender.o .libs/basicconfigurator.o .libs/bufferedwriter.o .libs/bytearrayinputstream.o .libs/bytearrayoutputstream.o .libs/bytebuffer.o .libs/cacheddateformat.o .libs/charsetdecoder.o .libs/charsetencoder.o .libs/class.o .libs/classnamepatternconverter.o .libs/classregistration.o .libs/condition.o .libs/configurator.o .libs/consoleappender.o .libs/cyclicbuffer.o .libs/dailyrollingfileappender.o .libs/datagrampacket.o .libs/datagramsocket.o .libs/date.o .libs/dateformat.o .libs/datelayout.o .libs/datepatternconverter.o .libs/defaultloggerfactory.o .libs/defaultconfigurator.o .libs/defaultrepositoryselector.o .libs/domconfigurator.o .libs/exception.o .libs/fallbackerrorhandler.o .libs/file.o .libs/fileappender.o .libs/filedatepatternconverter.o .libs/fileinputstream.o .libs/filelocationpatternconverter.o .libs/fileoutputstream.o .libs/filerenameaction.o .libs/filewatchdog.o .libs/filter.o .libs/filterbasedtriggeringpolicy.o .libs/fixedwindowrollingpolicy.o .libs/formattinginfo.o .libs/fulllocationpatternconverter.o .libs/gzcompressaction.o .libs/hierarchy.o .libs/htmllayout.o .libs/inetaddress.o .libs/inputstream.o .libs/inputstreamreader.o .libs/integer.o .libs/integerpatternconverter.o .libs/layout.o .libs/level.o .libs/levelmatchfilter.o .libs/levelrangefilter.o .libs/levelpatternconverter.o .libs/linelocationpatternconverter.o .libs/lineseparatorpatternconverter.o .libs/literalpatternconverter.o .libs/loggerpatternconverter.o .libs/loggingeventpatternconverter.o .libs/loader.o .libs/locale.o .libs/locationinfo.o .libs/logger.o .libs/loggingevent.o .libs/loglog.o .libs/logmanager.o .libs/logstream.o .libs/manualtriggeringpolicy.o .libs/messagebuffer.o .libs/messagepatternconverter.o .libs/methodlocationpatternconverter.o .libs/mdc.o .libs/mutex.o .libs/nameabbreviator.o .libs/namepatternconverter.o .libs/ndcpatternconverter.o .libs/ndc.o .libs/nteventlogappender.o .libs/objectimpl.o .libs/objectptr.o .libs/objectoutputstream.o .libs/obsoleterollingfileappender.o .libs/odbcappender.o .libs/onlyonceerrorhandler.o .libs/optionconverter.o .libs/outputdebugstringappender.o .libs/outputstream.o .libs/outputstreamwriter.o .libs/patternconverter.o .libs/patternlayout.o .libs/patternparser.o .libs/pool.o .libs/properties.o .libs/propertiespatternconverter.o .libs/propertyconfigurator.o .libs/propertyresourcebundle.o .libs/propertysetter.o .libs/reader.o .libs/relativetimedateformat.o .libs/relativetimepatternconverter.o .libs/resourcebundle.o .libs/rollingfileappender.o .libs/rollingpolicy.o .libs/rollingpolicybase.o .libs/rolloverdescription.o .libs/rootlogger.o .libs/serversocket.o .libs/simpledateformat.o .libs/simplelayout.o .libs/sizebasedtriggeringpolicy.o .libs/smtpappender.o .libs/socket.o .libs/socketappender.o .libs/socketappenderskeleton.o .libs/sockethubappender.o .libs/socketoutputstream.o .libs/strftimedateformat.o .libs/stringhelper.o .libs/stringmatchfilter.o .libs/stringtokenizer.o .libs/synchronized.o .libs/syslogappender.o .libs/syslogwriter.o .libs/system.o .libs/systemerrwriter.o .libs/systemoutwriter.o .libs/telnetappender.o .libs/threadcxx.o .libs/threadlocal.o .libs/threadspecificdata.o .libs/threadpatternconverter.o .libs/throwableinformationpatternconverter.o .libs/timezone.o .libs/timebasedrollingpolicy.o .libs/transform.o .libs/triggeringpolicy.o .libs/transcoder.o .libs/ttcclayout.o .libs/writer.o .libs/writerappender.o .libs/xmllayout.o .libs/xmlsocketappender.o .libs/zipcompressaction.o  /home/jiyou/qnx660/host/linux/x86/usr/lib/gcc/i486-pc-nto-qnx6.6.0/4.7.3/pic/crtend.o /home/jiyou/qnx660/target/qnx6/x86/lib/crtn.o  -Wl,-soname -Wl,liblog4cxx.so.10 -o .libs/liblog4cxx.so.10.0.0
.libs/action.o: In function `log4cxx::rolling::Action::close()':
/home/jiyou/sdl_core/src/3rd_party/apache-log4cxx-cmake/../apache-log4cxx-0.10.0/src/main/cpp/action.cpp:59: undefined reference to `__stack_chk_fail_local'
.libs/action.o: In function `log4cxx::rolling::Action::run(log4cxx::helpers::Pool&)':
/home/jiyou/sdl_core/src/3rd_party/apache-log4cxx-cmake/../apache-log4cxx-0.10.0/src/main/cpp/action.cpp:51: undefined reference to `__stack_chk_fail_local'
.libs/appenderattachableimpl.o: In function `log4cxx::helpers::AppenderAttachableImpl::removeAllAppenders()':
/home/jiyou/sdl_core/src/3rd_party/apache-log4cxx-cmake/../apache-log4cxx-0.10.0/src/main/cpp/appenderattachableimpl.cpp:124: undefined reference to `__stack_chk_fail_local'
.libs/appenderattachableimpl.o: In function `log4cxx::helpers::AppenderAttachableImpl::getAppender(std::string const&) const':
/home/jiyou/sdl_core/src/3rd_party/apache-log4cxx-cmake/../apache-log4cxx-0.10.0/src/main/cpp/appenderattachableimpl.cpp:98: undefined reference to `__stack_chk_fail_local'
.libs/appenderattachableimpl.o: In function `log4cxx::helpers::AppenderAttachableImpl::removeAppender(std::string const&)':
/home/jiyou/sdl_core/src/3rd_party/apache-log4cxx-cmake/../apache-log4cxx-0.10.0/src/main/cpp/appenderattachableimpl.cpp:158: undefined reference to `__stack_chk_fail_local'
.libs/appenderskeleton.o:/home/jiyou/sdl_core/src/3rd_party/apache-log4cxx-cmake/../apache-log4cxx-0.10.0/src/main/cpp/appenderskeleton.cpp:101: more undefined references to `__stack_chk_fail_local' follow
cc: /home/jiyou/qnx660/host/linux/x86/usr/bin/i486-pc-nto-qnx6.6.0-ld error 1
make[9]: *** [liblog4cxx.la] Error 1
make[8]: *** [all-recursive] Error 1
make[7]: *** [all-recursive] Error 1
make[6]: *** [all-recursive] Error 1
make[5]: *** [src/3rd_party/apache-log4cxx-cmake/CMakeFiles/liblog4cxx] Error 2
make[4]: *** [src/3rd_party/apache-log4cxx-cmake/CMakeFiles/liblog4cxx.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [CMakeFiles/3rd_party_logger] Error 2
make[1]: *** [CMakeFiles/3rd_party_logger.dir/all] Error 2
make: *** [all] Error 2

How can I solve it?

**Comment by jacobkeeler** [comment]
This is not an issue with the project, please direct questions like this to the `core-help` channel in the [SDL Slack group](http://slack.smartdevicelink.com/)
