### ISSUE TITLE
SDL respond with not valid params ("resultCode": -1 and "maximumChangeVelocity" as string) in GetVehicleData response

### ISSUE THREAD

**Issue by dsmyrnov** [smartdevicelink/sdl_core#1657]
Environment:
OS: Ubuntu 16.04.
ARC: PC (x86)
SDL - Tag 4.2.1 commit e98cef9
Occurrence:
Always
Preconditions:
SDL is running and HMI is connected to SDL
Steps to reproduce:
Register any application with SDL
Send GetVehicleData request with all params with value true 
Check GetVehicleData response
Actual result:
SDL respond with not valid params ("resultCode": -1 and "maximumChangeVelocity" as string)
[SDL_log.txt](https://github.com/smartdevicelink/sdl_core/files/1138153/SDL_log.txt)
Expected result:
SDL respond with valid GetVehicleData response
Requirements: MOBILE_API.xml

**Comment by jacobkeeler** [comment]
Unable to reproduce on master branch. Looks like the HMI is sending this `-1` result code and Core is just passing it though, so this issue can be submitted to whichever HMI you are using (assuming you are using a public HMI).
