### ISSUE TITLE
how build sdl_core in android system

### ISSUE THREAD

**Issue by roger1Lo** [smartdevicelink/sdl_core#1658]
I want to build the sdl_core in android system. I have see the issue (PR for AGL Port: #1159),but  it must use the AGL. Have any suggestions for just build in embedded linux without using AGL?

**Comment by joeygrover** [comment]
Please use the Slack channel for asking questions. This is not an issue with the project and therefore will be closed. 

There is no port available for building in Android. You will have to manually try to port it over and fix any dependency issues that arise.

**Comment by roger1Lo** [comment]
thanks

**Comment by Gnagdhar** [comment]
@roger1Lo 
Did u port sdl On Android??

**Comment by roger1Lo** [comment]
No,I didn't port it.
