### ISSUE TITLE
iAP over BT re-connection

### ISSUE THREAD

**Issue by OlesiaV** [smartdevicelink/sdl_core#1659]
## Description:
_When the device connects over USB, SDL core shall notify HMI about the change in transportType via the UpdateDeviceList RPC.  
To mitigate the disruption to the user’s UI experience SDL Core must hold off on sending to HMI the information about disconnect of the applications till a pre-configured “reconnection” timer expires.  
This “reconnection” timer would be added to the SmartDeviceLink.ini file.   
Application is expected to be re-registered during "reconnection" timer and in case if re-registration was unsuccessful, SDL core must proceed with "unexpectedDisconnect"._ 

## .ini file change ##

New parameters "AppTransportChangeTimer" , "AppTransportChangeTimerAddition"   must be added to .ini file -> [MAIN] section

```
[MAIN] 
"AppTransportChangeTimer" = 500 ms 
defines the timeout for waiting the mobile app to reconnect between Bluetooth and USB transports change

```

```
[MAIN] 
"AppTransportChangeTimerAddition" = 0ms
Defines the timeout  for waiting of every mobile app to reconnect between Bluetooth and USB transports change in case the number of connected apps is more than one
```

## Related Diagrams:

N/A

## Links:

- **Requirement:**  [#37](https://github.com/smartdevicelink/sdl_requirements/issues/37) iAP over BT re-connection
- **Parent task:**

**Comment by LuxoftAKutsan** [comment]
Implementation https://github.com/smartdevicelink/sdl_core/pull/1927

**Comment by jacobkeeler** [comment]
Closing with the merge of #1927

**Comment by aravinddd** [comment]
i am not able to connect my ios device with my hmi but usb connection is working
