### ISSUE TITLE
Handling notifications from HMI during re-connection

### ISSUE THREAD

**Issue by OlesiaV** [smartdevicelink/sdl_core#1660]
## Description:

_Responses to any requests made by the app just prior to the transport switch would be discarded by SDL Core.   
If the user triggers any interaction to the app, such interactions will be buffered by SDL Core till the app reconnects (within reconnection timeout period) at which point the requests will be sent to the app or till the expiry of the reconnection timer after which the requests will be discarded.  
HMI can use the UpdateDeviceList request from SDL core to display any message to the user informing about the transport switch._  

## .ini file change ##

New parameters "AppTransportChangeTimer" , "AppTransportChangeTimerAddition"   must be added to .ini file -> [MAIN] section

```
[MAIN] 
"AppTransportChangeTimer" = 500 ms 
defines the timeout for waiting the mobile app to reconnect between Bluetooth and USB transports change

```

```
[MAIN] 
"AppTransportChangeTimerAddition" = 0ms
Defines the timeout  for waiting of every mobile app to reconnect between Bluetooth and USB transports change in case the number of connected apps is more than one
```

## Related Diagrams:

![iap transport change reconnection](https://user-images.githubusercontent.com/23719788/28126084-2df0e89a-6731-11e7-8cb7-4f653b1eeb1e.png)

## Links:

- **Requirement:**  [#38](https://github.com/smartdevicelink/sdl_requirements/issues/38) Handling notifications from HMI during re-connection
- **Parent task:** [issues/1659](https://github.com/smartdevicelink/sdl_core/issues/1659)

**Comment by jacobkeeler** [comment]
Related: #1587?
