### ISSUE TITLE
Build with cmake 3.5.2

### ISSUE THREAD

**Issue by mchalain** [smartdevicelink/sdl_core#1678]
from the tag 4.2.3 to 4.3 :
 cmake finishes with

> -- Check if the system is big endian - little endian
> -- Looking for off_t
> -- Looking for off_t - not found
> -- Looking for size_t
> -- Looking for size_t - not found
> -- Found OpenSSL: /usr/lib64/libssl.so;/usr/lib64/libcrypto.so (found version "1.0.2k") 
> -- Using PROPRIETARY policy mode
> -- Found PythonInterp: /usr/bin/python (found version "2.7.13") 
> -- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2") 
> -- Checking for module 'sqlite3>=3.7.11'
> --   Found sqlite3, version 3.13.0
> -- Found Sqlite3: /usr/lib64/libsqlite3.so
> -- Use regular policy
> -- Found Git: /usr/bin/git (found version "2.9.0") 
> -- Found Doxygen: /usr/bin/doxygen (found version "1.8.9.1") 
> -- Doxygen found. Documentation will be generated
> -- Configuring incomplete, errors occurred!
> See also "/home/mch/Projects/PSA/SDL/sdl_core.build/CMakeFiles/CMakeOutput.log".
> See also "/home/mch/Projects/PSA/SDL/sdl_core.build/CMakeFiles/CMakeError.log".
> 

after checking the error, it comes from expat 3thrd_party. But when I launch cmake from expat directly (following the CMake.README from expat) not error occurs.

My setup:
 - Slackware 14.2
 - host x86_64
 - cmake 3.5.2
 - gcc 5.3.0

**Comment by jacobkeeler** [comment]
Don't know what happened with 3.5.2, but the current master branch builds without issue on the latest cmake version, so I'm considering this resolved for now. Feel free to reopen if you are still experiencing this on the latest SDL Core version.
