### ISSUE TITLE
SDL respond with not supported resultCode = UNSUPPORTED_RESOURCE for ChangeRegistration

### ISSUE THREAD

**Issue by dsmyrnov** [smartdevicelink/sdl_core#1694]
Environment:
OS: Ubuntu 16.04.
ARC: PC (x86)
SDL - Tag 4.2.1 commit e98cef9
Occurrence:
Always
Preconditions:
SDL is running and HMI is connected to SDL
Application registered
Steps to reproduce:
Send ChangeRegistration with not supported ttsName (LHPLUS_PHONEMES or SILENCE)
Actual result:
SDL respond with not listed result code UNSUPPORTED_RESOURCE
Expected result:
SDL respond with listed in MOBILE_API.xml result code
Requirements: MOBILE_API.xml

**Comment by jacobkeeler** [comment]
I don't believe that these `resultCode` lists within individual RPCs are strictly enforced, but `UNSUPPORTED_RESOURCE` should be included as a potential results for the sake of clarity.

**Comment by iCollin** [comment]
Closed via #3091
