### ISSUE TITLE
 SDL respond with "clusterModes" instead "clusterModeStatus" in SubscribeVehicleData

### ISSUE THREAD

**Issue by dsmyrnov** [smartdevicelink/sdl_core#1696]
Environment:
OS: Ubuntu 16.04.
ARC: PC (x86)
SDL - Tag 4.2.1 commit e98cef9
Occurrence:
Always
Preconditions:
SDL is running and HMI is connected to SDL
Application registered
Steps to reproduce:
Send  SubscribeVehicleData with clusterModeStatus=true
Actual result:
SDL respond with "clusterModes"
[SmartDeviceLinkCore.txt](https://github.com/smartdevicelink/sdl_core/files/1182836/SmartDeviceLinkCore.txt)

Expected result:
SDL respond with "clusterModeStatus"
Requirements: MOBILE_API.xml

**Comment by jacobkeeler** [comment]
`clusterModes` is correct in this case (even though it is used inconsistently, which is unfortunate, but would require a breaking change and a proposal to fix). https://github.com/smartdevicelink/sdl_core/blob/master/src/components/interfaces/MOBILE_API.xml#L4212
