### ISSUE TITLE
SDL respond with "maximumChangeVelocity" as string  instead integer in GetVehicleData

### ISSUE THREAD

**Issue by dsmyrnov** [smartdevicelink/sdl_core#1703]
Environment:
OS: Ubuntu 16.04.
ARC: PC (x86)
SDL - Tag 4.2.1 commit e98cef9
Occurrence:
Always
Preconditions:
SDL is running and HMI is connected to SDL
Application registered
Steps to reproduce:
Send SubscribeVehicleData with emergencyEvent=true
Actual result:
SDL respond with "maximumChangeVelocity": "NO_EVENT"
[SmartDeviceLinkCore.log.zip](https://github.com/smartdevicelink/sdl_core/files/1196911/SmartDeviceLinkCore.log.zip)

Expected result:
SDL respond with "maximumChangeVelocity" as integer
Requirements: MOBILE_API.xml

**Comment by jacobkeeler** [comment]
The `emergencyEvent` in the `SubscribeVehicleData` response is supposed to be a `VehicleDataResult` (shown [here](https://github.com/smartdevicelink/sdl_core/blob/master/src/components/interfaces/MOBILE_API.xml#L4209)), which is what SDL Core responds with based on my tests. The HMI uses this "NO_EVENT" string for `GetVehicleData` responses, which is an issue, but it is translated to `0` by Core.
