### ISSUE TITLE
Core sends binary data only for PROPRIETARY requestType

### ISSUE THREAD

**Issue by robinmk** [smartdevicelink/sdl_core#1714]
The SDL protocol supports binary data to be sent to the app from the module. 
However, SDL Core only sends the binary data using the OnSystemRequest RPC for the PROPRIETARY requestType. SDL core should be capable of sending binary data for any requestType.

**Comment by iCollin** [comment]
Closed via https://github.com/smartdevicelink/sdl_core/pull/3575
