### ISSUE TITLE
SDL requires root access for building

### ISSUE THREAD

**Issue by LuxoftAKutsan** [smartdevicelink/sdl_core#1721]
Currently SDL force requiring super user access for installing bson library
There are 2 root causes:

 - No ability to install bson library to custom path
 - SDL force `sudo make install` for installing bson library

There are existing ability to setup custom path for installing SDL third party : 

- THIRD_PARTY_INSTALL_PREFIX
- THIRD_PARTY_INSTALL_PREFIX_ARCH

**Preconditions :** 
THIRD_PARTY_INSTALL_PREFIX and THIRD_PARTY_INSTALL_PREFIX_ARCH installed to custom use path 
```
➜  env | grep THIRD
THIRD_PARTY_INSTALL_PREFIX=/tmp/genivi_libs
THIRD_PARTY_INSTALL_PREFIX_ARCH=/tmp/genivi_libs/x86_64
``` 

**Steps :** 
Build sdl : 
```cmake ../ && make```

**Expected result:**
All 3rdparty libraries installed to /tmp/genivi_libs

**Actual result :**
bson installed to /usr/local/lib

**Comment by jacobkeeler** [comment]
Fixed with the merge of #1723 and https://github.com/smartdevicelink/bson_c_lib/pull/2
