### ISSUE TITLE
Multithreading build corrupted

### ISSUE THREAD

**Issue by LuxoftAKutsan** [smartdevicelink/sdl_core#1724]
Unable to build SDL in multi treading more.

There are several issues:

1. Broken dependencies between components
2. SDL requires sudo password during build.
 
Steps:
1. Build sdl in multiple threads: ```cmake ../ && make -j4```

**Expected result:**
successful build

**Actual result :** 
Build errors

**Comment by jacobkeeler** [comment]
I don't think this has ever worked in a release, but I remember it working in the old version of develop, so I know it's been resolved before. It just looks like the fix was never moved to the new develop.

**Comment by jacobkeeler** [comment]
Tested on release branch, multithreaded build was fixed at some point
