### ISSUE TITLE
Bson compiles multiple times during build

### ISSUE THREAD

**Issue by LuxoftAKutsan** [smartdevicelink/sdl_core#1725]
SDL is trying to build and install bson multiple times.
Preconditions:
Clear system
Steps : 
 - Build SDl and save log `cmake && make 2>&1 | tee make_log # Saving build output`
 - Calculate count of bson builds : 
`cat /tmp/make_log | grep "Built target libbson"`
**Actual result  :** 
Count of builds is 2
```
➜  cat /tmp/make_log | grep "Built target libbson"
[ 50%] Built target libbson
[ 50%] Built target libbson
Built target libbson
```

**Expected results :**
Count of bson builds is 1

**Comment by dboltovskyi** [comment]
Issue is not reproduced at https://github.com/smartdevicelink/sdl_core/tree/release/8.0.0 (de58a41)
