### ISSUE TITLE
Version negotiation on develop branch for v5 protocol causing mobile library issues

### ISSUE THREAD

**Issue by mrapitis** [smartdevicelink/sdl_core#1728]
## Description
The develop branch of SDL core with the protocol v5 implementation is causing an issue when negotiating versions with the mobile library.  

- The existing iOS proxy library release (4.6.1 or below) in the field will crash if it connects to the current develop branch of SDL core that includes the v5 protocol changes.  
- The existing Android proxy library (4.3.1 or below) in the field will not crash, however core from the develop branch does attempt to communicate with v5 protocol messages.

Originally sdl core's version negotiation logic was implemented in a way that would prevent core from attempting to communicate at a higher version then what was supported by the mobile library.  We need to ensure that this same logic remains accurate with the introduction of the v5 protocol as its is essential to maintain backwards compatibility with existing applications.

## Steps to Reproduce 
Build and run the current develop branch of sdl core
Try to connect an iOS SDL enabled application using the TCP transport
Take note that the iOS app crashes
More repro details found below: 
https://github.com/smartdevicelink/sdl_ios/issues/696

**Comment by jacobkeeler** [comment]
Fixed with the merge of #1729
