### ISSUE TITLE
GetWayPoints for last mile navigation

### ISSUE THREAD

**Issue by OlesiaV** [smartdevicelink/sdl_core#1741]
## Description:

_As a mobile app I want to send a request to get the details of the destination and waypoints set on the system so that I can get last mile connectivity._

## Related Diagrams:

![GetwayPoints](https://github.com/smartdevicelink/sdl_requirements/blob/GetWayPoints/detailed_docs/accessories/GetWayPoints.png)

## Links:

- **Requirement:** [#25](https://github.com/smartdevicelink/sdl_requirements/issues/25) Get Destination & Waypoints_GetWayPoints
- **Parent task:** 

## Expected Delivery (Definition of Done)

- [ ] Requirements analysis and updates
- [ ] Source code updates
- [ ] Code comments
- [ ] UTs add/update
- [ ] Integration tests add/update
- [ ] **Manual tests (not required)**
- [ ] Add/update CI plans/jobs
- [ ] SDD updates
- [ ] SAD updates
- [ ] Guidelines update 1 ([sdl_core_guides](https://github.com/smartdevicelink/sdl_core_guides))
- [ ] Guidelines update 2 ([sdl_hmi_integration_guidelines](https://github.com/smartdevicelink/sdl_hmi_integration_guidelines))

**Comment by jacobkeeler** [comment]
Closing, as this RPC was already implemented
