### ISSUE TITLE
SubscribeWayPoints

### ISSUE THREAD

**Issue by OlesiaV** [smartdevicelink/sdl_core#1742]
# Description:

_As a mobile app I want to be able to subscribe on notifications about any changes to the destination or waypoints._

## Related Diagrams:

![SubscribeWayPoints](https://github.com/smartdevicelink/sdl_requirements/blob/SubscribeWayPoints/detailed_docs/accessories/SubscribeWayPoints.png)

![OnWayPointChange_storing](https://github.com/smartdevicelink/sdl_requirements/blob/SubscribeWayPoints/detailed_docs/accessories/Store_OnWayPointsChange.png)

## Links:

- **Requirement:** [#26](https://github.com/smartdevicelink/sdl_requirements/issues/26) Subscribe to Destination & Waypoints_SubscribeWayPoints
- **Parent task:** 

## Expected Delivery (Definition of Done)

- [x] Requirements analysis and updates
- [x] Source code updates
- [x] Code comments
- [x] UTs add/update
- [x] Integration tests add/update
- [ ] **Manual tests (not required)**
- [ ] Add/update CI plans/jobs
- [ ] SDD updates
- [ ] SAD updates
- [ ] Guidelines update 1 ([sdl_core_guides](https://github.com/smartdevicelink/sdl_core_guides))
- [ ] Guidelines update 2 ([sdl_hmi_integration_guidelines](https://github.com/smartdevicelink/sdl_hmi_integration_guidelines))

**Comment by jacobkeeler** [comment]
Closing, as this RPC was already implemented
