### ISSUE TITLE
UnsubscribeWayPoints

### ISSUE THREAD

**Issue by OlesiaV** [smartdevicelink/sdl_core#1743]
## Description:

_As a mobile app I want to be able to unsubscribe from getting notifications about any changes to the destination or waypoints._

## Related Diagrams:

![UnsubscribeWayPoints](https://github.com/smartdevicelink/sdl_requirements/blob/UnsubscribeWayPoints/detailed_docs/accessories/UnsubscribeWayPoints.png)

## Links:

- **Requirement:** [#27](https://github.com/smartdevicelink/sdl_requirements/issues/27) Unsubscribe from Destination & Waypoints_UnsubscribeWayPoints
- **Parent task:** 

## Expected Delivery (Definition of Done)

- [ ] Requirements analysis and updates
- [ ] Source code updates
- [ ] Code comments
- [ ] UTs add/update
- [ ] Integration tests add/update
- [ ] **Manual tests (not required)**
- [ ] Add/update CI plans/jobs
- [ ] SDD updates
- [ ] SAD updates
- [ ] Guidelines update 1 ([sdl_core_guides](https://github.com/smartdevicelink/sdl_core_guides))
- [ ] Guidelines update 2 ([sdl_hmi_integration_guidelines](https://github.com/smartdevicelink/sdl_hmi_integration_guidelines))

**Comment by jacobkeeler** [comment]
Closing, as this RPC was already implemented
