### ISSUE TITLE
OnWayPointChange

### ISSUE THREAD

**Issue by OlesiaV** [smartdevicelink/sdl_core#1744]
## Description:

_As a mobile application I want to be able to be notified on changes to Destination or Waypoints based on my subscription_

## Related Diagrams:

![OnWayPointChange](https://github.com/smartdevicelink/sdl_requirements/blob/OnWayPointChange/detailed_docs/accessories/OnWayPointChange.png)

## Links:

- **Requirement:** [#28](https://github.com/smartdevicelink/sdl_requirements/issues/28) Notification about changes to Destination or Waypoints_OnWayPointChange
- **Parent task:** 

## Expected Delivery (Definition of Done)

- [x] Requirements analysis and updates
- [x] Source code updates
- [x] Code comments
- [x] UTs add/update
- [x] Integration tests add/update
- [ ] **Manual tests (not required)**
- [ ] Add/update CI plans/jobs
- [ ] SDD updates
- [ ] SAD updates
- [ ] Guidelines update 1 ([sdl_core_guides](https://github.com/smartdevicelink/sdl_core_guides))
- [ ] Guidelines update 2 ([sdl_hmi_integration_guidelines](https://github.com/smartdevicelink/sdl_hmi_integration_guidelines))

**Comment by jacobkeeler** [comment]
Closing, as this RPC was already implemented
