### ISSUE TITLE
Core cannot find App via BT

### ISSUE THREAD

**Issue by BrandonHe** [smartdevicelink/sdl_core#1753]
### Precondition:
- Ubuntu 16.04 x86 
- Core version 4.3.1
- SPT (Proxy: 20170804-Nightly-Android)
- Android Phone (Android 6.0)
### Reproduce:
1. Run SDL core and SDL_HMI
2. Open SPT on the phone
3. Connect Core and SPT via Bluetooth
4. SPT successfully registered in the HMI
5. Exit the Core
6. Kill the SPT 
7. Restart the Core
8. Re-open SPT on the phone
9. Connect Core and SPT via Bluetooth
10. Connect failed, SPT cannot registered in the HMI
### Probability
**100%**
### Analysis
While core is re-started, it will read BT data from *app_info.dat* file to get the address and channel information. But SPT is not launched, therefore, the connection fail.
```json
   "TransportManager" : {
      "BluetoothAdapter" : {
         "devices" : [
            {
               "address" : "84:9F:B5:99:1B:EC",
               "applications" : [
                  {
                     "rfcomm_channel" : "5"
                  },
                  {
                     "rfcomm_channel" : "6"
                  },
                  {
                     "rfcomm_channel" : "7"
                  }
               ],
               "name" : "DIG-AL00"
            }
         ]
      },
      "TcpAdapter" : null
   },
```
Also, the ```void ThreadedSocketConnection::Transmit()``` function called by ```void ThreadedSocketConnection::threadMmain()``` is blocked in the [poll](https://github.com/smartdevicelink/sdl_core/blob/develop/src/components/transport_manager/src/transport_adapter/threaded_socket_connection.cc#L231), leads the ```Finalize()``` function is not implemented. 
So after SPT is launched again, the core ```TransportAdapterImpl::Connect()``` function is detected status as ```ALREADY_EXISTS```

**Comment by ilikegithubcom** [comment]
If the connection fails, in the ThreadedSocketConnection:: threadMain () function, you should skip the Transmit function and call the Finalize function to release the connection object.

**Comment by yangbiao01** [comment]
Reviewed

**Comment by jacobkeeler** [comment]
Fixed for the case originally described in the issue, but not another related case:

### Environment:
- Ubuntu 14.04 x86_64 
- Core branch 4.4.0
- SPT (Proxy: 20170921-Nightly-Android)
- Android Phone (Android 6.0.1)
### Steps to Reproduce:
1. Run SDL core and SDL_HMI
2. Open SPT on the phone
3. Connect Core and SPT via Bluetooth
4. SPT successfully registered in the HMI
5. Exit Core
6. **Restart Core**
7. **Kill the SPT**
8. Re-open SPT on the phone
9. Connect Core and SPT via Bluetooth
10. Connect failed, SPT is unable to register in the HMI
### Probability
**100%**

**Comment by jacobkeeler** [comment]
Never mind, it appears that this second scenario has been fixed. Possibly with the merge of https://github.com/smartdevicelink/sdl_core/pull/1791
