### ISSUE TITLE
MenuIcon not sent to HMI in case of ResetGlobalProperties

### ISSUE THREAD

**Issue by madhuy** [smartdevicelink/sdl_core#1754]
in SDL core code I see below [comment](https://github.com/smartdevicelink/sdl_core/blob/master/src/components/application_manager/src/commands/mobile/reset_global_properties_request.cc#L140). Could you please clarify reason for not sending MenuIcon to HMI?

`
    // TODO(DT): clarify the sending parameter menuIcon
    // if (menu_icon) {
    //}
`

**Comment by jacobkeeler** [comment]
Unfortunately, this looks to be a comment from before the project became open source, so I doubt anyone that's still involved in the project knows where this comment came from.

That said, it looks like the default `menu_icon` was just never defined, and so nothing is sent for this parameter when sending a `ResetGlobalProperties` message.
