### ISSUE TITLE
AudioPassThru stops when another app is unregistered

### ISSUE THREAD

**Issue by shoamano83** [smartdevicelink/sdl_core#1756]
### Precondition:
1. Check out latest develop branch (commit da4b5766ca3f1fca4caa4b4815073f72dfe37182) and give a build
2. Start SDL Core by ./start.sh
3. Start generic_hmi
4. Open Google Chrome browser and show http://localhost:3000

### Step to reproduce:
1. Connect RPCBuilder app from an Android phone via Wi-Fi
2. Connect another app (let's say "App 2") from another phone via Wi-Fi
3. On the browser, click on App 2 and make it FULL level
4. Let App 2 start AudioPassThru with long maxDuration (e.g. 30 seconds)
5. While AudioPassThru is running, unregister RPCBuilder (by tapping the gear icon on upper right)

### Expected Result:
Audio Pass Thru operation continues because unregistered app is not related to the operation.

### Actual Result:
After RPCBuilder is unregistered, SDL Core stops sending audio data to App 2.

### Tested environment:
Ubuntu 16.04 (x86_64) on a VirtualBox machine
RPC Builder running on Nexus 6 (Android 5.0.1)
"App 2" is a proprietary sample app, running on iPhone 5s (iOS 8.4.1)

**Comment by jacobkeeler** [comment]
Closing with the merge of #1757
