### ISSUE TITLE
[SDL 0092] Mark public deprecated methods

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_core#1758]
Proposal: [Mark public deprecated methods](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0092-Deprecated-interfaces-markup.md)

>Public methods is part of SDL interface. New features may use some existing interfaces and expect some behavior. Sometimes some features use interfaces that are planned to be removed.

Review: https://github.com/smartdevicelink/sdl_evolution/issues/278

**Comment by jacobkeeler** [comment]
Closed with the merge of #1938
