### ISSUE TITLE
Core probabilistic crashes after unplugging USB during the video streaming

### ISSUE THREAD

**Issue by BrandonHe** [smartdevicelink/sdl_core#1770]
### Env:
* SDL WinCE port
* Android smart phone (Android 6.0)
* Navigation App(Sougou)

### Reproduce steps:
1. Run sdl_core
2. Run sdl_hmi
3. Connect Navigation App with Core
4. Start video streaming 
5. Unplug USB cable
6. repeat step 1 to step 5 tens of time
7. Core occurs crash 
### Probality:
bigger or equal 1/20
### Analysis:
Each time when SDL execute callback function [OnOutTransfer](https://github.com/smartdevicelink/sdl_core/blob/master/src/components/transport_manager/src/usb/libusb/usb_connection.cc#L202) for out transfer data. there is a possible that the value _current_out_message_ is not valid, then the ```current_out_message->data_size``` is a empty pointer to be used, thus it occurs crash.

**Comment by jacobkeeler** [comment]
Closing as a duplicate in favor of #1854, since the SDL WinCE port is not available in the open currently
