### ISSUE TITLE
RC related RPCs are DISALLOWED whenever an app has specifically defined policies

### ISSUE THREAD

**Issue by AKalinich-Luxoft** [smartdevicelink/sdl_core#1773]
**Steps to reproduce**
1. Edit PTU - Add "RemoteControl" group to specific app permissions
2. Edit PTU - Set moduleType to [“RADIO”, “CLIMATE”] for specific app permissions
3. Register mobile app with REMOTE_CONTROL HMI type and bring it to FULL
4. Send SetInteriorVehicleData(CLIMATE)
5. Expected DISALLOWED - OK
6. Perform PTU sequence using PT edited in steps 1-2
7. After successful PTU send SetInteriorVehicleData(CLIMATE) again

**Expected result**
SDL allows SetInteriorVehicleData() request and sends it to HMI

**Actual result**
SDL responds with DISALLOWD and does not send request to HMI

This same scenario ends with SUCCESS when no explicit app policy is specified and all of these steps are performed on the default policies. Adding explicit policies for an app causes this issue.

**Comment by jacobkeeler** [comment]
Closing with the merge of #1774
