### ISSUE TITLE
Core generates a lot of logs during streaming

### ISSUE THREAD

**Issue by shoamano83** [smartdevicelink/sdl_core#1777]
Currently SDL Core generates quite a few log lines each time it receives a frame from mobile. Because of this, we will get a large amount of logs during video streaming.
- Log files can be flushed away quickly.
- If the system has slow log output, log messages will queued up in memory and might cause system's RAM to exhaust.

**Comment by jacobkeeler** [comment]
Closing with the merge of #1778
