### ISSUE TITLE
Duplicate "PendingRequestsAmount" entries in smartDeviceLink.ini

### ISSUE THREAD

**Issue by shoamano83** [smartdevicelink/sdl_core#1790]
While reviewing the changes I found that latest smartDeviceLink.ini file contains duplicate entries of "PendingRequestsAmount".
https://github.com/smartdevicelink/sdl_core/blob/develop/src/appMain/smartDeviceLink.ini#L74

Please kindly clarify which is the intended value for latest code.
Thanks!

**Comment by jacobkeeler** [comment]
Fixed in https://github.com/smartdevicelink/sdl_core/commit/95aec12cbd07087af530413e574415056e45e067
