### ISSUE TITLE
Implementation new EngineOilLife parameter

### ISSUE THREAD

**Issue by KhrystynaDubovyk** [smartdevicelink/sdl_core#1809]
## Description:

_As a mobile app I want to get the engine oil life data to provide related information to the user._  

## Related Diagrams:
N/A

## Links:

- **Requirement:** [#40](https://github.com/smartdevicelink/sdl_requirements/issues/40) New vehicle data - EngineOilLife & VehicleInfo
- **Parent task:**

## Expected Delivery (Definition of Done)

- [x] Requirements analysis and updates
- [x] Source code updates
- [x] Code comments
- [x] UTs add/update
- [x] Integration tests add/update
- [ ] **Manual tests (not required)**
- [ ] Add/update CI plans/jobs
- [ ] SDD updates
- [ ] SAD updates
- [ ] Guidelines update 1 ([sdl_core_guides](https://github.com/smartdevicelink/sdl_core_guides))
- [ ] Guidelines update 2 ([sdl_hmi_integration_guidelines](https://github.com/smartdevicelink/sdl_hmi_integration_guidelines))

**Comment by joeygrover** [comment]
Closing as duplicate #1733 . Please search for existing issues before raising new ones.
