### ISSUE TITLE
ResumeCtrlImpl can crash during cleanup

### ISSUE THREAD

**Issue by fronneburg** [smartdevicelink/sdl_core#1829]
In case there is a problem during sdlCore initialization, the "main" function will attempt to clean up. When ApplicationManagerImpl::UnregisterAllApplications calls ResumeCtrlImpl::OnSuspend, but the ResumeCtrlImpl object hasn't been initialized, the "resumption_storage_" pointer may be NULL, thus causing a crash.

**Comment by iCollin** [comment]
Closed via https://github.com/smartdevicelink/sdl_core/pull/2621
