### ISSUE TITLE
addcommand response from sdl: generic_error

### ISSUE THREAD

**Issue by NDNELSON** [smartdevicelink/sdl_core#1845]
### Bug Report
I am testing my sdl android app in a tdk exactly in a ford fiesta titanium 2016. My app id was given me on June 2015. I have almost 19 sdl commands in my app. Everything was working good but yestarday that I reset from factory my fiesta the commands show only a ves seconds like 3 to  5 exactly and then disaper from screen and Í only get addcommand response from sdl: generic_error in the logcat but the code doesnt pass through ondelete commands callback
I use this 
Proxy.addcommand(idcommand,name,vr vector, correlación id)
EBAY HAPPEN WITH IT? DOES MY APPID expired? Bit by the  way I am able to  read  vehicle data
My test phone is a Samsung galaxy s6 soy Android 7.0

Thanks for your help. Best regards

**Comment by jacobkeeler** [comment]
Questions like this are best kept asked in the Slack group. In addition this is not strictly SDL Core related. Please post your question in the #ford channel on [Slack](http://slack.smartdevicelink.com/).
