### ISSUE TITLE
Remote Control Applications Auto Activate Apps

### ISSUE THREAD

**Issue by JackLivio** [smartdevicelink/sdl_core#1850]
### Bug Report
If an app connects with AppHMIType::REMOTE_CONTROL, Core automatically sends BC.Activate app to the HMI without any use input or needed app resumption.

##### Reproduction Steps
1. Start fresh build of core and launch hmi
2. Connect app with AppHMIType::REMOTE_CONTROL
3. Observe core send hmi BC.ActivateApp

##### Expected Behavior
Core should only send ActivateApp if app is supposed to be resuming.

##### Observed Behavior
Core Sends Activate App

##### OS & Version Information
* OS/Version: ubuntu 14.04
* SDL Core Version: Master 4.4.0
* Testing Against: SPT, SDL_HMI

**Comment by jacobkeeler** [comment]
Closing with the merge of #1844
