### ISSUE TITLE
[SDL 0108] AutoCompleteList

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_core#1858]
Proposal: [AutoCompleteList](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0108-AutoCompleteList.md)

> The AutoCompleteList will give apps the ability to have multiple listing options while searching for things like destination and information; instead of giving a single suggestion.

Review: https://github.com/smartdevicelink/sdl_evolution/issues/331

**Comment by theresalech** [comment]
Proposal markdown file has been updated per the revisions included in accepted Evolution Proposal [SDL 0108 Revisions - AutoCompleteList](https://github.com/smartdevicelink/sdl_evolution/issues/784).  These changes include updating the feature to support clearing the list by changing the `minsize` for `autoCompleteList` param from 1 to 0.  Please reference issue and markdown file for more details.

**Comment by jacobkeeler** [comment]
Closing with the merge of #2959
