### ISSUE TITLE
[SDL 0107] New vehicle data - TurnSignal

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_core#1859]
Proposal: [New vehicle data - TurnSignal](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0107-New-vehicle-data-turnSignal.md)

> This proposal is about adding a new vehicle data to get the value of the turn signal.

Review: https://github.com/smartdevicelink/sdl_evolution/issues/328

**Comment by theresalech** [comment]
Closed via #2293

**Comment by FStoikov** [comment]
Jira ticket created for current case: https://adc.luxoft.com/jira/browse/FORDTCN-1205

**Comment by FStoikov** [comment]
Jira ticket created for current case: https://adc.luxoft.com/jira/browse/FORDTCN-1205
