### ISSUE TITLE
SDL does not validate invalid characters in HMI requests.

### ISSUE THREAD

**Issue by GetmanetsIrina** [smartdevicelink/sdl_core#1862]
### Bug Report
SDL does not validate invalid characters (\n, \t, only whitespace ) in string parameters in HMI requests.

##### Steps
1. HMI sends SDL.GetUserFriendlyMessage request with invalid characters

##### Expected Behavior
SDL responds with code INVALID_DATA to HMI.

##### Observed Behavior
SDL responds with code:0 (SUCCESS) to HMI.

##### OS & Version Information
* OS/Version: Ubuntu 16.04
* SDL Core Version: 4eb09bf0da82e320723390abd877079af9457d20
* Testing Against: ATF

##### Test Case, Sample Code, and / or Example App
* [Defects.zip](https://github.com/smartdevicelink/sdl_core/files/1487432/Defects.zip)
* [SmartDeviceLinkCore.log.zip](https://github.com/smartdevicelink/sdl_core/files/1487434/SmartDeviceLinkCore.log.zip)

**Comment by aderiabin** [comment]
Contributor priority is set `Medium` with reason: The issue is related to functionality: existence of response from HMI/SDL

**Comment by HSavynetska** [comment]
Environment:
Script: https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/1949
SDL build: develop branch (621080d)
ATF: develop branch

Status: defect is reproduced.

**Comment by ValeriiMalkov** [comment]
The next PR provided fix this issue: [Pull request](https://github.com/smartdevicelink/sdl_core/pull/2390)

**Comment by VjKlepikov** [comment]
The issue is relevant on the current develop branch

Environment:
Test script: https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/1949
SDL build: https://github.com/smartdevicelink/sdl_core/tree/develop ( 891497b )
ATF: develop branch

**Comment by iCollin** [comment]
Closed via https://github.com/smartdevicelink/sdl_core/pull/3369
