### ISSUE TITLE
AOA USB transport buffer size too small

### ISSUE THREAD

**Issue by mrapitis** [smartdevicelink/sdl_core#1863]
SDL Core's AOA USB transport buffer size depends on the USB endpoint packet size (a maximum of 512 bytes), however Android documentation suggests using a value of 16384 bytes for simplicity with AOA connected devices (see link below).  
https://developer.android.com/guide/topics/connectivity/usb/accessory.html

In testing we have found that the larger (16384 byte) Android recommended buffer size improves video streaming performance and usabilty.  Please see table below for a comparison of benchmark details:

| in_buffer_ size | Bit Rate | Frame Rate | Video Latency(ms) |
|-----------------|----------|:------------------:|---------------------------|
| 512 bytes       |  1Mpbs   |  avg:30 min:22 max:33  | avg:254 min:213 max:269 |
| 512 bytes       |  2Mpbs   |  avg:30 min:22 max:32  | avg:289 min:266 max:374 |
| 512 bytes       |  4Mpbs   |  avg:15 min:14 max:18  | avg:630 min:561 max:699 |
| 512 bytes       |  6Mpbs   |  avg:10 min:9 max:13  | avg:889 min:774 max:978 |

| in_buffer_ size | Bit Rate | Frame Rate | Video Latency(ms) |
|-----------------|----------|:------------------:|---------------------------|
| 16K bytes       |  1Mpbs   |  avg:30 min:21 max:33  | avg:252 min:227 max:286 |
| 16K bytes       |  2Mpbs   |  avg:30 min:22 max:32  | avg:254 min:217 max:282 |
| 16K bytes       |  4Mpbs   |  avg:30 min:22 max:33  | avg:246 min:220 max:293 |
| 16K bytes       |  6Mpbs   |  avg:30 min:22 max:33  | avg:240 min:215 max:282 |

**Comment by JackLivio** [comment]
@mrapitis I believe this was fixed by #1864
