### ISSUE TITLE
PoliciesManager allows all requested params in case "parameters" field is empty

### ISSUE THREAD

**Issue by GetmanetsIrina** [smartdevicelink/sdl_core#1873]
## Occurrence: 
Always 

## Steps to reproduce:
1. Make sure SDL is built with default flags
2. Start SDL and HMI
3. Connect mobile device
4. Register new application
5. Make sure "parameters" field is an empty array at PolicyTable for some RPC and this RPC is allowed for the application
6. Send this RPC

## Expected result:
SDL does not process RPC and respond to application with DISALLOWED result code

## Actual result:
SDL transfers received request with all requested parameters as is to HMI

## Test script:
[1873_Parameters_empty_in_policy_table.lua](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Defects/4_5/1873_Parameters_empty_in_policy_table.lua)
[1873_UnsubscribeVD_OnVD_Parameters_empty_in_policy_table.lua](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Defects/4_5/1873_UnsubscribeVD_OnVD_Parameters_empty_in_policy_table.lua)

## Attachments:
Note: Extract attached folder Defects.zip with script to test_scripts folder. 
[Defects.zip](https://github.com/smartdevicelink/sdl_core/files/1505099/Defects.zip)

# Expected delivery
- [ ] Source code updates
- [ ] Code comments
- [x] **UTs add/update _(not required)_**
- [ ] ATF tests add/update
- [x] **Manual tests _(not required)_**
- [x] **Add/update CI plans/jobs _(not required)_**
- [x] **SDD updates _(not required)_**
- [x] **Guidelines update ([sdl_core_guides](https://github.com/smartdevicelink/sdl_core_guides)) _(not required)_**
- [x] **Guidelines update ([sdl_hmi_integration_guidelines](https://github.com/smartdevicelink/sdl_hmi_integration_guidelines)) _(not required)_**

**Comment by aderiabin** [comment]
Contributor priority is set `High` with reason: The issue is related to policy functionality

**Comment by GetmanetsIrina** [comment]
Defect is reproduced on develop branch(0b19cf4).
Fix in #1965,
ATF version for verification https://github.com/smartdevicelink/sdl_atf/commits/develop(ae3c97da2ca77031b645773917b63eff1421c04d),
script for verification https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Defects/4_5/1873_Parameters_empty_in_policy_table.lua
