### ISSUE TITLE
SDL does not send GetVehilceData_response to mobile app in case of receiving 'gpsData' structure with only one parameter with valid value

### ISSUE THREAD

**Issue by AByzhynar** [smartdevicelink/sdl_core#1879]
**Occurrence: Always** 

# Description
SDL does not send GetVehilceData_response to mobile app in case of receiving 'gpsData' structure
with only one parameter with valid value

## Preconditions
 - SDL and HMI are started.
 - App is registered and activated.

## Steps to reproduce
1. HMI sends GetVehilceData_response with 'gpsData' structure and this structure has one parameter with valid value.

## Actual result
N/V

## Expected result
SDL must treat GetVehicleData_response as valid and transfer GetVehicleData_response to mobile app

# Environment

# Attachments
Note: Extract attached folder with script to test_scripts folder. 
[Defects.zip](https://github.com/smartdevicelink/sdl_core/files/1517724/Defects.zip)

# Expected delivery
- [ ] Source code updates
- [ ] Code comments
- [] **UTs add/update _(not required)_**
- [ ] ATF tests add/update
- [x] **Manual tests _(not required)_**
- [x] **Add/update CI plans/jobs _(not required)_**
- [x] **SDD updates _(not required)_**
- [x] **Guidelines update ([sdl_core_guides](https://github.com/smartdevicelink/sdl_core_guides)) _(not required)_**
- [x] **Guidelines update ([sdl_hmi_integration_guidelines](https://github.com/smartdevicelink/sdl_hmi_integration_guidelines)) _(not required)_**

**Comment by aderiabin** [comment]
Contributor priority is set `Medium` with reason: The issue is related to critical functionality: existence of response from HMI/SDL.

**Comment by HSavynetska** [comment]
The defect is not reproduced on the current develop

Environment:
SDL build: https://github.com/smartdevicelink/sdl_core/tree/develop (891497b )
ATF: develop branch
[Script to reproduce the defect_1879.zip](https://github.com/smartdevicelink/sdl_core/files/3869988/Script.to.reproduce.the.defect_1879.zip)
