### ISSUE TITLE
[OnDriverDistraction] SDL does not send notification to app right after this app changes level from NONE to any other

### ISSUE THREAD

**Issue by LitvinenkoIra** [smartdevicelink/sdl_core#1881]
## Occurrence: 
Always 

## Steps to reproduce:
1. Make sure SDL is built with default flags
2. Start SDL and HMI
3. Connect mobile device
4. Register new application → it gets NONE HMI level and SDL receives OnDriverDistraction (<state>) fom HMI 
5. Change HMI level to any other than NONE: (FULL, BACKGROUND, LIMITED)
6. Check that 'OnDriverDistraction' notification is sent to application

## Expected result:
SDL must transfer the last known (actual) OnDriverDistraction (<state>) to the mobile app right after this mobile app changes HMI level to any other than NONE.

## Actual result:
N/A

## Test script:
[1881_OnDriverDistraction_After_changing_HMIlevel_from_NONE.lua](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Defects/4_5/1881_OnDriverDistraction_After_changing_HMIlevel_from_NONE.lua)

## Attachments:
Note: Extract attached folder with script to test_scripts folder. 
[Defects.zip](https://github.com/smartdevicelink/sdl_core/files/1517516/Defects.zip)

# Expected delivery
- [ ] Source code updates
- [ ] Code comments
- [x] **UTs add/update _(not required)_**
- [ ] ATF tests add/update
- [x] **Manual tests _(not required)_**
- [x] **Add/update CI plans/jobs _(not required)_**
- [x] **SDD updates _(not required)_**
- [x] **Guidelines update ([sdl_core_guides](https://github.com/smartdevicelink/sdl_core_guides)) _(not required)_**
- [x] **Guidelines update ([sdl_hmi_integration_guidelines](https://github.com/smartdevicelink/sdl_hmi_integration_guidelines)) _(not required)_**

**Comment by aderiabin** [comment]
Contributor priority is set `High` with reason: Currently the newly registered applications know nothing about Driver Distraction mode, but only after it changes, the issue fixes this case.

**Comment by dboltovskyi** [comment]
Issue is reproduced on develop (0b19cf4) and fixed in https://github.com/smartdevicelink/sdl_core/pull/1970
