### ISSUE TITLE
[OnVehicleData] PoliciesManager does not allow all requested params in case "parameters" field is omited

### ISSUE THREAD

**Issue by LitvinenkoIra** [smartdevicelink/sdl_core#1886]
**Occurrence: Always** 

# Description
PoliciesManager must allow all requested params in case "parameters" field is omited

## Preconditions
 - SDL and HMI are started.
 - App is registered and activated.
 - "parameters" field is omited at PolicyTable for used request

## Steps to reproduce
1. In case SDL receives OnVehicleData notification from HMI
and this notification is allowed by Policies for this mobile app

## Actual result
N/A

## Expected result
SDL must transfer received notification with all parameters as is to mobile app
respond with <received_resultCode_from_HMI> to mobile app

# Environment

# Attachments
Note: Extract attached folder with script to test_scripts folder. 
[Defects.zip](https://github.com/smartdevicelink/sdl_core/files/1526636/Defects.zip)

# Expected delivery
- [ ] Source code updates
- [ ] Code comments
- [x] **UTs add/update _(not required)_**
- [ ] ATF tests add/update
- [x] **Manual tests _(not required)_**
- [x] **Add/update CI plans/jobs _(not required)_**
- [x] **SDD updates _(not required)_**
- [x] **Guidelines update ([sdl_core_guides](https://github.com/smartdevicelink/sdl_core_guides)) _(not required)_**
- [x] **Guidelines update ([sdl_hmi_integration_guidelines](https://github.com/smartdevicelink/sdl_hmi_integration_guidelines)) _(not required)_**

**Comment by KVGrygoriev** [comment]
Defect ain't reproducing on sdl_core develop 91123c3cae83ad41e1f5f37d37e46e9f07264d1b
