### ISSUE TITLE
SDL must start heartbeat only after first Heartbeat request from mobile app

### ISSUE THREAD

**Issue by LitvinenkoIra** [smartdevicelink/sdl_core#1892]
## Occurrence: 
Always 

## Steps to reproduce:
1. Make sure SDL is built with default flags
2. Make sure the value of "HeartBeat" parameter at SDL .ini file is more than zero
3. Start SDL and HMI
4. Connect mobile device over protocol v3 or higher
5. Register new application 
6. Check SDL messages on HB
7. Application sends first HeartBeat request by itself over control service to SDL
8. Check SDL messages on HB

## Expected result:
1. SDL does not send HB messages to application just after app registration
2. SDL starts sending HB messages when application had sent 1st HeartBeat request

## Actual result:
1. SDL start sending HB messages just after app registration

## Test Script
[1892_HB_from_SDL_after_receiving_HB_from_mobile.lua](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Defects/4_5/1892_HB_from_SDL_after_receiving_HB_from_mobile.lua)

## Attachments:

# Expected delivery
- [ ] Source code updates
- [ ] Code comments
- [x] **UTs add/update _(not required)_**
- [ ] ATF tests add/update
- [x] **Manual tests _(not required)_**
- [x] **Add/update CI plans/jobs _(not required)_**
- [x] **SDD updates _(not required)_**
- [x] **Guidelines update ([sdl_core_guides](https://github.com/smartdevicelink/sdl_core_guides)) _(not required)_**
- [x] **Guidelines update ([sdl_hmi_integration_guidelines](https://github.com/smartdevicelink/sdl_hmi_integration_guidelines)) _(not required)_**

**Comment by aderiabin** [comment]
Contributor priority is set `High` with reason: The issue is related to connection/session logic
Heartbeat should be applied only after establishing service

**Comment by GetmanetsIrina** [comment]
Fix in https://github.com/AKalinich-Luxoft/sdl_core/pull/2 (5329f5e70ce3b93dcaee1bc09111b17a3f13b015),
 ATF version for verification https://github.com/smartdevicelink/sdl_atf/pull/110 (58e36f1c18f6575926db58b0bf60cf99d11cbf2b) with HB fix,
script for verification  https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Defects/4_5/1892_HB_from_SDL_after_receiving_HB_from_mobile.lua.
