### ISSUE TITLE
Building/running occasionally modifies src/3rd_party/apr-1.5.0/include/apr.h in the source tree

### ISSUE THREAD

**Issue by lea255ace** [smartdevicelink/sdl_core#19]
apr.h is a generated file, and so should change, but these changes should show up in the build directory, not a tracked repository file.

**Comment by justinjdickow** [comment]
Should this file just be added to the .gitignore?

**Comment by lea255ace** [comment]
Maybe as a temporary workaround, with a better fix rolled into a build system update.

**Comment by justinjdickow** [comment]
This hasn't been reproduced in a while, believed fixed for now.
