### ISSUE TITLE
Non-media app must be activated during active embedded navigation

### ISSUE THREAD

**Issue by GetmanetsIrina** [smartdevicelink/sdl_core#1907]
**Occurrence: Always** 

# Description
Non-media app must be activated during active embedded navigation

## Preconditions
- SDL and HMI are started.
- Non-media app is registered.
- Non-media app in BACKGROUND and NOT_AUDIBLE due to active embedded navigation

## Steps to reproduce
- SDL receives SDL.ActivateApp(<appID_of_non-media_app>) from HMI

## Actual result
SDL does not set required HMILevel and audioStreamingState.

## Expected result
 SDL must respond SDL.ActivateApp (SUCCESS) to HMI send OnHMIStatus (FULL, NOT_AUDIBLE).

# Environment

# Attachments

# Expected delivery
- [ ] Source code updates
- [ ] Code comments
- [x] **UTs add/update _(not required)_**
- [ ] ATF tests add/update
- [x] **Manual tests _(not required)_**
- [x] **Add/update CI plans/jobs _(not required)_**
- [x] **SDD updates _(not required)_**
- [x] **Guidelines update ([sdl_core_guides](https://github.com/smartdevicelink/sdl_core_guides)) _(not required)_**
- [x] **Guidelines update ([sdl_hmi_integration_guidelines](https://github.com/smartdevicelink/sdl_hmi_integration_guidelines)) _(not required)_**

**Comment by dboltovskyi** [comment]
Priority was set to Medium. Issue is related to setting wrong HMI level and/or audioStreamingState for activated application in some specific cases. May affect correct permissions calculation for non-media application during active embedded navigation.

**Comment by HSavynetska** [comment]
Environment:
Script: https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/1967
SDL build: develop branch ( b7da3b5 )
ATF: develop branch

Status: defect is reproduced.

**Comment by HSavynetska** [comment]
The defect is reproduced on the current develop

Environment:
Script: https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/1967
SDL build: https://github.com/smartdevicelink/sdl_core/tree/develop (891497b )
ATF: develop branch

**Comment by E-SAITO-TMC** [comment]
@theresalech -san, We were able to reproduce this issue with Core 6.0.1. This is a high priority issue for Toyota. Could you please include this in the Core 6.2 release planning?

**Comment by theresalech** [comment]
@GetmanetsIrina can you please advise if you are able to reproduce this issue in the latest Core release?

**Comment by dboltovskyi** [comment]
@theresalech Please notice issue is still actual for Core 6.1
ATF script and logs: [2020-06-04_15-05-19_1907.tar.gz](https://github.com/smartdevicelink/sdl_core/files/4732222/2020-06-04_15-05-19_1907.tar.gz)

**Comment by theresalech** [comment]
@dboltovskyi thank you for the update!  Can you please advise if Luxoft is planning to submit a PR to resolve this issue?

**Comment by dboltovskyi** [comment]
@theresalech Please notice we're not planning to create the fix in scope of 6.2, though will try to do as much as possible

**Comment by jacobkeeler** [comment]
Closing with the merge of #3476
