### ISSUE TITLE
SDL must respond NACK in case navigation app connected over protocol v2 sends StartService for audio service

### ISSUE THREAD

**Issue by LitvinenkoIra** [smartdevicelink/sdl_core#1912]
**Occurrence: Always** 

## Steps to reproduce
1. Make sure SDL is built with default flags
2. Start SDL and HMI
3. Connect mobile device over protocol v2
4. Register new application
5. Start audio service on mobile app
6. Application sends StartService for audio service to SDL

## Expected result
SDL must respond StartService_NACK to this app

## Actual result
SDL starts audio service via 2 protocol and sends StartService_ACK to app

## Test script
[1912_Video_service_start_via_2_protocol.lua](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Defects/4_5/1912_Video_service_start_via_2_protocol.lua)

## Attachments

# Expected delivery
- [ ] Source code updates
- [ ] Code comments
- [x] **UTs add/update _(not required)_**
- [ ] ATF tests add/update
- [x] **Manual tests _(not required)_**
- [x] **Add/update CI plans/jobs _(not required)_**
- [x] **SDD updates _(not required)_**
- [x] **Guidelines update ([sdl_core_guides](https://github.com/smartdevicelink/sdl_core_guides)) _(not required)_**
- [x] **Guidelines update ([sdl_hmi_integration_guidelines](https://github.com/smartdevicelink/sdl_hmi_integration_guidelines)) _(not required)_**

**Comment by dboltovskyi** [comment]
Priority was set to High. Issue may cause a problems with streaming for applications which is using protocol v2.

**Comment by GetmanetsIrina** [comment]
Issue is reproduced on develop branch(0b19cf498d1c9972d67b85793dc6b029c26378a0)

**Comment by jacobkeeler** [comment]
Verified that this is fixed by #1971.

**Comment by jacobkeeler** [comment]
Fixed with the merge of #1971
