### ISSUE TITLE
SDL must start <defaultTimeout> for VR.PerformInteraction

### ISSUE THREAD

**Issue by AStasiuk** [smartdevicelink/sdl_core#1926]
**Occurrence: Always** 

# Description
SDL must start defaultTimeout for VR.PerformInteraction

## Preconditions
1. SDL and HMI are started.
2. App is registered and activated.

## Steps to reproduce
1. App sends PerformInteraction(params)
2. SDL sends UI.PerformInteraction and VR.PerformInteraction to HMI
3. SDL starts default timeouts for VR portions (defined in .ini file)
4. HMI responds UI.PerformInteraction(SUCCESS) to SDL
5. HMI send OnResetTimeout notification during timeout

## Actual result
N/V

## Expected result
1. start <DefaultTimeout> timer for VR.PerformInteraction
2. renew <DefaultTimeout> timer for VR.PerformInteraction right after OnResetTimeout_notification from HMI

# Environment

# Attachments

# Expected delivery
- [ ] Source code updates
- [ ] Code comments
- [ ] **UTs add/update _(not required)_**
- [ ] ATF tests add/update
- [x] **Manual tests _(not required)_**
- [x] **Add/update CI plans/jobs _(not required)_**
- [x] **SDD updates _(not required)_**
- [x] **Guidelines update ([sdl_core_guides](https://github.com/smartdevicelink/sdl_core_guides)) _(not required)_**
- [x] **Guidelines update ([sdl_hmi_integration_guidelines](https://github.com/smartdevicelink/sdl_hmi_integration_guidelines)) _(not required)_**

**Comment by dboltovskyi** [comment]
Priority has changed to Low since issue is related to specific case with OnResetTimeout notification in conjuction with VR.PerformInteraction request

**Comment by dboltovskyi** [comment]
Issue is not applicable within implementation and merge of https://github.com/smartdevicelink/sdl_core/pull/3726
