### ISSUE TITLE
StartService fail after Core restarted 

### ISSUE THREAD

**Issue by BrandonHe** [smartdevicelink/sdl_core#1932]
### Bug Report
In current version of sdl core, in TM implementation of [AddTransportAdapter](https://github.com/smartdevicelink/sdl_core/blob/master/src/components/transport_manager/src/transport_manager_impl.cc#L417-L424), the TransportAdpater is listened after the TransportAdapter is initialized.
This logic causes problem of class ConnectionHandlerImpl fail to update connection device information during the TA restore , and then OnSessionStartedCallBack response fail to connected App.

The logic changing occurred in sdl core version 4.3.0. Before the version 4.3.0, the logic sequence was firstly listen and then init.

#### Reproduction Steps
1. Run SDL core and generic_hmi
2. Open SPT on the phone
3. Connect Core and SPT via Bluetooth
4. SPT successfully registered in the generic HMI
5. Exit the Core and generic_hmi 
6. Restart the Core and generic_hmi
7. Connect Core and SPT via Bluetooth
8. Connect failed, SPT cannot registered in the generic HMI

#### Expected Behavior
step 8 connect success, SPT successfully registered in the generic HMI

#### Observed Behavior
Connect failed, SPT cannot registered in the generic HMI

#### Probability
100%

#### OS & Version Information
* OS/Version: Ubuntu16.04 x86
* SDL Core Version:
[https://github.com/smartdevicelink/sdl_core/tree/master](https://github.com/smartdevicelink/sdl_core/tree/master)

* Testing Against: 
[https://github.com/smartdevicelink/generic_hmi/tree/master](https://github.com/smartdevicelink/generic_hmi/tree/master)
#### Example App
SPT

### Analysis
After the **step 6** is executed, the blew steps will be executed in SDL process:
1. Read app_info.data file to get the address and channel relate Bluetooth device
2. Initialize `TransportManagerImpl::AddTransportAdapter`, during the initialization, create `ThreadedSocketconnection::ThreadMain` to run `BluetoothTransportAdapter::Restore`
3. The `BluetoothTransportAdapter::Restore` function will call the function `TransportAdapterImpl::AddDevice` to store the device information in template `device_list_` in class `ConnectionHandlerImpl`, but **BluetoothTransportAdapter** is not listened at this time, so failed to store the device information.
4. `TransportManagerImpl::AddTransportAdapter` listen to `BluetoothTransportAdapter`
5. `ThreadedSocketConnection::threadMain` try to do connection, if successfully connected with device, the connect information will be inserted to the list `connection_list_`. In fact, this step fails because no device information is stored in step 3.
6. Core protocol handle `StartService` fame data from App, and response with `OnSessionStartedCallback`
7. Failed response to App, because the connection_handler has no right connection information which was caused in Analysis3 and Analysis5

**Comment by JackLivio** [comment]
fixed by #2018
