### ISSUE TITLE
Deadlock during shutdown if HMI isn't cooperating

### ISSUE THREAD

**Issue by fronneburg** [smartdevicelink/sdl_core#1955]
### Bug Report
If the HMI never responds during UpdateDeviceListRequest processing, SDL_CORE cannot shut down, because the Connection Handler is holding the "connection_handler_observer_" lock while it waits indefinitely for the HMI.

**Comment by iCollin** [comment]
Hello, I cannot reproduce this issue in [`sdl_core@6.1.1`](https://github.com/smartdevicelink/sdl_core/tree/6.1.1).

I have tried to reproduce by making the following change in the generic_hmi:

```
diff --git a/src/js/Controllers/BCController.js b/src/js/Controllers/BCController.js
index b0cdaabc..1a08af94 100644
--- a/src/js/Controllers/BCController.js
+++ b/src/js/Controllers/BCController.js
@@ -62,7 +62,7 @@ class BCController {
                                          rpc.params.offset, rpc.params.length, rpc.params.isSystemFile, rpc.params.isPersistentFile))
                 return null
             case "UpdateDeviceList":
-                return true
+                return null
             case "MixingAudioSupported":
                 return {"rpc": RpcFactory.MixingAudioResponse(rpc)}
             case "PolicyUpdate":
```

I then started core, rebuilt and started the HMI, and connected a mobile device to the HMI. I activated the mobile app and then disconnected the device to be sure that the UpdateDeviceList request was being sent and NOT being replied to. After this I pressed the HMI's shutdown button to simulate an IGNITION_OFF, which caused core to gracefully stop.

Please let me know if you are still seeing this issue!
