### ISSUE TITLE
How to transfer multi screens?

### ISSUE THREAD

**Issue by gmmyok** [smartdevicelink/sdl_core#196]
I want to develop multi screens in the same App HMI.
(such as A screen and B screen)

First, A screen is displayed, 
user presses a button of A screen, 
and then B screen is displayed
(the screen is transferred from A to B)

Dose the SmartDeviceLink framework support it?
How to do it?

**Comment by gmmyok** [comment]
@justinjdickow Could you help me or give me some advice?

**Comment by stefanek22** [comment]
Although this is ultimately dependent upon a platform's HMI support, the overall concept is supported by any platform that integrates the SetDisplayLayout RPC.  Using that RPC, you can switch to other defined templates.

**Comment by gmmyok** [comment]
Basically I know what you mean, and I will investigate the SetDisplayLayout RPC.
thx a lot.
