### ISSUE TITLE
[SDL 0120] GetSystemTime RPC

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_core#1963]
Proposal: [GetSystemTime RPC](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0120-GetSystemTime.md)

> This proposal is about adding a new RPC GetSystemTime in order for SDL Core to get accurate system time information which is utilized by the TLS handshake mechanism.

Review: https://github.com/smartdevicelink/sdl_evolution/issues/362

Steering Committee Decision:

> After additional discussion about the OnSystemTimeReady notification, the Steering Committee voted to accept this proposal. While there were concerns with adding another RPC, it was determined that this is the most efficient route.

**Comment by jacobkeeler** [comment]
Closing with the merge of #2105
