### ISSUE TITLE
New remote control modules (LIGHT, AUDIO, HMI_SETTINGS) and parameters (SIS Data)

### ISSUE THREAD

**Issue by dboltovskyi** [smartdevicelink/sdl_core#1978]
## Description
_As a mobile application I want to be able to control components of the vehicle such as AUDIO, LIGHT and HMI_SETTINGS_

## Links
Proposal: [0099-new-remote-control-modules-and-parameters](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0099-new-remote-control-modules-and-parameters.md)

**Comment by joeygrover** [comment]
Closing as duplicate #1798 . Please search for existing issues before raising new ones.
