### ISSUE TITLE
Remote Control (Seats)

### ISSUE THREAD

**Issue by dboltovskyi** [smartdevicelink/sdl_core#1979]
## Description
_As a mobile application I want to be able to control components of the vehicle such as SEATs_

## Links
Proposal: [0105-remote-control-seat](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0105-remote-control-seat.md)

**Comment by joeygrover** [comment]
Closing as duplicate #1860. Please search for existing issues before raising new ones.
