### ISSUE TITLE
Remote Control - OnRCStatus notification

### ISSUE THREAD

**Issue by dboltovskyi** [smartdevicelink/sdl_core#1980]
## Description
_As a mobile application I want to be able to get OnRCStatus notification in order to have an information about allocated RC modules_

## Links
Proposal: [0106-remote-control-onRcStatus-notification](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0106-remote-control-onRcStatus-notification.md)

**Comment by joeygrover** [comment]
Closing as duplicate #1930 . Please search for existing issues before raising new ones.
