### ISSUE TITLE
DTLS encryption

### ISSUE THREAD

**Issue by dboltovskyi** [smartdevicelink/sdl_core#1981]
## Description
_As a mobile application I want communicate with SDL over DTLS protocol_

## Links
Proposal: [0040-DTLS-encryption](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0040-DTLS-encryption.md)

**Comment by joeygrover** [comment]
Closing as duplicate #1479 . Please search for existing issues before raising new ones.
