### ISSUE TITLE
GetSystemTime RPC

### ISSUE THREAD

**Issue by dboltovskyi** [smartdevicelink/sdl_core#1982]
## Description
_As SDL I want to be able to send GetSystemTime request to HMI in order to get accurate system time information_

## Links
Proposal: [0120-GetSystemTime](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0120-GetSystemTime.md)

**Comment by joeygrover** [comment]
Closing as duplicate #1963 . Please search for existing issues before raising new ones.
