### ISSUE TITLE
Provide AppIcon resumption across app registration requests

### ISSUE THREAD

**Issue by dboltovskyi** [smartdevicelink/sdl_core#1983]
## Description
_As a mobile application I want to see application icon immediately available upon registration of the app_

## Links
Proposal: [0041-appicon-resumption](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0041-appicon-resumption.md)

**Comment by joeygrover** [comment]
Closing as duplicate #1456. Please search for existing issues before raising new ones.
