### ISSUE TITLE
Expand Mobile putFile RPC

### ISSUE THREAD

**Issue by dboltovskyi** [smartdevicelink/sdl_core#1984]
## Description
_As a mobile application I want to enhance the reliability of large data transfers to the head unit by introducing a field for CRC in the putFile RPC_

## Links
Proposal: [0037-Expand-Mobile-putfile-RPC](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0037-Expand-Mobile-putfile-RPC.md)

**Comment by joeygrover** [comment]
Closing as duplicate #1455. Please search for existing issues before raising new ones.
