### ISSUE TITLE
Expandable Design for Proprietary Data Exchange

### ISSUE THREAD

**Issue by dboltovskyi** [smartdevicelink/sdl_core#1985]
## Description
_As a mobile application I want to have expandable design for Proprietary Data Exchange with Head Unit_

## Links
Proposal: [0083-Expandable-design-for-proprietary-data-exchange](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0083-Expandable-design-for-proprietary-data-exchange.md)

**Comment by joeygrover** [comment]
Closing as duplicate #1734. Issue is also already closed and merged. Please search for existing issues before raising new ones.
