### ISSUE TITLE
Template images

### ISSUE THREAD

**Issue by dboltovskyi** [smartdevicelink/sdl_core#1986]
## Description
_As a mobile application I want to be able to customize icons used on HMI_  

## Links
Proposal: [0062-template-images](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0062-template-images.md)

**Comment by joeygrover** [comment]
Closing as duplicate #1588. Issue is also already closed and merged. Please search for existing issues before raising new ones.
