### ISSUE TITLE
SendLocation for Mobile Nav

### ISSUE THREAD

**Issue by dboltovskyi** [smartdevicelink/sdl_core#1987]
## Description
_As a mobile application I want to have the capability of the system to re-route SendLocation requests to a capable Mobile Nav application, thus this allows applications to enhance the capability of a Head Unit by providing services which it natively may not support_

## Links
Proposal: [0130-SendLocation-for-Mobile-Nav](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0130-SendLocation-for-Mobile-Nav.md)

**Comment by joeygrover** [comment]
This evolution proposal has not yet been accepted and therefore should not have an issue attached.
