### ISSUE TITLE
Mobile Projection

### ISSUE THREAD

**Issue by dboltovskyi** [smartdevicelink/sdl_core#1988]
## Description
_As a mobile application I want to be able to stream a video feed to the system and allow users to interact with the application by touching the system's screen_

## Links
Proposal: [0031-mobile-projection](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0031-mobile-projection.md)

**Comment by joeygrover** [comment]
Closing as duplicate #1344. Issue is also already closed and merged. Please search for existing issues before raising new ones.
