### ISSUE TITLE
BlueZ 5.x transport adapter

### ISSUE THREAD

**Issue by justinjdickow** [smartdevicelink/sdl_core#2]
Should implement a separate transport adapter that supports OEMs using BlueZ 5.x.  Known issues so far with the current implementation of BlueZ 4.x are that bt-device is not supported for querying paired devices and connecting with the BlueZ 5.x dev APIs.

**Comment by JackLivio** [comment]
Bluez 5 is not supported on the current version of Ubuntu 14. When the sdl core supported environment is moved to Ubuntu 16, Bluez will be upgraded to version 5.
