### ISSUE TITLE
[SDL 0145] Driver Distraction Notification Upon Registration

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_core#2054]
Proposal: [Driver Distraction Notification Upon Registration](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0145-distraction-notification-after-registration.md)

> This document proposes that Core send an additional Driver Distraction Notification just after registration to ensure that the mobile device knows the distraction status at all times.

Review: https://github.com/smartdevicelink/sdl_evolution/issues/411

**Comment by jacobkeeler** [comment]
Closing with the merge of #2344
