### ISSUE TITLE
initialText in PerformInteraction does not accept nil

### ISSUE THREAD

**Issue by t-yoshii** [smartdevicelink/sdl_core#2061]
### Bug Report
initialText in PerformInteraction does not accept nil, empty string and spaces only text.
initialText is used as initial display string when input method is keyboard. Empty default string is very common use case for keyboard input. Threfore, SDL Core should accept empty string as initialText.

##### Reproduction Steps
1. Create PerformInteraction RPC with initialText nil or  "" (empty string) or "   " (space only)
2. Send RPC to SDL Core
3. SDL Core returns INVALID_DATA response to proxy

##### Expected Behavior
INVALID_DATA is not sent

##### Observed Behavior
INVALID_DATA is sent

##### OS & Version Information
* OS/Version: iOS/Android
* SDL Core Version: 4.5, 4.4
* Testing Against: Our internal devboard

##### Test Case, Sample Code, and / or Example App
I will create PR later.

**Comment by jacobkeeler** [comment]
This change would require a proposal
