### ISSUE TITLE
Broken link in README.md for Software Architecture Documentation

### ISSUE THREAD

**Issue by Nijhazer** [smartdevicelink/sdl_core#2091]
In the Documentation section of the README, there's a broken link titled Software Architecture Documentation. It points to this address:

https://smartdevicelink.com/en/guides/core/software-architecture-document/table-of-contents/

That link resolves in a 404.

**Comment by jacobkeeler** [comment]
So it is, some restructuring was done on the developer portal and it a appears that this link was never updated. The new link is https://smartdevicelink.com/en/docs/sdl-core/master/software-architecture-document/table-of-contents/

**Comment by jacobkeeler** [comment]
Closing with the merge of #2096
