### ISSUE TITLE
Invalid PTU starts infinite update loop

### ISSUE THREAD

**Issue by jacobkeeler** [smartdevicelink/sdl_core#2109]
### Bug Report
SDL doesn't respect the normal PTU retry sequence when it receives an invalid policy table from the update server, resulting in an infinite update loop. 

##### Reproduction Steps
1. Build SDL Core with default flags
2. Start Core
3. Perform a policy update with an invalid policy table from the cloud

##### Expected Behavior
SDL Core rejects the policy table and attempts an update after the specified retry timeout

##### Observed Behavior
SDL Core rejects the policy table and immediately attempts another policy table update, resulting in an endless PTU loop (assuming that the server continues sending an invalid policy table).

##### OS & Version Information
* OS/Version: Ubuntu 14.04
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/commit/6212599da217e95899d63d4b33088082489841bd
* Testing Against: N/A

**Comment by theresalech** [comment]
Fixed via #2114

**Comment by jacobkeeler** [comment]
Reopening with new case on EXTERNAL_PROPRIETARY mode:

##### Reproduction Steps
1. Build SDL Core with default flags
2. Start Core
3. Perform a policy update with an invalid policy table from the cloud
4. When a retry is attempted after the failure, return a valid policy table from the server

Infinite PTU occurs (caused by the update status never being updated from UPDATE_NEEDED to UPDATING)

**Comment by theresalech** [comment]
Closed via #2141
