### ISSUE TITLE
[SDL 0154] Add SDL Core Daemon script

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_core#2124]
Proposal: [Add SDL Core Daemon script](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0154-add-sdl-core-daemon-script.md)

> This proposal is for the addition of a daemon script allowing simple control over the lifecycle of SDL Core. This script would allow users to easily start/restart/stop SDL Core in the background without needing to create their own scripts to manage this behavior, as is currently the case.

Review: https://github.com/smartdevicelink/sdl_evolution/issues/444

**Comment by jacobkeeler** [comment]
Closing with the merge of #3417
