### ISSUE TITLE
[SDL 0149] Add capability to disable resumption based on app type and transport type

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_core#2130]
Proposal: [Add capability to disable resumption based on app type and transport type](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0149-mt-registration-limitation.md)

> This document proposes to add an advanced feature to disable or limit resumption feature based on AppHMIType and transport type. This is related to proposal [SDL-0141: Supporting simultaneous multiple transports](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0141-multiple-transports.md).

Review: https://github.com/smartdevicelink/sdl_evolution/issues/428

**Comment by jacobkeeler** [comment]
Closing with the merge of #2164
