### ISSUE TITLE
Add platform support for WinCE

### ISSUE THREAD

**Issue by henry-fan** [smartdevicelink/sdl_core#214]
We've successfully had sdl_core up and run on wince6. The changes were made for 3.6, we are merging them to 4.0. Raise the issue for upcoming pull requests. Thanks!

**Comment by jacobkeeler** [comment]
Outdated, but the PR for this is #274

**Comment by jacobkeeler** [comment]
I believe that to maintain such a port, we would need a corresponding proposal, closing for now
