### ISSUE TITLE
Building SDL-Core with -DBUILD_BT_SUPPORT=OFF stills links with BlueZ library

### ISSUE THREAD

**Issue by chinlin0924** [smartdevicelink/sdl_core#2152]
[Delete any non-applicable sections, but we may ask for more information.]

### Bug Report
[Summary]
Building sdl-core with -DBUILD_BT_SUPPORT=OFF stills links with bluez library due to misused CMakefile script.

Fix solution is here:
https://github.com/smartdevicelink/sdl_core/pull/2150/commits

##### Reproduction Steps
1. [Step 1]
Ensure you don't have libbluetooth-dev installed in PC
2. [Step 2]
Build SDL-Core with BUILD_BT_SUPPORT=OFF
3. [Step 3]
Got compiler error due to bluez library not installed
##### Expected Behavior
1. compiling should not link with bluez under the -DBUILD_BT_SUPPORT=OFF
##### Observed Behavior
1. Compiler error due to bluez linking failed
##### OS & Version Information
* OS/Version: 
1. Ubuntu 16.04
* SDL Core Version:
1. SDL Core 4.4.1
* Testing Against:
N/A
##### Test Case, Sample Code, and / or Example App
N/A

**Comment by jacobkeeler** [comment]
Not reproducible on master, seems to have been fixed by #2900
