### ISSUE TITLE
[SDL 0162] Define Handling of Duplicate Correlation IDs

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_core#2169]
Proposal: [Define Handling of Duplicate Correlation IDs](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0162-define-handling-of-duplicate-correlation-ids.md)

> This proposal is for the clarification of the SDL protocol behavior in the case that an app sends multiple messages with the same correlation ID.

Review: https://github.com/smartdevicelink/sdl_evolution/issues/476

Steering Committee Decision:

> The Steering Committee voted to accept this proposal. It was also confirmed by the Project Maintainer during the discussion that this proposal applies to all RPCs, and is trying to clarify that a Correlation ID should never be a duplicate from request to request. A request needs a response before a developer sends the same Correlation ID again in a new request.

**Comment by jacobkeeler** [comment]
Closing with the merge of #2101
