### ISSUE TITLE
[SDL 0164] Modernize Ubuntu Support

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_core#2170]
Proposal: [Modernize Ubuntu Support](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0164-modernize-ubuntu-support.md)

> This proposal is to add official support of the latest Ubuntu LTS Release (version 18.04 as of April 26th, 2018) to SDL Core, as well as update the minimum supported version from Ubuntu 14.04 to Ubuntu 16.04 as the former reaches the end of its support lifetime.

Review: https://github.com/smartdevicelink/sdl_evolution/issues/478

Steering Committee Decision:

> The Steering Committee agreed to accept this proposal, noting the two implementation parts as described in [jacobkeeler's comment](https://github.com/smartdevicelink/sdl_evolution/issues/478#issuecomment-384682205).

**Comment by jacobkeeler** [comment]
Partially complete with the merge of #2180.

Support for Ubuntu 14.04 will be dropped in SDL Core 5.0, at that time this proposal will be complete

**Comment by jacobkeeler** [comment]
Next release has been made a major release, meaning that this proposal is now fully complete
