### ISSUE TITLE
Invalid memory accesses detected by valgrind

### ISSUE THREAD

**Issue by shoamano83** [smartdevicelink/sdl_core#2177]
### Bug Report
Valgrind reports several invalid memory accesses while running a simple sequence.

##### Precondition

- Build Valgrind 3.13 from source and install (since Ubuntu 16.04 offers only up to 3.11)
- Pair the Linux system and Android phone through Bluetooth
- Build SDL Core with default configuration

##### Reproduction Steps
1. Start sdl_hmi (`$ google-chrome index.html`)
2. Start SDL Core with following command:
`$ LD_LIBRARY_PATH=. valgrind ./smartDeviceLinkCore > valgrind_output.txt 2>&1`
3. On Android phone, Launch RPC builder app and attempt to establish a connection over Bluetooth
4. Hit Ctrl-C to stop SDL Core

##### Expected Behavior
Valgrind does not report invalid memory access issues.

##### Observed Behavior
Valgrind reports several invalid memory access issues. Please refer to the attached log file.

##### OS & Version Information
* OS/Version: Ubuntu 16.04 (amd64), running on VirtualBox on Mac
* SDL Core Version: commit df9b67026d90f0f9cdf04bec7dd3c7666a25db87 from `develop` branch
* HMI: commit 5fc453a64b9962a66e203299e5a0ac57bb62541d from `master` branch
* Testing Against: Nexus 6 (Android 5.0.1), running rpc_builder_app from latest `master` branch

##### Test Case, Sample Code, and / or Example App
- valgrind log output: [valgrind_output.txt](https://github.com/smartdevicelink/sdl_core/files/1986379/valgrind_output.txt)
- SDL Core log file: [SmartDeviceLinkCore.log](https://github.com/smartdevicelink/sdl_core/files/1986380/SmartDeviceLinkCore.log)

**Comment by jacobkeeler** [comment]
Closing with the merge of #2178
