### ISSUE TITLE
Location of application info file (app_info.dat) is fixed to current directory

### ISSUE THREAD

**Issue by shoamano83** [smartdevicelink/sdl_core#2194]
### Bug Report

The application info JSON file `app_info.dat` is created in the current directory, which is same as the executable file. Though I could not find a clear specification, it seemed that the file was meant to be stored in the folder specified by `AppStorageFolder`.

- In https://github.com/smartdevicelink/sdl_core/blob/develop/src/components/resumption/src/last_state_impl.cc#L59, the code makes sure that the folder specified by `AppStorageFolder` exists before creating app_info.dat file.
- If I turn on `UseDBForResumption` flag in smartDeviceLink.ini, resumption.sqlite file is created in the folder specified by `AppStorageFolder`.

This behavior may be a problem on some systems where the executable is stored in a read-only directory (for example, mounted over squashfs.)

##### Reproduction Steps

1. Check out latest develop branch and give a build
2. Run SDL Core with ./start.sh

##### Expected Behavior

I think app_info.dat file should be created under "storage" folder.

##### Observed Behavior

app_info.dat file is created in the current directory.

##### OS & Version Information
* OS/Version: Ubuntu 16.04 (amd64)
* SDL Core Version: commit 65c1e7eb77fa949cce9c07f229e2cf747f297e14 from `develop` branch
* Testing Against: N/A

##### Test Case, Sample Code, and / or Example App

I also found that if I change the value of `AppInfoStorage` in the ini file to include directories, SDL Core doesn't start up properly. For exmaple,
```ini
AppInfoStorage = mytestdir/storage/app_info.dat
```

will result:

```
$ ./start.sh 
smartDeviceLinkCore: /home/samano/projects/xevo_github_sdl_core/sdl_core/src/components/resumption/src/last_state_impl.cc:62: virtual void resumption::LastStateImpl::SaveStateToFileSystem(): Assertion `(file_system::Write(app_info_storage_, char_vector_pdata))' failed.
./start.sh: line 2:   383 Aborted                 (core dumped) LD_LIBRARY_PATH=. ./smartDeviceLinkCore
```
Log is attached: [SmartDeviceLinkCore.zip](https://github.com/smartdevicelink/sdl_core/files/2021568/SmartDeviceLinkCore.zip)

**Comment by shoamano83** [comment]
I think there are two approaches to resolve this issue.

1. Move app_info.dat into the directory specified by `AppStorageFolder`. I think this is the intention of the original code. I created PR for this: https://github.com/smartdevicelink/sdl_core/pull/2195
2. Fix the implementation so that `AppInfoStorage` can also contain directories, not only a file name.

Hi @JackLivio , @jacobkeeler , could you kindly share your thoughts?
Thanks.

**Comment by jacobkeeler** [comment]
Closing with the merge of #3686
