### ISSUE TITLE
Icons should be stored in dedicated folder

### ISSUE THREAD

**Issue by shoamano83** [smartdevicelink/sdl_core#2200]
### Bug Report

In the default smartDeviceLink.ini configuration, both `AppStorageFolder` and `AppIconsFolder` point to a single folder. With this configuration, a file in the folder might be accidentally removed when the folder size reaches to the quota specified by `AppIconsFolderMaxSize`.

The code in set_app_icon_request.cc assumes that the icon folder includes only icon files. Therefore, I think `AppIconsFolder` should point to a dedicated folder.

##### Reproduction Steps

1. Increase `AppDirectoryQuota` value in smartDeviceLink.ini file to 1000 MB:
```
AppDirectoryQuota = 1048576000
```
2. Create "storage" folder and create a dummy file of 200 MB in it:
```
$ mkdir storage
$ dd if=/dev/zero of=storage/dummy_file.bin count=204800 bs=1024
```
3. Run ./start.sh
4. Launch sdl_hmi
5. Using sdl_ios' example app, connect the app to Core through TCP transport
6. Make the app in FULL level

##### Expected Behavior

Files in "storage" folder should be kept intact as `AppDirectoryQuota` is large enough.

##### Observed Behavior

The dummy file in "storage" folder is deleted.

##### OS & Version Information
* OS/Version: Ubuntu 16.04 (amd64)
* SDL Core Version: commit 65c1e7eb77fa949cce9c07f229e2cf747f297e14 from `develop` branch
* Testing Against: sdl_hmi (commit 18460356c02e985df598b94f5a6bdbba1c451fff from `master`), example app of sdl_ios release 5.2.0 on iPhone X (iOS 11.3 beta)

##### Test Case, Sample Code, and / or Example App
Log: [SmartDeviceLinkCore.zip](https://github.com/smartdevicelink/sdl_core/files/2022473/SmartDeviceLinkCore.zip)
smartDeviceLink.ini: [smartDeviceLink.zip](https://github.com/smartdevicelink/sdl_core/files/2022475/smartDeviceLink.zip)

**Comment by shoamano83** [comment]
I know this issue can be easily avoided by each OEM configuring appropriate folder for `AppIconsFolder`. Also, I agree that this issue won't happen easily as the quota is fairly large (100MB, I think this is another issue though). Nevertheless, I still think that the default ini file should clarify that `AppIconsFolder` contains only icon files.

**Comment by iCollin** [comment]
Closed via https://github.com/smartdevicelink/sdl_core/pull/2202
