### ISSUE TITLE
[SDL 0158] Cloud App Transport Adapter

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_core#2215]
Proposal: [Cloud App Transport Adapter](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0158-cloud-app-transport-adapter.md)

> This proposal will detail a possible solution for allowing SDL-enabled cloud applications to be used in a vehicle. This proposal will cover the process of obtaining cloud application server endpoints, enabling which cloud apps should appear in the HMI app list, opening connections between Core and a cloud based app server, and how a cloud application can authenticate connected head units.

Review Issue: smartdevicelink/sdl_evolution#493

Revisions to the review issue: https://github.com/smartdevicelink/sdl_evolution/issues/666

Steering Committee Decision:
> The Steering Committee voted to accept this proposal with revisions. The revisions will include changing the `app_icon_url` policy table attribute to `icon_url` as mentioned in [this comment](https://github.com/smartdevicelink/sdl_evolution/issues/666#issuecomment-459826599), include the affecting platforms based on the protocol changes mentioned in [this comment](https://github.com/smartdevicelink/sdl_evolution/issues/666#issuecomment-460424274), and rename `cloudAppAuthToken` to `authToken` noted in [this comment](https://github.com/smartdevicelink/sdl_evolution/issues/666#issuecomment-460661104).  
Additionally, the author stated that OEMs have the ability to specify secure websockets or unsecured websockets whether you have WS or WSS specified in `cloud_transport_type` in the policy table.

> Revisions have been made 

Additional revisions accepted on 2019-03-15:

- Make CloudAppProperties parameter `appName` non-mandatory. 
- Make CloudAppProperties parameter `appName` an array.
- Rename CloudAppProperties parameter `appName` to `nicknames`

**Comment by jordynmackool** [comment]
Accepted revisions as of 2019-03-06: https://github.com/smartdevicelink/sdl_evolution/issues/666#issuecomment-461205796

Additional revisions accepted on 2019-03-15: https://github.com/smartdevicelink/sdl_evolution/pull/689

- Make CloudAppProperties parameter `appName` non-mandatory. 
- Make CloudAppProperties parameter `appName` an array.
- Rename CloudAppProperties parameter `appName` to `nicknames`

**Comment by jacobkeeler** [comment]
Closing with the merge of #2853
