### ISSUE TITLE
Can't git clone the tutorial code

### ISSUE THREAD

**Issue by kingtheus** [smartdevicelink/sdl_core#222]
hi, i can't get the code: https://bitbucket.org/fmcalt/sdlmobile_ios_mobileweather_tutorial

fatal: Authentication failed for 'https://bitbucket.org/fmcalt/sdlmobile_ios_mobileweather_tutorial/'

is this project in private mode?

**Comment by justinjdickow** [comment]
@kingtheus The correct URL for mobile weather iOS is https://github.com/smartdevicelink/sdl_mobileweather_tutorial_ios.git
