### ISSUE TITLE
SDL core dump by usb unplug after unsuccessful processed SetInteriorVD

### ISSUE THREAD

**Issue by GetmanetsIrina** [smartdevicelink/sdl_core#2228]
[Delete any non-applicable sections, but we may ask for more information.]

### Bug Report
SDL core dump by usb unplug after unsuccessful processed SetInteriorVD

##### Reproduction Steps
1. RADIO and CLIMATE modules, RC RPCs are allowed by policies.
2. RC app is registered and activated
3. Mobile app requests SetInteriorVD(RADIO) with all params 
4. HMI returns error result code
5. Repeat steps 3,4 few times
6. Try to exit from app and re-registered it again( before re-registration it is needed to unplug, plug USB )

##### Expected Behavior
App is re-registered successful

##### Observed Behavior
Code dump

##### OS & Version Information
* OS/Version: Ubuntu 16.04
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/tree/feature/rc_OnRCStatus(  9a0fa27  )
* Testing Against: Transport: USB, HMI : https://github.com/smartdevicelink/sdl_hmi/tree/feature/new_remote_control_modules( 83fbb79), Mobile app: Ford SPT: 20180516

##### Attach 
[setinteriorVD_onrcstatus.tar.gz](https://github.com/smartdevicelink/sdl_core/files/2062522/setinteriorVD_onrcstatus.tar.gz)

**Comment by dboltovskyi** [comment]
Issue is not reproduced at environment: 
sdl_core: https://github.com/smartdevicelink/sdl_core/tree/release/8.0.0 (de58a41)
sdl_hmi: https://github.com/smartdevicelink/sdl_hmi/tree/release/5.6.0 (aa84d6b)
SPT: 20210729
