### ISSUE TITLE
"language" and "hmiDisplayLanguage" in RAI response are set to -1 when UI, TTS, VR active languages are not valid.

### ISSUE THREAD

**Issue by t-yoshii** [smartdevicelink/sdl_core#2230]
### Bug Report
"language" value in Register App Interface response are set to -1 when VR active language at HMI is INVALID_ENUM.
"hmiDisplayLanguage" value in Register App Interface response are set to -1 when UI active language at HMI is INVALID_ENUM.
-1 is the raw value of INVALID_ENUM.

INVALID_ENUM(-1) is not defined for "Language" type in MOBILE_API.xml.
"language" and "hmiDisplayLanguage" are not mandatory parameter in RAI response, therefore, these values should not be set when not valid instead of being set to -1.

iOS SDL Proxy expects these values are string, therefore, iOS SDL Apps can cause crash due to this value. 

##### Reproduction Steps
1. Set active VR language or UI language on HMI invalid.
2. Register iOS SDL app
3. Access SDLManager.registerResponse.language or SDLManager.registerResponse.hmiDisplayLanguage in app.
4. App crash occur

##### Expected Behavior
App does not crash

##### Observed Behavior
App crash occurs

##### OS & Version Information
* OS/Version: iOS proxy 5.2.0
* SDL Core Version: SDL Core 4.4, 4.5
* Testing Against: Our internal HU devboard and internal iOS SDL testing app

##### Test Case, Sample Code, and / or Example App
I will create PR later.

**Comment by E-SAITO-TMC** [comment]
@joeygrover -san
A fix has been proposed for this bug. When will it be merged? For the next HU development of TOYOTA, it is necessary to improve the quality of SDLCore, so we believe it is necessary to modify this item.

**Comment by theresalech** [comment]
Hi @E-SAITO-TMC, contents for SDL releases are determined by the Steering Committee, and the Project Maintainer works on features and bug fixes raised as high priority by Steering Committee representatives.  This particular issue has not yet been raised as high priority.  However, if Toyota would like to see this fix in the next release of SDL Core (planned for October 28, 2020), we can make note of such.  

Please confirm if this is priority for Toyota.  If so, we will include this issue in our proposed release contents, which will be presented to the Steering Committee and voted upon/finalized in June.  Thank you!

**Comment by E-SAITO-TMC** [comment]
@theresalech -san Thank you for your comment. This issue is important for Toyota. Therefore, we would appreciate it if you can make this a high-priority.

**Comment by theresalech** [comment]
@E-SAITO-TMC, thank you.  We have documented that this is priority for Toyota, and will include for Steering Committee review and vote when planning the contents for the Q4 Core release. This planning will take place in June.
