### ISSUE TITLE
[SDL 0170] SDL behavior in case of LOW_VOLTAGE event

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_core#2233]
Proposal: [SDL behavior in case of LOW_VOLTAGE event](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0170-sdl-behavior-in-case-of-Low-Voltage.md)

> This proposal defines SDL behavior when HMI requires SDL's services to be suspended due to a low voltage event. A low voltage scenario is triggered when the battery voltage hits below a certain predefined threshold set by the system. In case of such an event, the EMMC is turned off and all read/write operations are unavailable. After the voltage level is restored all operations are resumed.

Review: smartdevicelink/sdl_evolution#489

Steering Committee Decision:
> The Steering Committee has voted to accept this proposal with revisions. The revisions will include the use of 3 signals of the range SIGRTMIN - SIGRTMAX for LowVoltage, WakeUp and IgnitionOff - in place of using mqueue messages.

> The proposal .md was updated on June 5, 2018 to include the agreed upon revisions.

**Comment by theresalech** [comment]
Proposal markdown file has been updated per the revisions included in accepted Evolution Proposal [SDL 0170 Revisions - Accepted SDL behavior in case of LOW_VOLTAGE event: Resumption during Low Voltage](https://github.com/smartdevicelink/sdl_evolution/pull/538).

**Comment by jacobkeeler** [comment]
Closing with the merge of #2418

**Comment by FStoikov** [comment]
Jira ticket created for current case: https://adc.luxoft.com/jira/browse/FORDTCN-928

**Comment by FStoikov** [comment]
Jira ticket created for current case: https://adc.luxoft.com/jira/browse/FORDTCN-928
