### ISSUE TITLE
SubscribeVehicleData/UnsubscribeVehicleData: SDL sends SUCCESS:true in case if all RPC parameters are disallowed

### ISSUE THREAD

**Issue by dboltovskyi** [smartdevicelink/sdl_core#2245]
### Bug Report
SDL sends SUCCESS:true in case if all RPC parameters are disallowed.

##### Reproduction Steps
1. Make sure some parameters are disallowed for SubscribeVehicleData/UnsubscribeVehicleData RPC in Policy Table.
2. Try to send RPC with these parameters only.

##### Expected Behavior
SDL sends to mobile app: DISALLOWED:false
E.g.:
```
{
    "resultCode": "DISALLOWED",
    "success": false,
    "info": "'engineOilLife' disallowed by policies.",
    "engineOilLife": {
        "dataType": "VEHICLEDATA_ENGINEOILLIFE",
        "resultCode": "DISALLOWED"
    }   
}
```

##### Observed Behavior
SDL sends to mobile app: SUCCESS:true
E.g.:
```
{
    "resultCode": "SUCCESS",
    "success": true,
    "info": "Already subscribed on provided VehicleData. 'engineOilLife' disallowed by policies.",
    "engineOilLife": {
        "dataType": "VEHICLEDATA_ENGINEOILLIFE",
        "resultCode": "DISALLOWED"
    }   
}
```

##### OS & Version Information
* OS/Version: Ubuntu 16.04
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/tree/develop
* Testing Against: ATF

##### Test Case, Sample Code, and / or Example App
Issue is related to https://github.com/smartdevicelink/sdl_atf_test_scripts/issues/1890

ATF test scripts:
  - [API/VehicleData/OnVehicleData/003_NotificationParameterDisallowedByPolicies_Ignored_flow](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/API/VehicleData/OnVehicleData/003_NotificationParameterDisallowedByPolicies_Ignored_flow.lua) 
  - [API/VehicleData/SubscribeVehicleData/002_RPC_parameter_DISALLOWED_by_policies_flow](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/API/VehicleData/SubscribeVehicleData/002_RPC_parameter_DISALLOWED_by_policies_flow.lua)

**Comment by E-SAITO-TMC** [comment]
@joeygrover -san
A fix has been proposed for this bug. When will it be merged? For the next HU development of TOYOTA, it is necessary to improve the quality of SDLCore, so we believe it is necessary to modify this item.

**Comment by theresalech** [comment]
Hi @E-SAITO-TMC, contents for SDL releases are determined by the Steering Committee, and the Project Maintainer works on features and bug fixes raised as high priority by Steering Committee representatives.  This particular issue has not yet been raised as high priority.  However, if Toyota would like to see this fix in the next release of SDL Core (planned for October 28, 2020), we can make note of such.  

Please confirm if this is priority for Toyota.  If so, we will include this issue in our proposed release contents, which will be presented to the Steering Committee and voted upon/finalized in June.  Thank you!

**Comment by E-SAITO-TMC** [comment]
@theresalech -san Thank you for your comment. This issue is medium-priority for Toyota.

**Comment by theresalech** [comment]
@E-SAITO-TMC, thank you. We have documented that this is medium priority for Toyota, and will include for Steering Committee review and vote when planning the contents for the Q4 Core release. This planning will take place in June.

**Comment by iCollin** [comment]
@dboltovskyi Hello, I see `test_scripts/API/VehicleData/SubscribeVehicleData/002_RPC_parameter_DISALLOWED_by_policies_flow.lua` passing against current develop. Can you confirm if issue is still actual?

**Comment by dboltovskyi** [comment]
@iCollin Confirmed. Issue is not actual for current develop of `sdl_core` (f2119f4b99) and can be closed.

**Comment by theresalech** [comment]
Closing per comments above.
