### ISSUE TITLE
Memory leaks in media_manager_test unit tests

### ISSUE THREAD

**Issue by shoamano83** [smartdevicelink/sdl_core#2274]
### Bug Report
Memory leaks are observed when `media_manager_test` is executed under valgrind.

##### Reproduction Steps
1. Check out commit 1527db9a68a54e07891ccfad0c2532f0813704d7 from `develop` branch
2. Give a build with `cmake ../sdl_core -DBUILD_TESTS=ON` and `make`
3. under `src/components/media_manager/test` directory, run `valgrind --trace-children=yes --leak-check=full ./media_manager_test > media_manager_test_valgrind.txt 2>&1`

##### Expected Behavior
Memory leaks should not be observed.

##### Observed Behavior
Valgrind reports several memory leaks. Please refer to attached log files.

##### OS & Version Information
* OS/Version: Ubuntu 16.04 (amd64)
* SDL Core Version: Commit 1527db9a68a54e07891ccfad0c2532f0813704d7 from `develop` branch
* Testing Against: N/A (unit testing)

##### Test Case, Sample Code, and / or Example App
Valgrind log is attached: [media_manager_test_valgrind.txt](https://github.com/smartdevicelink/sdl_core/files/2111027/media_manager_test_valgrind.txt)

**Comment by jacobkeeler** [comment]
Closing with the merge of #2275
