### ISSUE TITLE
SDL does not send UnsubscribeVehicleData request to HMI after unregister second app

### ISSUE THREAD

**Issue by GetmanetsIrina** [smartdevicelink/sdl_core#2282]
### Bug Report
SDL does not send UnsubscribeVehicleData request to HMI after unregister second app

##### Reproduction Steps
1. app1 and app2 are registered
2. Apps are activated, app1 in FULL, app2 in LIMITED
3. app1, app2 is subscribed to vd_1
4. Unregister app1 and app2 or perform unexpected disconnect

##### Expected Behavior
By unregistration of the second app2 SDL sends VehicleInfo.UnsubscribeVehicleData request to HMI.

##### Observed Behavior
SDL does not send VehicleInfo.UnsubscribeVehicleData request to HMI.

##### OS & Version Information
* OS/Version: Ubuntu 16.04
* SDL Core Version: develop branch (2ec732c56e3f06b7043cf02cf98109720d6ff38a)
* Testing Against: ATF: [develop branch](https://github.com/smartdevicelink/sdl_atf/tree/develop)
Script: https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/1936 (006_Success_flow_2_apps_unregister.lua)

[Updated_scrpt_for_reproducing_defect.tar.gz](https://github.com/smartdevicelink/sdl_core/files/3656520/Updated_scrpt_for_reproducing_defect.tar.gz)

##### Attach
[SmartDeviceLinkCore_unsubscribe_unregister.log.tar.gz](https://github.com/smartdevicelink/sdl_core/files/2118408/SmartDeviceLinkCore_unsubscribe_unregister.log.tar.gz)

**Comment by jacobkeeler** [comment]
Closing with the merge of #2501
