### ISSUE TITLE
Unclear message dump in protocol handler unit test (when a test case fails)

### ISSUE THREAD

**Issue by shoamano83** [smartdevicelink/sdl_core#2310]
### Bug Report
Some of protocol handler unit tests output message dumps when they fail. Unfortunately, the dump doesn't help debugging because of an issue in its format.

##### Reproduction Steps
1. Check out commit a79341d7a35b7d97e239d4908a34b72978d5a821 of `develop` branch
2. Apply attached diff to make a test case fail
3. Give a build and run `./protocol_handler_test --gtest_filter="ProtocolHandlerImplTest.StartSession_Unprotected_Multiple_SessionObserverAcceptAndReject"` in `src/components/protocol_handler/test/` directory

##### Expected Behavior
The test case fails. We should get a clear hex dump of a message to help debugging.

##### Observed Behavior
The hex dump has a format issue. Please refer to the log output below.
```
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from ProtocolHandlerImplTest
[ RUN      ] ProtocolHandlerImplTest.StartSession_Unprotected_Multiple_SessionObserverAcceptAndReject
unknown file: Failure

Unexpected mock function call - returning default value.
    Function call: SendMessageToDevice(1)
          Returns: 0
Google Mock tried the following 2 expectations, but none matched:

/home/samano/projects/xevo_github_sdl_core/sdl_core/src/components/protocol_handler/test/protocol_handler_tm_test.cc:744: tried expectation #0: EXPECT_CALL(transport_manager_mock, SendMessageToDevice(ControlMessage(FRAME_DATA_START_SERVICE_ACK, PROTECTION_OFF, connection_id1, Eq(ack_params))))...
  Expected arg #0: Unprotected control message 
           Actual: 1, Message with 62 byte data : 0x3e000126d74750e830000002766964656f50726f746f636f6c0400052415702766964656f436f646563050004832363400
         Expected: to be called once
           Actual: never called - unsatisfied and active
```

In the hex dump, I found **a byte is expressed either in one digit or in two digits**. So, in the dump `0x3e000126d...` we cannot distinguish if it's `0x3e 0x00 0x00 0x00 0x01 0x02 0x6d ...` or `0x3e 0x00 0x00 0x00 0x12 0x6d ...` or even `0x3e 0x00 0x00 0x00 0x01 0x26 0xd7 ...`.

IMHO such hex dump should always output a byte in two digits to avoid confusion.

##### OS & Version Information
* OS/Version: Ubuntu 16.04 (amd64)
* SDL Core Version: commit a79341d7a35b7d97e239d4908a34b72978d5a821 of `develop` branch
* Testing Against: N/A (unit testing)

##### Test Case, Sample Code, and / or Example App
[protocol_handler_test_failure_example.patch.txt](https://github.com/smartdevicelink/sdl_core/files/2143513/protocol_handler_test_failure_example.patch.txt)

**Comment by jacobkeeler** [comment]
Closing with the merge of #2311
