### ISSUE TITLE
Change post-increments to pre-increments

### ISSUE THREAD

**Issue by ghost** [smartdevicelink/sdl_core#2314]
### Introduction

Post-increments on iterators may be the reason of performance leaks. Also pre-increments are required by the [Google styleguide](https://google.github.io/styleguide/cppguide.html#Preincrement_and_Predecrement).

### Motivation

When a variable is incremented (++i or i++) or decremented (--i or i--) and the value of the expression is not used, one must decide whether to preincrement (decrement) or postincrement (decrement).
When the return value is ignored, the "pre" form (++i) is never less efficient than the "post" form (i++), and is often more efficient. This is because post-increment (or decrement) requires a copy of i to be made, which is the value of the expression. If i is an iterator or other non-scalar type, copying i could be expensive.

### Proposed solution

The issue is about to change the all post-increment to pre-increment because it will save the memory and won't to copy the object.

**Comment by iCollin** [comment]
Closed via https://github.com/smartdevicelink/sdl_core/pull/3687
