### ISSUE TITLE
Increase Policy unit-tests speed

### ISSUE THREAD

**Issue by ZhdanovP** [smartdevicelink/sdl_core#2316]
### Description

We can speed up the running of policy unit-tests by optimizing calls to sql.
The following unit-tests need to be optimized: 

.../policy/
    policy_external/
        **sql_pt_ext_representation_test.cc**
        **sql_pt_representation_test.cc**
    policy_regular/
        **sql_pt_representation_test.cc**

### Motivation

Increase tests running speed to reduce costs time for CI server

### Proposed solution

Increase Policy unit-tests speed by moving policy data base used by unit tests from file system to RAM.

**Comment by iCollin** [comment]
Closed via https://github.com/smartdevicelink/sdl_core/pull/2315
