### ISSUE TITLE
Remove commented code

### ISSUE THREAD

**Issue by ZhdanovP** [smartdevicelink/sdl_core#2324]
### Bug Report

After this [commit](https://github.com/smartdevicelink/sdl_core/commit/376c972ba76aa042fbd17f36cce9518d57d7b52d#diff-4a218fe8200a2573d8f1a13e6c55dcda) we have a lot of unnecessary commented code. It would be good to eliminate all of this code.

##### Reproduction Steps
Check out develop branch [...57d7b52d](https://github.com/smartdevicelink/sdl_core/commit/376c972ba76aa042fbd17f36cce9518d57d7b52d#diff-4a218fe8200a2573d8f1a13e6c55dcda)

##### Expected Behavior
Delete all unnecessary commented code.

##### OS & Version Information
* OS/Version: Ubuntu 16.04 (amd64)
* SDL Core Version: Commit [...57d7b52d](https://github.com/smartdevicelink/sdl_core/commit/376c972ba76aa042fbd17f36cce9518d57d7b52d#diff-4a218fe8200a2573d8f1a13e6c55dcda)
* Testing Against: N/A

**Comment by iCollin** [comment]
Closed via https://github.com/smartdevicelink/sdl_core/pull/2328
