### ISSUE TITLE
Cppcheck failure in Travis build

### ISSUE THREAD

**Issue by shoamano83** [smartdevicelink/sdl_core#2326]
### Bug Report
Travis build isn't successful on latest `develop` branch.
https://travis-ci.org/smartdevicelink/sdl_core/builds/398256262

##### Reproduction Steps
1. Please refer to the Travis CI output.

##### Expected Behavior
Travis build should be successful.

##### Observed Behavior
Travis detects an error with cppcheck:
```
$ cppcheck --force -isrc/3rd_party -isrc/3rd_party-static --quiet --error-exitcode=1 src
[src/components/application_manager/rpc_plugins/sdl_rpc_plugin/test/commands/hmi/activate_app_request_test.cc:109]: (error) Invalid number of character (() when these macros are defined: ''.
The command "cppcheck --force -isrc/3rd_party -isrc/3rd_party-static --quiet --error-exitcode=1 src" exited with 1.
```
##### OS & Version Information
* SDL Core Version: commit ba1da7bc2ff3fd37638620f6bea526384646ab0e from `develop` branch
* Testing Against: Detected by Travis CI

**Comment by jacobkeeler** [comment]
Closing with the merge of #2327
