### ISSUE TITLE
[SDL 0180] Broaden Choice Uniqueness

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_core#2346]
Proposal: [Broaden Choice Uniqueness](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0180-broaden-choice-uniqueness.md)

>This proposal broadens choice and sub-menu uniqueness to allow `PerformInteraction` and sub-menu `AddCommand` primary text to be identical.

Review: https://github.com/smartdevicelink/sdl_evolution/issues/530

Steering Committee Decision:

> The Steering Committee voted to accept this proposal with the following revisions: numbers should be added after duplicate(s) for older versions of core, and documentation should call out that while the primary text doesn't have to be unique, it has to be clear.
> The proposal was revised to incorporate these revisions on July 12, 2018.

**Comment by jordynmackool** [comment]
The proposal markdown file has been updated per the revisions included in the accepted [Revise SDL-0180 - Broaden Choice Uniqueness](https://github.com/smartdevicelink/sdl_evolution/issues/1116). 

Accepted revisions can be reviewed in the merged PR here: https://github.com/smartdevicelink/sdl_evolution/pull/1115.

**Comment by jordynmackool** [comment]
closed via https://github.com/smartdevicelink/sdl_core/pull/3607
