### ISSUE TITLE
Request from HMI has param with out of bounds

### ISSUE THREAD

**Issue by HSavynetska** [smartdevicelink/sdl_core#2348]
### Bug Report
Request from HMI has param with out of bounds.

##### Reproduction Steps
1. HMI sends *request to SDL (please see list of impacted RPCs below) and this request has at least one param with out-of-bounds array ranges OR out-of-bounds parameters values (including parameters of the structures) of any type.

Information;
a. List of impacted RPCs:

    SDL.GetDeviceConnectionStatus
    SDL.ActivateApp
    SDL.GetUserFriendlyMessage
    SDL. GetListOfPermissions
    SDL. UpdateSDL
    SDL. GetStatusUpdate
    SDL. GetURLs
    BC.GetSystemTime

##### Expected Behavior
Log corresponding error internally respond with 'INVALID_DATA' to HMI.

##### OS & Version Information
* OS/Version: 
* SDL Core Version: 
* Testing Against:

**Comment by dboltovskyi** [comment]
Issue is closed since the same case is described in https://github.com/smartdevicelink/sdl_core/issues/1865
