### ISSUE TITLE
Request from HMI has param with wrong type

### ISSUE THREAD

**Issue by HSavynetska** [smartdevicelink/sdl_core#2350]
### Bug Report
Request from HMI has param with wrong type.

##### Reproduction Steps
1. HMI sends *request to SDL (please see list of impacted RPCs below) and this request has at least param with wrong type.

##### Expected Behavior
Log corresponding error internally respond with 'INVALID_DATA' to HMI.

##### OS & Version Information
* OS/Version: 
* SDL Core Version: 
* Testing Against:

**Comment by dboltovskyi** [comment]
Issue is closed since the same case is described in https://github.com/smartdevicelink/sdl_core/issues/1865
