### ISSUE TITLE
SDL behavior: HMI sends request (response, notification) with fake parameters that SDL should transfer to mobile

### ISSUE THREAD

**Issue by HSavynetska** [smartdevicelink/sdl_core#2353]
### Bug Report
SDL behavior: HMI sends request (response, notification) with fake parameters that SDL should transfer to mobile.

##### Reproduction Steps
1. HMI sends request (response, notification) with fake parameters that SDL should transfer to mobile app

##### Expected Behavior
SDL must:
validate received response
cut off fake parameters
transfer this request (response or notification) to mobile app

##### OS & Version Information
* OS/Version: 
* SDL Core Version: 
* Testing Against:

**Comment by jacobkeeler** [comment]
Not reproducible on the latest develop
