### ISSUE TITLE
SDL behavior: HMI sends request (response, notification) with fake parameters that SDL should use internally

### ISSUE THREAD

**Issue by HSavynetska** [smartdevicelink/sdl_core#2354]
### Bug Report
SDL behavior: HMI sends request (response, notification) with fake parameters that SDL should use internally.

##### Reproduction Steps
1. HMI sends request (response, notification) with fake parameters that SDL should use internally.

##### Expected Behavior
SDL must:
validate received response
cut off fake parameters
contimue processing of received request (response, notification) from HMI

##### OS & Version Information
* OS/Version: 
* SDL Core Version: 
* Testing Against:

**Comment by jacobkeeler** [comment]
Not reproducible on the latest develop
