### ISSUE TITLE
SDL behavior in case HMI sends invalid response AND SDL must transfer this response to mobile app

### ISSUE THREAD

**Issue by HSavynetska** [smartdevicelink/sdl_core#2355]
### Bug Report
SDL behavior in case HMI sends invalid response AND SDL must transfer this response to mobile app.

##### Reproduction Steps
1. HMI sends invalid response by any reason that SDL must transfer to mobile app.

Information:
1. Invalid response means the response contains:
a. params out of bounds
b. mandatory params are missing
c. params of wrong type
d. invalid json
Note: in case SDL cannot parse 'method_name' from json then SDL must respond to mobile app GENERIC_ERROR, info: "'%component-name%' component does not respond"
e.incorrect combination of params

##### Expected Behavior
SDL must:
Log the error internally
respond GENERIC_ERROR (success:false, info: "Invalid message received from vehicle") to mobile app

##### OS & Version Information
* OS/Version: 
* SDL Core Version: 
* Testing Against:

**Comment by dboltovskyi** [comment]
Described scenario is covered in many existing scripts. E.g.:
```
./test_scripts/API/VehicleData/GetVehicleData/004_GetVD_HMI_responds_with_invalid_data.lua
./test_scripts/API/VehicleData/SubscribeVehicleData/004_SubscribeVD_HMI_responds_with_invalid_data.lua
./test_scripts/API/VehicleData/UnsubscribeVehicleData/004_UnsubscribeVD_HMI_responds_with_invalid_data.lua
./test_scripts/RC/AUDIO_LIGHT_HMI_SETTINGS/GetInteriorVehicleData/008_GENERIC_ERROR_in_case_HMI_respond_with_invalid_data.lua
./test_scripts/RC/CLIMATE_RADIO/GetInteriorVehicleData/008_GENERIC_ERROR_in_case_HMI_respond_with_invalid_data.lua
./test_scripts/RC/CLIMATE_RADIO/GetInteriorVehicleDataConsent/010_HMI_invalid_response_BP.lua
./test_scripts/RC/CLIMATE_RADIO/SetInteriorVehicleData/014_GENERIC_ERROR_in_case_HMI_respond_with_invalid_data.lua
./test_scripts/RC/SEAT/GetInteriorVehicleData/005_GENERIC_ERROR_in_case_HMI_respond_with_invalid_data.lua
./test_scripts/RC/SEAT/SetInteriorVehicleData/007_GENERIC_ERROR_in_case_HMI_respond_with_invalid_data.lua{code}
 ```
Since all these scripts PASSED on a current develop (218aee1) issue is closed.
