### ISSUE TITLE
SDL must send GENERIC_ERROR to mobile app in case SDL cuts off fake params from RPC and this RPC becomes invalid

### ISSUE THREAD

**Issue by HSavynetska** [smartdevicelink/sdl_core#2356]
### Bug Report
SDL must send GENERIC_ERROR to mobile app in case SDL cuts off fake params from RPC and this RPC becomes invalid.

##### Reproduction Steps
1. SDL cuts off fake parameters from response (request ) that SDL should transfer to mobile app AND this response (request) is invalid.

##### Expected Behavior
SDL must: Respond GENERIC_ERROR (success:false, <info>) to mobile app.

##### OS & Version Information
* OS/Version: 
* SDL Core Version: 
* Testing Against:

**Comment by AStasiuk** [comment]
Implemented in PR - https://github.com/smartdevicelink/sdl_core/pull/2394
