### ISSUE TITLE
Description for SeatControlCapabilities, RadioControlCapabilities moduleName are wrong in mobile api

### ISSUE THREAD

**Issue by mrapitis** [smartdevicelink/sdl_core#2372]
### Bug Report
The description for SeatControlCapabilities, RadioControlCapabilities in the mobile api makes reference to the climate control module.  Likely a copy / paste error during development.  Please see links below for details.
https://github.com/smartdevicelink/sdl_core/blob/develop/src/components/interfaces/MOBILE_API.xml#L2897

https://github.com/smartdevicelink/sdl_core/blob/develop/src/components/interfaces/MOBILE_API.xml#L2768

**Comment by iCollin** [comment]
Closed via https://github.com/smartdevicelink/rpc_spec/pull/319; https://github.com/smartdevicelink/rpc_spec/issues/321 added to the rpc_spec project.
