### ISSUE TITLE
SDL must send log error and ignore invalid RPC in case SDL cuts off fake parameters and RPC becomes invalid

### ISSUE THREAD

**Issue by HSavynetska** [smartdevicelink/sdl_core#2379]
### Bug Report
SDL must send log error and ignore invalid RPC in case SDL cuts off fake parameters and RPC becomes invalid

##### Reproduction Steps
1. In case:
SDL cuts off fake parameters from response (request) that SDL should use internally
and this response (request) is invalid by any reason

##### Expected Behavior
SDL must:
log the corresponding error
ignore this response (request)

##### OS & Version Information
* OS/Version: 
* SDL Core Version:
* Testing Against:

**Comment by jacobkeeler** [comment]
Not reproducible on the latest develop
