### ISSUE TITLE
(OnVehicleData) PoliciesManager must allow all requested params in case "parameters" field is omited

### ISSUE THREAD

**Issue by HSavynetska** [smartdevicelink/sdl_core#2380]
### Bug Report
(OnVehicleData) PoliciesManager must allow all requested params in case "parameters" field is omited

##### Reproduction Steps
1. In case 
SDL receives OnVehicleData notification from HMI
and this notification is allowed by Policies for this mobile app
and "parameters" field is omited at PolicyTable for this notification

##### Expected Behavior
SDL must:
transfer received notification with all parameters as is to mobile app
respond with received_resultCode_from_HMI to mobile app

##### OS & Version Information
* OS/Version: 
* SDL Core Version: 
* Testing Against:

**Comment by ValeriiMalkov** [comment]
### Not reproducible

* SDL Core Version: 43e53192045daeff8e9e2887c8b67894725240b5
* Test script from PR: https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/2005

**Comment by AStasiuk** [comment]
Closed as not reproducible.
