### ISSUE TITLE
SDL must start <DefaultTimeout>+<RPCs_internal_timeout> for all RPCs with own timer

### ISSUE THREAD

**Issue by HSavynetska** [smartdevicelink/sdl_core#2382]
### Bug Report
SDL must start <DefaultTimeout>+<RPCs_internal_timeout> for all RPCs with own timer

##### Reproduction Steps
1. In case
mobile app sends *RPC with own timeout to SDL (please see list with impacted *RPCs below)

##### Expected Behavior
SDL must:
transfer this *RPC to HMI
start + *RPCs_own_timeout for waiting the reponse from HMI
transfer received_resultCode_from_HMI to mobile app IN CASE HMi respond during + *RPCs_own_timeout timer

##### OS & Version Information
* OS/Version: 
* SDL Core Version: 
* Testing Against:

**Comment by AStasiuk** [comment]
Duplicate of https://github.com/smartdevicelink/sdl_core/issues/792
