### ISSUE TITLE
[ProtocolVersion][INI file]: .ini file - 'MaxSupportedProtocolVersion' param must be added to .ini file

### ISSUE THREAD

**Issue by HSavynetska** [smartdevicelink/sdl_core#2386]
### Bug Report
[ProtocolVersion][INI file]: .ini file - 'MaxSupportedProtocolVersion' param must be added to .ini file

##### Expected Behavior
New parameter "MaxSupportedProtocolVersion" must be added to [PROTOCOL_HANDLER] section of .ini file

##### OS & Version Information
* OS/Version: 
* SDL Core Version: 
* Testing Against:

**Comment by jacobkeeler** [comment]
This behavior already exists in master, please only post issues with existing behavior.
