### ISSUE TITLE
Compatible mobile applications

### ISSUE THREAD

**Issue by GregDescamps** [smartdevicelink/sdl_core#239]
As far as I know, this page lists up SDL compatible applications for iOS and Android:
http://owner.ford.com/how-tos/sync-technology/all/sync-applink/use-voice-commands-to-control-your-smartphone-apps.html
However, I heard that there are some limitations. For example, such app is not compatible with such data transport.
Is there centralized and up to date information about applications compatibility?

**Comment by justinjdickow** [comment]
That information is not currently available - I've added it to our internal backlog to put together a matrix of app partners with supported head units and features :D hopefully this will see a release with the SmartDeviceLink developer portal in the coming months
