### ISSUE TITLE
SDL must store OnWayPointChange internally and re-send this notification to each subscribed apps

### ISSUE THREAD

**Issue by HSavynetska** [smartdevicelink/sdl_core#2395]
### Bug Report
SDL must store OnWayPointChange internally and re-send this notification to each subscribed apps

##### Reproduction Steps
1. In case
app_1 and app_2 successfully subscribes on wayPonts-related data
and SDL stores OnWayPointChange (<wayPoints_1>) notification received from HMI
and HMI sends OnWayPointChange (<wayPoints_2>) notification to SDL
SDL must:
transfer this notification to both app_1 and app_2
rewrite <wayPoints_1> to <wayPoints_2> internally
send OnWayPointChange (<wayPoints_2>) to each application successfully subscribed to wayPoints-related data

2. In case
app_1 successfully subscribes on wayPonts-related data
and HMI sends OnWayPointChange (<wayPoints>) notification to SDL
SDL must:
transfer this notification to app_1
store OnWayPointChange (<wayPoints>) internally
send OnWayPointChange (<wayPoints>) to each application successfully subscribed to wayPoints-related data

##### Expected Behavior
SDL must store OnWayPointChange internally and re-send this notification to each subscribed apps
![image](https://user-images.githubusercontent.com/11210973/81415096-a16e6800-9150-11ea-9409-9d12c6688144.png)

##### OS & Version Information
* OS/Version: 
* SDL Core Version: 
* Testing Against:

**Comment by iCollin** [comment]
Closed via https://github.com/smartdevicelink/sdl_core/pull/2490
