### ISSUE TITLE
SDL must respond UNSUPPORTED_RESOURCE to mobile app in case SDL 4.0 feature is required to be ommited in implementation

### ISSUE THREAD

**Issue by HSavynetska** [smartdevicelink/sdl_core#2399]
### Bug Report
SDL must respond UNSUPPORTED_RESOURCE to mobile app in case SDL 4.0 feature is required to be ommited in implementation

##### Reproduction Steps
1. In case SDL 4.0 was omited in implementation 
and mobile app sends SystemRequest (QUERY_APPS) 

##### Expected Behavior
SDL must:
respond SystemRequest (UNSUPPORTED_RESOURCE, success:false) to modile application.

##### OS & Version Information
* OS/Version: 
* SDL Core Version:
* Testing Against:

**Comment by iCollin** [comment]
Closed via https://github.com/smartdevicelink/sdl_core/pull/2502
