### ISSUE TITLE
Application behaviour during usage

### ISSUE THREAD

**Issue by GregDescamps** [smartdevicelink/sdl_core#240]
What are the guidelines for the behaviour of a mobile application while it is connected with the Head-Unit? Or what is the de-facto behaviour?

Can we switch off the phone? 
Can we switch to another application?
If same application, is it still usable?

**Comment by justinjdickow** [comment]
Applications that are connected on the phone which receive the OnDriverDistraction notification should use it to display a lock screen and lock the user out based on Ford-specific requirements. In coming enhancements to the SDKs we'll have a lock screen manager which handles this logic for the developer. For your other questions, we do not dictate the user behavior but the following would happen

Power off the phone - All registered applications will disconnect
Lock the phone - Nothing
Switch applications - Nothing
Launch an application (iOS) - the application will connect and register
