### ISSUE TITLE
SDL behavior in case mobile app sends reques with at least one choiseSet without <vrCommands> parameter and at least one choiseSet with <vrCommands> at MANUAL_ONLY mode

### ISSUE THREAD

**Issue by HSavynetska** [smartdevicelink/sdl_core#2400]
### Bug Report
SDL behavior in case mobile app sends reques with at least one choiseSet without <vrCommands> parameter and at least one choiseSet with <vrCommands> at MANUAL_ONLY mode

##### Reproduction Steps
1. In case
mobile app sends PerformInteraction with
interactionMode: MANUAL_ONLY
and one or more choiseSet_created_ without _<vrCommands>
and one or more choiseSet_created_ with _<vrCommands>

##### Expected Behavior
SDL must:
send VR.PerformInteraction with all prompts (helpPrompt, timeoutPrompt, initialPrompt) to HMI
send UI.PerformInteraction with all requested choiseSets to HMI

##### OS & Version Information
* OS/Version: 
* SDL Core Version: 
* Testing Against:

**Comment by jacobkeeler** [comment]
This was addressed in #2415, but the expected behavior was defined as an INVALID_DATA response if both a set with no vrCommands and a set with vrCommands: https://github.com/smartdevicelink/sdl_core/pull/2415/files#diff-85712df3e6b0c3a8dd09355b5d4f42a5R2724
