### ISSUE TITLE
SDL behavior in case  mobile app sends request with at least one choiseSet without  <vrCommands> parameter and at least one choiseSet with  <vrCommands> at VR_ONLY or BOTH mode

### ISSUE THREAD

**Issue by HSavynetska** [smartdevicelink/sdl_core#2401]
### Bug Report
SDL behavior in case  mobile app sends request with at least one choiseSet without  <vrCommands> parameter and at least one choiseSet with  <vrCommands> at VR_ONLY or BOTH mode

##### Reproduction Steps
1. In case
mobile app sends PerformInteraction with
interactionMode: VR_ONLY or BOTH
and one or more choiseSet_created_ without _<vrCommands>
and one or more choiseSet_created_ with _<vrCommands>

##### Expected Behavior
SDL must:
respond INVALID_DATA to mobile app

##### OS & Version Information
* OS/Version: 
* SDL Core Version:
* Testing Against:

**Comment by jacobkeeler** [comment]
Closed via #2415
