### ISSUE TITLE
Build with EXTERNAL PROPRIETARY policy flag

### ISSUE THREAD

**Issue by LitvinenkoIra** [smartdevicelink/sdl_core#2403]
### Bug Report
Develop branch **does not build** with EXTERNAL PROPRIETARY policy flag

commit:  734fb7d

**Comment by LitvinenkoIra** [comment]
Develop branch does not build with EXTERNAL PROPRIETARY policy flag

commit: ddc79ce414adcd966bdab61b814ce8a422e780f8

**Comment by jacobkeeler** [comment]
Closing again with the merge of #2559
