### ISSUE TITLE
DialNumber: Update HMI API description to match Mobile API description

### ISSUE THREAD

**Issue by atiwari9** [smartdevicelink/sdl_core#2408]
### Bug Report
DialNumber: Need to update description for param `number` in HMI API so that it matches with corresponding Mobile API description as `DialNumber` should allow digits 0-9 and * # , ; +

HMI API Ref: (**Incorrect**)
https://github.com/smartdevicelink/sdl_core/blob/master/src/components/interfaces/HMI_API.xml#L4062

Mobile API Ref: (**Correct**)
https://github.com/smartdevicelink/sdl_core/blob/develop/src/components/interfaces/MOBILE_API.xml#L7353

**Comment by atiwari9** [comment]
@JackLivio  - Can you please Triage this issue, HMI API description is incorrect. Implementation is correct though.

**Comment by atiwari9** [comment]
@JackLivio  - Bumping this up in your list. Can you please Triage this issue.

**Comment by jordynmackool** [comment]
@atiwari9 Do you plan on submitting a PR fix for this issue?

**Comment by atiwari9** [comment]
@jordynmackool - https://github.com/smartdevicelink/sdl_evolution/pull/820

**Comment by theresalech** [comment]
@atiwari9 an Evolution proposal is not needed for this issue.  The Livio team will plan to submit an sdl_core PR to resolve this issue within the 6.0 release.

**Comment by jacobkeeler** [comment]
Closing with the merge of #2408
