### ISSUE TITLE
SDL does not send EndService for Audio/Video

### ISSUE THREAD

**Issue by dboltovskyi** [smartdevicelink/sdl_core#2423]
### Bug Report
SDL does not send EndService for Audio/Video when there is an event that interrupts A/V streaming

##### Reproduction Steps
1. Application is registered with PROJECTION appHMIType
2. And starts A/V streaming
3. Perform the action that interrupts A/V streaming:
- Respond from HMI to SDL's 'Navigation.StartAudioStream' request with 'REJECTED' code several times
-  'BC.OnExitApplication' (USER_EXIT)
-  'BC.OnEventChanged' (AUDIO_SOURCE)

##### Expected Behavior
SDL sends EndService for A/V service

##### Observed Behavior
SDL does not send EndService for A/V service

##### OS & Version Information
* OS/Version: Ubuntu 16.04
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/tree/develop
* Testing Against: ATF

##### Test Case, Sample Code, and / or Example App
* [MobileProjection/Phase1/013_Rejecting_StartAudioStream_during_audio_service_start](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/MobileProjection/Phase1/013_Rejecting_StartAudioStream_during_audio_service_start.lua)
* [MobileProjection/Phase1/014_Rejecting_StartStream_during_video_service_start](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/MobileProjection/Phase1/014_Rejecting_StartStream_during_video_service_start.lua)
* [MobileProjection/Phase1/015_Restore_video_streaming_from_NONE](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/MobileProjection/Phase1/015_Restore_video_streaming_from_NONE.lua)
* [MobileProjection/Phase1/016_Restore_audio_streaming_from_NONE](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/MobileProjection/Phase1/016_Restore_audio_streaming_from_NONE.lua)
* [MobileProjection/Phase2/019_SDL_stop_audio_video](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/MobileProjection/Phase2/019_SDL_stop_audio_video.lua)

##### Notes:
- Issue is introduced by https://github.com/smartdevicelink/sdl_core/pull/2164 and not reproduced before

**Comment by jacobkeeler** [comment]
Closing with the merge of #2607
