### ISSUE TITLE
SDL must processing SystemRequest for RequestType: CLIMATE with fileName:(binary file)

### ISSUE THREAD

**Issue by HSavynetska** [smartdevicelink/sdl_core#2426]
### Bug Report
SDL must processing SystemRequest for RequestType: CLIMATE with fileName:(binary file)

##### Reproduction Steps
1. Start SDL and HMI
2. Connect mobile and create mobile session
3. Register mobile app and activated
4. Mobile app send SystemRequest( RequestType: CLIMATE, fileName:(binary file)

##### Expected Behavior
SDL must processing SystemRequest for RequestType: CLIMATE, fileName:(binary file) with resultCode:"SUCCESS" on the mobile app

##### Observed Behavior
SDL respond with resultCode:"REJECTED" to mobile app

##### OS & Version Information
* OS/Version:
* SDL Core Version:

**Comment by ShobhitAd** [comment]
Unable to reproduce the issue on the latest develop 0736ea1
