### ISSUE TITLE
Fix crash in libusb callback handling

### ISSUE THREAD

**Issue by HSavynetska** [smartdevicelink/sdl_core#2429]
### Bug Report
Fix crash in libusb callback handling

Preconditions:
SDLCore and HMI are started.
Start SDL with command ./smartDeviceLinkCore | grep -e '.eart.eat' to check heartbeat only

##### Reproduction Steps
Start application with "HeartBeat" is switched on
Wait 30 minutes 

##### Expected Behavior
1.Application is registered
2. Heartbeat is sent
3. Connection is not closed by HB timeout reason.
4. No core dumps 

##### Observed Behavior
Connection is closed with core dump

##### OS & Version Information
* OS/Version: 
* SDL Core Version: 
* Testing Against:

**Comment by iCollin** [comment]
Closed via https://github.com/smartdevicelink/sdl_core/pull/2505
