### ISSUE TITLE
 Fix messages protocol version check 

### ISSUE THREAD

**Issue by HSavynetska** [smartdevicelink/sdl_core#2430]
### Bug Report
 Fix messages protocol version check 

Precondition:
1. "MaxSupportedProtocolVersion" = 2 in .ini file
2. MalformedMessageFiltering = false in .ini file
3. Max protocol version of mobile app is v2
4. "HeartBeat" is default in .ini. file (5000 ms)

##### Reproduction Steps
1. Open SPT
2. Register App with Maximum Protocol Version is 2
3. Select "Malformed Message" in App's menu
4. Set "Protocol": 03
5. Press "Send" button
6. Press "Close" button

##### Expected Behavior
 SDL should consider such message as malformed message then disconnect connection with app

##### Observed Behavior
 SDL does not consider such message as malformed message and connection with app still alive.

##### OS & Version Information
* OS/Version:
* SDL Core Version: 
* Testing Against:

**Comment by iCollin** [comment]
Closed via https://github.com/smartdevicelink/sdl_core/pull/2771
