### ISSUE TITLE
 SDL is crashed when HMI responds DialNumber(info value is not string)

### ISSUE THREAD

**Issue by HSavynetska** [smartdevicelink/sdl_core#2432]
### Bug Report
 SDL is crashed when HMI responds DialNumber(info value is not string)

### Precondition:
DialNumber rpc is allowed in policy table.
App is activated.

##### Reproduction Steps
1. MOB -> SDL:DialNumber()
2. SDL -> BC:DialNumber()
3. BC > SDL:DialNumber(SUCCESS, info = 1111)

##### Expected Behavior
SDL ->MOB:DialNumber(SUCCESS) without "info" parameter.

##### Observed Behavior
SDL is crashed.

##### OS & Version Information
* OS/Version:
* SDL Core Version:
* Testing Against:

**Comment by GetmanetsIrina** [comment]
Issue is not relevant on 
SDL: https://github.com/smartdevicelink/sdl_core/tree/6.1.0
Script: https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/2008
