### ISSUE TITLE
SDL doesn't finish its working by sending SDL_STOP message to mqueue

### ISSUE THREAD

**Issue by HSavynetska** [smartdevicelink/sdl_core#2436]
### Bug Report
SDL doesn't finish its working by sending SDL_STOP message to mqueue

### Preconditions:
1. First SDL life cycle.
2. HMI, SDL are starte

##### Reproduction Steps
1. Connect Iphone 6 via USB.
2. Make sure that apps are registered.
3. Send from console:
echo '\0021' > /dev/mqueue/AppLinkSDLProxy

##### Expected Behavior
SDL process is stopped and no dumps are observed

##### Observed Behavior
1. Apps are unregistered
2. SDL process is not stopped

    pidin | grep Smart
    1470558 1 ps/SmartDeviceLink 12r CONDVAR (0x174afdc)
    1470558 2 ps/SmartDeviceLink 12r READY
    1470558 3 ps/SmartDeviceLink 12r CONDVAR (0x1480fdc)
    1470558 5 ps/SmartDeviceLink 12r CONDVAR (0x1480ebc)
    1470558 6 ps/SmartDeviceLink 12r CONDVAR (0x14c4454)
    1470558 7 ps/SmartDeviceLink 12r CONDVAR (0x14c4574)
    1470558 8 ps/SmartDeviceLink 12r CONDVAR (0x14d25f0)
    1470558 9 ps/SmartDeviceLink 12r CONDVAR (0x14d36cc)
    1470558 10 ps/SmartDeviceLink 12r CONDVAR (0x14cb6f8)
    1470558 11 ps/SmartDeviceLink 12r CONDVAR (0x14cb764)
    1470558 12 ps/SmartDeviceLink 12r CONDVAR (0x14da254)
    1470558 13 ps/SmartDeviceLink 12r REPLY 28686
    1470558 14 ps/SmartDeviceLink 12r CONDVAR (0x14fc0c0)
    1470558 17 ps/SmartDeviceLink 12r CONDVAR (0x14c440c)
    1470558 18 ps/SmartDeviceLink 12r CONDVAR (0x14c45bc)
    1470558 19 ps/SmartDeviceLink 12r CONDVAR (0x14da54c)
    1470558 20 ps/SmartDeviceLink 12r CONDVAR (0x160cf94)
    1470558 21 ps/SmartDeviceLink 12r CONDVAR (0x160cb14)
    1470558 26 ps/SmartDeviceLink 12r RUNNING
    1470558 28 ps/SmartDeviceLink 12r CONDVAR (0x14d265c)
    1470558 29 ps/SmartDeviceLink 12r REPLY 999502
    1470558 30 ps/SmartDeviceLink 12r CONDVAR (0x15d3c7c)
    1470558 31 ps/SmartDeviceLink 12r REPLY 999502
    1470558 32 ps/SmartDeviceLink 12r REPLY 999502
    1470558 33 ps/SmartDeviceLink 12r CONDVAR (0x16b1140)
    1470558 34 ps/SmartDeviceLink 12r CONDVAR (0x174ad0c)
    1470558 35 ps/SmartDeviceLink 12r CONDVAR (0x1800d88)
    1470558 36 ps/SmartDeviceLink 12r CONDVAR (0x15f8df0)
    1470558 37 ps/SmartDeviceLink 12r REPLY 999502
    1470558 38 ps/SmartDeviceLink 12r CONDVAR (0x1800df4)
    1470558 39 ps/SmartDeviceLink 12r CONDVAR (0x14db1f0)
    1470558 40 ps/SmartDeviceLink 12r CONDVAR (0x14db25c)
    1470558 41 ps/SmartDeviceLink 12r CONDVAR (0x16c325c)
    1470558 43 ps/SmartDeviceLink 12r REPLY 999502
    1470558 44 ps/SmartDeviceLink 12r CONDVAR (0x15f8e5c)
    1470558 45 ps/SmartDeviceLink 12r CONDVAR (0x175cbc8)
    1470558 47 ps/SmartDeviceLink 12r CONDVAR (0x175cc34)
    1470558 48 ps/SmartDeviceLink 12r CONDVAR (0x165d9ac)
    1470558 49 ps/SmartDeviceLink 12r REPLY 999502
    1470558 50 ps/SmartDeviceLink 12r CONDVAR (0x16bf130)
    1470558 52 ps/SmartDeviceLink 12r CONDVAR (0x16bf19c)
    1470558 53 ps/SmartDeviceLink 12r CONDVAR (0x14c4724)
    1470558 54 ps/SmartDeviceLink 12r CONDVAR (0x162aee0)
    1470558 56 ps/SmartDeviceLink 12r CONDVAR (0x16b11ac)
    1470558 57 ps/SmartDeviceLink 12r CONDVAR (0x16a5870)
    1470558 58 ps/SmartDeviceLink 12r CONDVAR (0x16a58dc)
    1470558 59 ps/SmartDeviceLink 12r CONDVAR (0x1702184)
    1470558 60 ps/SmartDeviceLink 12r REPLY 999502
    1470558 61 ps/SmartDeviceLink 12r CONDVAR (0x15f67fc)
    1470558 62 ps/SmartDeviceLink 12r REPLY 999502
    1470558 64 ps/SmartDeviceLink 12r CONDVAR (0x16babd0)
    1470558 65 ps/SmartDeviceLink 12r CONDVAR (0x16bac3c)
    1470558 66 ps/SmartDeviceLink 12r CONDVAR (0x162af4c)
    1470558 67 ps/SmartDeviceLink 12r CONDVAR (0x15f9240)
    1470558 68 ps/SmartDeviceLink 12r CONDVAR (0x15f92ac)
    1470558 69 ps/SmartDeviceLink 12r CONDVAR (0x164c860)
    1470558 70 ps/SmartDeviceLink 12r CONDVAR (0x164c8cc)
    1470558 71 ps/SmartDeviceLink 12r CONDVAR (0x16c3844)
    1470558 72 ps/SmartDeviceLink 12r REPLY 999502
    1470558 74 ps/SmartDeviceLink 12r CONDVAR (0x1689100)
    1470558 75 ps/SmartDeviceLink 12r CONDVAR (0x168916c)
    1470558 76 ps/SmartDeviceLink 12r CONDVAR (0x1636710)
    1470558 77 ps/SmartDeviceLink 12r CONDVAR (0x163677c)
    1470558 78 ps/SmartDeviceLink 12r CONDVAR (0x1685090)
    1470558 79 ps/SmartDeviceLink 12r CONDVAR (0x14c4694)
    1470558 80 ps/SmartDeviceLink 12r CONDVAR (0x16850fc)
    1470558 81 ps/SmartDeviceLink 12r CONDVAR (0x16118e0)
    1470558 82 ps/SmartDeviceLink 12r CONDVAR (0x161194c)

### Attachments:
[APPLINK-33560.zip](https://github.com/smartdevicelink/sdl_core/files/2240264/APPLINK-33560.zip)

##### OS & Version Information
* OS/Version: 
* SDL Core Version: 
* Testing Against:

**Comment by ShobhitAd** [comment]
@HSavynetska Is this issue is still reproducible on the latest develop commit?
