### ISSUE TITLE
SDL doesn't send spaceAvailable in INVALID_DATA response message

### ISSUE THREAD

**Issue by HSavynetska** [smartdevicelink/sdl_core#2438]
### Bug Report
SDL doesn't send spaceAvailable in INVALID_DATA response message

### Preconditions:
1. SDL and HMI are running
2. Registered and Activated App

##### Reproduction Steps
1. SendRPC PutFile without any parameters

##### Expected Behavior
SDL should return: success = false, resultCode = "INVALID_DATA", spaceAvailable = xxxxxx (mandatory parameter)

##### Observed Behavior
SDL returns: success = false, resultCode = "INVALID_DATA" without spaceAvailable

### Attachments:
[APPLINK-32994.zip](https://github.com/smartdevicelink/sdl_core/files/2240281/APPLINK-32994.zip)

##### OS & Version Information
* OS/Version: 
* SDL Core Version:

**Comment by jacobkeeler** [comment]
This field is being made non-mandatory: https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0163-make-spaceavailable-field-non-mandatory.md
