### ISSUE TITLE
SDL does not set initialize state for the Interger type

### ISSUE THREAD

**Issue by HSavynetska** [smartdevicelink/sdl_core#2440]
### Bug Report
SDL does not set initialize state for the Interger type

##### Description:
The default constructor of Interger class assigns the min value
for the wrapped variable, hoowever it keeps the initialize state us
`Uninitialized`. So in case when latter user apply such operations as
`++`, `+=` the value will be changed but the state is not.

##### Expected Behavior
SDL does set initialize state for the Interger type

##### OS & Version Information
* OS/Version: 
* SDL Core Version: 
* Testing Against:

**Comment by iCollin** [comment]
Closed via https://github.com/smartdevicelink/sdl_core/pull/2548
