### ISSUE TITLE
SDL sending redundant UnregisterAppInterface notification 

### ISSUE THREAD

**Issue by HSavynetska** [smartdevicelink/sdl_core#2441]
### Bug Report
SDL sending redundant UnregisterAppInterface notification 

##### Description:
The reason for this issue is redundant notification send from
unregister_app_interface_request.cc.
SDL must send response to mobile applications request and send
notification to HMI. It should not send notification to mobile
application`s request.

##### OS & Version Information
* OS/Version: 
* SDL Core Version: 
* Testing Against:

**Comment by Ypostolov** [comment]
Verified:
SDL build: current develop branch

ATF: develop branch

Script: https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/2028

[SmartDeviceLinkCore.log.zip](https://github.com/smartdevicelink/sdl_core/files/2324017/SmartDeviceLinkCore.log.zip)


Status: Defect is not reproduced in current develop.

**Comment by AStasiuk** [comment]
Closed as not reproducible.
