### ISSUE TITLE
SDL does not check for non-manadatory parameters

### ISSUE THREAD

**Issue by HSavynetska** [smartdevicelink/sdl_core#2443]
### Bug Report
SDL does not check for non-manadatory parameters
##### Description:
The OnPutFile notification has non mandatory parameters
`fileSize` and `length`. If the mobile application has no provided
appropriate parameters SDL sends `fileSize`: null as json value to HMI.

##### OS & Version Information
* OS/Version: 
* SDL Core Version:
* Testing Against:

**Comment by jacobkeeler** [comment]
Closing with the merge of #2538
