### ISSUE TITLE
SDL doesn't resume status of subscribtion on wayPoint-related data

### ISSUE THREAD

**Issue by HSavynetska** [smartdevicelink/sdl_core#2445]
### Bug Report
SDL doesn't resume status of subscribtion on wayPoint-related data

### Preconditions:
1. Into sdl_preloaded_pt.json add additional information about SubscribeWayPoints and UnSubscribeWayPoints
2. SDL and HMI are started.
3. App registered and activated.

##### Reproduction Steps
1. Do SubscribeWayPoints for this app
2. Do Unexpected disconnect via CloseMobileSession() and receive UnSubscribeWayPoints in this way
3. Register app with the same ID once more

##### Expected Behavior
Register an application successfully and resume status of subscribtion on wayPoint-related data, also resume HMIlevel being before unexpected disconnect (it means "FULL" level) 

Note: For reproduce this defect use attach script.

##### Observed Behavior
App registered with the same ID, but SDL doesn't resume status of subscribtion on wayPoint-related data .

### Attachments:
[APPLINK-33392.zip](https://github.com/smartdevicelink/sdl_core/files/2240441/APPLINK-33392.zip)

##### OS & Version Information
* OS/Version:
* SDL Core Version: 
* Testing Against:

**Comment by dboltovskyi** [comment]
Issue is not actual due to implementation of https://github.com/smartdevicelink/sdl_core/issues/2486
