### ISSUE TITLE
Fix problem with validation of array

### ISSUE THREAD

**Issue by HSavynetska** [smartdevicelink/sdl_core#2451]
### Bug Report
Fix problem with validation of array

### Description: 
supportedDiagModes value is truncated

##### Reproduction Steps
1. Change value in smartdeviceLink.ini file: SupportedDiagModes contains 102 elements:
SupportedDiagModes = 0x01,0x02,0x03,0x04,0x05,0x06,0x07,0x08,0x09,0x11,0x12,0x13,0x14,0x15,0x16,0x17,0x18,0x19,0x21,0x22,0x23,0x24,0x25,0x26,0x27,0x28,0x29,0x31,0x32,0x33,0x34,0x35,0x36,0x37,0x38,0x39,0x41,0x42,0x43,0x44,0x45,0x46,0x47,0x48,0x49,0x51,0x52,0x53,0x54,0x55,0x56,0x57,0x58,0x59,0x61,0x62,0x63,0x64,0x65,0x66,0x67,0x68,0x69,0x71,0x72,0x73,0x74,0x75,0x76,0x77,0x78,0x79,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99,0x10,0x20,0x30,0x40,0x50,0x60,0x70,0x80,0x90,0x9A,0x9B,0x9C

2. Start SDL

##### Expected Behavior
SupportedDiagModes can contain maximum 100 elements.
Refer to SDLAQ-CRS-2701.

##### Observed Behavior
SupportedDiagModes can contain 98 elements.
'0x01,0x02,0x03,0x04,0x05,0x06,0x07,0x08,0x09,0x11,0x12,0x13,0x14,0x15,0x16,0x17,0x18,0x19,0x21,0x22,0x23,0x24,0x25,0x26,0x27,0x28,0x29,0x31,0x32,0x33,0x34,0x35,0x36,0x37,0x38,0x39,0x41,0x42,0x43,0x44,0x45,0x46,0x47,0x48,0x49,0x51,0x52,0x53,0x54,0x55,0x56,0x57,0x58,0x59,0x61,0x62,0x63,0x64,0x65,0x66,0x67,0x68,0x69,0x71,0x72,0x73,0x74,0x75,0x76,0x77,0x78,0x79,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99,0x10,0x20,0x30,0x40,0x50,0x60,0x70,0x80,'

Note:
If user registers application, RegisterAppInterface response contains supportedDiagModes with only 98 elements.
### Attachments: 
[APPLINK-10910.zip](https://github.com/smartdevicelink/sdl_core/files/2240639/APPLINK-10910.zip)

##### OS & Version Information
* OS/Version: 
* SDL Core Version: 
* Testing Against:

**Comment by jacobkeeler** [comment]
Closing with the merge of #2669
