### ISSUE TITLE
SDL sends twice SDL.OnStatusUpdate(UPDATE_NEEDED) when has wrong value for optional parameter

### ISSUE THREAD

**Issue by HSavynetska** [smartdevicelink/sdl_core#2453]
### Bug Report
SDL sends twice SDL.OnStatusUpdate(UPDATE_NEEDED) when has wrong value for optional parameter

#### Preconditions:
1. SDL is built with External Proprietary flag.
2. HMI and SDL are running.
3. New application is registered and activated. Device is consented.
=> PTU is triggered.

##### Reproduction Steps
1. Try to perform successful PTU with file files/jsons/Policies/PTU_ValidationRules/PTU_invalid_optional.json
parameter "certificate" has integer value: 123456, correct value is string.
parameter messages["AppPermissionsRevoked"].languages["de-de"].tts: has integer value, correct is string.

##### Expected Behavior
SDL should invalidate this received PolicyTableUpdated - OK
SDL.OnStatusUpdate(UPDATE_NEEDED)

##### Observed Behavior
SDL invalidates PTU - correct
SDL sends twice SDL.OnStatusUpdate(UPDATE_NEEDED)

##### Attachments:
[APPLINK-30864.zip](https://github.com/smartdevicelink/sdl_core/files/2240676/APPLINK-30864.zip)

##### OS & Version Information
* OS/Version: 
* SDL Core Version: 
* Testing Against:

**Comment by ychernysheva** [comment]
This issue is not reproduced on RC_6.1, corresponding ATF script was already merged.
