### ISSUE TITLE
SDL does not clear app_info.dat after MASTER_RESET

### ISSUE THREAD

**Issue by HSavynetska** [smartdevicelink/sdl_core#2454]
### Bug Report
SDL does not clear app_info.dat after MASTER_RESET

##### Reproduction Steps
1. HMI and SDL are started.
2.  Perform MASTER_RESET

##### Expected Behavior
All SDL data are cleaned and reset.

##### Observed Behavior
app_info.dat is not cleaned.

#### Attachments:
[APPLINK-11361(1).zip](https://github.com/smartdevicelink/sdl_core/files/2240685/APPLINK-11361.1.zip)

##### OS & Version Information
* OS/Version:
* SDL Core Version: 
* Testing Against:

**Comment by GetmanetsIrina** [comment]
Defect is reproduced on develop branch  28235f8

**Comment by GetmanetsIrina** [comment]
Issue is the duplicate of #2448
