### ISSUE TITLE
Need substitute SDL's shared pointer with the one from c++11 standard and std::auto_ptr with std::unique_ptr

### ISSUE THREAD

**Issue by HSavynetska** [smartdevicelink/sdl_core#2455]
### Bug Report
Need substitute SDL's shared pointer with the one from c++11 standard and std::auto_ptr with std::unique_ptr

##### Description
SDL has own implementation of shared pointer. Since this one is not quite efficient and in some cases danger to use, SDL has to use shared pointer from standard library.

Required activities:
1. Substitute utils::SharedPtr with std::shared_ptr
2. Use std::make_shared instead of SDL's analogue as well as explicit new operator
3. Substitute std::auto_ptr with std::unique_ptr
3. Check if it compiles fine for QNX 6.5

##### OS & Version Information
* OS/Version: 
* SDL Core Version: 
* Testing Against:

**Comment by jacobkeeler** [comment]
Already done in #2391
