### ISSUE TITLE
 Need change OnButtonEventNotification logic for OK button 

### ISSUE THREAD

**Issue by HSavynetska** [smartdevicelink/sdl_core#2458]
###Bug Report
 Need change OnButtonEventNotification logic for OK button 

#### Description:

If app_id parameter is present - send OnButtonEventNotification
for OK button to specified application in LIMITED and FULL hmi level

If app_id parameter is not present - send OnButtonEventNotification
for OK button to to all applications in FULL hmi level

#### OS & Version Information
OS/Version:
SDL Core Version:
Testing Against:

**Comment by LitvinenkoIra** [comment]
already fixed in O-S SDL:
https://github.com/smartdevicelink/sdl_core/commit/c201c11a35d360c0b96f36b103a2590bfaeb6026

**Comment by LitvinenkoIra** [comment]
Closed as not reproducible.
