### ISSUE TITLE
HMILevel is not resumed to LIMITED for non-media applications

### ISSUE THREAD

**Issue by HSavynetska** [smartdevicelink/sdl_core#2459]
### Bug Report
HMILevel is not resumed to LIMITED for non-media applications

#### Preconditions:
1. Values configured in .ini file:
AppSavePersistentDataTimeout =10000;
ResumptionDelayBeforeIgn = 30;
ResumptionDelayAfterIgn = 30;
ApplicationResumingTimeout = 5000
2. Core and HMI are started.
3. Non-media application(COMMUNIATION) is registered and activated. -> HMI level = FULL
4. Go to menu Apps. HMI level of application becomes LIMITED
5. Stop WiFi connection.

##### Reproduction Steps
1. Press "Go To CD" -> HMI sends OnEventChanged(AUDIO_SOURCE, isActive: true) notification to SDL.
2. Activate WiFi connection.
3. Wait ApplicationResumingTimeout to expire.

##### Expected Behavior
SDL must resume HMILevel for non-media app. 

##### Observed Behavior
HMI level becomes BACKGROUND, audioStreamingState : NOT_AUDIBLE

##### OS & Version Information
* OS/Version: 
* SDL Core Version: 
* Testing Against:

**Comment by AStasiuk** [comment]
Defect is not actual according to current requirement item 5.1 in https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0150-video-streaming-state.md
