### ISSUE TITLE
Need updated logic for checking user consent prompt after PTU

### ISSUE THREAD

**Issue by HSavynetska** [smartdevicelink/sdl_core#2462]
### Bug Report
Need updated logic for checking user consent prompt after PTU

##### Description:
SDL does not check is new added group
from PTU requires user consent prompt if it was not present in
local PT. And SDL does not send onAppPermissionChange
notification with appPermissionsConsentNeeded set to true for affected
application. As a result permissions popup is shown only after the
next application activation.

##### OS & Version Information
* OS/Version: 
* SDL Core Version: 
* Testing Against:

**Comment by VjKlepikov** [comment]
Status: Defect is not reproducing in current develop

Environment:
Test script: https://github.com/smartdevicelink/sdl_core/issues/2462
SDL build: https://github.com/smartdevicelink/sdl_core/tree/develop ( 891497b )
ATF: develop branch
