### ISSUE TITLE
SDL policy table does not load actual value of the `unpaired` flag from devices table

### ISSUE THREAD

**Issue by HSavynetska** [smartdevicelink/sdl_core#2463]
### Bug Report
SDL policy table does not load
actual value of the `unpaired` flag from devices table

##### Description:
SDL policy table does not load
actual value of the `unpaired` flag from devices table
so this value just lost after database backup

##### OS & Version Information
* OS/Version: Ubuntu 16.04
* SDL Core Version: [develop](https://github.com/smartdevicelink/sdl_core/commit/aadea479ba2ac48bee55699265559c14348b2274)
* Testing Against: SPT and BT transport

**Comment by jacobkeeler** [comment]
Issue is not reproducible in the latest version of master
