### ISSUE TITLE
SDL does not send OnSDLClose notification by switching off with reason IGNITION_OFF

### ISSUE THREAD

**Issue by HSavynetska** [smartdevicelink/sdl_core#2464]
# Description
SDL must send OnSDLClose by IGNITION_OFF

## Preconditions
1. SDL and HMI are started.
2. App is registered.

## Steps to reproduce
1. Perform IGNITION_OFF

## Actual result
SDL does not send OnSDLClose notification to HMI by switching off with reason IGNITION_OFF. 

## Expected result
1. SDL receives OnExitAllApplications(SUSPEND) from HMI and sends OnSDLPersistenceComplete to HMI.
2. SDL received OnExitAllApplications(IGNITION_OFF) from HMI, sends to mobile application OnAppInterfaceUnregistered(IGNITION_OFF) and OnAppUnregistered(unexpectedDisconnect = false)
3. SDL sends to HMI OnSDLClose notification.

# Attachments
[Script_IGN_OFF_OnSDLClose.zip](https://github.com/CustomSDL/Sync3.2v2/files/1698610/Script_IGN_OFF_OnSDLClose.zip)
[SmartDeviceLinkCore_log.zip](https://github.com/CustomSDL/Sync3.2v2/files/1655129/SmartDeviceLinkCore_log.zip)
[ATF_TestingReports.zip](https://github.com/CustomSDL/Sync3.2v2/files/1655130/ATF_TestingReports.zip)
**Note:** Extract Script_IGN_OFF_OnSDLClose.zip in head ATF folder.

# Expected delivery
- [ ] Source code updates
- [ ] Code comments
- [x] **UTs add/update _(not required)_**
- [ ] ATF tests add/update
- [x] **Manual tests _(not required)_**
- [x] **Add/update CI plans/jobs _(not required)_**
- [x] **SDD updates _(not required)_**
- [x] **Guidelines update ([sdl_core_guides](https://github.com/smartdevicelink/sdl_core_guides)) _(not required)_**
- [x] **Guidelines update ([sdl_hmi_integration_guidelines](https://github.com/smartdevicelink/sdl_hmi_integration_guidelines)) _(not required)_**

**Comment by unni07** [comment]
Confirmed with OpenSDL team. This will not make it to 5.0 release so IVI-Luxoft team will have to take the ownership and follow the CCB process

**Comment by GetmanetsIrina** [comment]
_Environment:_
Script: https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Defects/5_0/2464_SDL_does_not_send_OnSDLClose_notification_by_switching_off_with_reason_IGNITION_OFF.lua
SDL build: https://github.com/smartdevicelink/sdl_core/commit/4c7c756a3ed0be95fd90097bea64ac97679bd91c
ATF: [develop branch](https://github.com/smartdevicelink/sdl_atf/commit/b5dfe4f0cf99ab5ddbdc1b100cf16d0d8ef91b22)

**Status: Defect is not reproduced on current develop.**
