### ISSUE TITLE
Core & HMI AddCommand Desynchronization 

### ISSUE THREAD

**Issue by Jack-Byrne** [smartdevicelink/sdl_core#2468]
### Bug Report
When a large number of addCommands are sent by the mobile, it can take core and the hmi a long time to process all of the messages. At a certain point the default 10 second RPC timeout will occur before a message can be processed and core will respond to the mobile with result::GENERIC_ERROR. When this happens an AddCommand could have been sent to the HMI and the HMI doesn't respond with success before the timeout occurs. Core assumes that HMI doesn't have the add command stored and does not send a deleteCommand to the HMI. HMI assumes that core received its addCommand::SUCCCESS response and the states between the HMI and Core are now desynchronized. 

##### Reproduction Steps
1. Use Develop Core and Develop Generic HMI
2. Connect App that can send 2000+ addCommands.

##### Reproduction Steps 2
1. Use Develop Core and Develop Generic HMI
2. Modify Generic HMI to not respond to any addCommands sent by Core
3. Connect App and send one addCommand
4. Wait 10 seconds for timeout. 

##### Expected Behavior
AddCommands sent to the HMI that don't respond to core by 10 second timeout should receive a deleteCommand from Core. 
##### Observed Behavior
Mobile receives addCommand was unsuccessful but "bad" addCommands still appear in the HMI.

##### OS & Version Information
* OS/Version: Android, Ubuntu 16, Manticore
* SDL Core Version: Develop

**Comment by jacobkeeler** [comment]
Closed via #3940
