### ISSUE TITLE
develop build breaks with ENABLE_HMI_PTU_DECRYPTION=OFF

### ISSUE THREAD

**Issue by conlain-k** [smartdevicelink/sdl_core#2471]
### Bug Report
Since the `std::shared_ptr` merge, there are a couple unsafe raw pointer assignments in `src/components/policy/policy_regular/src/policy_manager_impl.cc` that break the build. Converting these `return new` into `return std::make_shared<>...` should fix it.

##### Reproduction Steps
1. Build core with ENABLE_HMI_PTU_DECRYPTION set to OFF

##### Expected Behavior
core builds successfully

##### Observed Behavior
build crashes since a shared pointer has no assignment operator for a raw pointer

##### OS & Version Information
* OS/Version: ubuntu 18.04
* SDL Core Version: develop

**Comment by jacobkeeler** [comment]
Closing with the merge of #2473
