### ISSUE TITLE
develop build breaks with EXTENDED_POLICY=EXTERNAL_PROPRIETARY

### ISSUE THREAD

**Issue by conlain-k** [smartdevicelink/sdl_core#2472]
### Bug Report
Since the boost lock merge, there is no `Lock(bool)` constructor. The EXTERNAL_PROPRIETARY cache_manager still has an instance of one such constructor that I missed, this should be converted to a `RecursiveLock`

##### Reproduction Steps
1. build core with EXTENDED_POLICY=EXTERNAL_PROPRIETARY
2. watch as it fails due to no appropriate constructor

##### Expected Behavior
core builds successfully with external_proprietary

##### Observed Behavior
core fails with an error message like that below

##### OS & Version Information
* OS/Version: Ubuntu 18.04
* SDL Core Version: develop
* Testing Against: just gcc

##### Test Case, Sample Code, and / or Example App
```
/home/conlain/programs/sdl_core_develop/src/components/policy/policy_external/src/cache_manager.cc:257:23: error: no matching function for call to ‘sync_primitives::Lock::Lock(bool)’
     , cache_lock_(true) {
```

**Comment by jacobkeeler** [comment]
Closing with the merge of #2474
