### ISSUE TITLE
SDL should send to HMI all params for RPC "SubMenuICon"

### ISSUE THREAD

**Issue by HSavynetska** [smartdevicelink/sdl_core#2475]
### Bug Report
Parameter "menuIcon" is not transferred by SDL to HMI

##### Reproduction Steps
1. SDL is started
2. Mobile app sends AddSubMenu with  "menuIcon" and with another related to request valid params

##### Expected Behavior
SDL must: transfer AddSubMenu request with all params  to HMI 

##### Observed Behavior
SDL transfers AddSubMenu request (other params) to HMI ( without "menuIcon")

##### OS & Version Information
* OS/Version: 
* SDL Core Version: 
* Testing Against:

**Comment by jacobkeeler** [comment]
Looks like this was included in https://github.com/smartdevicelink/sdl_core/pull/2250, but this also introduced #2744
