### ISSUE TITLE
Many DD_ OFF notifications are received

### ISSUE THREAD

**Issue by HSavynetska** [smartdevicelink/sdl_core#2480]
### Bug Report
Many DD_ OFF notifications are received

#### Pre-conditions:
Vehicle Ignition On and Running

##### Reproduction Steps
Perform Master Reset
Connect iPhone via USB
Register SyncProxyTester on SYNC.(The app is in HMI_NONE)
Verify the DD notifications on phone console.

##### Expected Behavior
Only 1 DD_OFF notification is received

##### Observed Behavior
Many continuous DD_OFF notifications are received

##### OS & Version Information
* OS/Version: 
* SDL Core Version: 
* Testing Against:

**Comment by GetmanetsIrina** [comment]
Defect is not reproduced on 28235f8.

Script for reproducing: https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Defects/5_0/2480_Vefiry_that_SDL_sends_OnDD_notification_once_upon_registration.lua
