### ISSUE TITLE
[SDL 0190] Handle response from HMI during resumption data

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_core#2486]
Proposal: [Handle response from HMI during resumption data](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0190-resumption-data-error-handling.md)

> The aim of this feature is to handle HMI error responses while restoring the data during resumption process.

Review: https://github.com/smartdevicelink/sdl_evolution/issues/562

**Comment by iCollin** [comment]
Closed via #3475
