### ISSUE TITLE
SDL doesn't send SDL.OnStatusUpdate(UPDATE_NEEDED) in case of failed retry strategy during previous IGN_ON

### ISSUE THREAD

**Issue by dboltovskyi** [smartdevicelink/sdl_core#2489]
### Bug Report
SDL doesn't send SDL.OnStatusUpdate(UPDATE_NEEDED) in case of failed retry strategy during previous IGN_ON

##### Reproduction Steps
1. Start SDL and HMI
2. Connect mobile device
3. Register new application → Policy Table Update sequence is triggered:
‘SDL.OnStatusUpdate (UPDATE_NEEDED)’ notification is sent to HMI
4. Perform Ignition Off / On
5. Start SDL and HMI
6. Connect mobile device
7. Register the same application

##### Expected Behavior
Policy Table Update sequence is triggered: ‘SDL.OnStatusUpdate (UPDATE_NEEDED)’ notification is sent to HMI

##### Observed Behavior
‘SDL.OnStatusUpdate (UPDATE_NEEDED)’ notification isn’t sent

##### OS & Version Information
* OS/Version: Ubuntu 16.04
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/tree/develop
* Testing Against: ATF

##### Test Case, Sample Code, and / or Example App
* HTTP:
  - [Defects/4_5/1206_REQUEST_PTU_Trigger_PTU_failed_previous_IGN_ON](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Defects/4_5/1206_REQUEST_PTU_Trigger_PTU_failed_previous_IGN_ON.lua)
  - [Policies/build_options/050_ATF_Request_PTU_Trigger_PTU_failed_previous_IGN_ON_HTTP](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Policies/build_options/050_ATF_Request_PTU_Trigger_PTU_failed_previous_IGN_ON_HTTP.lua)
  - [Policies/build_options/098_ATF_PTU_Unsuccessful_Even_After_Retry_Strategy_HTTP](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Policies/build_options/098_ATF_PTU_Unsuccessful_Even_After_Retry_Strategy_HTTP.lua)
* PROPRIETARY:
  - [Policies/build_options/107_ATF_PTU_in_case_of_failed_retry_strategy_during_previous_IGN_ON_PROPRIETARY](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Policies/build_options/107_ATF_PTU_in_case_of_failed_retry_strategy_during_previous_IGN_ON_PROPRIETARY.lua)
* EXTERNAL_PROPRIETARY:
  - [Policies/Policy_Table_Update/122_ATF_PTU_NotSuccessful_AppID_ListedPT_NewIgnCycle](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Policies/Policy_Table_Update/122_ATF_PTU_NotSuccessful_AppID_ListedPT_NewIgnCycle.lua)

**Comment by jacobkeeler** [comment]
Closing with the merge of #2494
