### ISSUE TITLE
SDL doesn't close mobile session in case of heartbeat timeout and protocol version greater than 3

### ISSUE THREAD

**Issue by dboltovskyi** [smartdevicelink/sdl_core#2491]
### Bug Report
SDL doesn't close mobile session in case of heartbeat timeout and protocol version grater than 3

##### Reproduction Steps
1. Make sure default SDL protocol version is grater than 3 (e.g. 4 or 5) 
2. Start SDL and HMI
3. Connect mobile device using WiFi and register application
4.  App -> SDL: Heartbeat
5. SDL -> App: Heartbeat ACK
6. Wait 2x heartbeat timeout (2x7=14 sec)

##### Expected Behavior
SDL sends `BC.OnAppUnregistered` to HMI and close session (as for v3)

##### Observed Behavior
SDL doesn't close session, and doesn't send `BC.OnAppUnregistered` to HMI

##### OS & Version Information
* OS/Version: Ubuntu 16.04
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/tree/develop
* Testing Against: ATF

##### Test Case, Sample Code, and / or Example App
[Paste a link to a PR, gist, or other code that exemplifies this behavior]

**Comment by dboltovskyi** [comment]
Please notice according to https://github.com/smartdevicelink/sdl_core/issues/1893 SDL has to close only session (not connection)

**Comment by jacobkeeler** [comment]
Heartbeat is a feature only available to protocol version 3 apps, as it was deprecated in protocol version 4: https://github.com/smartdevicelink/protocol_spec#45-heartbeat
