### ISSUE TITLE
SDL process SetInteriorVD with SEAT module with resultCode UNSUPPORTED_RESOURCE

### ISSUE THREAD

**Issue by GetmanetsIrina** [smartdevicelink/sdl_core#2520]
### Bug Report
SDL process SetInteriorVD with SEAT module with resultCode UNSUPPORTED_RESOURCE

##### Reproduction Steps
1. REMOTE_CONTROL app is registered and activated
2. mobile app requests SetInteriorVD("SEAT")

##### Expected Behavior
SDL sends request to HMI and process response from it.

##### Observed Behavior
SDL does not sends SetInteriorVD request to HMI adn responds with UNSUPPORTED_RESOURCE to mobile app

##### OS & Version Information
* OS/Version:Ubuntu16.04
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/commit/9bdf1c823482e9bc8db0756b33826551ffd7a640
Script: https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/RC/SEAT/SetInteriorVehicleData/001_Success_flow.lua

##### Test Case, Sample Code, and / or Example App
[Paste a link to a PR, gist, or other code that exemplifies this behavior]

**Comment by yang1070** [comment]
why this happens? previously it was working for SEAT

**Comment by jacobkeeler** [comment]
Closing with the merge of #2521
