### ISSUE TITLE
Link is broken of jenkins ci status

### ISSUE THREAD

**Issue by vkushnirenko-luxoft** [smartdevicelink/sdl_core#2524]
### Bug Report
README of develop branch consists the broken link on build job of develop branch with unit tests and test coverage report. 

### PR
Fix Jenkins CI status #2525

##### Reproduction Steps
  1. Open https://github.com/smartdevicelink/sdl_core/tree/develop README.md 

##### Expected Behavior
[![Build Status](http://opensdl-jenkins.luxoft.com:8080/view/develop/job/develop_nightly_coverage/badge/icon)](http://opensdl-jenkins.luxoft.com:8080/view/develop/job/develop_nightly_coverage/)

##### Observed Behavior
http://opensdl-jenkins.luxoft.com:8080/view/All/job/OpenSDL_Nightly/

**Comment by LuxoftAKutsan** [comment]
@vkushnirenko-luxoft  please always link PRs to the issues. Looks like this one already fixed

**Comment by vkushnirenko-luxoft** [comment]
@LuxoftAKutsan I added link to PR into description

**Comment by LuxoftAKutsan** [comment]
@vkushnirenko-luxoft fixed the link, Please take a note.
