### ISSUE TITLE
SDL does not process required language struct in jsons for SDL4.0 feature

### ISSUE THREAD

**Issue by GetmanetsIrina** [smartdevicelink/sdl_core#2556]
### Bug Report
SDL does not process required language struct in jsons for SDL4.0 feature

##### Reproduction Steps
1. App is registered via 4 protocol
2. Mobile app sends correct json in OnSystemRequest(QUERY_APPS) to SDL.
Language structure is
```
                "languages": {
                    "default": {
                        "ttsName": "Rock music App tts name default",
                        "vrSynonyms": [
                            "Rock music App 1 default",
                            "Rock music App 2 default"
                        ]
                    },
                    "EN-US": {
                        "ttsName": "Rock music App tts name EN"
                    }
                ]
```

##### Expected Behavior
SDL processes json as valid (according to comment in https://github.com/smartdevicelink/sdl_core/issues/994), returns SystemRequest(SUCCESS) response on mobile app and sends UpdateAppList to HMI with update from json file.

##### Observed Behavior
SDL processes json as not valid and return GENERIC_ERROR to SystemRequest reqeust and does not update app list by UpdateAppList.

##### OS & Version Information
* OS/Version: Ubuntu 16.04
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/commit/9e677078ba660d1602beb24d678a5c816e7558b8

**Comment by dboltovskyi** [comment]
Looks like currently Core assumes array in `languages` parameter.
In: https://github.com/smartdevicelink/sdl_core/blob/f43fbe015e5c7f84d1bcc1c154aeec6afad217d9/src/components/application_manager/src/application_manager_impl.cc#L2776
And in: https://github.com/smartdevicelink/sdl_core/blob/f43fbe015e5c7f84d1bcc1c154aeec6afad217d9/src/components/application_manager/src/application_manager_impl.cc#L2785

So this issue can be marked as not actual, though initial https://github.com/smartdevicelink/sdl_core/issues/994 is still actual.
