### ISSUE TITLE
SDL processes request successfully with not allowed parameters after changed permissions for parameters

### ISSUE THREAD

**Issue by GetmanetsIrina** [smartdevicelink/sdl_core#2581]
### Bug Report
SDL processes request successfully with not allowed parameters after changed permissions for parameters

##### Reproduction Steps
1. App1 is registered
2. App1 has permissions in Group_1 for `gps`
3. App1 requests `GetVehicleData(gps)` and received response `SUCCESS`
4. App2 is registered and triggers PTU
5. Group_1 is updated without `gps` parameter
6. App1 requests `GetVehicleData(gps)`

##### Expected Behavior
SDL responds with `DISALLOWED` resultCode

##### Observed Behavior
SDL successfully process request and resends `GetVehicleData` request to HMI

##### OS & Version Information
* OS/Version: Ubuntu 16.04
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/commit/08e2e6ed06bbcd68c4e84f06e2c2f3b414cb8215
* ATF: https://github.com/smartdevicelink/sdl_atf/commit/b5dfe4f0cf99ab5ddbdc1b100cf16d0d8ef91b22
* Script: https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/API/VehicleData/GetVehicleData/002_RPC_parameter_DISALLOWED_by_policies_flow.lua
https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/API/VehicleData/UnsubscribeVehicleData/004_RPC_parameter_disallowed_by_policies_Result_DISALLOWED_flow.lua
* Logs: 
[TestingReports.zip](https://github.com/smartdevicelink/sdl_core/files/2360841/TestingReports.zip)

**Comment by E-SAITO-TMC** [comment]
@theresalech -san, We were able to reproduce this issue with Core 6.0.1. This is a medium priority issue for Toyota. Could you please include this in the Core 6.2 release planning?

**Comment by theresalech** [comment]
@GetmanetsIrina can you please advise if this issue is reproducible in Core 6.1.1?
