### ISSUE TITLE
CCB: Possible undefined behavior in case thread stopped before it was actually started.

### ISSUE THREAD

**Issue by LuxoftAKutsan** [smartdevicelink/sdl_core#2599]
Current thread implementation contains various possibilities of race conditions because the state of thread store in multiple boolean variables. 
Thread state should be refactored to enum to avoid race conditions.

**Comment by E-SAITO-TMC** [comment]
@theresalech -san, This is a high priority issue for Toyota. Could you please include this in the Core 6.2 release planning?

**Comment by theresalech** [comment]
@LuxoftAKutsan can you please advise if you are able to reproduce this issue in the latest Core release?  If so, can you provide more details on reproduction steps?

**Comment by LuxoftAKutsan** [comment]
@theresalech the issue was not reproducible on open SDL.
SYNC-sdl made the changes to improve thread management.
There is no special test case. 
Code will be ported to open sdl and full regression will be checked.

**Comment by theresalech** [comment]
Hi @LuxoftAKutsan, thank you!  Please let us know once the PR is ready for Livio review.

**Comment by dboltovskyi** [comment]
@theresalech Please notice we're not planning to create the fix in scope of 6.2, though will try to do as much as possible

**Comment by theresalech** [comment]
@E-SAITO-TMC please see notes above from Luxoft team, as they have found this issue to **not** be reproducible on open SDL.  If Toyota is able to reproduce the issue and submit a PR to resolve, please let us know.

**Comment by SNiukalov** [comment]
@theresalech 
Possible fix for this issue is ready.
Thank you!
