### ISSUE TITLE
Posible race conditions in MessageLoopThread

### ISSUE THREAD

**Issue by LuxoftAKutsan** [smartdevicelink/sdl_core#2600]
In `MessageLoopThread<Q>::WaitDumpQueue()  ` exist possibility of race condition of work with message_queue_. 
In MessageLoopThread should be added additional synchronization primitives

**Comment by jordynmackool** [comment]
@LuxoftAKutsan is this issue still present?

**Comment by AKalinich-Luxoft** [comment]
@jordynmackool I think this issue is not actual for the current release as `MessageQueue<T, Q>` class has its internal `queue_lock_` to make everything synchronized inside.
Additionally, some stabilization jobs were done in #3471 so there is nothing to fix at the moment.

**Comment by jordynmackool** [comment]
@AKalinich-Luxoft thanks for the quick response, can we close this issue based on your comment?

**Comment by AKalinich-Luxoft** [comment]
@jordynmackool yes, this can be closed

**Comment by jordynmackool** [comment]
Closing based on this [comment](https://github.com/smartdevicelink/sdl_core/issues/2600#issuecomment-920327308).
