### ISSUE TITLE
Make Size() function thread safe to avoid core dump 

### ISSUE THREAD

**Issue by HSavynetska** [smartdevicelink/sdl_core#2603]
### Bug Report
Make Size() function thread safe to avoid core dump 

##### Expected Behavior
The Size() function calls the CheckSetSizes() function which compares the sizes of the two sets and checks this value in DCHECK. So must be sure that the function Size() will not be called at the same time when there is addition or removal of requests from sets

##### OS & Version Information
* OS/Version: 
* SDL Core Version: 
* Testing Against:

**Comment by HSavynetska** [comment]
Fixed by #1569

**Comment by t-yoshii** [comment]
Hi, I also hit this issue. 
Are there any reasons or risks that this pull request (#1569) has not yet been merged?

**Comment by LitvinenkoIra** [comment]
@jacobkeeler please take a look at https://github.com/smartdevicelink/sdl_core/pull/1569 one more time

**Comment by theresalech** [comment]
@HSavynetska please provide Observed Behavior and OS & Version Information for this issue

**Comment by LuxoftAKutsan** [comment]
@HSavynetska  Please make proper description . Not clear Size function of what class. 
If it is not just potential but fix some wrong behavior observer, please add it to the description

**Comment by LitvinenkoIra** [comment]
closed as https://github.com/smartdevicelink/sdl_core/pull/1569 merged
