### ISSUE TITLE
Replaces assert macro with logic in case of failed handshake

### ISSUE THREAD

**Issue by HSavynetska** [smartdevicelink/sdl_core#2604]
### Bug Report
Replaces assert macro with logic in case of failed handshake

##### Expected Behavior
Establishing of secure connection requires checking of application name and
application id which can be assigned only to already registered application.
Due to wrong mobile behavior (it starts handshake before RAI response received)
SDL triggers assertion on missing application. So it is replaced with logic
and in case application is not registered yet handshake will fail and no
secure connection will be established. Mobile can try to establish that
connection after application is registered.

##### OS & Version Information
* OS/Version:
* SDL Core Version: 
* Testing Against:

**Comment by HSavynetska** [comment]
Fixed by #1571

**Comment by ychernysheva** [comment]
Issue has been already fixed in #2921 - similar changes as in CCB were provided
