### ISSUE TITLE
when SDL receive OnInteriorVehicleData, it shall update (not replace) the cached data

### ISSUE THREAD

**Issue by yang1070** [smartdevicelink/sdl_core#2643]
### Bug Report
when SDL receives OnInteriorVehicleData regarding LIGHT module, it shall update (not replace) the cached data. 
SDL shall replace cached data when receives a response of GetInteriorVehicleData.

##### Reproduction Steps
1. build sdl core release/5.0.0 and clone sdl hmi develop branch
2. run sdl core and sdl hmi
3. register a remote control app connect to sdl
4. activate the app from hmi
5. from the app, send GetInteriorVechicleData with moduleType=LIGHT, it get status of all available lights
6. on hmi change the status of one light
7. from the app, send GetInteriorVechicleData with moduleType=LIGHT again

##### Expected Behavior
App shall get the status of all available lights
SDL shall send the status of all available lights in the response

##### Observed Behavior
App only get one light in the response.
SDL only include the status of one recent changed light in the response

##### OS & Version Information
* OS/Version: Ubuntu 16.04 
* SDL Core Version:  5.0 release candidate (release 5.0.0 branch)
* SDL HMI Version: current develop branch
* Testing Against: remote control of Light

**Comment by jacobkeeler** [comment]
Closing with the merge of #2667

**Comment by yang1070** [comment]
@jacobkeeler 
I can produce it on branch release/5.0.0 with commit  up to c9697970a6ad6300936fe893efe7f3acae92a7c0

**Comment by yang1070** [comment]
@JackLivio I have update my core to the latest commit, can still reproduce this issue
