### ISSUE TITLE
SDL process RC requests with resultCode DISALLOWED after IGN_OFF and IGN_ON

### ISSUE THREAD

**Issue by GetmanetsIrina** [smartdevicelink/sdl_core#2670]
[Delete any non-applicable sections, but we may ask for more information.]

### Bug Report
SDL process GetInteriorVehicleData with resultCode DISALLOWED after IGN_OFF and IGN_ON

##### Reproduction Steps
1. Define module type module_1 and in default section in preloaded_pt.json
2. Update groups in default with "RemoteControl" group
3. Register RC app
4. App requests successful GetInteriorVD with module_1
5. Perform IGN_OFF
6. Perform IGN_ON
7. Register same RC app
8. Request GetInteriorVD with allowed module_1

##### Expected Behavior
SDL process  GetInteriorVD with allowed module_1 successful and resend request to HMI

##### Observed Behavior
SDL responds with DISALLOWED resultCode to GetInteriorVD

##### OS & Version Information
* OS/Version: Ubuntu 16.04
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/commit/8da2a76d7dbde7845c1116034f8a60490f4fad0c
* HMI version: https://github.com/smartdevicelink/sdl_hmi/commit/51a4ace4be6bab9613de87d3831522ad443acd68

SDL logs: 
[logs.tar.gz](https://github.com/smartdevicelink/sdl_core/files/2469848/logs.tar.gz)
Script for reproducing: 
[GetInteriorVD_after_ignition_off.lua.tar.gz](https://github.com/smartdevicelink/sdl_core/files/2470266/GetInteriorVD_after_ignition_off.lua.tar.gz)

ATF: https://github.com/smartdevicelink/sdl_atf/commit/c7022ed1aa9cec3a3ae5ceff86cc7690a4df7c14
Scripts: https://github.com/smartdevicelink/sdl_atf_test_scripts/commit/48d2a16eb73133cae7079a8457f3becb624ca23f

**Comment by GetmanetsIrina** [comment]
@JackLivio @theresalech @lauratonwe 
Issue reproduced, please triage.

**Comment by LuxoftAKutsan** [comment]
Reproduced after merging https://github.com/smartdevicelink/sdl_core/pull/2609

**Comment by jordynmackool** [comment]
After investigation, this appears to be an issue present in `master` making it not specific to the `release candidate 5.0.0`. It was determined that this bug should only affect the policies of app with default policies where default includes RC permissions making it a lower priority.

**Comment by jacobkeeler** [comment]
Closing with the merge of #2676
