### ISSUE TITLE
SDL does not translate OK button to PLAY_PAUSE for apps of 4.5.1 version

### ISSUE THREAD

**Issue by dboltovskyi** [smartdevicelink/sdl_core#2679]
### Bug Report
SDL does not translate OK button to PLAY_PAUSE for apps of 4.5.1 version

##### Reproduction Steps
1. Register Mobile App with `4.5.1` version
2. Subscribe for `OK` button 

##### Expected Behavior
SDL sends to HMI `Buttons.OnButtonSubscription` notification with `PLAY_PAUSE` button name

##### Observed Behavior
SDL sends notification with `OK`

Note: Issue is not reproduced if app is registered with `4.5.0` version

##### OS & Version Information
* OS/Version: Ubuntu 16.04
* SDL Core Version: 7b41964
* Testing Against: ATF

##### Test Case, Sample Code, and / or Example App
* Script:  [MobileVersioning/PlayPauseButton/002_play_pause_v4_invalid_data](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/SDL5_0/MobileVersioning/PlayPauseButton/002_play_pause_v4_invalid_data.lua)
* ATF: [develop](https://github.com/smartdevicelink/sdl_atf/tree/develop)
* Logs: [logs.zip](https://github.com/smartdevicelink/sdl_core/files/2479632/logs.zip)

**Comment by AStasiuk** [comment]
@theresalech @JackLivio, @jacobkeeler, @yang1070. Please triage. Thanks

**Comment by JackLivio** [comment]
@AStasiuk @dboltovskyi Does this still occur even after the merge of this fix?

https://github.com/smartdevicelink/sdl_core/pull/2673

**Comment by JackLivio** [comment]
```
MOB->SDL  (15 10 2018 14:09:10, 241) [rpcFunction: RegisterAppInterface, sessionId: 1, version: 2, frameType: 1, encryption: false, serviceType: 7, frameInfo: 0, messageId: 3, binaryDataSize: 0] : {"appName":"Test Application","isMediaApplication":true,"hmiDisplayLanguageDesired":"EN-US","fullAppID":"0000001","syncMsgVersion":{"majorVersion":4,"minorVersion":5,"patchVersion":1},"appID":"0001","languageDesired":"EN-US","deviceInfo":{"maxNumberRFCOMMPorts":1,"carrier":"Megafon","os":"Android","firmwareRev":"Name: Linux, Version: 3.4.0-perf","osVersion":"4.4.2"},"appHMIType":["NAVIGATION"]} 
SDL->MOB (15 10 2018 14:09:10, 335) [rpcFunction: RegisterAppInterface, sessionId: 1, version: 2, frameType: 3, encryption: false, serviceType: 7, frameInfo: 0, messageId: 1, binaryDataSize: 0] : {"systemSoftwareVersion":"ccpu_version","softButtonCapabilities":[{"longPressAvailable":true,"imageSupported":true,"shortPressAvailable":true,"upDownAvailable":true}],"pcmStreamCapabilities":{"samplingRate":"16KHZ","audioType":"PCM","bitsPerSample":"16_BIT"},"syncMsgVersion":{"majorVersion":4,"minorVersion":5,"patchVersion":1},
```

```
===== SubscribeButton_OK_Positive_Case : 
MOB->SDL  (15 10 2018 14:09:11, 073) [rpcFunction: SubscribeButton, sessionId: 1, version: 2, frameType: 1, encryption: false, serviceType: 7, frameInfo: 0, messageId: 4, binaryDataSize: 0] : {"buttonName":"OK"} 
SDL->HMI (15 10 2018 14:09:11, 083) : {"jsonrpc":"2.0","method":"Buttons.OnButtonSubscription","params":{"appID":1065726918,"isSubscribed":true,"name":"PLAY_PAUSE"}}
```

**Comment by JackLivio** [comment]
Using Core Commit 96aa5668f36e96c2cd5d93b2b29a4e2d601f8426

**Comment by JackLivio** [comment]
ATF test scripts commit bb6dcae7103a3dfae3bc946ae31043d642a15172

**Comment by JackLivio** [comment]
This issue made us realize there would be a problem if the app sent syncMsgVersion 4.6. Submitting a fix to check if app is < version 5.0.0, instead of  app <= version 4.5.1

**Comment by JackLivio** [comment]
#2680

**Comment by dboltovskyi** [comment]
@JackLivio On a commit 1ef06f5 and `4.5.1` app's version script is passed. Thank you for update.
