### ISSUE TITLE
Remove duplicate policy_handler_observer.h 

### ISSUE THREAD

**Issue by HSavynetska** [smartdevicelink/sdl_core#2686]
### Bug Report
Remove duplicate policy_handler_observer.h 

##### Reproduction Steps
1. The path to the file "policy_handler_observer.h":
src/components/application manager/include/application manager/policies/regular/policy_handler_observer.h
2. Make sure that duplicate policy_handler_observer.h is created.

##### Expected Behavior
Duplicate policy_handler_observer.h is not created.
**Note**: Make sure that removing this file does not cause problem for other configurations.

##### Observed Behavior
Duplicate policy_handler_observer.h is created.

##### OS & Version Information
* OS/Version: n/a
* SDL Core Version: [4.5.0](https://github.com/smartdevicelink/sdl_core/tree/4.5.0)
* Testing Against: Static analysis

**Comment by JackLivio** [comment]
@HSavynetska Please add version information. Please do not mark every issue as high priority.

**Comment by iCollin** [comment]
Thanks for reporting!
I do not see a duplicate `policy_handler_observer.h` file.
I am assuming this was fixed at some point in the last year.
