### ISSUE TITLE
Remove empty module_helper.cc source file 

### ISSUE THREAD

**Issue by HSavynetska** [smartdevicelink/sdl_core#2687]
### Bug Report
Remove empty module_helper.cc source file 

##### Steps
1. The path to the file "module_helper.cc":
src/components/remote_control/src/module_helper.cc

##### Expected Behavior
Empty module_helper.cc source file is not present
**Note**:The RC section has been re-factored and this folder path does not exist in the new code base

##### OS & Version Information
* OS/Version: 
* SDL Core Version: 
* Testing Against:

**Comment by ValeriiMalkov** [comment]
This folder doesn't exist in the [develop branch](https://github.com/smartdevicelink/sdl_core/tree/develop)
