### ISSUE TITLE
CCB: Prevent creation of SSL context during certificate updating 

### ISSUE THREAD

**Issue by HSavynetska** [smartdevicelink/sdl_core#2693]
### Bug Report
Sometimes SDL trigger redundant update

##### Reproduction Steps
1. Make sure SDL is built using `EXTERNAL_PROPRIETARY` flag 
2. Register App
3. Provide ptu with valid certificate
4. Start secure service

##### Expected Behavior
SDL sends OnStatusUpdate(UPDATE_NEEDED, UPDATING, UP_TO_DATE) during PTU.
Handshake started successfully.

##### Observed Behavior
Sometimes SDL triggers one more PTU

##### OS & Version Information
* OS/Version: ubuntu 16.04
* SDL Core Version: 4.5.0
* Testing Against: ATF

##### Test Case, Sample Code, and / or Example App
* [001_GetSystemTime_is_sent.lua](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Security/GetSystemTime/001_GetSystemTime_is_sent.lua)

**Comment by HSavynetska** [comment]
Updated issue according to requirements: added versions, detailed description

**Comment by LitvinenkoIra** [comment]
Trying to reproduce the issue

**Comment by iCollin** [comment]
@LitvinenkoIra did you have success reproducing this issue? It seems to me the script is passing on develop and failing on the fix branch.

**Comment by ydementieiev** [comment]
@iCollin you are right, this bug not reproduction using attached script, we tried to do this with unit test but finished without good result, having studied the problem, we believe that an attached pull request is a potential fix. I wrote why in the [Summary to PR](https://github.com/smartdevicelink/sdl_core/pull/2777). Thank you

**Comment by iCollin** [comment]
Closed via #2777
