### ISSUE TITLE
 Provide operation result to function file_system::CreateDirectory 

### ISSUE THREAD

**Issue by HSavynetska** [smartdevicelink/sdl_core#2695]
### Bug Report
 Provide operation result to function file_system::CreateDirectory 

##### Reproduction Steps
1. The path to the file: src/components/utils/include/utils/file_system.h 
and  ../src/components/utils/src/file_system.cc
2. For the CreateDirectory function, need to add a check that returns a Boolean value that corresponds to the execution of the result by this function.

##### Expected Behavior
Provided operation result to function file_system::CreateDirectory

##### Observed Behavior
Result is absent

##### OS & Version Information
* OS/Version: Ubuntu 16.04
* SDL Core Version: [4.5.0](https://github.com/smartdevicelink/sdl_core/tree/4.5.0)
* Testing Against: Static analysis

**Comment by JackLivio** [comment]
@HSavynetska Please include version information. Also please do not mark every issue "HighPriority"
