### ISSUE TITLE
Set proper function id in removeHMIFakeParameters 

### ISSUE THREAD

**Issue by HSavynetska** [smartdevicelink/sdl_core#2696]
### Bug Report
Set proper function id in removeHMIFakeParameters 

##### Expected Behavior
Added function id in removeHMIFakeParameters 

##### Observed Behavior
Adds a functionId parameter to "removeHMIFakeParameters".
There was an issue where the mobile SetInteriorVehicleData
functionID was not the same as the hmi api InteriorVehicleData
functionID. This caused all moduleData parameters to be removed
from the message.

##### OS & Version Information
* OS/Version:
* SDL Core Version: 
* Testing Against

**Comment by JackLivio** [comment]
@HSavynetska Please supply version information next time. Also we already fixed this issue
https://github.com/smartdevicelink/sdl_core/commit/5bc69aa9083145f3f5c27f50f6f7ddb79f47a3a0
