### ISSUE TITLE
Remove unused ShowCustomForm HMI RPC

### ISSUE THREAD

**Issue by jacobkeeler** [smartdevicelink/sdl_core#2717]
### Bug Report
[UI.ShowCustomForm](https://github.com/smartdevicelink/sdl_core/blob/master/src/components/interfaces/HMI_API.xml#L4392) is an unimplemented RPC in the HMI API, it should be removed. 

##### Reproduction Steps
N/A

##### OS & Version Information
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/commit/d36316738785c96dab2ee892762ed08c059fffde

##### Test Case, Sample Code, and / or Example App
N/A

**Comment by ShobhitAd** [comment]
Closing issue with merge of https://github.com/smartdevicelink/sdl_core/pull/3101
