### ISSUE TITLE
Update "ISSUE_TEMPLATE.md" with Best Practices Link

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_core#2719]
### Bug Report
We need to update the first section of the ISSUE_TEMPLATE.md to
>[Delete any non-applicable sections, but we may ask for more information. Please reference the [SmartDeviceLink GitHub Best Practices](https://d83tozu1c8tt6.cloudfront.net/media/resources/SDL_GitHub_BestPractices.pdf) for further instructions on how to enter an issue.]

**Comment by jacobkeeler** [comment]
Fixed with the merge of #2723
