### ISSUE TITLE
Update "PULL_REQUEST_TEMPLATE.md" with Best Practices Link and Review Info

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_core#2720]
### Bug Report
We need to update the first section of the PULL_REQUEST_TEMPLATE.md to the following
>[Things to note: Pull Requests must fix an issue. Discussion about the feature / bug takes place in the issue, discussion of the implementation takes place in the PR. Please also see the Contributing Guide for information on branch naming and the CLA, and the [SmartDeviceLink GitHub Best Practices](https://d83tozu1c8tt6.cloudfront.net/media/resources/SDL_GitHub_BestPractices.pdf) document for more information on how to enter a pull request.  Once this PR is ready for review, please request one from @ jordynmackool.
Delete the above section when you've read it.]

**Comment by jacobkeeler** [comment]
Closing with the merge of #2724
