### ISSUE TITLE
EmergencyEvent->maximumChangeVelocity data type is incorrect in HMI API

### ISSUE THREAD

**Issue by atiwari9** [smartdevicelink/sdl_core#2735]
### Bug Report
_maximumChangeVelocity_ param for _EmergencyEvent_ data type is mismatched between HMI and Mobile API. HMI API has data type _VehicleDataEventStatus_(**Incorrect**) and Mobile API has data type _Integer_ (**Correct**) as _maximumChangeVelocity_ is a number which ranges from 0-255

HMI API (**Incorrect**):
```
<param name="maximumChangeVelocity" type="Common.VehicleDataEventStatus" mandatory="true">
    <description>References signal "VedsMaxDeltaV_D_Ltchd". See VehicleDataEventStatus.</description>
</param>
```
Ref: https://github.com/smartdevicelink/sdl_core/blob/master/src/components/interfaces/HMI_API.xml#L3154

Mobile API(**Correct**):
```
<param name="maximumChangeVelocity" type="Integer" minvalue="0" maxvalue="255" mandatory="true">
    <description>References signal "VedsMaxDeltaV_D_Ltchd". Change in velocity in KPH.  Additional reserved values:
        0x00 No event
        0xFE Not supported
        0xFF Fault
    </description>
</param>
```
Ref: https://github.com/smartdevicelink/sdl_core/blob/develop/src/components/interfaces/MOBILE_API.xml#L1859

**Expected:** Data type for _maximumChangeVelocity_ in HMI API needs to be corrected so that it matches with Mobile API

**Comment by atiwari9** [comment]
@JackLivio  - Can you please Triage this issue, data type for MaxChangeVelocity is incorrect in HMI API

**Comment by atiwari9** [comment]
@JackLivio  @jacobkeeler  - What was decided for this issue?

**Comment by jordynmackool** [comment]
@atiwari9 Do you plan on submitting a PR fix for this issue?

**Comment by atiwari9** [comment]
@jordynmackool - https://github.com/smartdevicelink/sdl_evolution/pull/820

**Comment by theresalech** [comment]
@atiwari9 an Evolution proposal is not needed for this issue.  The Livio team will plan to submit an sdl_core PR to resolve this issue within the 6.0 release.

**Comment by jacobkeeler** [comment]
Closing with the merge of #3040
