### ISSUE TITLE
SDL sends ""menuIcon" : null" in case app requests AddSubMenu without "menuIcon"

### ISSUE THREAD

**Issue by GetmanetsIrina** [smartdevicelink/sdl_core#2744]
### Bug Report
SDL sends ""menuIcon" : null" in case app requests AddSubMenu without "menuIcon"

##### Reproduction Steps
1. App is registered and activated
2. App requests AddSubMenu without "menuIcon"
Reproduced with script https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/2142

##### Expected Behavior
SDL sends UI.AddSubMenu without "menuIcon" to HMI

##### Observed Behavior
SDL sends UI.AddSubMenu with  null value in "menuIcon":
```
 {
   "params" : {
      "appID" : 1676936826,
      "menuID" : 1000,
      "menuIcon" : null,
      "menuParams" : {
         "menuName" : "SubMenupositive",
         "position" : 500
      }
   }
}
```

##### OS & Version Information
* OS/Version: Ubuntu 13.04
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/commit/d36316738785c96dab2ee892762ed08c059fffde
* Testing Against: ATF: develop branch(6ed5c5c7a55fa05b015de3db7c04e13b91ace01a)

**Comment by jacobkeeler** [comment]
Closing with the merge of #2913
