### ISSUE TITLE
SDL should have posibility to work along with Policy Server for PROPRIETARY flow

### ISSUE THREAD

**Issue by dboltovskyi** [smartdevicelink/sdl_core#2746]
### Bug Report
Initially issue was created against `sdl_hmi` and described in [#151](https://github.com/smartdevicelink/sdl_hmi/issues/151) 
However `sdl_core` already has such functionality and currently it works for `EXTERNAL_PROPRIETARY` flow only. 
The idea is to use it for `PROPRIETARY` flow.

##### Reproduction Steps
1. Run Policy Server
2. Run SDL (which was build with default `PROPRIETARY` flow)
3. Run SPT
4. Register new application => Policy Table Update is started 

##### Expected Behavior
Policy Table Update is finished successfully: status `Up-To-Date`

##### Observed Behavior
Policy Table Update is not finished successfully: status `Update-Needed`

##### OS & Version Information
* OS/Version: Ubuntu 16.04
* SDL Core Version: [develop](https://github.com/smartdevicelink/sdl_core/tree/develop)
* Testing Against: SPT

**Comment by JackLivio** [comment]
SDL Core does work with proprietary flow. Build with -DHMI_PTU_DECRYPTION=OFF
