### ISSUE TITLE
IP address information isn't updated when a network interface is removed

### ISSUE THREAD

**Issue by shoamano83** [smartdevicelink/sdl_core#2758]
### Bug Report

When the network interface that is monitored by SDL Core is removed from Linux system, Core doesn't detect it as IP address change. Furthermore, TransportAdapter doesn't receive `DeviceDisconnected` event.

It may be unlikely that a network interface is removed, but current behavior isn't expected one.

##### Prerequisite

- Prepare a network device that can be detached. In this repro steps, a USB Wi-Fi dongle is used.
- Attach the dongle to Linux system. Confiure it to associate with an Wi-Fi access point.
- Make sure that the network interface corresponding to the dongle is UP, RUNNING and has an IP address.

##### Reproduction Steps
1. Build lates develop branch, commit d36316738785c96dab2ee892762ed08c059fffde.
2. Edit smartDeviceLink.ini and put the network interface name into `TCPAdapterNetworkInterface = ` field. In my case, the name is `wlx00160131532c`.
3. Start SDL Core by running `./start.sh`.
4. Start sdl_hmi.
5. Connect a SDL app using TCP transport.
4. Now, remove the network device. Actually, my Linux system runs on a VirtualBox, so I go to "Devices" -> "USB" then uncheck the USB Wi-Fi dongle.
5. After a few seconds, stop SDL Core and observe its log.

##### Expected Behavior
- The log should mention that after the network device is removed, Transport Manager detects and notifies a change of IP address.

i.e. you should see a log similar to:
```
transport_adapter::PlatformSpecificNetworkInterfaceListener::NotifyIPAddresses: IP address updated: "192.168.10.100" -> "", "fe80::3d3:6e83:54f3:c91c" -> ""
```

- Also, Transport Adapter's `DeviceDisconnected()` should be called.

##### Observed Behavior
Such logs cannot be observed.
Repro ratio is quite high - 2 times out of 3.

##### OS & Version Information
* OS/Version: Ubuntu 16.04 (amd64), running on VirtualBox
* SDL Core Version: commit d36316738785c96dab2ee892762ed08c059fffde from `develop` branch
* Testing Against: sdl_hmi, commit 18460356c02e985df598b94f5a6bdbba
1c451fff from `master` branch. RPC Builder app running on Android phone.

##### Test Case, Sample Code, and / or Example App
Transport Manager's log is attached: [TransportManager.log](https://github.com/smartdevicelink/sdl_core/files/2599690/TransportManager.log)

**Comment by ShobhitAd** [comment]
Closed via https://github.com/smartdevicelink/sdl_core/pull/2759
