### ISSUE TITLE
SDL 0204- Support running the same app from multiple devices at the same time

### ISSUE THREAD

**Issue by jordynmackool** [smartdevicelink/sdl_core#2763]
Proposal: [Support running the same app from multiple devices at the same time](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0204-same-app-from-multiple-devices.md)

> This proposal proposes that SDL shall support running the same app from multiple devices at the same time. Currently, SDL only allows one instance of the same app to register with SDL. However, there are valid use cases for running the same app from two or more devices at the same time.

Review: https://github.com/smartdevicelink/sdl_evolution/issues/618

Steering Committee Decision:

> The Steering Committee voted to accept this proposal with revisions. The revisions will include updating the descriptions of ttName and vrSynonyms as discussed in [this comment](https://github.com/smartdevicelink/sdl_evolution/issues/618#issuecomment-440345476).
In addition, the author will address numbers 2 and 4 in [this comment](https://github.com/smartdevicelink/sdl_evolution/issues/618#issuecomment-440308172).
•	2. I would specify in proposal that after policy update, it will be applied for both of registered applications
•	4. Application on different device should share same usage statistics, because they use same policy app_id. this should be added to the proposal.

Revisions were made on 11/21/18

**Comment by jordynmackool** [comment]
Proposal has not yet been update, Once it is updated I will create an issue in the core repo.

**Comment by AStasiuk** [comment]
Hi @jordynmackool,
the link in the description  "Support running the same app from multiple devices at the same time" led to another proposal:
https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0200-Removing-URL-Param-Max-Length.md
and not to https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0204-same-app-from-multiple-devices.md

**Comment by jordynmackool** [comment]
Hi @AStasiuk, thanks for catching that. I have updated the link.

**Comment by theresalech** [comment]
Closed via #2960
