### ISSUE TITLE
Reusing a `syncFileName` for `PutFile` does not update image on HMI

### ISSUE THREAD

**Issue by NicoleYarroch** [smartdevicelink/sdl_core#2779]
### Bug Report
If a `PutFile` with image data reuses  a `syncFileName` the new image data does not show up on the HMI, rather the old image data is shown on the HMI

##### Reproduction Steps
1. Send a `PutFile` with the image name of "test". Wait for a success response from Core.
1. Send a `Show` request with the primary image set to show "test". 
1. Delete the file with an image name of "test".  Wait for a success response from Core.
1. Send a `PutFile` with the image name of "test". Wait for a success response from Core.
1. Send a `Show` request with the primary image set to show "test". 

##### Expected Behavior
The new image shows up in the primary graphic position in the template.

##### Observed Behavior
The old image is still displayed. 

##### OS & Version Information
* OS/Version: iOS 12
* SDL Core Version: 5.0
* Testing Against: sdl_hmi, generic_hmi

**Comment by jacobkeeler** [comment]
This was an issue with both the HMI's due to image caching. The implementation of [SDL-0212](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0212-add-ability-to-reuse-a-syncfilename-for-a-putfile.md) resolves this.
