### ISSUE TITLE
[SDL 0205] - Avoid Custom button subscription in case HMI incompatibility

### ISSUE THREAD

**Issue by jordynmackool** [smartdevicelink/sdl_core#2789]
Proposal: [Avoid Custom button subscription in case HMI incompatibility](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0205-Avoid_custom_button_subscription_when_HMI_does_not_support.md)

> In case HMI does not support CUSTOM_BUTTON, SDL should not try to subscribe an application to it.

Review: https://github.com/smartdevicelink/sdl_evolution/issues/632

Steering Committee Decision:

> The Steering Committee voted to accept this proposal with the revisions on 2018-12-11. The revisions will include adding UNSUPPORTED_RESOURCE response in the event that a CUSTOM_BUTTON is not supported as noted in [this comment](https://github.com/smartdevicelink/sdl_evolution/issues/632#issuecomment-446365125). 

Revisions were made on 2018-12-18.

**Comment by iCollin** [comment]
Closed via https://github.com/smartdevicelink/sdl_core/pull/3744
