### ISSUE TITLE
[SDL 0212] - Add Ability to Reuse a SyncFileName for a PutFile

### ISSUE THREAD

**Issue by jordynmackool** [smartdevicelink/sdl_core#2799]
Proposal: [Add Ability to Reuse a SyncFileName for a PutFile](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0212-add-ability-to-reuse-a-syncfilename-for-a-putfile.md)

> Currently, when a developer tries to reuse the same syncFileName for a PutFile with image data, the HMI is not updated to show the new image. This is due to Core only sending a notification to the HMI when the PutFile is a system file. To remedy this issue, Core needs to send a notification to the HMI when it receives any type of PutFile.

https://github.com/smartdevicelink/sdl_evolution/issues/642

Steering Committee Decision:

>The Steering Committee voted to accept this proposal with revisions on 2018-12-18. The author is to updated this proposal to include an additional parameter name of the updated file to the HMI notification as called out in [this comment](https://github.com/smartdevicelink/sdl_evolution/issues/642#issuecomment-447108125). 

Revisions were made on 1.17.19

**Comment by jacobkeeler** [comment]
Closing with the merge of #2943
