### ISSUE TITLE
Resumption doesn't work in the next ignition cycle after unexpected disconnect for 2nd app

### ISSUE THREAD

**Issue by LitvinenkoIra** [smartdevicelink/sdl_core#2803]
### Bug Report
Resumption doesn't work in the next ignition cycle after unexpected disconnect for 2nd app

##### Reproduction Steps
1. App_1 is registered and activated (FULL level)
2. IGN_OFF/IGN_ON cycle is performed
3. Wait 35 sec
4. App_1 is registered
=> SDL does: not resume HMI level App_1
5. App_2 is registered and activated (FULL level)
6. Unexpected disconnect and reconnect are performed

##### Expected Behavior
SDL does resume HMI level of App_2

##### Observed Behavior
SDL doesn't send ActivateApp (for the 2nd app) to the Applink **(HMI level resumption not working in the current ignition cycle)**

##### OS & Version Information
* OS/Version: Ubuntu 16.04 
* SDL Core Version: 5.0.0
* Testing Against: ATF test script (in the archive) + ATF and SDL logs
[Resumption_after_Low_Voltage.zip](https://github.com/smartdevicelink/sdl_core/files/2791886/Resumption_after_Low_Voltage.zip)

**Comment by dboltovskyi** [comment]
Please notice issue is still actual for current `sdl_core` [develop](https://github.com/smartdevicelink/sdl_core/tree/develop) (a36ea82)
Report and logs: [2020-09-16_11-48-43.176.tar.gz](https://github.com/smartdevicelink/sdl_core/files/5233328/2020-09-16_11-48-43.176.tar.gz)

**Comment by dboltovskyi** [comment]
Please notice issue is not related to low voltage functionality and can be reproduced without it.
Summary and Description were updated accordingly.
Corresponding new steps to reproduce are implemented in ATF script in https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/2496

**Comment by jacobkeeler** [comment]
Closing with the merge of #3608
