### ISSUE TITLE
SDL doesn't increase the timeout if the driver’s permission pop up is needed [GetInteriorVehicleDataConsent] 

### ISSUE THREAD

**Issue by GetmanetsIrina** [smartdevicelink/sdl_core#2829]
### Bug Report
SDL doesn't increase the timeout if the driver’s permission pop up is needed [GetInteriorVehicleDataConsent]

##### Reproduction Steps
1. Set RA mode - **ASK DRIVER**
2. mob send SetInteriorVehicleData request to SDL
3. Wait 10 sec
4. HMI send response for SetInteriorVehicleData after the 10sec timeout  expires

##### Expected Behavior
SDL resend response from HMI to mobile 

- SDL shall respond to a SetInteriorVehicleData request within 10 seconds after a request is received if SDL allows or denies the request without asking for the driver’s permission. If the driver’s permission pop up is needed, SDL shall respond to the request within 20 seconds.

- SDL shall respond to a ButtonPress request within 10 seconds after a request is received if SDL allows or denies the request without asking for the driver’s permission. If the driver’s permission pop up is needed, SDL shall respond to the request within 20 seconds.

- The HMI shall respond to a GetInteriorVehicleDataConsent request within 10 seconds after a request is received from SDL.

![image](https://user-images.githubusercontent.com/11210973/53787868-d073c300-3f28-11e9-805a-573ca5f0ec31.png)

##### Observed Behavior
SDL send GENERIC_ERROR to mobile 

##### OS & Version Information
* OS/Version: Ubuntu 16.04
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/commit/d5649c98c74b5cf6ce812157037e46f824c746c8

**Comment by ShobhitAd** [comment]
Fixed with the merge of https://github.com/smartdevicelink/sdl_core/pull/3726
