### ISSUE TITLE
SDL sends unsucces general PerformIntereaction response to mobile app in case choiceID was selected via VR

### ISSUE THREAD

**Issue by GetmanetsIrina** [smartdevicelink/sdl_core#2830]
### Bug Report
SDL sends unsucces general PerformIntereaction response to mobile app in case choiceID was selected

##### Reproduction Steps
1. App is registered and activated
2. ChoiceSet is added
3. Mobile app requests PerformIntereaction(BOTH, VR_ONLY)
4. Make choice( in case BOTH only VR choice )

##### Expected Behavior
SDL receives successful VR.PI with choiceID value and sends UI.ClosePopUp to UI.PI, HMI responds with unsuccessful UI.PI, then SDL sends successful response with choiceID to mobile app. 

##### Observed Behavior
SDL responds with unsuccessful result code and without choiceId to mobile app and does not send UI.ClosePopUp to HMI

##### OS & Version Information
* OS/Version: Ubuntu 16.04
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/commit/d5649c98c74b5cf6ce812157037e46f824c746c8
* Testing Against: HMI https://github.com/smartdevicelink/sdl_hmi/commit/7962e1e858ca2c672fd53b1a1cd4ab08f59e4a32
Log: 
[SmartDeviceLinkCore.log.tar.gz](https://github.ford.com/SmartDeviceLinkMirror/sdl_core/files/6026/SmartDeviceLinkCore.log.tar.gz)

##### Diagrams
VR_ONLY mode:
![image](https://media.github.ford.com/user/8112/files/07ccaf00-36a1-11e9-9478-66ef617f7c36)
BOTH mode:
![image](https://media.github.ford.com/user/8112/files/0f8c5380-36a1-11e9-914d-1d54e1dd5bd1)
ClosePopUp 
![closepopup](https://media.github.ford.com/user/8112/files/b297d400-3912-11e9-92cd-78240ff231ca)

**Comment by YarikMamykin** [comment]
@theresalech Please triage this issue and notice linked fix is ready for review.

**Comment by theresalech** [comment]
@YarikMamykin both linked PRs (https://github.com/smartdevicelink/sdl_core/pull/3122, https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/2293) have `This PR is **not ready** for review.` in their descriptions.  Please tag me and @jordynmackool on those PRs when they are confirmed as ready for review and descriptions have been updated.

**Comment by YarikMamykin** [comment]
@theresalech please notice that PRs https://github.com/smartdevicelink/sdl_core/pull/3122 and https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/2293 are **ready** for review.

**Comment by iCollin** [comment]
Closed via #3122
