### ISSUE TITLE
[SDL 0173] Read Generic Network Signal Data

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_core#2840]
Proposal: [Read Generic Network Signal Data](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0173-Read-Generic-Network-Signal-data.md)

> This proposal is to make vehicle data APIs (GetVehicleData/SubscribeVehicleData/UnsubscribeVehicleData/OnVehicleData) more flexible to allow additional new vehicle data items, while maintaining the security access via policies.

Review: https://github.com/smartdevicelink/sdl_evolution/issues/502

Steering Committee Decision:

> The Steering Committee voted to accept this proposal with revisions. The author is to add a statement explaining how old core implementations using this method can be updated to expose new standardized vehicle data items. Additionally, the author is to add the three revisions noted in [this comment.](https://github.com/smartdevicelink/sdl_evolution/issues/502#issuecomment-465326262)

>The proposal .md was updated on March 11, 2019 to include the agreed upon revisions.

**Comment by theresalech** [comment]
Proposal markdown file has been updated per the revisions included in accepted Evolution Proposal [SDL 0173 Revisions - Read-Generic-Network-Signal-data](https://github.com/smartdevicelink/sdl_evolution/issues/768).  Please reference issue and proposal markdown file for more details.

**Comment by theresalech** [comment]
Proposal markdown file has been updated per the revisions included in accepted Evolution Proposal [SDL 0173 Revisions - Read Generic Network Signal Data Clarification](https://github.com/smartdevicelink/sdl_evolution/issues/806). Please reference issue and proposal markdown file for more details.

**Comment by jacobkeeler** [comment]
Closing with the merge of #2977

**Comment by theresalech** [comment]
Proposal markdown file has been updated per the revisions included in accepted Evolution Proposal [Revise 0173-Read-Generic-Network-Signal-data.md](https://github.com/smartdevicelink/sdl_evolution/issues/822). Please reference issue and proposal markdown file for more details.

**Comment by JackLivio** [comment]
closed via #3062
