### ISSUE TITLE
SDL ignores accessMode if allowed parameter does not exist in OnRemoteControlSettings 

### ISSUE THREAD

**Issue by yang1070** [smartdevicelink/sdl_core#2845]
### Bug Report
The parameters of HMI function `OnRemoteControlSettings` are defined as optional in HMI_API.xml. That means HMI can send a  `OnRemoteControlSettings`  notification with
- only `allowed` parameter 
- or only `accessMode` parameter 
- or both parameters. 

When SDL receives such notifications, it shall update its internal value and use the new value when needed.

However, the current SDL behavior (please see [RCOnRemoteControlSettingsNotification::Run](https://github.com/smartdevicelink/sdl_core/blob/d36316738785c96dab2ee892762ed08c059fffde/src/components/application_manager/rpc_plugins/rc_rpc_plugin/src/commands/hmi/rc_on_remote_control_settings_notification.cc#95)) is to ignore the `accessMode` parameter if `allowed` parameter does not exist or `allowed=false` in the notification.
That means `allowed` is mandatory and HMI shall always include  `allowed` parameter.

Suggest to update the [hmi_integration_guidelines](https://github.com/smartdevicelink/sdl_hmi_integration_guidelines/blob/master/docs/RC/OnRemoteControlSettings/index.md) to have a clause that HMI shall 
always include  `allowed` parameter  if we do not change sdl core.

A better solution is to  decouple the dependency of two parameters and update the sdl logic to make the parameters truly optional .
SDL shall do the flowing

if `accessMode` parameter exist {
    SetAccessMode(access_mode);
}
if `allowed` parameter exist {
   if `allowed`=true {
         set_rc_enabled(true);
    } else {
        DisallowRCFunctionality();
        ResetAllAllocations();
        set_rc_enabled(false);
  }
}

##### Reproduction Steps
From HMI send a `OnRemoteControlSettings`  notification with only `accessMode` parameter.

##### Expected Behavior
SDL update its internal value of `accessMode`.

##### Observed Behavior
SDL does not update its internal value of `accessMode`.

##### OS & Version Information

* SDL Core Version: 5.0
* Testing Against: HMI

##### Test Case, Sample Code, and / or Example App
[Paste a link to a PR, gist, or other code that exemplifies this behavior]

**Comment by ShobhitAd** [comment]
Closed via https://github.com/smartdevicelink/sdl_core/pull/3749
