### ISSUE TITLE
"ini_read_value" performance issue

### ISSUE THREAD

**Issue by zydjys** [smartdevicelink/sdl_core#2850]
### Bug Report
[Summary]
"ini_read_value" has performance problem when parser smartDeviceLink.ini file 

##### Reproduction Steps
[step1]
Execute smartDeviceLinkCore program with strace under embedded linux system;
[step2]
Analysis strace log
- found many file operation unit(open->mmap2->read->close) with smartDeviceLink.ini 
[step3]review source code ini_file.cc profile.cc
- found ini_read_value will be called many many time 
- ini_read_value will call std io fopen->fgets->fclose
- file operation unit is caused by function ini_read_value
##### Expected Behavior
- the frequencely file operation unit will cause performance issue under embedded linux system if the cpu & volatile memory io is not very powerful.
- when parse smartDeviceLink.ini file :  open ini file->and parse all the tag to Profile Class ->close the file
- smartDeviceLinkCore get config tag from Profile class directly;

##### OS & Version Information
* OS/Version: [all]
* SDL Core Version: [all]
* Testing Against: [sdl_core]

##### Test Case, Sample Code, and / or Example App
see "ini_read_value" in ini_file.cc

**Comment by iCollin** [comment]
Closed via https://github.com/smartdevicelink/sdl_core/pull/3688
