### ISSUE TITLE
SDL sends UnsubscribeWayPoint  request to HMI for App1 when App2 is still subscribed to the WayPoint

### ISSUE THREAD

**Issue by HSavynetska** [smartdevicelink/sdl_core#2862]
### Bug Report
SDL sends UnsubscribeWayPoint  request to HMI for App1 when App2 is still subscribed to the WayPoint

##### Pre-conditions
1. SDL and HMI are started
2. App1 and App2 are registered
3. App1 and App2 are subscribed to SubscribeWayPoint

##### Reproduction Steps
1. App1 requests  the UnsubscribeWayPoint
2. App2 requests  the UnsubscribeWayPoint

##### Expected Behavior
1. SDL does not transfer the request to HMI, unsubscribes internally and responds with result code SUCCESS, success: true for App1
2. SDL sends the request to HMI for app2 and unsubscribes after successful HMI response

##### Observed Behavior
1. SDL sends the request to HMI for App1
2. SDL sends the request to HMI for App2

##### OS & Version Information
* OS/Version: Ubuntu 16.04
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/tree/release/5.1.0 (fb88c17) 
* Testing Against: SPT App Version 20190122-Nightly-Android

**Comment by dboltovskyi** [comment]
@theresalech, please triage this issue
