### ISSUE TITLE
SDL does not send response to HMI in case App Service doesn't respond within defined timeout

### ISSUE THREAD

**Issue by dboltovskyi** [smartdevicelink/sdl_core#2866]
### Bug Report
SDL does not send response to HMI in case App Service doesn't respond within defined timeout

##### Reproduction Steps
1. App_1 published a particular service
2. HMI is requested `AppService.GetAppServiceData` RPC for this service type
3. App_1 does not provide response within defined timeout

##### Expected Behavior
SDL sends `TIMED_OUT` response to HMI

##### Observed Behavior
SDL does not send response to HMI

##### OS & Version Information
* OS/Version: Ubuntu 16.04
* SDL Core Version: [5.1.0](https://github.com/smartdevicelink/sdl_core/tree/release/5.1.0) (abdfa1d)
* Testing Against: ATF

##### Test Case, Sample Code, and / or Example App
[2019-04-01_13-48-30.tar.gz](https://github.com/smartdevicelink/sdl_core/files/3028965/2019-04-01_13-48-30.tar.gz)

**Comment by dboltovskyi** [comment]
@theresalech, please triage this issue

**Comment by jacobkeeler** [comment]
Fixed with the merge of #2871
