### ISSUE TITLE
SDL crash happens when receiving SystemRequest (ICON_URL)  with correlationID -1 (INVALID_ENUM)

### ISSUE THREAD

**Issue by VjKlepikov** [smartdevicelink/sdl_core#2874]
### Bug Report
SDL crash happens when receiving SystemRequest (ICON_URL)  with correlationID: -1 (INVALID_ENUM)

**Precondition:**

   1. Cloud App in the policy table
   2. HMI and SDL are started
   3. Mobile App (**SDL Message Version 5.0.0**) is registered and activated

**Reproduction Steps**

 1. Send SystemRequest (ICON_URL) with correlationID: -1 from Mobile App

**Expected Behavior**

1. No any failures

**Observed Behavior**

1. Core crash

**OS & Version Information**

* OS/Version: [16.04]
* Mobile app: Android 5.0.2
* Mobile device: Samsung SM-G530H
* Mobile Apps: SPT(20190122)
* Transport: BT
* SDL Core Version: [5.1.0] b9500e5

**Test Case, Sample Code, and / or Example App**
[SDL_log.zip](https://github.com/smartdevicelink/sdl_core/files/3038368/SDL_log.zip)

**Comment by dboltovskyi** [comment]
@theresalech Please triage this issue

**Comment by ShobhitAd** [comment]
Closing with merge of https://github.com/smartdevicelink/sdl_core/pull/2875
