### ISSUE TITLE
One SDL app (smartphone)  for all HU vendor or one SDL app for each HU vendor ?

### ISSUE THREAD

**Issue by kindow** [smartdevicelink/sdl_core#288]
SDL could connect HU with SmartPhone, it helps user interact with these smartphone app on HU interface.   My question is since tempalte is defined by vendor , so different HU vendor might define different template (layout) for SDL apps, i think it's impossible for smartphone app developer to develop just one version of sdl app compatible with all HU models by different vendor, right?  Or is there any template design principle for HU vendor to resolve the compatible problem?

**Comment by justinjdickow** [comment]
There are several predefined template layouts which guide an OEMs implementation of each template defined in SDL, which enables app developers to make assumptions about the screen or controls that are available to the user during the interaction with their app. See attached.

![App Templates](https://cloud.githubusercontent.com/assets/3627664/11782821/6f1792d0-a241-11e5-820f-1bc1d1a417c4.png)
