### ISSUE TITLE
Button Press notifications are not received on device when SEEK_LEFT hard button pressed when App in HMI Level LIMITED

### ISSUE THREAD

**Issue by LitvinenkoIra** [smartdevicelink/sdl_core#2888]
##### Reproduction Steps 
1 .SDL and HMI are started
2. Media app is registered, activated and subscribed to the <Button_Name> button
3. Change the app level to LIMITED
4. HMI sends OnButtonPress (<Button_Name> , appID, buttonPressMode)

##### Expected Behavior
SDL forwards the OnButtonPress notification to the mobile app

##### Observed Behavior
SDL  doesn't forward the OnButtonPress notification to the mobile app

-----------------------------------------------------------------------------------------

Also during the investigation of this problem I faced with issue that: **HMI API is mismatch with the current implementation** 
According to the current implementation OnButtonPress and OnButtonEvent notifications will be transferred to the subscribed app in **LIMITED** HMI level only if the **notification from the HMI contains the appID param**. 

Which is mismatch with the description in HMI API :
 https://github.com/smartdevicelink/sdl_core/blob/develop/src/components/interfaces/HMI_API.xml#L3853
https://github.com/smartdevicelink/sdl_core/blob/develop/src/components/interfaces/HMI_API.xml#L3870

Initially this logic for sending the notification to the app in LIMITED was applicable only for the "OK" button. But it was changed within:
- https://github.com/smartdevicelink/sdl_core/pull/576  
- https://github.com/smartdevicelink/sdl_core/pull/952 
- https://github.com/smartdevicelink/sdl_core/pull/1044 
- https://github.com/smartdevicelink/sdl_core/pull/775

So for now we have the following behavior:

- _If appID is present for **ANY BUTTON**  (except CUSTOM button) -> SDL transfers notification to the named app only if it is in FULL or LIMITED (ignores if app is in NONE or BACKGROUND)._
- _If appID is omitted for **ANY BUTTON** (except CUSTOM button) -> SDL transfers notification to app in FULL_

##### OS & Version Information
* OS/Version: Ubuntu 16.04
* SDL Core Version: [release/5.0.1](https://github.com/smartdevicelink/sdl_core/blob/release/5.0.1)
* Testing Against: [release/5.0.1](https://github.com/smartdevicelink/sdl_core/blob/release/5.0.1) (applicable for the  [release/5.1.0](https://github.com/smartdevicelink/sdl_core/blob/release/5.1.0) also)

Logs and ATF test script are attached: 
[ATF_OnButtonPress.zip](https://github.com/smartdevicelink/sdl_core/files/3095140/ATF_OnButtonPress.zip)

**Comment by E-SAITO-TMC** [comment]
@theresalech -san, We were able to reproduce this issue with Core 6.0.1. This is a high priority issue for Toyota. Could you please include this in the Core 6.2 release planning?

**Comment by theresalech** [comment]
@LitvinenkoIra can you please advise if you are able to reproduce this issue in the latest Core release?

**Comment by dboltovskyi** [comment]
@theresalech Please notice we're not planning to create the fix in scope of 6.2, though will try to do as much as possible

**Comment by iCollin** [comment]
@dboltovskyi I see the attached ATF test completely passing against current develop. Is the issue of button presses not being transferred to apps in LIMITED still actual?

**Comment by dboltovskyi** [comment]
@iCollin Confirmed. Issue is not reproduced on a current develop (5e2dff6d31)

**Comment by iCollin** [comment]
@LitvinenkoIra I have submitted a fix for the subscribed apps in LIMITED issue in #3461, please let me know if this does fix the reported issue. Thank you.

**Comment by iCollin** [comment]
Closed via https://github.com/smartdevicelink/sdl_core/pull/3461 and https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/2434
