### ISSUE TITLE
Build With Option `BUILD_CLOUD_APP_SUPPORT`=OFF Fails

### ISSUE THREAD

**Issue by JackLivio** [smartdevicelink/sdl_core#2895]
### Bug Report
Build With Option `BUILD_CLOUD_APP_SUPPORT`=OFF Fails

##### Reproduction Steps
1. Set CMAKE Flag `BUILD_CLOUD_APP_SUPPORT`=OFF
2. Build Core
##### Expected Behavior
Core compiles with no errors.

##### Observed Behavior
Build fails on undefined references to dependencies because there are missing ifdefs to only compile certain cloud app classes when the build option is ON.

##### OS & Version Information
* OS/Version: Ubuntu 18
* SDL Core Version: 5.1

**Comment by jacobkeeler** [comment]
Closing with the merge of #2900
