### ISSUE TITLE
Add Code Quality tools 

### ISSUE THREAD

**Issue by AByzhynar** [smartdevicelink/sdl_core#2905]
### Summary
Add the following tools for code quality checks and potential 
problems discovering on early stages: 
-  **cppcheck** -   is an analysis tool for C/C++ code. It detects the types of bugs that the compilers normally fail to detect. The goal is no false positives.
-  **cpplint** - Static code checker for C++
-  **pylint** -  code analyzer for Python (needed as lots of Python scripts are used in project)

**Note**: the tools specified above should be combined into one script and included into pre-commit hooks to make checks automatic

**Comment by zcloud-jzy** [comment]
good

**Comment by jacobkeeler** [comment]
Note: `cppcheck` is already included in the Travis CI build (https://github.com/smartdevicelink/sdl_core/blob/master/.travis.yml#L23)

**Comment by theresalech** [comment]
Closed via https://github.com/smartdevicelink/sdl_core/pull/3485.
