### ISSUE TITLE
Core is not able to complete handshake for cloud apps

### ISSUE THREAD

**Issue by bilal-alsharifi** [smartdevicelink/sdl_core#2914]
### Bug Report
We noticed that Core is failing to complete the handshake for cloud apps when there is a path passed the root in the cloud app endpoint

So, for example, when the websocket endpoint only has IP and port like the following, it works:
`ws://<ip>:<port>/`

But when the endpoint has path passed the root, it doesn't work
`ws://<ip>:<port>/testapp/`

##### Reproduction Steps
1. Setup core and HMI to add a cloud app with an endpoint that has path passed the root
2. Make sure cloud app is running and waiting for connection
3. Try to start the cloud app from HMI

##### Expected Behavior
Cloud app starts correctly

##### Observed Behavior
Cloud app doesn't start. Core fails to open the websocket connection with this error:
```
Could not complete handshake with host/port:
```

##### OS & Version Information
* OS/Version: Ubuntu 16
* SDL Core Version: 5.1.1
* Testing Against: Cloud app (JavaEE) / Glassfish server

**Comment by ShobhitAd** [comment]
Closing with the merge of https://github.com/smartdevicelink/sdl_core/pull/2930
