### ISSUE TITLE
App Service Data Images Missing Full Path

### ISSUE THREAD

**Issue by JackLivio** [smartdevicelink/sdl_core#2926]
### Bug Report

OnServiceData RPCs sent to the HMI that contain images only list the filename and not the full file path. When an image is sent by an app provider and the hmi is acting as an app consumer, the HMI has no way of knowing where to locate the image it wants to display.

##### Reproduction Steps
1. Subscribe HMI on OnAppServiceData
2. Publish an app service provider of type weather.
3. Send OnAppServiceData with an image

##### Expected Behavior
HMI receives full path for images stored on the FS.

##### Observed Behavior
HMI only receives file name for the image.

**Comment by jacobkeeler** [comment]
Closing with the merge of #2931
