### ISSUE TITLE
OnSystemRequest Empty URL when no endpoint is present

### ISSUE THREAD

**Issue by JackLivio** [smartdevicelink/sdl_core#2932]
### Bug Report
Core will still send an onSystemRequest to mobile even if there is no url present for request type: LOCK_SCREEN_ICON_URL.

##### Reproduction Steps
1. Remove lock_screen_icon_url endpoint from the policy table.
2. Connect and register an app

##### Expected Behavior
Core does not send onSystemRequest LOCK_SCREEN_ICON_URL

##### Observed Behavior
Core sends onSystemRequest with empty url parameter.

**Comment by iCollin** [comment]
Closed via #3257
