### ISSUE TITLE
SDL processes SetInteriorVD request with resultCode IN_USE

### ISSUE THREAD

**Issue by VjKlepikov** [smartdevicelink/sdl_core#2942]
**Bug Report**

SDL processes SetInteriorVD request with resultCode IN_USE

**Preconditions**
1. REMOTE_CONTROL app is registered and activated 

**Reproduction Steps**

1. Mobile app sends SetInteriorVehicleData request with params does not correspond to moduleType
2. Mobile app gets response with INVALID_DATA
3. Mobile app sends SetInteriorVD request with data for correspond moduleType

**Expected Behavior**

1.  SDL successfully processes SetInteriorVD request from Mobile app and sends this request to HMI

**Observed Behavior** 
1. SDL does not sends SetInteriorVD request to HMI and responds with IN_USE to mobile app

**OS & Version Information**
OS/Version:Ubuntu16.04 
SDL Core Version:  [7a7c31](https://github.com/smartdevicelink/sdl_core/commit/7a7c31b1ac64d6acd1796f5024472905b32ecf73)

**Test Case, Sample Code, and / or Example App**
Script:  [ScriptSetInteriotVD.zip](https://github.com/smartdevicelink/sdl_core/files/3272329/ScriptSetInteriotVD.zip)
ATF: [f53434](https://github.com/smartdevicelink/sdl_atf_test_scripts/commit/f53434a6340239bd587a9c663f61793da2280633)
Log:  [SetInteriotVD.zip](https://github.com/smartdevicelink/sdl_core/files/3272323/SetInteriotVD.zip)

**Comment by jacobkeeler** [comment]
Closed as part of #2984
