### ISSUE TITLE
Audio stream internal data stream error when using socket streaming

### ISSUE THREAD

**Issue by ShobhitAd** [smartdevicelink/sdl_core#2945]
### Bug Report
Audio stream returns a "internal data stream" error when using gstreamer command for socket streaming

##### Reproduction Steps
1. Set `AudioStreamConsumer` to `socket` and `AudioStreamingPort` to `5080` in `smartDeviceLink.ini`.
2. Start audio stream from app (accept prompt from HMI to start audio stream)
3. Start reading audio stream using the following `gstreamer` command:
```
gst-launch-1.0 souphttpsrc location=http://127.0.0.1:5080 ! audio/x-raw,format=S16LE,rate=16000,channels=1 ! pulsesink
```

##### Expected Behavior
Entire audio file is played

##### Observed Behavior
No audio is played and the audio stream is stopped due to an internal data stream error

##### OS & Version Information
* OS/Version: Ubuntu 18.04
* SDL Core Version: 5.1.2
* Testing Against: sdl_test_suite

##### Test Case
The `gstream` command prints the following output 
```
Setting pipeline to PAUSED ...
Pipeline is PREROLLING ...
Got context from element 'souphttpsrc0': gst.soup.session=context, session=(SoupSession)NULL, force=(boolean)false;
ERROR: from element /GstPipeline:pipeline0/GstSoupHTTPSrc:souphttpsrc0: Internal data stream error.
Additional debug info:
gstbasesrc.c(3055): gst_base_src_loop (): /GstPipeline:pipeline0/GstSoupHTTPSrc:souphttpsrc0:
streaming stopped, reason error (-5)
ERROR: pipeline doesn't want to preroll.
Setting pipeline to NULL ...
Freeing pipeline ...
```

**Comment by iCollin** [comment]
closed via https://github.com/smartdevicelink/sdl_core/pull/3057
