### ISSUE TITLE
SDL does not apply functional group consent for all registered application if it received OnAppPermissionConsent notification without appID

### ISSUE THREAD

**Issue by aderiabin** [smartdevicelink/sdl_core#2957]
### Bug Report
SDL does not apply functional group consent for all registered application if it received OnAppPermissionConsent notification without appID

##### Reproduction Steps
0. SDL built with `EXTERNAL PROPRIETARY`
Application data for App1 (`appId = 0000001`) and App2 (`appId = 0000002`) exists in policy table 
RPC Show is exists in functional group `ShowFuncGroup` which requires `user_consent_prompt: "ShowConsent"`.
App1 and App2 have group `ShowFuncGroup` in its allowed groups in policy table.

1. SDL and HMI are running
2. Mobile device is connected to SDL and consented by the User
3. Register App1 and App2 from mobile device.
4. Activate App1 and App2 consequentially
5. HMI received list of permissions via `GetListOfPermissions` RPC and display the 'app permissions consent' message.
6. User allows `ShowConsent` permissions and HMI sends `OnAppPermissionConsent` notification without `appID` parameter (`source: "GUI", consentedFunctions: [ {name:"ShowFuncGroup", id: 12345, allowed: true }]`)
7. App1 and App2 send `Show` RPC
 

##### Expected Behavior
App1 receives response with `resultCode: "SUCCESS"` (RPC allowed by policy)
App2 receives response with `resultCode: "SUCCESS"` (RPC allowed by policy)

##### Observed Behavior
App1 receives response with `resultCode: "SUCCESS"` (RPC is allowed by policy for App1)
App2 receives response with `resultCode: "DISALLOWED"` (RPC is disallowed by policy App2)

##### OS & Version Information
* OS/Version: Ubuntu 16.04
* SDL Core Version: built from commit 94a46dd9cdbb7b8a281c067f81c188f66cfc6a5d

**Comment by iCollin** [comment]
Closed via https://github.com/smartdevicelink/sdl_core/pull/3770
