### ISSUE TITLE
SDL sends params from new assigned group for app in userDisallowed section of onPermissionChange in proprietary flow

### ISSUE THREAD

**Issue by GetmanetsIrina** [smartdevicelink/sdl_core#2961]
### Bug Report
SDL sends params from new assigned group for app in userDisallowed section of onPermissionChange in proprietary flow

##### Reproduction Steps
1. SDL is built with PROPRIETARY policy flow
2. App is registered and activated

##### Reproduction Steps
1. PTU is performed with new assigned group which contains the list of parameters in parameters section

##### Expected Behavior
During PTU SDL sends OnPermissionChange notification with parameters from new assigned group for appropriate RPC in allowed section

##### Observed Behavior
SDL sends parameters in userDisallowed section
```
{"parameterPermissions":{"userDisallowed":["gps","speed"],"allowed":["airbagStatus","clusterModeStatus","eCallInfo","emergencyEvent"]},"hmiPermissions":{"userDisallowed":["BACKGROUND","FULL","LIMITED"],"allowed":[]},"rpcName":"GetVehicleData"}
```
##### OS & Version Information
* OS/Version: Ubuntu 16.04
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/commit/18ca3b719bd2442a4370dfba34e1c4ab885ba6e7
* ATF version: https://github.com/smartdevicelink/sdl_atf/commit/ba1194bbd8e1a7dc798fb20d7899670bb45e1ecf
* Script: [Permissions_from_new_assigned_functional_group.lua.tar.gz](https://github.com/smartdevicelink/sdl_core/files/3368545/Permissions_from_new_assigned_functional_group.lua.tar.gz)

##### Logs
[SDLlogs.tar.gz](https://github.com/smartdevicelink/sdl_core/files/3368189/SDLlogs.tar.gz)

**Comment by jacobkeeler** [comment]
Confirmed non-reproducible on develop, closing
