### ISSUE TITLE
SDL does not send OnPermissionChange after PTU with updated parameters list in assigned group for app

### ISSUE THREAD

**Issue by GetmanetsIrina** [smartdevicelink/sdl_core#2962]
### Bug Report
SDL does not send OnPermissionChange after PTU with updated parameters list in assigned group for app

##### Reproduction Steps
1. Register app
2. PTU is performed with assigned "Emergency-1" group for app
3. PTU is triggered by HMI
4. Some parameters are removed from  "Emergency-1" in update from cloud
5. Status is UP_TO_DATE

##### Expected Behavior
SDL sends OnPermissionChange to app during PTU

##### Observed Behavior
SDL does not send OnPermissionChange to app during PTU

##### OS & Version Information
* OS/Version: Ubuntu 16.04
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/commit/18ca3b719bd2442a4370dfba34e1c4ab885ba6e7
* ATF version: https://github.com/smartdevicelink/sdl_atf/commit/ba1194bbd8e1a7dc798fb20d7899670bb45e1ecf
* Script: [OnPermissionsChange_after_update_with_updated_parameter_list.lua.tar.gz](https://github.com/smartdevicelink/sdl_core/files/3368729/OnPermissionsChange_after_update_with_updated_parameter_list.lua.tar.gz)

##### Logs
[ATF_and_SDL_logs.tar.gz](https://github.com/smartdevicelink/sdl_core/files/3368715/ATF_and_SDL_logs.tar.gz)

**Comment by jacobkeeler** [comment]
Closed via #2977
