### ISSUE TITLE
SDL incorectly assigns default permissions for an app if they were defined in preloaded

### ISSUE THREAD

**Issue by dboltovskyi** [smartdevicelink/sdl_core#2966]
### Bug Report
SDL incorectly assigns default permissions for an app if they were defined in preloaded

##### Reproduction Steps
1. Update SDL preloaded file and add default permissions for some app. E.g.:
```
"app_policies": 
{
  "app":"default",
  "default": {
    ...
    "groups": ["Base-4"],
    ...
  },
  ...
}
```
2. Register app
3. Check `OnHMIStatus` and `OnPermissionsChange` are sent to app

##### Expected Behavior
`OnHMIStatus` and `OnPermissionsChange` notifications are sent to app
Since these are in `Base-4` func. group and allowed at `NONE` HMI level

##### Observed Behavior
`OnHMIStatus` and `OnPermissionsChange` notifications are **not** sent to app

##### OS & Version Information
* OS/Version: Ubuntu 16.04 amd64
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/tree/develop (18ca3b7)
* ATF: https://github.com/smartdevicelink/sdl_atf/tree/develop

##### Test Case, Sample Code, and / or Example App
[2019-07-18_11-24-16.tar.gz](https://github.com/smartdevicelink/sdl_core/files/3407264/2019-07-18_11-24-16.tar.gz)
[002_default_app_policies_issue.zip](https://github.com/smartdevicelink/sdl_core/files/4230367/002_default_app_policies_issue.zip)

**Comment by GetmanetsIrina** [comment]
The small update was performed in the issue script. The archive with script is updated.

**Comment by LitvinenkoIra** [comment]
@theresalech please triage the issue. SDL incorrectly assigns default permissions for an app if they were defined in preloaded, its reproduced on proprietary and external proprietary policy flows.
 We have already prepared the fix for this issue in https://github.com/smartdevicelink/sdl_core/pull/3244

**Comment by theresalech** [comment]
@LitvinenkoIra this issue has not yet been raised to the Steering Committee as priority for Core 6.1. We will work to include if time allows, but would recommend raising as priority in the Steering Committee meeting if it's imperative the issue be included. Thanks!

**Comment by iCollin** [comment]
Closed via https://github.com/smartdevicelink/sdl_core/pull/3244
