### ISSUE TITLE
Set USB INI Configurations in the .ini

### ISSUE THREAD

**Issue by JackLivio** [smartdevicelink/sdl_core#2971]
This is not an issue. It is an idea for a minor enhancement. 

[Currently the usb aoa filtering parameters must be compiled with Core.](https://github.com/smartdevicelink/sdl_core/blob/master/src/components/transport_manager/src/usb/usb_device_scanner.cc#L174-L179) In order to make usb testing easier I am suggesting these filtering parameters be set in the .ini file so the developers testing USB do not need to recompile core every time this value needs to be changed.

**Comment by theresalech** [comment]
Closed via #2972
