### ISSUE TITLE
SDL does not send OnSDLClose notification by switching off with reason IGNITION_OFF

### ISSUE THREAD

**Issue by aderiabin** [smartdevicelink/sdl_core#2976]
### Bug Report
SDL does not send OnSDLClose notification by switching off with reason IGNITION_OFF

##### Occurrence: 
Sometimes

##### Preconditions
1. SDL and HMI are started.
2. Mobile application is registered.

##### Reproduction Steps
1. Perform IGNITION_OFF (send BasicCommunication.OnExitAllApplications with reason = "IGNITION_OFF")

##### Expected Behavior
SDL sends OnSDLClose notification to HMI

##### Observed Behavior
SDL does not send OnSDLClose notification to HMI

##### OS & Version Information
* OS/Version: Ubuntu 16.04 amd64
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/tree/develop
* ATF: https://github.com/smartdevicelink/sdl_atf/tree/develop

##### Test Case, Sample Code, and / or Example App
Test script: 
https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Smoke/ShutDown/001_ShutDown_IGNITION_OFF.lua

**Comment by aderiabin** [comment]
Test set [policies_happy_paths_PROPRIETARY](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_sets/policies_happy_paths_PROPRIETARY.txt) should be updated after closing this issue.

**Comment by IGapchuk** [comment]
The defect doesn't reproduce.

**Environment:**
**OS:** Ubuntu 18.0
**SDL Core:** develop (https://github.com/smartdevicelink/sdl_core/commit/e7b5c75c704f6cd577f0857e4cbe17cf6ec160fa)
**ATF:** develop (https://github.com/smartdevicelink/sdl_atf/commit/d6c2138f8d894d1e343d971226a16c47019ee92e)

**Comment by IGapchuk** [comment]
Currently the issue doesn't reproduce by switching off with reason IGNITION_OFF, but reproduces by reason MASTER_RESET.
Script for reproduce issue: https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Smoke/ShutDown/002_ShutDown_MASTER_RESET.lua

**Comment by dboltovskyi** [comment]
@theresalech Please triage this issue

**Comment by theresalech** [comment]
@dboltovskyi please advise if Luxoft will be submitting a PR to resolve this issue, and if so, when that PR is ready for Livio review.  Thanks!

**Comment by dboltovskyi** [comment]
@theresalech Yes, Luxoft is preparing a fix now.

**Comment by dboltovskyi** [comment]
@theresalech Fix is ready for review

**Comment by theresalech** [comment]
@dboltovskyi got it, thanks!  We'll review https://github.com/smartdevicelink/sdl_core/pull/3022
