### ISSUE TITLE
SDL allocates RC module and sends OnRCStatus notifications on receive SetInteriorVehicleData RPC with invalid data

### ISSUE THREAD

**Issue by aderiabin** [smartdevicelink/sdl_core#2978]
### Bug Report
SDL allocates RC module and sends OnRCStatus notifications on receive SetInteriorVehicleData RPC with invalid data

##### Reproduction Steps
Preconditions:
  1) SDL and HMI are started with App 1 and App 2 application data in LPT
  2) HMI sent HMI_SETTINGS module capabilities to the SDL
  3) Mobile is connected to the SDL
  4) Set RC access mode as: AUTO_DENY
  5) App 1 and App 2 are registered
  6) App 1 is activated

Steps:
1. Send incorrect "SetInteriorVehicleData"(moduleType = "HMI_SETTINGS", hmiSettingsControlData is absent) request from App 1 to the SDL
2. Activate App 2
3. Send correct "SetInteriorVehicleData" (moduleType = "HMI_SETTINGS", hmiSettingsControlData is correct) request from App2 to the SDL 

##### Expected Behavior
SDL sends "OnRCStatus" notifications to App 1 and App 2
SDL sends "RC.OnRCStatus" notifications to the HMI
SDL resends "RC.SetInteriorVehicleData" request to the HMI and receives respond from HMI
SDL responds with "SetInteriorVehicleData"(success = true, resultCode = "SUCCESS") to the App 2

##### Observed Behavior
SDL does NOT send "OnRCStatus" notifications to App 1 and App 2
SDL does NOT send "RC.OnRCStatus" notifications to the HMI
SDL does NOT resend "RC.SetInteriorVehicleData" request to the HMI
SDL responds with "SetInteriorVehicleData"(success = false, resultCode = "IN_USE") to the App 2

##### OS & Version Information
* OS/Version: Ubuntu 16.04 amd64
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/tree/develop (9a556df)
* ATF: https://github.com/smartdevicelink/sdl_atf/tree/develop

##### Test Case, Sample Code, and / or Example App
[test_script.zip](https://github.com/smartdevicelink/sdl_core/files/3451853/test_script.zip)
[logs.zip](https://github.com/smartdevicelink/sdl_core/files/3451859/logs.zip)

**Comment by jacobkeeler** [comment]
Fixed as part of #2984
