### ISSUE TITLE
SDL incorrect update interior vehicle data for LIGHT RC module with OnInteriorVehicleData notification

### ISSUE THREAD

**Issue by aderiabin** [smartdevicelink/sdl_core#2988]
### Bug Report
SDL incorrect updates interior vehicle data cache for LIGHT RC module with OnInteriorVehicleData notification

##### Reproduction Steps
0.Precondition:
  1) SDL and HMI are started with App 1 and App 2 application data in LPT
  2) HMI sent LIGHT module capabilities to the SDL
  3) HMI has next data for LIGHT RC module:
``` [
{
      id = "READING_LIGHTS",
      status = "ON",
      density = 0.5,
      color = { red = 150, green = 200, blue = 250 }
    },
    {
      id = "AMBIENT_LIGHTS",
      status = "ON",
      density = 0.7,
      color = { red = 100, green = 100, blue = 100 }
    }
]
```
  3) Mobile is connected to the SDL
  4) App 1 and App 2 are registered and activated

1. Send correct "GetInteriorVehicleData"(moduleType = "LIGHT", subscribe = true) request from App 1 to the SDL
2. Update data of LIGHT RC module with  `id: "AMBIENT_LIGHTS"` on HMI:
 HMI sends OnInteriorVehicleData ( 
``` 
lightState = [
   {
      id = "AMBIENT_LIGHTS",
      status = "ON",
      density = 0.3,
      color = { red = 50, green = 150, blue = 120 }
    }
]
```
)
3. Send correct "GetInteriorVehicleData"(moduleType = "LIGHT") request from App 2 to the SDL

##### Expected Behavior
SDL responds on "GetInteriorVehicleData" to the App 2 with data:
```
lightState = [
    {
      id = "READING_LIGHTS",
      status = "ON",
      density = 0.5,
      color = { red = 150, green = 200, blue = 250 }
    },
    {
      id = "AMBIENT_LIGHTS",
      status = "ON",
      density = 0.3,
      color = { red = 50, green = 150, blue = 120 }
    }
]
```

##### Observed Behavior
SDL responds on "GetInteriorVehicleData" to the App 2 with data:
```
lightState = [
   {
      id = "AMBIENT_LIGHTS",
      status = "ON",
      density = 0.3,
      color = { red = 50, green = 150, blue = 120 }
    }
]
```

##### OS & Version Information
* OS/Version: Ubuntu 16.04 amd64
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/tree/develop (b7a3f9c)
* ATF: https://github.com/smartdevicelink/sdl_atf/tree/develop
* Test scripts: https://github.com/smartdevicelink/sdl_atf_test_scripts/commits/develop (b0cabdc)
##### Test Case, Sample Code, and / or Example App
[logs.tar.gz](https://github.com/smartdevicelink/sdl_core/files/3486704/logs.tar.gz)
[test_script.tar.gz](https://github.com/smartdevicelink/sdl_core/files/3486705/test_script.tar.gz)

**Comment by dboltovskyi** [comment]
@theresalech @jordynmackool Please notice PRs for `core` and `scripts` are ready for review

**Comment by AStasiuk** [comment]
@theresalech, @jacobkeeler could you please close this issue, if no additional action required?

**Comment by jacobkeeler** [comment]
Closing with the merge of #3017
