### ISSUE TITLE
engineOilLife parameter is missed for OnVehicleData notification in HMI_API.xml

### ISSUE THREAD

**Issue by GetmanetsIrina** [smartdevicelink/sdl_core#2992]
### Bug Report
`engineOilLife` parameter is missed for OnVehicleData notification in HMI_API.xml

##### Expected Behavior
All vehicle data requests in MOBILE_API.xml contain `engineOilLife` parameter, so OnVehicleData notification in HMI_API.xml also should contain `engineOilLife` parameter

##### Observed Behavior
`engineOilLife` parameter is missed for OnVehicleData notification in [HMI_API.xml](https://github.com/smartdevicelink/sdl_core/blob/038666ade2fda1164596568a8ab852b9db48036f/src/components/interfaces/HMI_API.xml#L6128)

##### OS & Version Information
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/commit/038666ade2fda1164596568a8ab852b9db48036f

**Comment by jacobkeeler** [comment]
Closed with the merge of #2977
