### ISSUE TITLE
SDL sends UPDATE_NEEDED even if app is not registered yet

### ISSUE THREAD

**Issue by dboltovskyi** [smartdevicelink/sdl_core#2995]
### Bug Report
SDL sends `UPDATE_NEEDED` even if app is not registered yet

##### Reproduction Steps
1. Make sure SDL is built in `EXTERNAL_PROPRIETARY` policy mode
2. Start SDL, HMI, connect Mobile device
3. Consent Mobile device

##### Expected Behavior
SDL does not send `SDL.OnStatusUpdate(UPDATE_NEEDED)` notification to HMI until app is successfully registered.

##### Observed Behavior
SDL sends `SDL.OnStatusUpdate(UPDATE_NEEDED)` just after device is consented

##### OS & Version Information
* OS/Version: Ubuntu 16.04 amd64
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/tree/develop (038666a)
* ATF: https://github.com/smartdevicelink/sdl_atf/tree/develop
* Testing Against: ATF (script, report and logs are in attachment)

##### Test Case, Sample Code, and / or Example App
[2019-08-22_12-29-15.tar.gz](https://github.com/smartdevicelink/sdl_core/files/3531054/2019-08-22_12-29-15.tar.gz)

**Comment by dboltovskyi** [comment]
@theresalech Please triage this issue.
It's not a regression one, though we propose to include it in 6.0 release since fix is simple and it has successfully passed full regression cycle.

**Comment by iCollin** [comment]
Closed via #3090
