### ISSUE TITLE
SDL doesn't WAKE_UP after LOW_VOLTAGE signal

### ISSUE THREAD

**Issue by dboltovskyi** [smartdevicelink/sdl_core#2996]
### Bug Report
SDL does not WAKE_UP after LOW_VOLTAGE signal

##### Reproduction Steps
1. Start SDL, HMI, connect Mobile, register App
2. Send `LOW_VOLTAGE` signal
3. Wait a few seconds and send `WAKE_UP` signal

##### Expected Behavior
SDL wakes up and starts resumption sequence

##### Observed Behavior
SDL doesn't wake up

##### OS & Version Information
* OS/Version: Ubuntu 16.04 amd64
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/tree/develop (8db0c26)
* ATF: https://github.com/smartdevicelink/sdl_atf/tree/develop
* Testing Against: ATF (script, report and logs are in attachment)

##### Test Case, Sample Code, and / or Example App
- [SDL5_0/low_voltage.txt](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/master/test_sets/SDL5_0/low_voltage.txt)
- [2019-08-23_10-17-50.tar.gz](https://github.com/smartdevicelink/sdl_core/files/3534944/2019-08-23_10-17-50.tar.gz)

**Comment by dboltovskyi** [comment]
This is regression issue which is introduced by fix for https://github.com/smartdevicelink/sdl_core/pull/2939

**Comment by dboltovskyi** [comment]
@theresalech Please triage this issue

**Comment by theresalech** [comment]
Closed via #3029
