### ISSUE TITLE
SDL doesn't activate app to FULL after unexpected disconnect in case of 2 apps

### ISSUE THREAD

**Issue by dboltovskyi** [smartdevicelink/sdl_core#2999]
### Bug Report
SDL doesn't activate app to FULL after unexpected disconnect in case of 2 apps
Note: Issue is also reproduced for Ignition Off/On cycle instead of unexpected disconnect

##### Reproduction Steps
1. Start SDL, HMI, connect Mobile, register App_1
2. App_1 activated to FULL
3. Mobile disconnected and re-connected
4. App_1 re-registered
5. App_2 registered
6. App_1 activated to FULL
7. App_2 activated to FULL
8. App_1 activated to FULL one more time

##### Expected Behavior
App_1 is activated to FULL

##### Observed Behavior
App_1 is not activated to FULL (HMI level became NONE)

##### OS & Version Information
* OS/Version: Ubuntu 16.04 amd64
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/tree/develop (c42cbc9)
* ATF: https://github.com/smartdevicelink/sdl_atf/tree/develop
* Testing Against: ATF (script, report and logs are in attachment)

##### Test Case, Sample Code, and / or Example App
- [2019-08-28_15-39-00.tar.gz](https://github.com/smartdevicelink/sdl_core/files/3552617/2019-08-28_15-39-00.tar.gz)

**Comment by theresalech** [comment]
@AByzhynar will you be submitting a fix for this issue?

**Comment by dboltovskyi** [comment]
@theresalech Yes, we're going to submit fix
