### ISSUE TITLE
SDL does not  resend Error GetVehicleData response from HMI

### ISSUE THREAD

**Issue by VjKlepikov** [smartdevicelink/sdl_core#3014]
### Bug Report
SDL does not  resend Error GetVehicleData response from HMI

##### Reproduction Steps
1. Start SDL, HMI, connect Mobile, register new App
2. Send GetVehicleData with speed = true
3. Send HMI response with {"error":{"code":9,"data":{"method":"VehicleInfo.GetVehicleData"},  message:"error message" },"id":57,"jsonrpc":"2.0"}

##### Expected Behavior
1) SDL sends to HMI VehicleInfo.GetVehicleData: "params":  { "speed":true }
2) SDL sends to mobile response of GetVehicleData with {"resultCode":"VEHICLE_DATA_NOT_AVAILABLE", "success":false, info = "error message"}

##### Observed Behavior
1) SDL sends to HMI VehicleInfo.GetVehicleData: "params":  { "speed":true }
2) SDL sends to mobile response of GetVehicleData with {"resultCode":"GENERIC_ERROR","success":false}

##### OS & Version Information
* OS/Version: OS/Version: Ubuntu 16.04 amd64
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/tree/develop (bc8288d)
* ATF: https://github.com/smartdevicelink/sdl_atf/tree/feature/script_runner (e4b9574)

##### Test Case, Sample Code, and / or Example App
[logs.tar.gz](https://github.com/smartdevicelink/sdl_core/files/3575404/logs.tar.gz)
[script.tar.gz](https://github.com/smartdevicelink/sdl_core/files/3580760/script.tar.gz)

**Comment by dboltovskyi** [comment]
Please notice this is regression issue was introduced by implementation of https://github.com/smartdevicelink/sdl_core/issues/2840

**Comment by dboltovskyi** [comment]
@theresalech Please triage this issue

**Comment by theresalech** [comment]
@dboltovskyi please advise when a fix has been submitted and we will review.

**Comment by dboltovskyi** [comment]
@theresalech Sure, our team is working on it now. I suppose it will be ready in a day or two.

**Comment by iCollin** [comment]
Closed with merge of #3016
