### ISSUE TITLE
SDL sends OnStatusUpdate(UPDATE_NEEDED) for existing app

### ISSUE THREAD

**Issue by dboltovskyi** [smartdevicelink/sdl_core#3026]
### Bug Report
SDL sends OnStatusUpdate(UPDATE_NEEDED) for existing app

##### Reproduction Steps
1. Start SDL, HMI, connect Mobile, register App
2. Perform successful PTU => `UP_TO_DATE`
3. Re-connect app

##### Expected Behavior
SDL doesn't send `OnStatusUpdate(UPDATE_NEEDED)` since app already has it's policies and previous status was `UP_TO_DATE`

##### Observed Behavior
SDL sends OnStatusUpdate(UPDATE_NEEDED)

##### OS & Version Information
* OS/Version: Ubuntu 16.04 amd64
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/tree/develop (2449d7e)
* ATF: https://github.com/smartdevicelink/sdl_atf/tree/develop
* Testing Against: ATF (script, report and logs are in attachment)

##### Test Case, Sample Code, and / or Example App
Failed scripts:
 - [SSLHandshakeFlow/015_Navi-Predefined_cert_valid_PTU_is_not_started](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Security/SSLHandshakeFlow/015_Navi-Predefined_cert_valid_PTU_is_not_started.lua)
 - [SSLHandshakeFlow/016_Non-Navi-Predefined_cert_valid_PTU_is_not_started](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Security/SSLHandshakeFlow/016_Non-Navi-Predefined_cert_valid_PTU_is_not_started.lua)
 - [Policies/build_options/109_ATF_PTU_Trigger_IGN_cycles_PROPRIETARY](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Policies/build_options/109_ATF_PTU_Trigger_IGN_cycles_PROPRIETARY.lua)

**Comment by dboltovskyi** [comment]
This is regression issue which is introduced by implementation of fix for https://github.com/smartdevicelink/sdl_core/issues/3019

**Comment by dboltovskyi** [comment]
@theresalech @jordynmackool Please triage this issue

**Comment by jordynmackool** [comment]
@mked-luxoft will do, please let us know once the PR is ready for Livio review!

**Comment by iCollin** [comment]
Closed with merge of #3035
