### ISSUE TITLE
[SDL 0249] Persisting HMI Capabilities specific to headunit

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_core#3037]
Proposal: [Persisting HMI Capabilities specific to headunit](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0249-Persisting-HMI-Capabilities-specific-to-headunit.md)

> This proposal is to change the way SDL Core initializes HMI capabilities for a headunit, which are used to communicate to apps/other SDL features.

Review: https://github.com/smartdevicelink/sdl_evolution/issues/816

**Comment by AStasiuk** [comment]
@theresalech is it necessary to add **proposal** label to this issue?

**Comment by theresalech** [comment]
Closed via #3397
