### ISSUE TITLE
Need help in BUILDING  sdl core on Android Platform

### ISSUE THREAD

**Issue by amitchaturvedi** [smartdevicelink/sdl_core#3041]
Working on a critical assignment where we need SDL core on ANdroid Platform.
Can you provide the necessary steps  to compile the same. It is very urgent since we want to integrate this ASAP.

Or if u can guide us how to build SDL core with NDK ?

Regards,
AMIT
Senior Architect

**Comment by jordynmackool** [comment]
Hi @amitchaturvedi, 

Please use the available documentation on our site to further assist you. If you have specific questions, please post them in the appropriate slack channels (http://slack.smartdevicelink.com) and someone from our team or from the SDL community will respond. 
 
- https://smartdevicelink.com/en/guides/hmi/overview/
- https://smartdevicelink.com/en/guides/core/overview/
- https://smartdevicelink.com/en/guides/android/getting-started/installation/

**Comment by amitchaturvedi** [comment]
Hi,
SDL core can only run on Linux platform as per content available on SDL website .
 "SDL core" support is not available for Android platform. 

I have a HU running on Android. I want to run SDL core on Android platform. Can you please let me know if we can run this SDL core on Android and what are the steps to build SDL core with Android platform

**Comment by jordynmackool** [comment]
@amitchaturvedi Please post your questions in slack for assistance. The sdl_core repo should only be used when reporting an issue or submitting a PR related to core.

**Comment by amitchaturvedi** [comment]
Provide the link for slack please..I will post my query there ..

**Comment by jordynmackool** [comment]
http://slack.smartdevicelink.com
