### ISSUE TITLE
SDL incorrectly handle iAP2 transport switching

### ISSUE THREAD

**Issue by dboltovskyi** [smartdevicelink/sdl_core#3044]
### Bug Report
SDL incorrectly handle iAP2 transport switching.
All 4 ATF test scripts for iAP2 transport switching functionality fails. 
Below is a description for one of them (`002`).

##### Reproduction Steps
1. SDL is built with BUILD_TEST = ON to enabled iAP2 BT/USB transport adapter emulation
2. Start SDL, HMI
3. Connect iAP2 Bluetooth mobile device and register App
4. App sends `SubscribeButton` for `PRESET_0` button (resume data)
  - SDL successfully registers application and notifies HMI and mobile
  - SDL->HMI: OnAppRegistered(params)
  - SDL->appID: SUCCESS, success:"true":RegisterAppInterface()
  - SDL->appID: SUCCESS, success:"true": SubscribeButtons()
  - SDL->appID: OnHashChange
5. Same iAP2 mobile device is connected over USB to system and re-registers within AppTransportChangeTimer timeout with wrong hashID

##### Expected Behavior
  - SDL successfully registers application and notifies mobile only with RAI response
  - SDL->appID: RESUME_FAILED, success:"true":RegisterAppInterface()
  - application remains registered internally
  - SDL does not send OnAppUnregistered notification to HMI
  - SDL does not send OnAppRegistered notification to HMI
  - SDL->HMI: Buttons.OnButtonSubscription, isSubscribed = false, name = PRESET_0

##### Observed Behavior
  - SDL does send OnAppRegistered notification to HMI
  - SDL sends OnButtonSubscription, isSubscribed = true

##### OS & Version Information
* OS/Version: Ubuntu 16.04 amd64
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/tree/develop (2449d7e)
* Testing Against: ATF (script, report and logs are in attachment)

##### Test Case, Sample Code, and / or Example App
 - Scripts: [iAP2TransportSwitch/*](https://github.com/smartdevicelink/sdl_atf_test_scripts/tree/develop/test_scripts/iAP2TransportSwitch)
 - Report and logs: [2019-09-23_11-20-03.tar.gz](https://github.com/smartdevicelink/sdl_core/files/3642870/2019-09-23_11-20-03.tar.gz)

**Comment by dboltovskyi** [comment]
This is follow up issue initially created in scripts repo https://github.com/smartdevicelink/sdl_atf_test_scripts/issues/2262 in order to track fix in `core`

**Comment by dboltovskyi** [comment]
@theresalech Please triage this issue and notice fix is already prepared in [PR3034](https://github.com/smartdevicelink/sdl_core/pull/3034) and already discussed with @JackLivio

**Comment by theresalech** [comment]
Closed via #3034
