### ISSUE TITLE
Undefined symbol encountered at launch time

### ISSUE THREAD

**Issue by mrapitis** [smartdevicelink/sdl_core#3063]
### Bug Report
When building and running the current develop branch of SDL core on Ubuntu 16.04 LTS, an undefined symbol is encountered as soon as the user attempts to launch SDL core.  Please see terminal output below:
``
markos@markos-Parrot:~/develop10-1/sdl_core/bin$ ./smartDeviceLinkCore 
./smartDeviceLinkCore: symbol lookup error: /home/markos/develop10-1/sdl_core/bin/libPolicy.so: undefined symbol: _ZN6policy19UpdateStatusManagerC1Ev
``
I have installed SDL core on a fresh Ubuntu 16.04 to confirm the undefined symbol is present in a clean environment.  The issue was introduced after the merge of #2840 (Read Generic Network Signal Data)
The error is not present when checking out and building the commit prior to the RGNSD implementation

##### Reproduction Steps

- Stand up an Ubuntu 16.04 LTS system

- Clone the SDL core repo and checkout commit 4566d5196109591fd3cc515826ecfc725c95c79b  - (this is the commit prior to #2840)
- Build SDL core and launch the binary
- Take note that SDL Core launches successfully with no errors
- Next checkout 0186b8c46584aa86e96f0bfa8c38e735c3f0ac0a which corresponds to the changes needed for #2840 
- Build SDL core and launch the binary
- Take note of the undefined symbol: _ZN6policy19UpdateStatusManagerC1Ev error.

Its not clear if additional dependencies were introduced with the implementation of #2840, however if they were it would be expected that the make / cmake process would have failed prior to build.  Its also important to note that a good number of make file changes were included in the RGNSD implementation.

##### Expected Behavior
SDL Core launches without symbol errors.

##### Observed Behavior
SDL Core launches then crashes due to symbol errors.

##### OS & Version Information
* OS/Version: Ubuntu 16.04 LTS
* SDL Core Version: Current develop branch
* Testing Against: SDL Core develop branch + Ubuntu 16.04

**Comment by JackLivio** [comment]
Issue reported fixed by author
