### ISSUE TITLE
 Resource allocation manager unit tests are not included in /resource_allocation_manager_tests testing binary .

### ISSUE THREAD

**Issue by IGapchuk** [smartdevicelink/sdl_core#3069]
### Bug Report
 Resource allocation manager unit tests are not included in /resource_allocation_manager_tests testing binary.

##### Reproduction Steps
1. Build project with UT
2. Run resource_allocation_manager_test.
(<build_folder>/src/components/application_manager/rpc_plugins/rc_rpc_plugin/test/resource_allocation_manager/resource_allocation_manager_test)

##### Expected Behavior
`resource_allocation_manager_test` successfully runs `29 tests from 1 test case` and marks result as `[PASSED].`

##### Observed Behavior
`resource_allocation_manager_test` successfully runs `0 tests from 0 test case`, but also marks result as `[PASSED]`.

##### OS & Version Information
* OS/Version: Ubuntu 18.04
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/tree/develop (2b09ea3adf962e25717b6b4cd751173f0aa40d02)

**Comment by dboltovskyi** [comment]
@theresalech Please triage this issue

**Comment by theresalech** [comment]
Closed via #3070
