### ISSUE TITLE
SDL does not set the app to NONE HMI level after a rejecting of StartService

### ISSUE THREAD

**Issue by GetmanetsIrina** [smartdevicelink/sdl_core#3073]
### Bug Report
SDL does not set the app to NONE HMI level after a rejecting of StartService

##### Precondition
1. HMI and SDL are started
2. Navigation app is registered and activated

##### Reproduction Steps
1. App requests start of the protected video/audio/rpc service
2. Protected service can't be started by any reason: invalid cert, invalid ptu, not successful response to GetSystemTime

##### Expected Behavior
1. SDL responds with NACK to mobile application
2. SDL sends BC.OnServiceUpdate(serviceEvent = "REQUEST_REJECTED") to HMI with the appropriate reason 
3. SDL sends BC.CloseApplication(appID)
4. SDL sets app to NONE HMI level and sends OnHMILevel(NONE) to mobile application 

##### Observed Behavior
SDL does not sent app to NONE HMI level and does not send the OnHMILevel(NONE) to mobile application 

##### OS & Version Information
* OS/Version: Ubuntu 18.04
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/commit/2b09ea3adf962e25717b6b4cd751173f0aa40d02
* HMI: https://github.com/smartdevicelink/sdl_hmi/tree/develop(1db5de1dfb5afbbbcdca266662faeb0d7d2050e4)
* SPT: https://rink.hockeyapp.net/apps/dbc7db5274027027262185753824e34d
* Scripts: https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/2280

Logs:
[2019-10-11_12-09-16.zip](https://github.com/smartdevicelink/sdl_core/files/3716733/2019-10-11_12-09-16.zip)

**Comment by GetmanetsIrina** [comment]
@theresalech, Please triage this issue.

**Comment by theresalech** [comment]
@GetmanetsIrina can you please advise if Luxoft anticipates submitting a PR to fix this issue?

**Comment by dboltovskyi** [comment]
@theresalech Yes, our team is going to prepare a fix.

**Comment by theresalech** [comment]
@dboltovskyi thank you!  Please let us know when it is ready for Livio review.

**Comment by dboltovskyi** [comment]
@theresalech Please notice both fixes in `core` and `scripts` are ready for review

**Comment by JackLivio** [comment]
Fixed by #3082
