### ISSUE TITLE
[SDL 0252] Aligning HMI and MOBILE API for pcmStreamCapabilities

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_core#3078]
Proposal: [Aligning HMI and MOBILE API for pcmStreamCapabilities](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0252-Aligning-HMI-and-MOBILE-API-for-pcmStreamCapabilities.md)

>This proposal is to add param `pcmStreamCapabilities` in `UI.GetCapabilities` response in HMI API.

Review: https://github.com/smartdevicelink/sdl_evolution/issues/829

Steering Committee Decision:

>The Steering Committee voted to accept this proposal with the following revision: change `pcmStreamCapabilities` to non-mandatory, as described in [this comment](https://github.com/smartdevicelink/sdl_evolution/issues/829#issuecomment-539505777).

> The proposal .md file was updated to reflect these revisions on 10/15/19.

**Comment by iCollin** [comment]
Closed via https://github.com/smartdevicelink/sdl_core/pull/3297
