### ISSUE TITLE
Core dump by ignition off after removing of custom vehicle data during PTU

### ISSUE THREAD

**Issue by GetmanetsIrina** [smartdevicelink/sdl_core#3079]
### Bug Report
Core dump by ignition off after removing of custom vehicle data during PTU

##### Reproduction Steps
1. App is registered and activated
2. custom_data_1 presets in DB
3. PTU is performed with removing custom_data_1
4. Ignition off is performed

##### Expected Behavior
SDL shuts down successful

##### Observed Behavior
Core dump
```
smartDeviceLinkCore: /home/jenkins/workspace/Release_6.0.0_SDL_NoUT_Proprietary/src/components/application_manager/rpc_plugins/vehicle_info_plugin/src/vehicle_info_plugin.cc:159: ns_smart_device_link::ns_smart_objects::SmartObjectSPtr vehicle_info_plugin::VehicleInfoPlugin::GetUnsubscribeIVIRequest(const std::vector<std::__cxx11::basic_string<char> >&): Assertion `(!key_name.empty())' failed.
log4cxx: No appender could be found for logger (ApplicationManager).
```

##### OS & Version Information
* OS/Version:Ubuntu 18.04
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/releases/tag/6.0.0_RC ( 2b09ea3 )
* ATF: [develop](https://github.com/smartdevicelink/sdl_atf/tree/develop)
* Script: https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/API/VehicleData/GenericNetworkSignalData/036_Subscribtion_after_removing_VD_from_permissions.lua

##### Log
[SmartDeviceLinkCore.zip](https://github.com/smartdevicelink/sdl_core/files/3733576/SmartDeviceLinkCore.zip)

**Comment by GetmanetsIrina** [comment]
@theresalech, Please triage this issue.
Luxoft team is going to prepare a fix.

**Comment by dboltovskyi** [comment]
@theresalech Please notice fix for core and updates for scripts are ready for review.

**Comment by ShobhitAd** [comment]
Closing with merge of #3081
