### ISSUE TITLE
SDL does not send REQUEST REJECTED notification to HMI in case of App start streaming from NONE level

### ISSUE THREAD

**Issue by TMyza** [smartdevicelink/sdl_core#3093]
### Bug Report
SDL does not send REQUEST REJECTED notification to HMI in case of App start streaming from NONE level

##### Reproduction Steps
1. HMI and SDL are started
2. Navigation app is registered and not activated
3. App start streaming

##### Expected Behavior
SDL sends NACK and EndVideoStream to App
SDL sends BC.OnServiceUpdate(REQUEST_REJECTED) notification to HMI

##### Observed Behavior
SDL sends NACK and EndVideoStream to App 
SDL does not send BC.OnServiceUpdate(REQUEST_REJECTED) notification to HMI

##### OS & Version Information
* OS/Version: Ubuntu 16.04
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/commit/2b09ea3adf962e25717b6b4cd751173f0aa40d02
* HMI: https://github.com/smartdevicelink/sdl_hmi/tree/develop(1db5de1dfb5afbbbcdca266662faeb0d7d2050e4)
* SPT: 20181116-Nightly-Android(1014)
* Scripts: https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/2288

##### Test Case, Sample Code, and / or Example App
[SmartDeviceLinkCore.log](https://github.com/smartdevicelink/sdl_core/files/3749521/SmartDeviceLinkCore.log)

**Comment by dboltovskyi** [comment]
@theresalech Please notice fixes in `core` and `scripts` are ready for review

**Comment by iCollin** [comment]
Closed via #3095
