### ISSUE TITLE
Application does not retrieve subscriptions to app service after resumption 

### ISSUE THREAD

**Issue by YarikMamykin** [smartdevicelink/sdl_core#3096]
### Bug Report
Application does not retrieve subscriptions to app service after resumption.

##### Reproduction Steps
1. Register application
2. Subscribe application to app service(s)
3. Perform unexpected disconnect
4. Perform resumption

##### Expected Behavior
After resumption application retrieves all its subscriptions to app service(s)

##### Observed Behavior
After resumption application **does not** retrieve all its subscriptions to app service(s)

##### OS & Version Information
* OS/Version: [Ubuntu 18.04]
* SDL Core Version: [https://github.com/smartdevicelink/sdl_core/tree/develop](url)
* Testing Against: ATF test scripts + UT
* Scripts: https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/2289

**Comment by dboltovskyi** [comment]
@theresalech Please triage this issue.
Fixes in `core` and `scripts` are ready for review.

**Comment by ShobhitAd** [comment]
Closing with the merge of https://github.com/smartdevicelink/sdl_core/pull/3097
