### ISSUE TITLE
SDL Crash - SegFault during execution of transport_manager unit tests

### ISSUE THREAD

**Issue by AByzhynar** [smartdevicelink/sdl_core#3110]
### Bug Report
SDL crashed during app registration

##### Occurrence:
Sometimes

##### Reproduction Steps
1. Build SDL Core with "BUILD_TESTS=On" option
2. Run Transport Manager Unit tests

##### Expected Behavior
All unit tests are PASSED

##### Observed Behavior
SDL crashed during transport manager unit tests

##### OS & Version Information
* OS/Version: Ubuntu 16.04
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/releases/tag/6.0.0_RC2 ( 4d283e )

##### Attachments
  - build log: [build_log.txt.tar.gz](https://github.com/smartdevicelink/sdl_core/files/3793577/build_log.txt.tar.gz)
  - corefile: [coredump.tar.gz](https://github.com/smartdevicelink/sdl_core/files/3793578/coredump.tar.gz)

**Comment by AByzhynar** [comment]
After issue analysis - it appears that the problem is in the SDL code but not in unit tests. The problem is that after TM destruction - one thread which has created usb devices (as well as used file descriptors for them) is in lock state. Thus this thread does not free acquired resources. Threfore when the tests run multiple times - OS has no free dile descriptors - as result we got core crash.

**Comment by theresalech** [comment]
@dboltovskyi please let us know once your additional analysis is complete, and we'll review.  Thanks!

**Comment by theresalech** [comment]
@AStasiuk @dboltovskyi are you still investigating this issue?  Do you have plans to submit a fix for Livio review?

**Comment by dboltovskyi** [comment]
@theresalech Yes, we're testing a potential fix now. We will notify PM once PR is ready for review.

**Comment by dboltovskyi** [comment]
@theresalech Please notice fix in https://github.com/smartdevicelink/sdl_core/pull/3121 is ready for PM review.

Please take into account this fix reveals two other issues:
 - https://github.com/smartdevicelink/sdl_core/issues/2465
 - https://github.com/smartdevicelink/sdl_core/issues/3118

Fixes for them going to be provided in separate PRs

**Comment by theresalech** [comment]
Closed via #3121
