### ISSUE TITLE
SDL switches applications into incorrect HMILevel after IGNITION_OFF/IGNITION_ON cycle

### ISSUE THREAD

**Issue by IGapchuk** [smartdevicelink/sdl_core#3111]
### Bug Report
There is an issue when SDL switches applications into incorrect HMILevel after IGNITION_OF/IGNITION_ON cycle.

##### Reproduction Steps
1. SDL and WebHMI are successfully started.
2. Register and activate App1 (SDL switches App1 into HMILevel::FULL).
3. Register and activate App2 (SDL switches App2 into HMILevel::FULL and switches App1 into HMILevel::BACKGROUND).
4. Send "BasicCommunication.OnExitAllApplications","params":{"reason":"IGNITION_OFF"} from WebHMI.
5. SDL is stopped successfully.
6. Start SDL (the new ignition cycle).
7. SDL and WebHMI are successfully started.
8. Register App1
9. Wait some time ~1sec
10. Register App2 
11. SDL starts resumption.
12. App1 is registered and does not resume the level because the  `BACKGROUND` level should not be resumed, so app is set to default HMI level (NONE)
13. App2 is registered and resumes HMI level FULL
14. Activate App1 manually from HMI after resumption is finished.

##### Expected Behavior
App1 is set to FULL HMI level and App2 is switched to BACKGROUND HMI level

##### Observed Behavior
1. HMI sends SDL.ActivateApp(appIs of App1)
2. SDL responds with success result code, but does not set app to FULL HMI level
3. There is no ability to change HMI level of App1 from NONE to something else.
Note: HMI level can be changes only after reregistration of App1

##### OS & Version Information
* OS/Version: Ubuntu 18.04
* SDL Core Version: release/6.0.0 (4d283e625dfa09d166d572fa7bf6e98e91f05050)
* WebHMI: develop (https://github.com/smartdevicelink/sdl_hmi/commit/bd53f11339ee4d95a41caf5e5edf4ae0839d5957)

SDL log: 
  - [SmartDeviceLinkCore.log.tar.gz](https://github.com/smartdevicelink/sdl_core/files/3797531/SmartDeviceLinkCore.log.tar.gz)
  - WebHMI log: [HMI_log.log.tar.gz](https://github.com/smartdevicelink/sdl_core/files/3797533/HMI_log.log.tar.gz)
  - Script: [GH-3111.lua.tar.gz](https://github.com/smartdevicelink/sdl_core/files/3801273/GH-3111.lua.tar.gz)

**Comment by JackLivio** [comment]
@IGapchuk Thank you for noting this issue. Were both apps located on the same device?

**Comment by IGapchuk** [comment]
@JackLivio Yes, both applications were located on the same device. We've retested the same test case from two devices and the result is the same. Appropriate logs are attached.
[InCorrectHMILevel_two_devices.tar.gz](https://github.com/smartdevicelink/sdl_core/files/3798275/InCorrectHMILevel_two_devices.tar.gz)

**Comment by dboltovskyi** [comment]
It seems issue was introduced with merge of https://github.com/smartdevicelink/sdl_core/pull/2980

**Comment by dboltovskyi** [comment]
Appropriate ATF script is attached and mentioned in description

**Comment by JackLivio** [comment]
This issue is not reproducible when I try it manually. I am using most recent master branches of SDL Core and SDL HMI.

After I restart Core and HMI, the first app that registers is not put into full. When I register the second app, the second app is resumed into full. I am observing the correct behavior.

**Comment by dboltovskyi** [comment]
@JackLivio Please notice after Ignition cycle 1st app needs to be activated and deactivated withing 3 sec timeout
This is default duration before SDL starts resumption of apps' HMI levels (in .INI this is `ApplicationResumingTimeout` parameter)

**Comment by theresalech** [comment]
Closed via #3117
