### ISSUE TITLE
SDL doesn't populate displayCapabilities in RAI response with default values if HMI doesn't provide UI.GetCapabilities

### ISSUE THREAD

**Issue by dboltovskyi** [smartdevicelink/sdl_core#3113]
### Bug Report
SDL doesn't populate `displayCapabilities` in RAI response with default values if HMI doesn't provide UI.GetCapabilities

##### Reproduction Steps
1. Start SDL, Web-HMI, 
Make sure Web-HMI doesn't not provide `UI.GetCapabilities` response to SDL
2. Connect Mobile device and register new application
```
App->SDL: RegisterAppInterface(...) request
SDL->App: RegisterAppInterface(...) response
```

##### Expected Behavior
SDL populates `displayCapabilities` in RAI response with default ones (defined in `hmi_capabilities.json`)

##### Observed Behavior
SDL doesn't provide `displayCapabilities` in RAI response

##### OS & Version Information
* OS/Version: Ubuntu 16.04
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/tree/release/6.0.0 (4d283e6)
* Testing Against: ATF

##### Test Case, Sample Code, and / or Example App
  - Script: [GH-3113.lua.tar.gz](https://github.com/smartdevicelink/sdl_core/files/3809648/GH-3113.lua.tar.gz)
  - Reports and logs: [2019-11-05_10-13-28.tar.gz](https://github.com/smartdevicelink/sdl_core/files/3809650/2019-11-05_10-13-28.tar.gz)

**Comment by iCollin** [comment]
Closed via #3128
