### ISSUE TITLE
SDL Crash - SIGABRT during execution of transport_manager unit tests

### ISSUE THREAD

**Issue by SNiukalov** [smartdevicelink/sdl_core#3118]
### Bug Report
SDL crashed during TcpServerOriginatedSocketConnection destroy

##### Occurrence:
on OS/Version: Ubuntu 18.04.3 reproducible 1/20000 times

##### This issue can be reproduced after https://github.com/smartdevicelink/sdl_core/issues/3110 fix
1. Build SDL Core with "BUILD_TESTS=On" option
2. Run Transport Manager Unit tests with --gtest_repeat=20000

##### Expected Behavior
All unit tests are PASSED

##### Observed Behavior
SDL crashed during transport manager unit tests

##### OS & Version Information
* OS/Version: Ubuntu 18.04.3
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/releases/tag/6.0.0

##### Attachments
  - backtrace:[backtrace.zip](https://github.com/smartdevicelink/sdl_core/files/3819520/backtrace.zip)
  - corefile:[core.1000.Socket unique_t.zip](https://github.com/smartdevicelink/sdl_core/files/3819519/core.1000.Socket.unique_t.zip)

**Comment by jacobkeeler** [comment]
Closing with the merge of #3134
