### ISSUE TITLE
[SDL 0260] Deprecate HMI RPC OnFindApplications

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_core#3125]
Proposal: [Deprecate HMI RPC OnFindApplications](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0260-Deprecate-HMI-RPC-OnFindApplications.md)

> This proposal is for deprecating and removing an unusable HMI RPC `OnFindApplications`.

Review: https://github.com/smartdevicelink/sdl_evolution/issues/860

**Comment by iCollin** [comment]
Closed via #3451
