### ISSUE TITLE
CCB: SmartDeviceLink crash SIGABRT in file_system::DirectorySize 

### ISSUE THREAD

**Issue by VjKlepikov** [smartdevicelink/sdl_core#3131]
### Bug Report
SmartDeviceLink crashed during SetAppIcon :file_system::

#### Linked issues from CCB list
- Potential fix for a core crash in SetAppIcon object 
- More potentially dangerous places fixes 

##### Reproduction Steps
1. Start SDL, HMI, connect Mobile
2. Register new app

##### Expected Behavior
1. App registered successfully

##### Observed Behavior
1. SDL crashed during SetAppIcon

##### OS & Version Information
OS/Version: Ubuntu 16.04
SDL Core Version: https://github.com/AByzhynar/sdl_core/tree/fix/SegFault_in_TransportManagerDefault_unit_tests (a47127) on base https://github.com/smartdevicelink/sdl_core/tree/release/6.0.1 (60b57cd)
HMI: https://github.com/smartdevicelink/sdl_hmi/tree/develop (91d5940)
Mobile Apps: SPT(20191112)
Transport: USB/WiFi
Testing : Manually

##### Attachments
[Core_dump.zip](https://github.com/smartdevicelink/sdl_core/files/3879507/Core_dump.zip)
[SDL.zip](https://github.com/smartdevicelink/sdl_core/files/3879508/SDL.zip)
[StackTrace.zip](https://github.com/smartdevicelink/sdl_core/files/3879509/StackTrace.zip)
[HMI_log.zip](https://github.com/smartdevicelink/sdl_core/files/3879512/HMI_log.zip)

**Comment by jacobkeeler** [comment]
Closing with the merge of #3145
