### ISSUE TITLE
CCB:  Fix undefined behavior after SO cleanup 

### ISSUE THREAD

**Issue by SNiukalov** [smartdevicelink/sdl_core#3135]
### Bug Report
SDL crash in the random places.

##### Reproduction Steps
This issue is often observed during cable unplug
while audio/video streaming is active.

##### Expected Behavior
SDL no crashes

##### Observed Behavior
SDL crash in the random places.

#### OS & Version Information

OS/Version: Ubuntu 16.04
SDL Core Version: https://github.com/smartdevicelink/sdl_core/tree/develop (e137556512215ded94228e33d21ab4c3e1af3017)
Testing : Unit tests

**Comment by iCollin** [comment]
Closed via #3116 and #3146
