### ISSUE TITLE
SDL does not start the new PTU after a failed retry sequence in case some trigger occurs during the retry sequence

### ISSUE THREAD

**Issue by GetmanetsIrina** [smartdevicelink/sdl_core#3136]
### Bug Report
SDL does not start the new PTU after a failed retry sequence in case some trigger occurs during the retry sequence

##### Reproduction Steps
1. New App1 is registered
2. SDL starts the PTU
3. Mobile app receives `BC.OnSystemRequest` notification but not provide the update
4. SDL starts the retry sequence
5. App2 is registered during retry sequence

##### Expected Behavior
After retry sequence is finished SDL sends `SDL.OnStatusUpdate(UPDATE_NEEDED)` notification to HMI and then `BC.PolicyUpdate` request to HMI to start the new PTU sequence after retry.

##### Observed Behavior
SDL does not send `BC.PolicyUpdate` request to HMI after retry sequence

##### OS & Version Information
* OS/Version: Ubuntu 18.04
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/commit/891497bc9fb23434242dbe92e1f13dd1273fcb21
* ATF: https://github.com/smartdevicelink/sdl_atf/commit/37da7aba8929e14dbd692befdea8540c5dd1dbbb
* Script: TBA

##### Logs
TBA

**Comment by theresalech** [comment]
Closed via #3208
