### ISSUE TITLE
Sometimes SDL sends BasicCommunication.PolicyUpdate twice

### ISSUE THREAD

**Issue by LitvinenkoIra** [smartdevicelink/sdl_core#3138]
### Bug Report
SDL sends BasicCommunication.PolicyUpdate twice

##### Occurrences:
Sometimes (5%) 

##### Reproduction Steps
1. SDL is built with EXTERNAL_PROPRIETARY policy flag
2. HMI and SDL are started
3. App is registered and activated

##### Expected Behavior
SDL->HMI: BasicCommunication.PolicyUpdate

##### Observed Behavior
SDL send BasicCommunication.PolicyUpdate twice

##### OS & Version Information
* OS/Version: Ubuntu 18.04
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/commit/891497bc9fb23434242dbe92e1f13dd1273fcb21
* ATF: https://github.com/smartdevicelink/sdl_atf/commit/37da7aba8929e14dbd692befdea8540c5dd1dbbb
* Script: [308_ATF_Check_app_registration_language_gui.zip](https://github.com/smartdevicelink/sdl_core/files/3887258/308_ATF_Check_app_registration_language_gui.zip)

##### Logs
[BC.PolicyUpdate_twice.zip](https://github.com/smartdevicelink/sdl_core/files/3887247/BC.PolicyUpdate_twice.zip)

**Comment by JackLivio** [comment]
Fixed by #3203
