### ISSUE TITLE
SDL does not stops streaming from mobile app with NOT_STREAMABLE state

### ISSUE THREAD

**Issue by mkorniichuk** [smartdevicelink/sdl_core#3139]
### Bug Report
SDL keeps processing video streaming data from an application with **NOT_STREAMABLE** streaming state.

##### Reproduction Steps
1. Register Navigation and Projection applications
2. Activate Navigation app and start streaming
3. Activate Projection app: Navigation app should receive **LIMITED** HMI level and **NOT_STREAMABLE** state. 
**!NOTE**: Navigation app keeps streaming

##### Expected Behavior
After timeout expires, SDL unregisters Navigation application with **PROTOCOL_VIOLATION** reason

##### Observed Behavior
SDL keeps processing stream from Navigation application

##### OS & Version Information
* OS/Version: Ubuntu 18.04
* SDL Core Version: develop (891497bc9fb23434242dbe92e1f13dd1273fcb21)
* Testing Against: WebHMI [91d5940](https://github.com/smartdevicelink/sdl_hmi/tree/91d59402b8e0967f9a3532b2cf3f2537ee068b95)

**Comment by ShobhitAd** [comment]
Closing with merge of https://github.com/smartdevicelink/sdl_core/pull/3151
