### ISSUE TITLE
SDL unregister streaming app if it's deactivated/activated during `StopStreamingTimeout`

### ISSUE THREAD

**Issue by mkorniichuk** [smartdevicelink/sdl_core#3140]
### Bug Report
SDL unregister streaming app if it's deactivated/activated during `StopStreamingTimeout`

##### Reproduction Steps
1. Set StopStreamingTimeout = 3000 in SDL .INI file
2. Start SDL, HMI, connect Mobile device
3. Register 2 NAVIGATION applications: App_1 and App_2 
4. Activate App_1 and start Video streaming
=> SDL starts streaming successfully
5. Deactivate App_1 and activate App_2
=> SDL stops streaming successfully
6. Deactivate App_2, activate App_1 and start Video streaming (within `StopStreamingTimeout`)
-- 

##### Expected Behavior
SDL does not send `OnAppInterfaceUnregistered` notification to App_1 and `BC.OnAppUnregistered` notification to HMI

##### Observed Behavior
SDL unregisters App_1 with `PROTOCOL_VIOLATION` reason once `StopStreamingTimeout` expires

##### OS & Version Information
* OS/Version: Ubuntu 18.04
* SDL Core Version: develop (891497bc9fb23434242dbe92e1f13dd1273fcb21)
* Testing Against: ATF

**Comment by dboltovskyi** [comment]
I seems issue is related to pure connection.
In case if Video packet is not received by SDL during 1 sec (defined by `VideoDataStoppedTimeout` .ini parameter) SDL sends `Navigation.OnVideoDataStreaming {"available" = false}`
Once new packet is received SDL sends `Navigation.OnVideoDataStreaming {"available" = true}`

**Comment by dboltovskyi** [comment]
Description is corrected, issue is reopened

**Comment by dboltovskyi** [comment]
@theresalech Please triage this issue

**Comment by theresalech** [comment]
@dboltovskyi this issue has not yet been raised to the Steering Committee as priority for the upcoming Core release.  We can work to include if time allows, but would recommend raising as priority in the Steering Committee meeting if it's imperative the issue be included.  Thanks!

**Comment by iCollin** [comment]
Closed via #3202
