### ISSUE TITLE
SDL sends misplaced OnVideoDataStreaming notification

### ISSUE THREAD

**Issue by mkorniichuk** [smartdevicelink/sdl_core#3142]
### Bug Report
SDL sends misplaced OnVideoDataStreaming notification which leads to a video streaming issue on HMI

##### Reproduction Steps
1. Register 2 Navigation apps
2. Activate 1st app and start streaming
3. Activate 2nd app and start streaming.
4. `Navigation.OnVideoDataStreaming { "available" = true }` is sent to HMI
5. 1st app obtains `NOT_STREAMABLE` state but keeps sending data. Since timeout is not yet expired, the application is not yet unregistered. But the stream is suspended.

##### Expected Behavior
SDL provides HMI with streaming data from 2nd application and keeps streaming from 1st application suspended.
No extra notifications are sent to HMI.

##### Observed Behavior
SDL sends `OnVideoDataStreaming { "available" = false }` notification to HMI. 
Though, 1st application keeps streaming. And this notification could cause streaming issue on HMI.

##### OS & Version Information
* OS/Version: Ubuntu 18.04
* SDL Core Version: develop (891497bc9fb23434242dbe92e1f13dd1273fcb21)
* Testing Against: WebHMI [91d5940](https://github.com/smartdevicelink/sdl_hmi/tree/91d59402b8e0967f9a3532b2cf3f2537ee068b95)

**Comment by ShobhitAd** [comment]
Closing with merge of https://github.com/smartdevicelink/sdl_core/pull/3154
