### ISSUE TITLE
SDL doesn't increment 'count_of_rejections_duplicate_name' counter

### ISSUE THREAD

**Issue by dboltovskyi** [smartdevicelink/sdl_core#3144]
### Bug Report
SDL doesn't increment 'count_of_rejections_duplicate_name' counter

##### Reproduction Steps
0. Make sure SDL is built with `EXTERNAL_PROPRIETARY` policy mode
1. Start SDL, HMI, connect Mobile
2. Register App_1 with name, e.g. `Test App`
3. Register App_2 with another name
4. Unregister App_2
5. Register App_2 one more time with name `Test App`

##### Expected Behavior
SDL rejects App_2 with `DUPLICATE_NAME` result code and increment `count_of_rejections_duplicate_name` counter

##### Observed Behavior
SDL rejects App_2 with `DUPLICATE_NAME` result code and does not increment counter

##### OS & Version Information
* OS/Version: Ubuntu 16.04
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/tree/develop (e137556)
* Testing Against: ATF

##### Test Case, Sample Code, and / or Example App
 - Script: https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/2295
 - Report & logs: [2019-11-25_14-29-16.tar.gz](https://github.com/smartdevicelink/sdl_core/files/3888357/2019-11-25_14-29-16.tar.gz)

**Comment by dboltovskyi** [comment]
@theresalech Please triage this issue

**Comment by jordynmackool** [comment]
@dboltovskyi, are you planning on submitting a PR for this issue?

**Comment by dboltovskyi** [comment]
@jordynmackool Yes, we're planning to open PR with fix

**Comment by jordynmackool** [comment]
@dboltovskyi please inform us when the PR is ready for Livio review.

**Comment by dboltovskyi** [comment]
@theresalech Please notice all required updates are ready for PM review:
 - core: 
https://github.com/smartdevicelink/sdl_core/pull/3147
 - scripts:
  https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/2295
  https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/2299

**Comment by iCollin** [comment]
Closed via #3147
