### ISSUE TITLE
SDL Core crash after quickly and repeatedly connect/disconnect USB cable

### ISSUE THREAD

**Issue by zhouxin627** [smartdevicelink/sdl_core#3149]
##### Bug Report
SDL Core crash after quickly and repeatedly connect/disconnect the USB cable

##### Preconditions
Install more than 3 SDL apps on the phone

##### Reproduction Steps
Quickly and repeatedly connect/disconnect USB cable

##### Expected Behavior
SDL core should not crash

##### Observed Behavior
SDL Core crash after quickly and repeatedly connect/disconnect the USB cable.

The reason seems to be that AM Pool is not thread-safe, it is possible to use the Object just removed when users quickly and repeatedly connect/disconnect the USB cable. 
Please refer to the attached logs for further details.

`src/components/application_manager/src/policies/policy_handler.cc`

##### OS & Version Information
* iOS Version:10.2
* SDL iOS Version:6.3.0
* Android Version: Android 9
* SDL Android Version: 4.9.0
* Testing Against: SDL Core 5.1.3 + HMI running on our development environment.

##### Occurrence
10%

##### Recovery Method
Acc off/on

##### Test Case, Sample Code, and / or Example App
Logs:logs.txt
[logs.txt](https://github.com/smartdevicelink/sdl_core/files/3903624/logs.txt)

**Comment by E-SAITO-TMC** [comment]
This is one of the issues that Toyota reported at the 11/18 Roadmap workshop.

**Comment by theresalech** [comment]
@E-SAITO-TMC is the Toyota team working on a fix for this issue? If so, can you please let us know when the fix will be ready for Livio review?

**Comment by E-SAITO-TMC** [comment]
@theresalech 
I'm sorry, I found a bug.
It has not been fixed yet.
We will let you know when a solution is found.

**Comment by JackLivio** [comment]
resolved by #3230
