### ISSUE TITLE
CCB: Fix crash in WebsocketSession on start 

### ISSUE THREAD

**Issue by SNiukalov** [smartdevicelink/sdl_core#3150]
### Bug Report
SDL crashed after starting WebHMI

##### Reproduction Steps
1. Start 'SmartDeviceLink'
2. Start sdl_hmi 'chromium-browser index.html'
3. Wait for interact between SDL and HMI
4. Try above steps multiple times.

##### Expected Behavior
SDL no crashes

##### Observed Behavior
SDL crashed

#### OS & Version Information

OS/Version: Ubuntu 16.04
SDL Core Version: https://github.com/smartdevicelink/sdl_core/tree/develop (e137556512215ded94228e33d21ab4c3e1af3017)

**Comment by iCollin** [comment]
Closed via #3191
