### ISSUE TITLE
[SDL 0262] New vehicle data SeatOccupancy

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_core#3152]
Proposal: [New vehicle data SeatOccupancy](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0262-New-vehicle-data-SeatOccupancy.md)

> This proposal is to add new vehicle data `SeatOccupancy` to know if a vehicle seat is occupied and belted.

Review: https://github.com/smartdevicelink/sdl_evolution/issues/870

Steering Committee Decision:

> The Steering Committee voted to accept this proposal with the following revision: update `SeatOccupancy` parameter description to "Seat status array containing the location and whether the seats are belted."

> The proposal .md file was updated to reflect these revisions on 12/4/19.

**Comment by jacobkeeler** [comment]
closing with the merge of #3152
