### ISSUE TITLE
[SDL 0265] Remove duplicate parameter FileName from HMI RPC BasicCommunication.OnPutFile

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_core#3153]
Proposal: [Remove duplicate parameter FileName from HMI RPC BasicCommunication.OnPutFile](https://github.com/smartdevicelink/sdl_evolution/tree/master/proposals/0265-Remove-Duplicate-Parameter-HMI-RPC-OnPutFile.md)

> This proposal is for removing the duplicate parameter `FileName` from the HMI RPC `BasicCommunication.OnPutFile`.

Review: https://github.com/smartdevicelink/sdl_evolution/issues/873

**Comment by iCollin** [comment]
Closed via https://github.com/smartdevicelink/sdl_core/pull/3850
