### ISSUE TITLE
CCB: Fixed core crash on accesing the application pointer

### ISSUE THREAD

**Issue by LitvinenkoIra** [smartdevicelink/sdl_core#3156]
### Bug Report
iOS switch from BT to USB is causing SDL to crash

### Detailed analysis:
App pointer check missing from ApplyPostponedStateForApp() function.

##### Reproduction Steps
1. Start SDL, HMI, connect Mobile
2. iOS initially paired to B/T
3. Launch SYNC Proxy Tester
4. Go to Apps Page
5. Connect Same iOS device via USB
6. Observe behavior

##### Expected Behavior
SDL should not crash

##### Observed Behavior
When Apps un-register and re-register over USB, SDL is crashing

#### Occurrence: 
Random

#### OS & Version Information
* OS/Version : SYNC4
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/releases/tag/5.0.1 
* Testing Against: SYNC4 Applink

**Comment by LitvinenkoIra** [comment]
[sdl crash 2.zip](https://github.com/smartdevicelink/sdl_core/files/3945736/sdl.crash.2.zip)

**Comment by JackLivio** [comment]
Fixed with merge of #3194
