### ISSUE TITLE
CCB: Remove direct usage of applications_ instance 

### ISSUE THREAD

**Issue by LitvinenkoIra** [smartdevicelink/sdl_core#3157]
### Bug Report
iOS switch from BT to USB is causing SDL to crash

### Detailed analysis:
This is a bad practice to use applications_ element directly as it is protected with own lock and there is a separate function that provides a data accessor for work with this element. Also was noticed that in some cases applications_ list was used without acquiring its lock what can cause a data races. To avoid such issues, AM implementation should be changed to work with
applications_ list only via accessor which guarantees a thread-safe access to this list and its elements.

##### Reproduction Steps
1. Start SDL, HMI, connect Mobile
2. iPhone is connected to SYNC via BT/USB
3. Multiple testing and commercial Apps are registered to SYNC.
4. Perform multiple RPC scenarios with multiple devices(Android BT, IOS BT, IOS USB)
5. Observe behavior

##### Expected Behavior
SDL should not crash

##### Observed Behavior
SDL is crashing

#### Occurrence: 
10/10

#### OS & Version Information
* OS/Version : SYNC4
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/releases/tag/5.0.1 
* Testing Against: SYNC4 Applink

**Comment by AKalinich-Luxoft** [comment]
@theresalech fix has been submitted and ready for Livio review
