### ISSUE TITLE
CCB: Fixing deadlock during transport switching

### ISSUE THREAD

**Issue by LitvinenkoIra** [smartdevicelink/sdl_core#3158]
### Bug Report
SDL crash observed when iPhone device is connected via BT over Wifi and later connected via USB

### Detailed analysis:
IsAppInReconnectMode acquires the reregister_wait_list_lock_ and also OnDeviceSwitchingStart/OnDeviceSwitchingFinish acquires the same reregister_wait_list_lock_.
The situation posible when threadX implicitly acquire reregister_wait_list_lock_ via calling IsAppInReconnectMode during responce senging from RequestController::onTimer and waiting_for_response_.
The threadY can call OnDeviceSwitchingStart/OnDeviceSwitchingFinish at the same time and acquire reregister_wait_list_lock_ and waiting for opportunity to acquire waiting_for_response_.

##### Reproduction Steps
1. Start SDL, HMI, connect Mobile
2. iPhone is connected to the SYNC via BT over Wifi
3. SyncProxyTester(Navigation/Projection) App is registered to SYNC
4. Select Apps from Status/Interaction bar and Select SyncProxyTester app
5. From iPhone select Menu -> AV Streaming -> Start Video
6. Connect iPhone via USB
7. Disconnect USB, and wait for all apps to re-register.
8. Connect iPhone via USB again.
9. Observe the HMI behavior.

##### Expected Behavior
Apps should register to SYNC

##### Observed Behavior
Apps doesnot register to SYNC.
SDL is crashing

#### Occurrence: 
10/10

#### OS & Version Information
* OS/Version : SYNC4
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/releases/tag/5.0.1 
* Testing Against: SYNC4 Applink

**Comment by iCollin** [comment]
Closed via #3215
