### ISSUE TITLE
CCB: Add initialization of protocol so factory

### ISSUE THREAD

**Issue by LitvinenkoIra** [smartdevicelink/sdl_core#3159]
### Bug Report
SDL crashed while testing Projection video rendering

### Detailed analysis:
Core crash appeared during attachSchema call from v4_protocol_so_factory
This happened in rpc_handler_impl.cc with V1 protocol RPCHanddler is using v4_protocol_so_factory from application manager but app manager didn't initialize v4_protocol_so_factory

##### Reproduction Steps
1. Start SDL, HMI, connect Mobile
2. iPhone is connected to the SYNC via USB
3. When Apps are loaded Select any Navigation App

##### Expected Behavior
SDL should not crash

##### Observed Behavior
SDL crashed

#### OS & Version Information
* OS/Version : SYNC4
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/releases/tag/5.0.1 
* Testing Against: SYNC4 Applink

**Comment by AKalinich-Luxoft** [comment]
Not applicable to OpenSDL: this issue is not actual for OpenSDL as it has different architecture design and such changes are not required. Application manager does not contain v4 protocol factory as well.
