### ISSUE TITLE
CCB: Fix streamer activity in case of suspend

### ISSUE THREAD

**Issue by LitvinenkoIra** [smartdevicelink/sdl_core#3160]
### Bug Report
SDL stops streaming data by timeout when no new data from mobile received

### Detailed analysis:
The problem of the current implementation is that SDL kills streaming thread responsible for sending a/v streaming data to HMI when streaming timeout expires.
This issue is observed when mobile app dumps 10-seconds audio file to SDL during 2 seconds and after that app does not send any data. In that case, HMI will play audio file during 2 seconds + timeout = 5 seconds. At the 5th second SDL just kills streaming thread with all pending messages, however, audio service is still open. As a result, not a whole audio file is played.

The correct behavior from SDL side in that case is not kill streaming thread when streaming timeout was expired. SDL should kill streaming thread only when service is
actually stopped.

##### Reproduction Steps
1. Start SDL and modified HMI
2. Register SPT with type Navi over TCP transport
3. Activate that app
4. In SPT go to Menu options on the mobile device --> AV Streaming -->Under Audio Streaming Encrypt Video to NONE --> Start session --> Start Audio
5. Select 30 sec file and send it to HMI
6. Wait until the whole audio file is played

##### Expected Behavior
Should be played whole audio file

##### Observed Behavior
Audio is played just a few seconds

#### OS & Version Information
* OS/Version : SYNC4
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/releases/tag/5.0.1 
* Testing Against: SYNC4 Applink

**Comment by AKalinich-Luxoft** [comment]
@theresalech fix has been submitted and ready for Livio review

**Comment by iCollin** [comment]
Issue as described was fixed by https://github.com/smartdevicelink/sdl_core/pull/3057. 

Issue title and PR #3488 seem to suggest there is a problem when a stream is suspended, can you please update the reproduction steps and/or description to reflect that?

**Comment by AKalinich-Luxoft** [comment]
> Issue as described was fixed by #3057.
> 
> Issue title and PR #3488 seem to suggest there is a problem when a stream is suspended, can you please update the reproduction steps and/or description to reflect that?

PR #3057 is just solves audio playback issue on socket transport. PR #3488 suggest another solution for all the transports

**Comment by iCollin** [comment]
Closed via #3488
