### ISSUE TITLE
[SDL 0248] HMI Policy Table Update using vehicle modem

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_core#3161]
Add configurations and support for the proposal described and linked below:

Proposal: [HMI Policy Table Update using vehicle modem](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0248-hmi-ptu-support.md)

> This proposal describes an enhanced policy table update PTU sequence where the IVI system sends the policy table snapshots (PTS) directly to the policy server using the in-vehicle modem and returns a policy table update (PTU) back to SDL Core without using any `SystemRequest` RPC.

Review: https://github.com/smartdevicelink/sdl_evolution/issues/813

Steering Committee Decision:

>The Steering Committee voted to accept this proposal with the following revisions:
- Note `SDL.GetURLs` as deprecated, and add `GetPolicyConfigurationData`
- Include implementation details for HMI Integration Guidelines, SDL HMI, Generic HMI, and ATF/ATF Test Scripts, as outlined in [this comment](https://github.com/smartdevicelink/sdl_evolution/issues/813#issuecomment-525335714)

> The proposal .md file was updated to reflect these revisions on 9/3/19.

**Comment by ShobhitAd** [comment]
Closing with the merge of https://github.com/smartdevicelink/sdl_core/pull/3201
