### ISSUE TITLE
CCB: Fix for a potential SDL crash on boot

### ISSUE THREAD

**Issue by LitvinenkoIra** [smartdevicelink/sdl_core#3163]
### Bug Report
SmartDeviceLink crash

### Detailed analysis:
One of the reasons why SDL is crashing on start is related to lazy initialization of the HMI/Mobile/v4 API classes. These classes are initialized on demand when some of the threads are trying to get the object of that class first time. Most likely, at SDL start might be a situation when HMI/Mobile/v4 API classes are constructing in the one thread and at that moment another thread is trying to get access to the inner data of not-yet-fully-constructed object and this causes a core crash with ~ISchemaItem() calls in stack trace. That is possible because access to these factories is not synchronized.

To avoid such situation, factory creation should be moved to AM ctor and all other sub-components should just use getters when they need to get access to API instances.

##### Reproduction Steps
1. Simulate ignition OFF followed by door open and door close. Wait until SYNC is fully powered down
2. Wait 2 minutes
3. Simulate door open, door close followed by ignition on.
4. Wait 5 seconds
5. Simulate gear change to R
6. Wait 5 seconds
7. Simulate gear change to D
8. After 10 seconds, simulate gear change to P.
9. Wait 2 minutes.
10. Repeat 1 - 9 for 36 hours.

##### Expected Behavior
No crashes

##### Observed Behavior
Detected SmartDeviceLink core dump (once)

#### OS & Version Information
* OS/Version : SYNC4
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/releases/tag/5.0.1 
* Testing Against: SYNC4 Applink

**Comment by iCollin** [comment]
Closed via https://github.com/smartdevicelink/sdl_core/pull/3581
