### ISSUE TITLE
CCB: Projection/Navigation app not going to FULL

### ISSUE THREAD

**Issue by LitvinenkoIra** [smartdevicelink/sdl_core#3167]
### Bug Report
Projection/Navigation app is not getting HMI Status when "Enable Mobile Apps" option is disabled

### Detailed analysis:
TBD

##### Reproduction Steps
1. Toggle off "Enable Mobile Apps"
2. Register SPT with type Projection/Navigation
3. Launch
4. A pop up seeking permission should be shown

##### Expected Behavior
App should receive HMIStatus and should launch successfully

##### Observed Behavior
App is stuck in "Waiting for Device" pop up and app did not receive HMIStatus

#### OS & Version Information
* OS/Version : SYNC4
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/releases/tag/5.0.1 
* Testing Against: SYNC4 Applink

**Comment by jacobkeeler** [comment]
@AKalinich-Luxoft Are you able to verify if this was resolved by #3476?

**Comment by IGapchuk** [comment]
Hi, @jacobkeeler We have verified the issue on the last develop (1f52a0ef360475ba268c49e1eec8b0a93050f132). The issue wasn't reproduced.
[SmartDeviceLinkCore.log.tar.gz](https://github.com/smartdevicelink/sdl_core/files/5245260/SmartDeviceLinkCore.log.tar.gz)
