### ISSUE TITLE
CCB: Fixes race condition in messagemeter.h

### ISSUE THREAD

**Issue by LitvinenkoIra** [smartdevicelink/sdl_core#3168]
### Bug Report
iOS/Android USB- Apps are not Unregistering

### Detailed analysis:
Unprotected critical section accessed by two different threads,
timing_map is being modified by clearing the map identifiers causing a
crash in boost::date_time

##### Reproduction Steps
1. Connect an iOS device with Applink compatible Apps downloaded on to the phone to SYNC via USB
2. Verify the Apps Registration on SYNC
3. Unplug the device from SYNC

##### Expected Behavior
Apps should Unregister

##### Observed Behavior
Apps are not Unregistering

#### OS & Version Information
* OS/Version : SYNC4
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/releases/tag/5.0.1 
* Testing Against: SYNC4 Applink

**Comment by E-SAITO-TMC** [comment]
@joeygrover -san @theresalech -san This issue is a top priority for Toyota. Does this occur with the reproduction steps described? Also, does this issue occur in the latest version?

**Comment by theresalech** [comment]
Hi @E-SAITO-TMC, we have documented that this is priority for Toyota, and will include for Steering Committee review and vote when planning the contents for the Q4 Core release. This planning will take place in June.
@LitvinenkoIra, can you please advise if the Luxoft team is seeing this issue in Core 6.1?

**Comment by LuxoftAKutsan** [comment]
@theresalech
Issue reproduced on SYNC version of SDL.
Issue is related to  iOS device and can't be reproduced in open sdl environment. 
Fix from SYNC ported to open : #3377

**Comment by jacobkeeler** [comment]
Closing with the merge of #3377
