### ISSUE TITLE
CCB: Fix SIGSEGV Crash subscribed_data 

### ISSUE THREAD

**Issue by LitvinenkoIra** [smartdevicelink/sdl_core#3172]
### Bug Report
SmartDeviceLink crash with SIGSEGV

### Detailed analysis:
unprotected access to the VehicleInfoAppExtension::subscribed_data from different threads

##### Reproduction Steps
1. Start SDL, HMI, connect Mobile
2. Register app
3. Perform multiple RPC scenarios and send OnVehicleDataNotification
4. Observe behavior

##### Expected Behavior
SDL should not crash

##### Observed Behavior
SDL crashed
[bt.txt](https://github.com/smartdevicelink/sdl_core/files/3932241/bt.txt)

#### OS & Version Information
* OS/Version : SYNC4
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/releases/tag/5.0.1 
* Testing Against: SYNC4 Applink

**Comment by E-SAITO-TMC** [comment]
@theresalech -san, We were able to reproduce this issue with Core 6.0.1. This is a high priority issue for Toyota. Could you please include this in the Core 6.2 release planning?

**Comment by theresalech** [comment]
@LitvinenkoIra can you please advise if you are able to reproduce this issue in the latest Core release?

**Comment by LuxoftAKutsan** [comment]
Fix form SYNC4 will be applied.
Test script will be created, but test script may pass on open  sdl_core even without fix. Issue related to race conditions and may be not reproducible on open sdl.

**Comment by theresalech** [comment]
@LuxoftAKutsan, thank you for the additional information! Please let us know when a PR is ready for Livio's review.
