### ISSUE TITLE
CCB: SmartDeviceLink SIGSEGV crash in std::__1::__tree_ 

### ISSUE THREAD

**Issue by LitvinenkoIra** [smartdevicelink/sdl_core#3173]
### Bug Report
SmartDeviceLink SIGSEGV crash in std::__1::__tree_iterator

### Detailed analysis:
When one thread accessing data of capabilities other thread can delete the pointer. So it necessary to change it to shared pointers.

##### Reproduction Steps
1. Start SDL, HMI, connect Mobile
2. Register app
3. Observe behavior

##### Expected Behavior
SDL should not crash

##### Observed Behavior
SDL crashed
[bt.txt](https://github.com/smartdevicelink/sdl_core/files/3932264/bt.txt)

#### OS & Version Information
* OS/Version : SYNC4
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/releases/tag/5.0.1 
* Testing Against: SYNC4 Applink

**Comment by E-SAITO-TMC** [comment]
@theresalech -san, We were able to reproduce this issue with Core 6.0.1. This is a high priority issue for Toyota. Could you please include this in the Core 6.2 release planning?

**Comment by theresalech** [comment]
@LitvinenkoIra can you please advise if you are able to reproduce this issue in the latest Core release?

**Comment by LuxoftAKutsan** [comment]
Fix from SYNC4 applicable for open sdl. 
Additional test will not be created. any test case contains steps t reproduce. 
Probably issue can't be reproduce in open sdl environment. 
Regression will be checked

**Comment by theresalech** [comment]
@LuxoftAKutsan, thank you for the additional information! Please let us know when a PR is ready for Livio's review.

**Comment by JackLivio** [comment]
Resolved by #3528
