### ISSUE TITLE
CCB: Fix deadlock in PolicyHandler 

### ISSUE THREAD

**Issue by LitvinenkoIra** [smartdevicelink/sdl_core#3179]
### Bug Report
Deadlock in PolicyHandler 

### Detailed analysis:
A deadlock occurs due to wrong use of a policy_manager_lock_ mutex. dlclose call should be guaranteed after deleting the PolicyManager

##### Reproduction Steps
1. TBD

##### Expected Behavior
SDL should not crash

##### Observed Behavior
SDL crashed

#### OS & Version Information
* OS/Version : SYNC4
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/releases/tag/5.0.1 
* Testing Against: SYNC4 Applink

**Comment by ShobhitAd** [comment]
Closed via https://github.com/smartdevicelink/sdl_core/pull/3497
