### ISSUE TITLE
CCB: Fix data races in logger 

### ISSUE THREAD

**Issue by LitvinenkoIra** [smartdevicelink/sdl_core#3183]
### Bug Report
Data races related to Logger

### Detailed analysis:
Now MessageQueue::shutting_down_ should be atomic.
Wrong multiple inheritances from LogMessageLoopThread should be removed.
Functions logs_enabled and set_logse enabled should be thread safe.

##### Reproduction Steps
1. TBD

##### Expected Behavior
SDL should not crash

##### Observed Behavior
SDL crashed

#### OS & Version Information
* OS/Version : SYNC4
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/releases/tag/5.0.1 
* Testing Against: SYNC4 Applink

**Comment by LuxoftAKutsan** [comment]
@theresalech PR for this fix is ready for review. 
Full regression tested. Results are the same as on the develop branch.
