### ISSUE TITLE
CCB: wait for UsbHandler thread end in UsbHandler dtor

### ISSUE THREAD

**Issue by LitvinenkoIra** [smartdevicelink/sdl_core#3184]
### Bug Report
Data races related to UsbHandler

### Detailed analysis:
The Thread dedicated to handling libusb events should exit successfully on it's own. This guarantees that libusb_close() being called on all devices, as well as libusb_exit() call is properly sequenced.
Thread exits in recommended by libusb doc way:
  1. set exit flag
  2. deregister hotplug callbacks, which will wake up
     libusb_handle_events() once again.

The way the Thread being joined should be changed. It should ensure that join() is called with kNoStop flag, which prevents force stop using pthread_cancel().

##### Reproduction Steps
1. TBD

##### Expected Behavior
SDL should not crash

##### Observed Behavior
SDL crashed

#### OS & Version Information
* OS/Version : SYNC4
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/releases/tag/5.0.1 
* Testing Against: SYNC4 Applink

**Comment by AKalinich-Luxoft** [comment]
@theresalech fix has been submitted and ready for Livio review

**Comment by ShobhitAd** [comment]
Closed via https://github.com/smartdevicelink/sdl_core/pull/3492
