### ISSUE TITLE
CCB: Fix data races in TcpClientListener 

### ISSUE THREAD

**Issue by LitvinenkoIra** [smartdevicelink/sdl_core#3187]
### Bug Report
Data races related to TcpClientListener

### Detailed analysis:
Type of TcpClientListener::thread_stop_requested_ should be changed from bool to std::atomic_bool.

##### Reproduction Steps
1. TBD

##### Expected Behavior
SDL should not crash

##### Observed Behavior
SDL crashed

#### OS & Version Information
* OS/Version : SYNC4
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/releases/tag/5.0.1 
* Testing Against: SYNC4 Applink

**Comment by AKalinich-Luxoft** [comment]
@theresalech fix has been submitted and ready for Livio review

**Comment by iCollin** [comment]
Closed via #3495
