### ISSUE TITLE
CCB: using atomic bool for shutdown_requested_ flag 

### ISSUE THREAD

**Issue by LitvinenkoIra** [smartdevicelink/sdl_core#3188]
### Bug Report
Data races related to UsbHandler

### Detailed analysis:
UsbHandler::shutdown_requested_ flag should be atomic to guarantee
mutual access to it.

##### Reproduction Steps
1. TBD

##### Expected Behavior
SDL should not crash

##### Observed Behavior
SDL crashed

#### OS & Version Information
* OS/Version : SYNC4
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/releases/tag/5.0.1 
* Testing Against: SYNC4 Applink

**Comment by AKalinich-Luxoft** [comment]
@theresalech fix has been submitted and ready for Livio review

**Comment by ShobhitAd** [comment]
Closed via https://github.com/smartdevicelink/sdl_core/pull/3492
