### ISSUE TITLE
CCB: Fix dead lock in usb connection 

### ISSUE THREAD

**Issue by LitvinenkoIra** [smartdevicelink/sdl_core#3189]
### Bug Report
Data races related to UsbConnection

### Detailed analysis:
In a while called method locks mutex for protecting data and if USB connection is failed it means that method will call and will try to lock the same mutex again. That's why this mutex should be recursive.

##### Reproduction Steps
1. TBD

##### Expected Behavior
SDL should not crash

##### Observed Behavior
SDL crashed

#### OS & Version Information
* OS/Version : SYNC4
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/releases/tag/5.0.1 
* Testing Against: SYNC4 Applink

**Comment by AKalinich-Luxoft** [comment]
@theresalech fix has been submitted and ready for Livio review

**Comment by ShobhitAd** [comment]
Closed via https://github.com/smartdevicelink/sdl_core/pull/3494
