### ISSUE TITLE
[SDL 0261] New vehicle data WindowStatus

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_core#3193]
Proposal: [New vehicle data WindowStatus](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0261-New-vehicle-data-WindowStatus.md)

> This proposal is to add new vehicle data `WindowStatus` to know the position of windows in a vehicle.

Review: https://github.com/smartdevicelink/sdl_evolution/issues/869

Steering Committee Decision:

>The Steering Committee voted to accept this proposal with the revision to `WindowStatus` described in [this comment](https://github.com/smartdevicelink/sdl_evolution/issues/869#issuecomment-564050172).

> The proposal .md file was updated to reflect these revisions on 12/12/19.

**Comment by theresalech** [comment]
Proposal markdown file has been updated per the revisions included in accepted Evolution Proposal [SDL 0261 Revisions - New vehicle data WindowStatus](https://github.com/smartdevicelink/sdl_evolution/issues/1028).  Revisions adding `mandatory=true` attribute to `approximatePosition` and `deviation`, and changing `minValue/MaxValue` attributes to `minvalue/maxvalue`.  Please reference the issue and proposal markdown file for revisions details.

**Comment by ShobhitAd** [comment]
Closed via https://github.com/smartdevicelink/sdl_core/pull/3391
