### ISSUE TITLE
SDL responds "resultCode: GENERIC_ERROR" while dataType:VEHICLEDATA_EXTERNTEMP is VEHICLE_DATA_NOT_AVAILABLE and not in subscribed list store

### ISSUE THREAD

**Issue by HSavynetska** [smartdevicelink/sdl_core#3196]
## Occurrence
Always

## Preconditions
1. Core and HMI are started.
2. SubscribeVehicleData (speed, externalTemperature), OnVehicleData is allowed by policy for app_1 and app_2.
3. Navi App1 and navi app2 are registered and activated.

## Steps to reproduce
1. Send SubscribeVehicleData (speed, externalTemperature) from app_1
=> SDL responds SubscribeVehicleData ((speed:success),(externalTemperature:VEHICLE_DATA_NOT_AVAILABLE), SUCCESS).
2. Send SubscribeVehicleData (speed, externalTemperature) from app_2.

## Actual result
SDL sends "resultCode: GENERIC_ERROR, success:false" to mobile app1 and app2.

## Expected result
SDL should send "SUCCESS, (speed: SUCCESS),
(externalTemperature: VEHICLE_DATA_NOT_AVAILABLE)" to mobile app1 and app2.

# Environment
SDL repo: https://github.com/smartdevicelink/sdl_core
SDL branch: develop
SDL commit: e137556
OS: Ubuntu 16.04 LTS

**Comment by ShobhitAd** [comment]
Closed via #3264
