### ISSUE TITLE
SDL sends OnAppInterfaceUnregistered with the reason IGNITION_OFF during FACTORY_DEFAULTS exit

### ISSUE THREAD

**Issue by GetmanetsIrina** [smartdevicelink/sdl_core#3204]
### Bug Report
SDL sends OnAppInterfaceUnregistered with the reason `IGNITION_OFF` during `FACTORY_DEFAULTS` exit

##### Reproduction Steps
1. SDL and HMI are started
2. App is registered
3. HMI sends `BC.OnExitAllApplications(FACTORY_DEFAULTS)`

##### Expected Behavior
SDL unregisters app and sends OnAppInterfaceUnregistered(FACTORY_DEFAULTS) to it.

##### Observed Behavior
SDL sends OnAppInterfaceUnregistered(IGNITION_OFF) to mobile application

##### OS & Version Information
* OS/Version: Ubuntu 18.04
* SDL Core Version:https://github.com/smartdevicelink/sdl_core/commit/e137556512215ded94228e33d21ab4c3e1af3017
* ATF: develop
* Script: https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Defects/4_5/1225_FACTORY_DEFAULTS.lua

##### Logs
[SDL_and_ATF_logs.zip](https://github.com/smartdevicelink/sdl_core/files/4007004/SDL_and_ATF_logs.zip)

**Comment by LitvinenkoIra** [comment]
https://github.com/smartdevicelink/sdl_atf_test_scripts/issues/2355

**Comment by E-SAITO-TMC** [comment]
@theresalech -san This issue is a medium priority for Toyota. I would like know if this issue occur in the latest version. And could you please include this issue in your plan? Thank you.

**Comment by E-SAITO-TMC** [comment]
@theresalech -san This issue is a medium priority for Toyota. I would like know if this issue occur in the latest version. And could you please include this issue in your plan? Thank you.

**Comment by theresalech** [comment]
Hi @E-SAITO-TMC, we have documented that this is medium priority for Toyota, and will include for Steering Committee review and vote when planning the contents for the Q4 Core release.

@GetmanetsIrina, can you please advise if you are seeing this issue when using Core 6.1?

**Comment by GetmanetsIrina** [comment]
@theresalech, this issue is still actual for Core 6.1(https://github.com/smartdevicelink/sdl_core/commit/a85ef58358c456f69fee93addb7066dc02ecae48)

**Comment by iCollin** [comment]
Closed via https://github.com/smartdevicelink/sdl_core/pull/3274
