### ISSUE TITLE
SDL returns INVALID_DATA result code for SubscribeVehicleData instead of UNSUPPORTED_RESOURCE in case VehicleInfo interface is unavailable

### ISSUE THREAD

**Issue by GetmanetsIrina** [smartdevicelink/sdl_core#3205]
### Bug Report
SDL returns `INVALID_DATA` result code for `SubscribeVehicleData` instead of `UNSUPPORTED_RESOURCE` in case `VehicleInfo` interface is unavailable

##### Reproduction Steps
1.HMI and SDL are started
2. HMI responds with `{"method":"VehicleInfo.IsReady","code":0,"available":false}` to SDL
3. App is registered
4.PTU is performed and provides the permissions for SubscribeVehicleData(gps, speed)
5. App requests SubscribeVehicleData(gps=true)

##### Expected Behavior
SDL responds with result code `UNSUPPORTED_RESOURCE` to mobile app

##### Observed Behavior
SDL responds with result code `INVALID_DATA` and info `"No data in the request"`

##### OS & Version Information
* OS/Version: Ubuntu 18.04
* SDL Core Version:https://github.com/smartdevicelink/sdl_core/commit/e137556512215ded94228e33d21ab4c3e1af3017
* ATF: develop
* Script: https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Defects/5_0/972_SDL_should_respond_IGNORED_with_correct_result_code_for_UnSubscribeVehicleData_in_case_vi_interface_is_not_available.lua

##### Logs
[SDL_and_ATF_logs.zip](https://github.com/smartdevicelink/sdl_core/files/4007020/SDL_and_ATF_logs.zip)

**Comment by jacobkeeler** [comment]
Closing with the merge of #3433
