### ISSUE TITLE
ATF tests failed using IAP2 transport

### ISSUE THREAD

**Issue by SNiukalov** [smartdevicelink/sdl_core#3218]
##### Issue
Some ATF tests failed when SDL build without BUILD_TEST flag. 
But ATF tests are not dependent on unit tests.

##### Expected Behavior
SDL should be build without BUILD_TEST flag to run ATF tests.

##### Observed Behavior
Some ATF tests failed if the SDL assembly is without the BUILD_TEST flag:
https://github.com/smartdevicelink/sdl_atf_test_scripts/tree/master/test_scripts/iAP2TransportSwitch

**Comment by iCollin** [comment]
Closed via #3219
