### ISSUE TITLE
openssl1.1.x support

### ISSUE THREAD

**Issue by jpsalm** [smartdevicelink/sdl_core#3220]
Is migration to openssl1.1 something on your roadmap?

I am attempting to move the [meta-sdl yocto layer](https://github.com/phongt/meta-sdl/tree/warrior) to a more current yocto release as well as utilize the latest 6.0.1 sdl-core release.

An issue I'm currently running into is sdl-core using openssl1.0 while more current yocto releases are using 1.1.  I can successfully compile the project with "-DENABLE_SECURITY=OFF" but there is still a segfault from somewhere in sdl-core calling into libcrypto.so.1.1 (expecting 1.0).

I can identify and patch the problem or perhaps include openssl1.0 alongside 1.1 just for sdl-core but I thought I'd check to see if 1.1 is something that is planned to be addressed in the near/medium future.

**Comment by iCollin** [comment]
Closed via https://github.com/smartdevicelink/sdl_core/pull/3582
