### ISSUE TITLE
SDL is not built with EXTERNAL_PROPRIETARY

### ISSUE THREAD

**Issue by GetmanetsIrina** [smartdevicelink/sdl_core#3225]
### Bug Report
SDL is not built with EXTERNAL_PROPRIETARY

##### Reproduction Steps
1. Set `EXTENDED_POLICY=EXTERNAL_PROPRIETARY` in cmake CMakeCache.txt
2. build SDL

##### Expected Behavior
SDL is built successful

##### Observed Behavior
SDL is not built successful

##### OS & Version Information
* OS/Version: Ubuntu 18.10
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/tree/develop (fe71aef64d7c9e1e35a614721acda513bb785c2a)

**Comment by iCollin** [comment]
Closed via #3224
