### ISSUE TITLE
SDL crashes when the HMI sends UI.OnTouchEvent with the 'ts' param has a value greater than maxvalue (not valid)

### ISSUE THREAD

**Issue by HSavynetska** [smartdevicelink/sdl_core#3226]
### Bug Report
SDL crashes when the HMI sends UI.OnTouchEvent with the 'ts' param has a value greater than maxvalue (not valid)

##### Reproduction Steps
1. SDL and HMI are started
2. Navi_App is registered and activated
3. OnTouchEventOnlyGroup is allowed by policies
4. HMI sends OnTouchEvent notification with the 'ts' param has a value greater than maxvalue (not valid)

##### Expected Behavior
No Crash should be observed while testing

##### Observed Behavior
SDL crashed while testing

#### OS & Version Information
* OS/Version : Ubuntu 16.04
* SDL Core Version: 
* ATF: develop

[logs.zip](https://github.com/smartdevicelink/sdl_core/files/4148083/logs.zip)

**Comment by jacobkeeler** [comment]
Closed with the merge of #3750
