### ISSUE TITLE
[SDL 0264] Separating the change of Audible status and the change of HMI Status

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_core#3227]
Proposal: [Separating the change of Audible status and the change of HMI Status](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0264-Separating-the-change-of-Audible-status-and-the-change-of-HMI-Status.md)

> Currently, there is no way to independently notify the Audible status to applications that output audio such as SDL Media. By changing the behavior of the existing API, the Audible state can be switched while maintaining the screen.

Review: https://github.com/smartdevicelink/sdl_evolution/issues/872

Steering Committee Decision:

> The Steering Committee voted to accept this proposal, with the revision that it should specify it requires a documentation update for the integrators. 

> The proposal .md file was updated to reflect these revisions on 2/3/2020.

**Comment by jacobkeeler** [comment]
Closed via #3738
