### ISSUE TITLE
SDL failed to start video streaming due to App switching on iPhone(connection via BT+WIFI)

### ISSUE THREAD

**Issue by zhouxin627** [smartdevicelink/sdl_core#3233]
### Bug Report
SDL failed to start video streaming due to App switching on iPhone(connection via BT+WIFI)

### Preconditions
1. Connect the head unit to iPhone via BT+WiFi
2. Register 2 iOS apps:
・App1: navigation App
・App2: navigation App

##### Reproduction Steps
1. Activate App1 on HU
2. App1 starts video streaming
3. Switch App1 to the background on iPhone
4. Launch App2 on iPhone
5. Activate App2 on HU
6. App2 failed to start video streaming

##### Expected Behavior
App2 starts video streaming successfully.

##### Observed Behavior
A timing issue due to that VPM terminate operation and playing video is being executed by separate threads (these threads run simultaneously).
1. When switching App1 to the background on iPhone, WIFISession will be closed according to the processing logic of iOS, Proxy will send VPM termination request to SDLCore.
2. SDLCore will call `OnServiceEndedCallback(11)` to terminate VPM.
3. At this time, SDLCore received the video data that still not be sent completed.
Then SDLCore will think there's still has video data to play, and restarts VPM that shouldn't be done.
4. Eventually, App1 is switched to the background on iPhone but SDLCore still sends `StartStream` to HU that shouldn't be done, therefore, the status of VPM becomes chaotic.
5. App2 failed to start video streaming.

##### OS & Version Information
* iOS Version:10.2
* Proxy Version: 6.4.1
* Testing Against: SDL Core 6.0.1 + HMI running on our development environment.

##### Occurrence:
80%

##### Recovery Method:
ACC OFF/ON

**Comment by mrapitis** [comment]
@theresalech would it be possible to prioritize review of this bug and plan for an upcoming sdl core release?

**Comment by jacobkeeler** [comment]
@zhouxin627 point of clarification, could you define VPM?

**Comment by zhouxin627** [comment]
@jacobkeeler Hi, “VPM” is the abbreviation of “Video streaming Projection Mode”. Actually, “VPM“  has the same meaning as video streaming.

**Comment by JackLivio** [comment]
Fixed with merge #3290
