### ISSUE TITLE
APTDisplayText is not displayed properly

### ISSUE THREAD

**Issue by zhouxin627** [smartdevicelink/sdl_core#3238]
### Bug Report
APTDisplayText is not displayed properly

##### Preconditions
Mobile side：only set audioPassThruDisplayText2，but not set audioPassThruDisplayText1.

##### Reproduction Steps
1.Activate test apps to display APTDisplayText.

##### Expected Behavior
audioPassThruDisplayText2 is displayed.

##### Observed Behavior
audioPassThruDisplayText2 is not displayed.

PerformAudioPassThru has two lines of text defined in RPC Spec.
1. audioPassThruDisplayText1
2. audioPassThruDisplayText2

There are no rules that both of them must be set together.

SDLCore receives audioPassThruDisplayText1 and audioPassThruDisplayText2 from Mobile,
then does the string conversion of them.
If audioPassThruDisplayText1 is not be set, SDLCore thinks that the text data received is incorrect,
so it would abandon the text data received.
Eventually, audioPassThruDisplayText2 does not display as expected.

##### OS & Version Information
* SDL Core Version: 6.0.1
* Testing Against: SDL Core 6.0.1 + HMI running on our development environment.

##### Occurrence:
100%

##### Recovery Method:
None

**Comment by ShobhitAd** [comment]
Closed via #3291
