### ISSUE TITLE
How to determine which template will be used?

### ISSUE THREAD

**Issue by luchengchao** [smartdevicelink/sdl_core#324]
There are several templates in the stack. When one app is registered and activated, how to determine which template will be used? Through which RPC? What is the procedure?

**Comment by justinjdickow** [comment]
The developer can use the setDisplayLayout RPC to specify a preferred template.

The PredefinedLayout enum lists the current templates that are supported. The registerAppInterface response RPC from SDL Core to Mobile has a parameter called DisplayCapabilities which contains a list of all the supported templates on that specific vehicle.
