### ISSUE TITLE
End session handler returns `hashId` as a rejected parameter regardless of the service type

### ISSUE THREAD

**Issue by NicoleYarroch** [smartdevicelink/sdl_core#3240]
### Bug Report
In `HandleControlMessageEndSession`, if the protocol version is greater than or equal to version 5.0 and the end session did not succeeded, then `hashId` is appended to the `rejectedParams` regardless of the service type. Since only the RPC service has the `hashId` parameter, this means that `hashId` is returned incorrectly as one of the `rejectedParams` for a video end service NAK and an audio end service NAK. 

##### Reproduction Steps
1. Connect an SDL video streaming app supporting protocol version 5+ to SDL Core. 
1. Start start streaming video.
1. Send an end video service control frame from the SDL app. 

##### Expected Behavior
If the end video service NAKs, then the `rejectedParams` should not contain `hashId`. 

##### Observed Behavior
If the end video service NAKs, the `rejectedParams` contains `hashId` even though `hashId` has nothing to do with ending a video or audio service. 

##### OS & Version Information
* OS/Version: I saw this bug on SYNC 4 (20016_DEVTEST) 
* SDL Core Version: I am not sure what version of Core SYNC 4 has. I can see the bug when doing a code inspection on the master branch (v.6.0.1) 
* Testing Against: SYNC 4 (20016_DEVTEST)

**Comment by jacobkeeler** [comment]
Resolved with the merge of #3241
