### ISSUE TITLE
SDL does not support attribute "until" for any element in Mobile_API 

### ISSUE THREAD

**Issue by ydementieiev** [smartdevicelink/sdl_core#3246]
### Bug Report
During implementation [Proposal: Refactor Fuel Information Related Vehicle Data](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0256-Refactor-Fuel-Information-Related-Vehicle-Data.md)  was found that individual elements do not support attribute `until` in `Mobile_API`.

### Reproduction Steps
Update enum `VehicleDataType` adding `until` for individual elements:
```
<element name="VEHICLEDATA_FUELLEVEL" until="6.0"/>
<element name="VEHICLEDATA_FUELLEVEL_STATE" until="6.0"/>
```

### Expected Behavior
According to [Mobile API versioning](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0089-mobile-api-versioning.md) The attribute `since` and `until` should be used for any element (enum, element, function, struct, param) in the `Mobile_API`.

### Observed Behavior
Attribute "until" does not support for any element in Mobile_API

### OS & Version Information
OS/Version: [Ubuntu 18.0]
SDL Core Version: [Core version](https://github.com/smartdevicelink/sdl_core/commit/b281c67f167f385aabbb232333ddc8cef65172d7)

**Comment by ShobhitAd** [comment]
@ydementieiev The until param change should also be added to the https://github.com/smartdevicelink/rpc_spec/blob/develop/MOBILE_API.xsd file

**Comment by ShobhitAd** [comment]
Closed via https://github.com/smartdevicelink/sdl_core/pull/3249

**Comment by ShobhitAd** [comment]
Found additional attributes(`deprecated` and `removed`) which were also missing in the schema. Creating a new fix PR

**Comment by ShobhitAd** [comment]
Closed via https://github.com/smartdevicelink/sdl_core/pull/3266
