### ISSUE TITLE
[SDL 0277] Continuous integration and testing

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_core#3251]
Proposal: [Continuous integration and testing](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0277-Continuous-Integration-And-Testing.md)

> This proposal is about implementation of the Continuous Integration (CI) process for keeping SDL in a trouble-free state.

Review: https://github.com/smartdevicelink/sdl_evolution/issues/934

Steering Committee Decision:

> The Steering Committee voted to accept this proposal with revisions. The revisions will include removing “section 3. Creating a subfolder for storing infrastructure files,” with justification that the new CI feature should be hosted in its own/separate repository.

> The proposal .md file was updated to reflect these revisions on 2/20/2020.

**Comment by iCollin** [comment]
Closed via https://github.com/smartdevicelink/sdl_core_ci/pull/2 and https://github.com/smartdevicelink/sdl_core/pull/3509.
