### ISSUE TITLE
A race condition with re-starting the video service causes core to unregister the SDL app with a `PROTOCOL_VIOLATION`. 

### ISSUE THREAD

**Issue by NicoleYarroch** [smartdevicelink/sdl_core#3256]
### Bug Report
A race condition with re-starting the video service causes core to unregister the SDL app with a `PROTOCOL_VIOLATION`. 

##### Reproduction Steps
1. Connect an iOS SDL navigation app supporting secondary transports to the module. Launch the SDL app by selecting the app icon on the HMI. Video should start streaming over the secondary transport.
1. Put the app on the iOS device in the background. Due to iOS limitations, the TCP socket must be destroyed when the app on the device is in the background. When the socket is destroyed the `hmiLevel` is still `FULL`.
1. Bring the app on the device to the foreground. Since the `hmiLevel` is `FULL` the SDL app will send video and audio start service control frames. Core responds with ACK to both the video and audio start services. The SDL app starts streaming video/audio. The HMI starts playing audio, however it sometimes will not play video  (probably a bug with HMI?).  
1. Select the SDL app icon on the HMI to launch the app. A "waiting for SDL app" alert appears. Select the "cancel" button.
1. The `hmiLevel` goes to `NONE` and then `FULL` in less than 600 milliseconds. When the `hmiLevel` goes to `NONE`, the SDL app sends an end video and audio service control frame. Core responds with NAK to both the video and audio end services. When the `hmiLevel` goes to `FULL` the SDL app sends video and audio start service control frames. Core responds with ACK to both the video and audio start services (The ACKs occur less than 610 milliseconds after the `hmiLevel` went to `NONE`).

##### Expected Behavior
Core does not unregister the SDL app since the app does have permission to stream video. The `hmiLevel` is `FULL` and core ACKed the requests to start the video and audio services.

##### Observed Behavior
Core sends an `OnAppInterfaceUnregistered ` notification with a reason of `PROTOCOL_VIOLATION`. 

#### Race Condition
1. In the **application_manager_impl.cc**, `ProcessApp()` method, when the `hmiLevel` goes from non-`NONE` to `NONE`, `EndNaviServices()` is called. `EndNaviServices` has a close timer that checks after a set amount of time if the navigation app has closed. This time interval, `StopStreamingTimeout`, is set in the .ini file and the default is 1000 milliseconds.  
1. However, by the time the close timer has checked if the video and audio services have stopped for the `appId`, the mobile app has already sent an end video and audio control frame and then a start video and start audio service control frame successfully. Core thinks mobile has not shut down the audio and/or video service and unregisters the app.
1. When I delay sending the start video and audio control frames by 2 seconds in the SDL app, this solves the issue of Core unregistering the SDL app . However, since each OEM can set a unique `StopStreamingTimeout`, this is not an optimal fix on the mobile side. 

##### OS & Version Information
* OS/Version: SYNC 4
* SDL Core Version:SYNC 4
* Testing Against: SYNC 4

**Comment by iCollin** [comment]
Hello, this issue was fixed in https://github.com/smartdevicelink/sdl_core/pull/3202

I am not sure when this fix will be propagated to SYNC4 but as this bug has already been fixed in sdl_core I will close this issue. Please let me know if you have any questions or think the issue should be reopened.
