### ISSUE TITLE
iOS OnSystemRequest fails to parse PT Snapshot

### ISSUE THREAD

**Issue by JackLivio** [smartdevicelink/sdl_core#3260]
### Bug Report
OnSystemRequest policy table updates are failing on ios.

##### Reproduction Steps
1. Connect ios app over tcp on a clean core build

##### Expected Behavior
PTU takes place

##### Observed Behavior
iOS error on parsing the policy table snapshot received from Core's onSystemRequest notification.

##### OS & Version Information
* OS/Version: ios
* SDL Core Version: develop regular policies

**Comment by JackLivio** [comment]
I think it is related to the new JSONCPP library changes.

**Comment by theresalech** [comment]
Closed via #3262
