### ISSUE TITLE
SDL does not send BC.PolicyUpdate to HMI if no apps are registered

### ISSUE THREAD

**Issue by ShobhitAd** [smartdevicelink/sdl_core#3279]
### Bug Report
Currently, if there are no registered apps, triggering a PTU results in the HMI sending a `BasicCommunication.OnSystemRequest` with `fileName: null`. 

The PTS filename is never set in the HMI because SDL does not send a `BasicCommunication.PolicyUpdate` request(which contains the PTS path) to the HMI. This prevents us from being able to use the HMI vehicle modem to handle the PTU if no apps are registered.

##### Reproduction Steps
Using the sdl hmi with external proprietary checked:
1. Build core with external proprietary
2. Start the policy server
3. Modify the `0x07` endpoint in the PT
4. Register app, successful PTU should occur
5. Unregister app
6. Change the kilometers to 5000 to trigger a PTU

##### Expected Behavior
1. SDL sends a `BasicCommunication.PolicyUpdate` request to the HMI.
2. The HMI sends a `BasicCommunication.OnSystemRequest(PROPRIETARY)` notification to SDL with a valid PTS `fileName`.

##### Observed Behavior
1. SDL does NOT send a `BasicCommunication.PolicyUpdate` request to the HMI.
2. The HMI sends a `BasicCommunication.OnSystemRequest(PROPRIETARY)` notification to SDL with `fileName: null`.

##### OS & Version Information
* OS/Version: Ubuntu 18.04
* SDL Core Version: origin/develop (https://github.com/smartdevicelink/sdl_core/commit/94f92bb7eb440c0ee878896b6281f38009d64094)
* Testing Against: Test Suite

**Comment by dboltovskyi** [comment]
@ShobhitAd If you don't mind we would like to help you with creating of ATF script for this issue. This will allow us not to face with such issue in future releases since this script will be included in our regression testing scope.

**Comment by ShobhitAd** [comment]
Closed via #3280

**Comment by ShobhitAd** [comment]
@dboltovskyi Sorry I just saw your comment. That sounds like a good idea. Please let me know when you make a PR for the testing the issue.

**Comment by ShobhitAd** [comment]
Closed via #3294

**Comment by ShobhitAd** [comment]
Closed via #3363
