### ISSUE TITLE
SDL does not set the sdlVersion in ini file

### ISSUE THREAD

**Issue by GetmanetsIrina** [smartdevicelink/sdl_core#3284]
### Bug Report
SDL does not set the `sdlVersion` in `ini` file

##### Reproduction Steps
1. SDL sources are in repo
2. Create a build folder
3. Go to the build folder and perform `cmake <link_to_sdl_sources>`
4. Perform `make` and `make install`
5. Check the `ini` file in `build_folder/bin`

##### Expected Behavior
sdlVersion has value of the current repo commit

##### Observed Behavior
sdlVersion is undefined

##### OS & Version Information
* OS/Version: Ubuntu 18.04
* SDL Core Version: 94f92bb7eb440c0ee878896b6281f38009d64094

**Comment by SNiukalov** [comment]
@theresalech please triage this issue. Fix is ready in [#3310](https://github.com/smartdevicelink/sdl_core/pull/3310)

**Comment by theresalech** [comment]
@SNiukalov can you please advise if this is a regression issue introduced by 6.1, or if this is an existing issue in SDL Core?

**Comment by SNiukalov** [comment]
@theresalech yes, this is an existing issue in SDL Core.

**Comment by theresalech** [comment]
@SNiukalov thank you, understood.  We will work to include a fix in the Core 6.1 release if time permits, but will not have this included in the first release candidate which will be delivered to the Steering Committee today (2020-03-31).

**Comment by iCollin** [comment]
Closed via #3310
