### ISSUE TITLE
SDL stops responding in case it has been started with EnablePolicy=false

### ISSUE THREAD

**Issue by GetmanetsIrina** [smartdevicelink/sdl_core#3285]
### Bug Report
SDL stops responding in case it has been started with EnablePolicy=false

##### Reproduction Steps
1. `EnablePolicy` value is set to `false` in `ini` file
2. Start SDL
3. Connect mobile device and try to register app

##### Expected Behavior
SDL connects the device and registers the app successful

##### Observed Behavior
SDL disconnects the device after the connection and stops responding

##### OS & Version Information
* OS/Version: Ubuntu 18.04
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/commit/3dcc409766b49f9914963a5c7b2ef0c0dc5fddc8
* ATF: develop
* Test script: https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Defects/4_6/842_App_does_not_activate_when_policies_are_disabled.lua

##### Logs:
[Script_1.zip](https://github.com/smartdevicelink/sdl_core/files/4317796/Script_1.zip)

**Comment by GetmanetsIrina** [comment]
@theresalech, this is the regression issue for 6.1 release. Should we prepare the fix?

**Comment by theresalech** [comment]
@GetmanetsIrina yes, if you can prepare a fix, that would be much appreciated!  Please let us know once a PR is ready for review.  Thank you!

**Comment by jacobkeeler** [comment]
Closing with the merge of #3292
