### ISSUE TITLE
Namespace capitalization

### ISSUE THREAD

**Issue by lea255ace** [smartdevicelink/sdl_core#33]
The following namespaces contain capital letters:
- [x] Errors
- [x] Formatters
- [x] NsJSONHandler
- [x] NsMessageBroker
- [x] NsSmartDeviceLink
- [x] NsSmartObjects
- [x] protocol_handlerHandler

This is inconsistent with the style guide, and should be fixed. This will not be addressed in #25, and needs its own fix branch.

**Comment by jacobkeeler** [comment]
Several of the namespaces mentioned were present in the 3rd party libraries, which don't need to be edited, so I removed those entries. Will submit a PR for the rest

**Comment by jacobkeeler** [comment]
Closing with the merge of #2552
