### ISSUE TITLE
SDL sends BC.GetSystemInfo twice 

### ISSUE THREAD

**Issue by LitvinenkoIra** [smartdevicelink/sdl_core#3302]
### Bug Report
SDL sends BC.GetSystemInfo twice on **EXTERNAL policy** flow

##### Reproduction Steps
1. Build SDL with  **EXTERNAL policy**
2. Start HMI and SDL

##### Expected Behavior
SDL requests BC.GetSystemInfo one time

##### Observed Behavior
SDL requests BC.GetSystemInfo twice

##### OS & Version Information
* OS/Version: Ubuntu 18.04
* SDL Core Version: develop branch https://github.com/smartdevicelink/sdl_core/commit/9118fcdf8d5bfad411444513d44a59c8dfa6ff41
* Testing Against: atf test script

##### Test Case, Sample Code, and / or Example App
Script: https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/2377
[TestingReports.zip](https://github.com/smartdevicelink/sdl_core/files/4370411/TestingReports.zip)

**Comment by LitvinenkoIra** [comment]
@theresalech please triage this issue. This is not 6.1 regression issue, but anyway fix is ready in https://github.com/smartdevicelink/sdl_core/pull/3305 
Thank you!

**Comment by theresalech** [comment]
Hi @LitvinenkoIra, thanks for letting us know.  I'll share with the team.  Please note that if it's imperative this be included in the 6.1 release, it will need to be raised to the Steering Committee as high priority.  Thank you!

**Comment by iCollin** [comment]
Closed via #3305
