### ISSUE TITLE
Deadlock during transport re-connect via USB

### ISSUE THREAD

**Issue by GetmanetsIrina** [smartdevicelink/sdl_core#3323]
### Bug Report
Deadlock during transport re-connect via USB with Android device

##### Occurrences
2/30

##### Reproduction Steps
1. HMI and SDL are started
2. Register 3 mobile apps via USB
3. Perform transport re-connect

##### Expected Behavior
Mobile apps reconnect successfully.

##### Observed Behavior
Deadlock is occurred.

##### OS & Version Information
* sdl_hmi branch: [develop](https://github.com/smartdevicelink/sdl_hmi/tree/develop)
* commit: e8baa2d8f3f4b43d261323e0dd2c30843509e925
* sdl_core branch: https://github.com/smartdevicelink/sdl_core/tree/6.1.0_RC

##### Logs
[SmartDeviceLinkCore.zip](https://github.com/smartdevicelink/sdl_core/files/4437220/SmartDeviceLinkCore.zip)

**Comment by GetmanetsIrina** [comment]
@theresalech , Please triage this issue.

**Comment by theresalech** [comment]
Hi @GetmanetsIrina, can you please advise if Luxoft will be preparing a fix for this issue?

**Comment by LitvinenkoIra** [comment]
Hi @theresalech, yes, we are in progress with the fix. Thank you

**Comment by theresalech** [comment]
@LitvinenkoIra thank you!  Please let us know once the PR is ready for Livio review.

**Comment by SNiukalov** [comment]
@theresalech PR is ready for Livio team review. Thank you.

**Comment by ShobhitAd** [comment]
Closed via #3332
