### ISSUE TITLE
SDL sends response with "resultCode: GENERIC_ERROR" on GetVehicleData request in case vehicle data is not available

### ISSUE THREAD

**Issue by VjKlepikov** [smartdevicelink/sdl_core#3327]
**Bug Report**
SDL sends response with "resultCode: GENERIC_ERROR" on GetVehicleData request in case vehicle data is not available

**Reproduction Steps**

   1. Start SDL, HMI, connect Mobile, register new App
   2. Send GetVehicleData with speed = true
   3. Send HMI response with {"error":{"code":9,"data": {"method":"VehicleInfo.GetVehicleData"}, message:"error message" },"id":57,"jsonrpc":"2.0"}

**Expected Behavior**
   1. SDL sends to HMI VehicleInfo.GetVehicleData: "params": { "speed":true }
   2. SDL sends to mobile response of GetVehicleData with {"resultCode":"VEHICLE_DATA_NOT_AVAILABLE", "success":false, info = "error message"}

**Observed Behavior**
    1. SDL sends to HMI VehicleInfo.GetVehicleData: "params": { "speed":true }
    2. SDL sends to mobile response of GetVehicleData with {"resultCode":"GENERIC_ERROR","success":false}

**OS & Version Information**
    sdl_hmi branch: develop
    commit: 74d24927cf77282c44678eba219adadbb6dcd072
    sdl_core branch: https://github.com/smartdevicelink/sdl_core/tree/6.1.0_RC

**Test Case, Sample Code, and / or Example App**
Script: https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/2387
Report and Logs: 
[SDL_ATF_logs.zip](https://github.com/smartdevicelink/sdl_core/files/4450741/SDL_ATF_logs.zip)

**Comment by theresalech** [comment]
@VjKlepikov please advise if this is a regression issue introduced by Core 6.1, or if it is an issue that already exists in SDL Core.  Thank you!

**Comment by VjKlepikov** [comment]
@theresalech Please notice this is regression issue for 6.1 release
