### ISSUE TITLE
Build fails for EXTERNAL_PROPRIETARY policy mode

### ISSUE THREAD

**Issue by dboltovskyi** [smartdevicelink/sdl_core#3340]
### Bug Report
Build fails for EXTERNAL_PROPRIETARY policy mode

##### Reproduction Steps
1. Try to build SDL with `-DEXTENDED_POLICY=EXTERNAL_PROPRIETARY` cmake option

##### Expected Behavior
Build finished successfully

##### Observed Behavior
Build fails with error:
```
[ 24%] Linking CXX executable policyValidator
In file included from /home/developer/sdl/sdl_core/src/components/application_manager/include/application_manager/message_helper.h:46:0,
                 from /home/developer/sdl/sdl_core/src/components/application_manager/src/message_helper/message_helper.cc:36:
/home/developer/sdl/sdl_core/src/components/include/application_manager/policies/policy_handler_interface.h:354:13: error: ‘PTUIterationType’ does not name a type
       const PTUIterationType iteration_type =
```

##### OS & Version Information
* OS/Version: Ubuntu 18.04
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/tree/release/6.1.0 (ab90f16653)
* Testing Against: N/A

##### Test Case, Sample Code, and / or Example App
N/A

**Comment by dboltovskyi** [comment]
@theresalech Please triage this regression issue.

**Comment by theresalech** [comment]
@dboltovskyi thank you for reporting.  Can you please advise if the Luxoft team plans to submit a PR to resolve this issue?

**Comment by dboltovskyi** [comment]
@theresalech We appreciate if PM fixes this issue. Thank you.

**Comment by jacobkeeler** [comment]
Closing with the merge of #3341
