### ISSUE TITLE
Unit test in WebsocketSessionTest fails with core dump

### ISSUE THREAD

**Issue by ychernysheva** [smartdevicelink/sdl_core#3399]
### Bug Report
Currently on develop branch unit test WebsocketSessionTest._SendMessage_UnpreparedConnection_WithoutFall fails with ENABLE_GCOV=ON flag (on any policy flow).
##### Reproduction Steps
1. Build SDL core with flag ENABLE_GCOV=ON
2. Run command "make test"

##### Expected Behavior
No core dump

##### Observed Behavior

WebsocketSessionTest.SendMessage_UnpreparedConnection_WithoutFall
/home/developer/sdl/sdl_core/src/components/hmi_message_handler/test/hmi_message_handler_impl_test.cc:230: Failure
Death test: send_message()
    Result: died but not with expected exit code:
            Terminated by signal 11 (core dumped)
Actual msg:
[  DEATH   ] 
[  FAILED  ] WebsocketSessionTest.SendMessage_UnpreparedConnection_WithoutFall (4 ms)

Also following backtrace of core dump is available:
(gdb) bt
0x00005586c20509ee in gcov_do_dump ()
0x00005586c2051e22 in __gcov_dump_one ()
0x00005586c2052118 in __gcov_dump_int ()
0x00005586c2051faf in __gcov_flush ()
0x00005586c204ffd2 in __gcov_execve ()
0x00005586c1e0662d in testing::internal::ExecDeathTestChildMain (child_arg=0x7fff55fe7fd0) at /home/developer/sdl/sdl_core/src/3rd_party-static/gmock-1.7.0/gtest/src/gtest-death-test.cc:965
0x00007f850cde088f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

##### OS & Version Information
* OS/Version: Ubuntu 18.04
* SDL Core Version: 6.1.0
* gcc compiler version: 7.4

**Comment by iCollin** [comment]
Hello @ychernysheva does your team plan to make a fix or should PM investigate this issue?

**Comment by ychernysheva** [comment]
@iCollin Yes, I've already prepared potential fix for this issue, now this PR is on internal review.

**Comment by iCollin** [comment]
Closed via https://github.com/smartdevicelink/sdl_core/pull/3418
