### ISSUE TITLE
CCB: Fixed Issue related to SetAppIcon Path 

### ISSUE THREAD

**Issue by LuxoftAKutsan** [smartdevicelink/sdl_core#3406]
### Bug Report
set_app_icon_request modifying the path as a URL
Converting "!#$&'()*+,:;=?@[] " to there corresponding hex values. This function is
not required for path.

##### Reproduction Steps
1. Execute setupIconrequest with "!#$&'()*+,:;=?@[] " 

##### Expected Behavior

"!#$&'()*+,:;=?@[] " transferent to HMI as is 

##### Observed Behavior
"!#$&'()*+,:;=?@[] " converted to hex values

##### OS & Version Information
* OS/Version: QNX 7.0 
* SDL Core Version: [5.0.1]( https://github.com/smartdevicelink/sdl_core/releases/tag/5.0.1) integrated to SYNC environment   
* Testing Against:  SyncProxy tester

**Comment by jacobkeeler** [comment]
Closing with the merge of #3407
