### ISSUE TITLE
CCB: AppLink; Apps do not load when Waze is active 

### ISSUE THREAD

**Issue by LuxoftAKutsan** [smartdevicelink/sdl_core#3408]
### Bug Report
App resuming Flag is not cleared if resumption fails and also not cleared when the resuming app is activated. which causes  HMIstate to mismatch with the hmilevel of HMI. i.e instead of FULL it stays background

##### Reproduction Steps
TODO : transfer from SYNC4 

##### Expected Behavior
TODO : transfer from SYNC4 

##### Observed Behavior
TODO : transfer from SYNC4 

##### OS & Version Information
* OS/Version: QNX 7.0 
* SDL Core Version: [5.0.1]( https://github.com/smartdevicelink/sdl_core/releases/tag/5.0.1) integrated to SYNC environment   
* Testing Against: Wase

**Comment by AKalinich-Luxoft** [comment]
Issue has been already fixed in #3550 - similar changes as in CCB were provided
