### ISSUE TITLE
CCB: Co-Existence: Dummy Icon remains when iOS device is disconnected

### ISSUE THREAD

**Issue by LuxoftAKutsan** [smartdevicelink/sdl_core#3409]
### Bug Report
Co-Existence: Dummy Icon remains when iOS device is disconnected 

##### Reproduction Steps
Pre-Condition:
1. bench Up and running
2. iOS device available with supported applink apps
3. iOS connected via USB

How To Reproduce:
1. When CP message is displayed accepts terms to have CP available
2. In Apps page applink mobile apps should load
3. disconnect device
4. repeat until issue is seen

##### Expected Behavior
no icon should remain when device is not connected

##### Observed Behavior
dummy icon remains for this example it was Accuweather. 

##### OS & Version Information
* OS/Version: QNX 7.0 
* SDL Core Version: [5.0.1]( https://github.com/smartdevicelink/sdl_core/releases/tag/5.0.1) integrated to SYNC environment   
* Testing Against: Accuweather

**Comment by jacobkeeler** [comment]
Closing with the merge of #3617
