### ISSUE TITLE
Generic Error is getting with in 30 -40 sec while performing Perfrom Interction"BOTH"

### ISSUE THREAD

**Issue by LuxoftAKutsan** [smartdevicelink/sdl_core#3413]
### Bug Report
Pre-Requisite:
1. Turn IGN to Run
2. Android device is connected to the SYNC via BT
3. Make sure SyncProxyTester(App ID: 584421907) is registered to SYNC.
4. Make sure policy table is updated

##### Reproduction Steps

1. Select Apps from Status/Interaction bar and select SyncProxyTester app
2. Send CreateInteractionChoiceSet RPC with default values.
3. Send PerformInteraction RPC with Interaction Mode as "BOTH"

##### Expected Behavior
Generic Error is getting with in 30 -40 sec while performing Perfrom Interction"BOTH"

##### Observed Behavior
Generic Error is getting with in 30 -40 sec while performing Perfrom Interction"BOTH"

##### OS & Version Information
OS/Version: QNX 7.0
SDL Core Version: 5.0.1 integrated to SYNC environment
Testing Against:

**Comment by VjKlepikov** [comment]
Issue is not reproduced on the https://github.com/smartdevicelink/sdl_core/tree/develop (31324d5)
