### ISSUE TITLE
SSL Context should use MACRO instead of direct struct access

### ISSUE THREAD

**Issue by mrapitis** [smartdevicelink/sdl_core#3421]
### Bug Report
SDL Core will not build with security enabled when using OpenSSL 1.1 because the SSL context used inside of ResetConnection is directly accessing the underlying structure inside of the connection.  Instead the context should be referenced by the proper MACRO which will allow core to build with OpenSSL 1.1 as well as older versions.

Replacing the line linked below with the following code snippet resolves this issue
https://github.com/smartdevicelink/sdl_core/blob/master/src/components/security_manager/src/ssl_context_impl.cc#L599
```SSL_CTX* ssl_context = SSL_get_SSL_CTX(connection_);```

##### Reproduction Steps
Clone SDL Core and attempt to build on a system with security enabled while using OpenSSL 1.1

##### Expected Behavior
Build is performed successfully

##### Observed Behavior
Error when attempting to build

##### OS & Version Information
* OS/Version: Ubuntu 18.04
* SDL Core Version: 6.1.1

**Comment by dboltovskyi** [comment]
@mrapitis Please notice this issue may be related to https://github.com/smartdevicelink/sdl_core/issues/3220

**Comment by iCollin** [comment]
Closed via https://github.com/smartdevicelink/sdl_core/pull/3582
