### ISSUE TITLE
[SDL 0308] Add a Reason Parameter to All Protocol NAKs

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_core#3434]
Proposal: [Add a Reason Parameter to All Protocol NAKs](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0308-protocol-nak-reason.md)

> As a maintainer of an app library, it is often difficult to understand why Core has NAKed a protocol message. Most NAKs currently have a `rejectedParams` parameter, but in practice, this has not been enough information to determine why a NAK has occurred and properly alert the developer. In place of the `rejectedParams` parameter, the `RegisterSecondaryTransportNAK` has a `reason` parameter to describe the failure reason. This is a better approach and we should expand it to all NAK parameters.

Review: https://github.com/smartdevicelink/sdl_evolution/issues/1027

**Comment by ShobhitAd** [comment]
Closed via https://github.com/smartdevicelink/sdl_core/pull/3462
