### ISSUE TITLE
Duplicated conversion functions in different SDL places

### ISSUE THREAD

**Issue by ychernysheva** [smartdevicelink/sdl_core#3448]
### Bug Report

We have lots of similar conversion functions, which are located in different SDL places (MessageHelper, RAI request, Application Manager etc.). This conversion functions are duplicates of each other in terms of conversion from string to enum and vice versa. There is no unified approach to perform this conversion, that's why in similar functions this operation is realized by different means (for example, using map, switch or SchemaItem-based convertor).

Many of this functions are present in MessageHelper as static public methods, which have corresponding mocked methods, used in unit tests. That's why in unit tests we cannot check actual values of converted enums, because now this values are hard-coded in expectations of mocked methods. Also presence of duplicated methods increases possibility of errors and makes code less clear and consistent.

##### OS & Version Information
* OS/Version: Ubuntu 18
* SDL Core Version: 6.1

**Comment by jacobkeeler** [comment]
Closing via #3449
