### ISSUE TITLE
If we want to port sdl to our platform , which  version is suggested to start with？

### ISSUE THREAD

**Issue by kingtheus** [smartdevicelink/sdl_core#345]
There are many tags & branches like 4.0RC2, 4.0.1, 4.0.2 etc, 

Which one is the best to start with ?

thanks in advance.

**Comment by huaguoping** [comment]
The latest released version。

**Comment by JackLivio** [comment]
The 'latest released' version was merged into the master branch. Use the master branch as it is the most up to date and stable version of SDL Core.
