### ISSUE TITLE
SDL doesn't send RC.SetGlobalProperties during resumption

### ISSUE THREAD

**Issue by dboltovskyi** [smartdevicelink/sdl_core#3469]
### Bug Report
SDL doesn't send RC.SetGlobalProperties during resumption

##### Reproduction Steps
1. Start SDL, HMI, connect Mobile device, register application
2. Send `SetGlobalProperties` with `userLocation` parameter
=> SDL sends `RC.SetGlobalProperties` request to HMI and after receiving succesful response sends `OnHashChange` notification to the app
3. Perform unexpected disconnect and then reconnect (with correct hashId)
=> SDL starts resumption procedure

##### Expected Behavior
SDL sends RC.SetGlobalProperties during resumption trying to restore global properties

##### Observed Behavior
SDL doesn't send RC.SetGlobalProperties during resumption

##### OS & Version Information
* OS/Version: Ubuntu 18.04
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/tree/develop (6560d02)
* Testing Against: ATF

##### Test Case, Sample Code, and / or Example App
 - ATF Script: [3469.lua.tar.gz](https://github.com/smartdevicelink/sdl_core/files/5008643/3469.lua.tar.gz)
 - Report and logs: [2020-07-31_15-07-07_3469.tar.gz](https://github.com/smartdevicelink/sdl_core/files/5008646/2020-07-31_15-07-07_3469.tar.gz)

**Comment by LitvinenkoIra** [comment]
Please notice issue is also applicable for 6.1.1 Release

**Comment by dboltovskyi** [comment]
It looks like issue is also applicable for `UI.SetGlobalProperties`
E.g.: if App defined keyboard properties:
```
  keyboardProperties = {
    language = "EN-US",
    keyboardLayout = "AZERTY",
    keypressMode = "SINGLE_KEYPRESS"
```
And then disconnects/reconnects SDL won't send `UI.SetGlobalProperties` during resumption.
Please see: [2020-12-14_14-28-12.786_FAIL.tar.gz](https://github.com/smartdevicelink/sdl_core/files/5691142/2020-12-14_14-28-12.786_FAIL.tar.gz)

However if App provides 2 additional parameters `vrHelpTitle` and `vrHelp` along with the previous ones SDL sends `UI.SetGlobalProperties` during resumption correctly with all required data.
Please see: [2020-12-14_14-29-59.771_SUCCESS.tar.gz](https://github.com/smartdevicelink/sdl_core/files/5691151/2020-12-14_14-29-59.771_SUCCESS.tar.gz)

**Comment by iCollin** [comment]
Closed via https://github.com/smartdevicelink/sdl_core/pull/3622
