### ISSUE TITLE
bson_c_lib build failed

### ISSUE THREAD

**Issue by SNiukalov** [smartdevicelink/sdl_core#3473]
When we build sdl_core first time and have no pre-built bson_c_lib, then sometimes build fails.

### Bug Report
lua/Makefile.am:5: error: 'luaexec_LTLIBRARIES' is used but 'luaexecdir' is undefined
lua/Makefile.am:6: warning: variable 'bson4lua_la_SOURCES' is defined but no program or
lua/Makefile.am:6: library has 'bson4lua_la' as canonical name (possible typo)
lua/Makefile.am:7: warning: variable 'bson4lua_la_LIBADD' is defined but no program or
lua/Makefile.am:7: library has 'bson4lua_la' as canonical name (possible typo)
/usr/share/automake-1.15/am/ltlibrary.am: warning: 'libbson.la': linking libtool libraries using a non-POSIX
/usr/share/automake-1.15/am/ltlibrary.am: archiver requires 'AM_PROG_AR' in 'configure.ac'
src/Makefile.am:7:   while processing Libtool library 'libbson.la'
/usr/share/automake-1.15/am/ltlibrary.am: warning: 'libemhashmap.la': linking libtool libraries using a non-POSIX
/usr/share/automake-1.15/am/ltlibrary.am: archiver requires 'AM_PROG_AR' in 'configure.ac'
src/emhashmap/Makefile.am:7:   while processing Libtool library 'libemhashmap.la'
Makefile:384: recipe for target 'Makefile.in' failed
make[3]: *** [Makefile.in] Error 1
src/3rd_party/CMakeFiles/libbson.dir/build.make:110: recipe for target 'src/3rd_party/libbson-prefix/src/libbson-stamp/libbson-build' failed
make[2]: *** [src/3rd_party/libbson-prefix/src/libbson-stamp/libbson-build] Error 2
CMakeFiles/Makefile2:299: recipe for target 'src/3rd_party/CMakeFiles/libbson.dir/all' failed
make[1]: *** [src/3rd_party/CMakeFiles/libbson.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

##### Reproduction Steps
branch: master
1. Download library 
2. ./configure
3. make

##### OS & Version Information
* Ubuntu 18.04.3 LTS

**Comment by jacobkeeler** [comment]
Seems this was fixed with https://github.com/smartdevicelink/bson_c_lib/pull/52, closing for now.
Feel free to reopen if you are still experiencing the issue
