### ISSUE TITLE
 SDL sometimes sends Navi.SubscribeVehicleData without parameters during resumption

### ISSUE THREAD

**Issue by dboltovskyi** [smartdevicelink/sdl_core#3501]
### Bug Report
 SDL sometimes sends Navi.SubscribeVehicleData without parameters during resumption

##### Occurrences:
~1%

##### Reproduction Steps
1. AddSubMenu related to resumption is sent by App1
2. App1 and App2 are subscribed to the same VehicleData
3. Unexpected disconnect and reconnect are performed
4. App1 and App2 re-register with actual HashId

##### Expected Behavior
SDL starts resumption process for App1 and App2
SDL sends `Navi.SubscribeVehicleData` with required parameters

##### Observed Behavior
SDL sends `Navi.SubscribeVehicleData` without parameters

##### OS & Version Information
* OS/Version: Ubuntu 18.04
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/tree/develop (a36ea82)
* Testing Against: ATF

##### Test Case, Sample Code, and / or Example App
 - ATF Script: [038_Another_RPC_VD_RAI2_before_request_to_HMI](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Resumption/Handling_errors_from_HMI/038_Another_RPC_VD_RAI2_before_request_to_HMI.lua)
 - Report and Logs: [2020-09-14_13-59-02_3501.tar.gz](https://github.com/smartdevicelink/sdl_core/files/5220366/2020-09-14_13-59-02_3501.tar.gz)

**Comment by dboltovskyi** [comment]
@theresalech Please notice this is regression issue which is related to implementation of [[SDL 0190] Handle response from HMI during resumption data](https://github.com/smartdevicelink/sdl_core/issues/2486) proposal.
Luxoft team is going to prepare a fix.

**Comment by theresalech** [comment]
@dboltovskyi thank you! Please let us know when the fix is ready for Livio review.
