### ISSUE TITLE
SDL sometimes doesn't revert the VehicleInfo subscription during resumprion 

### ISSUE THREAD

**Issue by dboltovskyi** [smartdevicelink/sdl_core#3503]
### Bug Report
SDL sometimes doesn't revert the VehicleInfo subscription during resumprion 

##### Occurrences:
~0.3%

##### Reproduction Steps
1. AddCommand, AddSubMenu, CreateInteractionChoiceSet, SetGlobalProperties, SubscribeButton, SubscribeVehicleData,
 SubscribeWayPoints, CreateWindow (<Rpc_n>) are sent by app
2. Unexpected disconnect and reconnect are performed
3. App re-registers with actual HashId
SDL does:
 - start resumption process
 - send set of <Rpc_n> requests to HMI
4. HMI responds with <erroneous> resultCode to one request and <successful> for others

##### Expected Behavior
SDL does:
 - process responses from HMI
 - remove already restored data

##### Observed Behavior
SDL does not remove already restored VehicleInfo data

##### OS & Version Information
* OS/Version: Ubuntu 18.04
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/tree/develop (a36ea82)
* Testing Against: ATF

##### Test Case, Sample Code, and / or Example App
 - ATF Script: [023_resume_all_data_with_one_error_rpc_unexpected_disconnect_limited.lua.tar.gz](https://github.com/smartdevicelink/sdl_core/files/5220807/023_resume_all_data_with_one_error_rpc_unexpected_disconnect_limited.lua.tar.gz)
This is modified version of [023_resume_all_data_with_one_error_rpc_unexpected_disconnect_limited](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Resumption/Handling_errors_from_HMI/023_resume_all_data_with_one_error_rpc_unexpected_disconnect_limited.lua) in order to catch the issue faster
 - Report and Logs: [2020-09-14_16-16-27_3503.tar.gz](https://github.com/smartdevicelink/sdl_core/files/5220817/2020-09-14_16-16-27_3503.tar.gz)

**Comment by dboltovskyi** [comment]
@theresalech Please notice this is regression issue which is related to implementation of [[SDL 0190] Handle response from HMI during resumption data](https://github.com/smartdevicelink/sdl_core/issues/2486) proposal.
Luxoft team is going to prepare a fix.

**Comment by theresalech** [comment]
@dboltovskyi thank you! Please let us know when the fix is ready for Livio review.

**Comment by iCollin** [comment]
Closed via #3515
