### ISSUE TITLE
SDL sends GetInteriorVehicleData response with moduleData = null in case of erroneous response type for GetInteriorVehicleData from HMI

### ISSUE THREAD

**Issue by AKalinich-Luxoft** [smartdevicelink/sdl_core#3514]
**Preconditions:**
1) sdl_preloaded_pt.json default app_policies
groups: [ "Base-4", "RemoteControl" ]
"moduleType": [ "RADIO", "CLIMATE", "SEAT", "AUDIO", "LIGHT", "HMI_SETTINGS" ]
HMI supports RC functionality
2) SDL and HMI started

**Reproduction Steps:**
1. App→SDL: GetInteriorVehicleData("moduleType": "module_1", subscribe = true )
SDL→HMI: RC.GetInteriorVehicleData("moduleType": "module_1", subscribe = true )
HMI→SDL: RC.GetInteriorVehicleData( GENERIC_ERROR)
{"error":{"code":22,"message":"Erroneous response is assigned by settings","data": {"method":"RC.GetInteriorVehicleData"}
}}

**Observed Behavior:**
SDL→App: GetInteriorVehicleData("moduleData":null, "resultCode": "GENERIC_ERROR", "success": "false", info )

**Expected Behavior:**
SDL→App: GetInteriorVehicleData( "resultCode": "GENERIC_ERROR", "success": "false", info )

**OS & Version Information**
https://github.com/LuxoftSDL/sdl_core/tree/develop (a36ea82) 
https://github.com/LuxoftSDL/sdl_hmi/tree/develop (6d32f1b)

**Comment by dboltovskyi** [comment]
@theresalech Please notice this is not regression issue and it's applicable for Release `6.1.1`

**Comment by theresalech** [comment]
@dboltovskyi, thank you for letting us know. We are currently focused on regression issues (issues introduced during Core 7.0 development), and existing issues that were previously prioritized by the Steering Committee for the Core 7.0 release. We'll therefore look at this issue/PR when time allows, following the regression and previously prioritized issues. Thanks!

**Comment by AKalinich-Luxoft** [comment]
@theresalech Please notice PR is ready for PM review.

**Comment by theresalech** [comment]
@AKalinich-Luxoft, thank you for letting us know! This issue was not requested as priority for the next Core release, but we will try to review as time allows. If it's imperative this be included in the next release, please raise as priority to the SDLC Steering Committee. Thanks!

**Comment by ShobhitAd** [comment]
Closed via https://github.com/smartdevicelink/sdl_core/pull/3565
