### ISSUE TITLE
SDL sends GetInteriorVehicleData response with "success":false in case success type of response(resultCode: WRONG_LANGUAGE, RETRY, SAVED) from HMI 

### ISSUE THREAD

**Issue by VjKlepikov** [smartdevicelink/sdl_core#3517]
**Preconditions:**
1. SDL and HMI started

**Reproduction Steps:**
Mobile app sends GetInteriorVehicleData("module_1",  subscribe = true) request
*App→SDL:* GetInteriorVehicleData("moduleType": "module_1",  subscribe = true )
*SDL→HMI:* RC.GetInteriorVehicleData("moduleType": "module_1", subscribe = true )
*HMI→SDL:* RC.GetInteriorVehicleData(*"code":16*, "moduleType": "module_1",* isSubscribed = true* , values same as shown on HMI, SUCCESS)

**Observed Behavior:**
*SDL→App:* GetInteriorVehicleData(*"success":**false**, "moduleType": "module_1", values same as shown on HMI, SUCCESS)

**Expected Behavior:**
*SDL→App:* GetInteriorVehicleData(*"success":**true**, "moduleType": "module_1", *isSubscribed = true* , values same as shown on HMI, SUCCESS)
*SDL→App:* OnHashChange(hashID) notification

**OS & Version Information**
SDL: https://github.com/smartdevicelink/sdl_core/commits/develop (a36ea82)
HMI: https://github.com/smartdevicelink/sdl_hmi/tree/develop (6d32f1b)

**Comment by dboltovskyi** [comment]
@theresalech Please notice this issue related to the [SDL-0188 Interior Vehicle Data resumption](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0188-get-interior-data-resumption.md) proposal which is in scope of `7.0` Release. It aligns error handling for `GetInteriorVehicleData` RPC in general and resumption scenarios.
Luxoft team is going to prepare a fix.

**Comment by theresalech** [comment]
@dboltovskyi, please advise when a fix is ready for Livio's review. Thank you!

**Comment by iCollin** [comment]
Closed via #3519
