### ISSUE TITLE
SDL sometimes finishes resumption successfully even if error has been received from HMI 

### ISSUE THREAD

**Issue by dboltovskyi** [smartdevicelink/sdl_core#3522]
### Bug Report
SDL sometimes finishes resumption successfully even if error has been received from HMI 

##### Occurrences:
~0.01% (very rare)

##### Reproduction Steps
1. App sends `AddCommand` request (which is stored by SDL as resumption data)
2. App adds some other resumption data (e.g. SubMenu, VD and WP subscription etc.)
3. Unexpected disconnect and reconnect are performed
4. App re-register with actual HashId
5. SDL starts resumption process for App and sends all required requests to HMI
6. HMI replies with erroneous response to one of the requests (e.g. `VR.AddCommand`)

##### Expected Behavior
SDL fails resumption and send `RESUME_FAILED` to app

##### Observed Behavior
SDL successfully finishes resumption and send `SUCCESS` to app

##### OS & Version Information
* OS/Version: Ubuntu 18.04
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/tree/develop (a36ea82)
* Testing Against: ATF

##### Test Case, Sample Code, and / or Example App
 - ATF Script: [004_resume_one_rpc_with_error_result_code_ign_off](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Resumption/Handling_errors_from_HMI/004_resume_one_rpc_with_error_result_code_ign_off.lua)
 - Report and Logs: [2020-09-29_21-34-37_3522.tar.gz](https://github.com/smartdevicelink/sdl_core/files/5302722/2020-09-29_21-34-37_3522.tar.gz)

**Comment by dboltovskyi** [comment]
@theresalech Please notice this issue is related to [SDL-0190 Handle response from HMI during resumption data](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0190-resumption-data-error-handling.md) proposal which is in scope of `7.0` Release

**Comment by theresalech** [comment]
@dboltovskyi, thank you. Please let us know once the fix is ready for Livio's review.

**Comment by iCollin** [comment]
Closed via #3525
