### ISSUE TITLE
SDL transfers AddSubMenu request with non-existent parentID parameter to HMI

### ISSUE THREAD

**Issue by VjKlepikov** [smartdevicelink/sdl_core#3524]
### Bug Report
SDL transfers AddSubMenu request with non-existent parentID parameter to HMI

#### Preconditions:

1. SDL and HMI are started
2. Mobile device connected
3. Mobile app is registered and activated

##### Reproduction Steps
1. Add submenu item AddSubMenu RPC with non-existent parentID parameter
AddSubMenu(parentID=1) 

##### Expected Behavior
APP→SDL: AddSubMenu ( "menuName":"Submenu Name 1","parentID":1, "menuID":1 )
SDL→APP: AddSubMenu ( resultCode: INVALID_ID, success=false ).

##### Observed Behavior
APP→SDL: AddSubMenu ( "menuName":"Submenu Name 1","parentID":1, "menuID":1 )
SDL→HMI: UI.AddSubMenu ( params, "menuParams":{"menuName":"Submenu Name 1","parentID":1,"position":0}, "menuID":1} )

##### OS & Version Information
SDL: https://github.com/smartdevicelink/sdl_core/commits/develop (9f61819)
HMI: https://github.com/smartdevicelink/sdl_hmi/tree/develop (f712d4e)

##### Test Case, Sample Code, and / or Example App
Logs:[SDL_logs.zip](https://github.com/smartdevicelink/sdl_core/files/5313925/SDL_logs.zip)

**Comment by dboltovskyi** [comment]
@theresalech Please notice issue is related to [SDL-0148 Additional SubMenus](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0148-template-additional-submenus.md) proposal which is in scope of `7.0` Release.
Luxoft team is going to prepare a fix.

**Comment by theresalech** [comment]
@dboltovskyi, thank you for letting us know. Please advise when a PR is ready for Livio review.

**Comment by iCollin** [comment]
Closed via https://github.com/smartdevicelink/sdl_core/pull/3534
