### ISSUE TITLE
SDL does not transfer OnSystemCapabilityUpdated notification to App after IGN_OFF/IGN_ON cycle

### ISSUE THREAD

**Issue by VjKlepikov** [smartdevicelink/sdl_core#3532]
### Bug Report
SDL does not transfer OnSystemCapabilityUpdated notification from HMI to an App after IGN_OFF/IGN_ON cycle in case App sent Show RPC with `templateConfiguration` parameter for widget window after `Show` response

#### Preconditions:
1) In sdl_preloaded_pt.json default app_policies groups:
["Base-4", "WidgetSupport" ]
2) SDL and HMI are started
3) App is registered and activated(App has hmi level FULL/LIMITED )
4) App created and activated a widget ( the widget has "hmi_level": FULL )
5) IGN_OFF and IGN_ON are performed
6) App is registered with actual hashId
7) Widget is activated

##### Reproduction Steps
App sends "Show" request with "templateConfiguration" param for the restored widget
HMI sends BC.OnSystemCapabilityUpdated:
HMI→SDL: "BC.OnSystemCapabilityUpdated"(params)

##### Expected Behavior
SDL→App: “OnSystemCapabilityUpdated” (params)

##### Observed Behavior
SDL does not transfer OnSystemCapabilityUpdated(params) to Mobile App

##### OS & Version Information
SDL: https://github.com/smartdevicelink/sdl_core/commits/develop (9f61819)
HMI: https://github.com/smartdevicelink/sdl_hmi/tree/develop (f712d4e)

**Comment by VjKlepikov** [comment]
@theresalech Please notice this is regression issue

**Comment by iCollin** [comment]
Closed via https://github.com/smartdevicelink/sdl_core/pull/3550
