### ISSUE TITLE
SDL core dump during app activation

### ISSUE THREAD

**Issue by dboltovskyi** [smartdevicelink/sdl_core#3535]
### Bug Report
SDL core dump observed during app activation. 
Issue is reproduced only at `Ubuntu 16.04` and not reproducible at `Ubuntu 18.04`

##### Reproduction Steps
1. Start SDL, init HMI, connect Mobile device
2. Register new mobile Application
3. Activate application on HMI

##### Expected Behavior
Application activated successfully

##### Observed Behavior
SDL crashed

##### OS & Version Information
* OS/Version: Ubuntu 16.04
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/tree/release/7.0.0 (87ff1bb)
* Testing Against: SPT

##### Test Case, Sample Code, and / or Example App
 - Trace: [Trace.txt.tar.gz](https://github.com/smartdevicelink/sdl_core/files/5349188/Trace.txt.tar.gz)
 - SDL log: [SmartDeviceLinkCore.log.tar.gz](https://github.com/smartdevicelink/sdl_core/files/5349185/SmartDeviceLinkCore.log.tar.gz)

**Comment by dboltovskyi** [comment]
Issue is not reproduced at  https://github.com/smartdevicelink/sdl_core/tree/release/7.0.0 (876856f)

**Comment by dboltovskyi** [comment]
@theresalech Please notice this is regression issue

**Comment by iCollin** [comment]
Thank you for noticing. Closed via #3536
