### ISSUE TITLE
SDL does not send reason info in NACK message to mobile app in specific cases

### ISSUE THREAD

**Issue by GetmanetsIrina** [smartdevicelink/sdl_core#3539]
### Bug Report
SDL does not send reason info in NACK messages to a mobile app in specific cases

##### Reproduction Steps
1. SDL and HMI are started
2. Mobile app is registered via 5.3 protocol and with `NAVIGATION` HMI type

##### Reproduction Steps
1. Mobile app requests start service in not appropriate HMI level.
or
2. Mobile app requests start service with not appropriate HMI type (not NAVI)
or
3. Mobile app requests protected start service in case service should be not protected according to settings in *.ini file
or
4. Mobile app requests unprotected start service in case service should be protected according to settings in *.ini file

##### Expected Behavior
SDL provides a reason in NACK message to mobile app

##### Observed Behavior
SDL does not provide a reason in NACK message to mobile app

##### OS & Version Information
* OS/Version: 18.04
* SDL Core Version: release/7.0.0 (fd291d76)
* HMI: develop(6d32f1ba)
* ATF: develop

**Comment by GetmanetsIrina** [comment]
@theresalech Please notice the issue is related to [SDL-0308 Add a Reason Parameter to All Protocol NAKs](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0308-protocol-nak-reason.md) proposal which is in the scope of 7.0 Release.
Luxoft team is going to prepare a fix.

**Comment by theresalech** [comment]
@GetmanetsIrina, thanks for letting me know. Please advise when Luxoft has a PR ready for Livio review!

**Comment by jacobkeeler** [comment]
Closed via #3545
