### ISSUE TITLE
Resumption for menuLayout does not occur within SetGlobalProperties, AddSubMenu RPCs

### ISSUE THREAD

**Issue by GetmanetsIrina** [smartdevicelink/sdl_core#3541]
### Bug Report
Resumption for `menuLayout` does not occur

##### Preconditions
1. SDL and HMI are started
2. Mobile app is registered and activated
3. Mobile app requests `SetGlobalProperties`/`AddSubMenu` with all mandatory params and `menuLayout`
4. `SetGlobalProperties` is set successfully/`AddSubMenu` is added successfully

##### Reproduction Steps
1. Perform Ignition off and ignition on/ transport reconnect
2. Mobile app registers with actual hashID 

##### Expected Behavior
SDL resumes `SetGlobalProperties`/`AddSubMenu`  with the same data added by the app

##### Observed Behavior
SDL resumes `SetGlobalProperties`/`AddSubMenu` without `menuLayout`

##### OS & Version Information
* OS/Version: 18.04
* SDL Core Version: tag 7.0.0-RC1 5c72cddc35
* Testing Against: HMI: develop 727d0d3, SPT: 20201007 

##### Logs:
[SmartDeviceLinkCore.zip](https://github.com/smartdevicelink/sdl_core/files/5377496/SmartDeviceLinkCore.zip)

**Comment by iCollin** [comment]
Closed via https://github.com/smartdevicelink/sdl_core/pull/3733
