### ISSUE TITLE
CMake warning when EXTERNAL_PROPRIETARY flag is used

### ISSUE THREAD

**Issue by dboltovskyi** [smartdevicelink/sdl_core#3544]
### Bug Report
CMake warning is shown during SDL build when EXTERNAL_PROPRIETARY flag is used

##### Reproduction Steps
1. Build SDL in `EXTERNAL_PROPRIETARY` policy mode:
```
cmake ../sdl_core -DEXTENDED_POLICY=EXTERNAL_PROPRIETARY
```
##### Expected Behavior
No warning messages are displayed.

##### Observed Behavior
Warning message is shown:
```
CMake Warning (dev) at CMakeLists.txt:436 (add_dependencies):
  Policy CMP0046 is not set: Error on non-existent dependency in
  add_dependencies.  Run "cmake --help-policy CMP0046" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  The dependency target "copy_policy_library" of target "smartDeviceLinkCore"
  does not exist.
This warning is for project developers.  Use -Wno-dev to suppress it.
```

##### OS & Version Information
* OS/Version: Ubuntu 18.04
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/tree/release/7.0.0 (3ec2b6b)
* Testing Against: N/A

##### Notes
Issue is not applicable for `PROPRIETARY` and `HTTP` policy modes

**Comment by jacobkeeler** [comment]
Closing with the merge of #3730
