### ISSUE TITLE
SDL sometimes doesn't send required number of StartStream/StartAudioStream requests

### ISSUE THREAD

**Issue by dboltovskyi** [smartdevicelink/sdl_core#3547]
### Bug Report
During start of Video(Audio) streaming SDL sends `Navigation.StartStream` (`Navigation.StartAudioStream`) requests to HMI and waiting for response. In case if HMI responds with erroneous code SDL re-send the same request several times (equal to `StartStreamRetry` .ini parameter). SDL sometimes doesn't send required number of such requests

##### Occurrences
~10-15%

##### Reproduction Steps
1. Navi app is registered and activated
2. App try to start Video(Audio) service
=> SDL does send `Navi.StartStream` (`Navi.StartAudioStream`) requests to HMI
3. HMI responds with `REJECTED`

##### Expected Behavior
SDL re-sends `Navi.StartStream` (`Navi.StartAudioStream`) requests to HMI a few times (equal to `StartStreamRetry` .ini parameter)

##### Observed Behavior
SDL doesn't send required number of requests
There is an error in log for Video:
```
ERROR [21 Oct 2020 15:56:56,257][140043616237312][Commands] /home/developer/sdl/sdl_core/src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/hmi/navi_start_stream_request.cc:155 commands::NaviStartStreamRequest::RetryStartSession: NaviStartStreamRequest aborted. Application not found
```
There is an error in log for Audio:
```
ERROR [21 Oct 2020 16:29:37,566][0x7f311ffff700][Commands] /home/developer/sdl/sdl_core/src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/hmi/navi_audio_start_stream_request.cc:156 commands::AudioStartStreamRequest::RetryStartSession: StartAudioStreamRequest aborted. Application not found
```

##### OS & Version Information
* OS/Version: Ubuntu 18.04
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/tree/release/7.0.0 (3ec2b6b)
* Testing Against: ATF

##### Test Case, Sample Code, and / or Example App
 - ATF Script: [3547_RetryStrategy_for_start_streaming.lua.tar.gz](https://github.com/smartdevicelink/sdl_core/files/5417611/3547_RetryStrategy_for_start_streaming.lua.tar.gz)
 - Report and Logs: [2020-10-21_11-56-44.289_3547.tar.gz](https://github.com/smartdevicelink/sdl_core/files/5417610/2020-10-21_11-56-44.289_3547.tar.gz)

**Comment by dboltovskyi** [comment]
Issue is also applicable for `6.1.1` release

**Comment by dboltovskyi** [comment]
@theresalech Please notice this is regression issue. Luxoft team is going to submit a fix.

**Comment by theresalech** [comment]
@dboltovskyi, we are defining regression issues as issues introduced by Core 7.0 development. If this issue is present in 6.1.1, it was not introduced in 7.0 and is therefore not considered regression. However, if you are able to submit a fix, we will do our best to review and include in the next 7.0 Release Candidate, which will be delivered to the Steering Committee for approval on November 2. Note that issues introduced by Core 7.0 will take priority at this time. Thank you!

**Comment by dboltovskyi** [comment]
@theresalech Please notice we found out this issue may lead to core dump in some scenarios (please see setails in https://github.com/smartdevicelink/sdl_core/pull/3552)
We would appreciate for PM review of the fix in `sdl_core` and update in `sdl_atf_test_scripts` if time allows.

**Comment by iCollin** [comment]
Closed via https://github.com/smartdevicelink/sdl_core/pull/3552
