### ISSUE TITLE
SDL sometimes doesn't send BC.OnAppUnregistered in case HMI close an app with RESOURCE_CONSTRAINT reason

### ISSUE THREAD

**Issue by dboltovskyi** [smartdevicelink/sdl_core#3561]
### Bug Report
SDL sometimes doesn't send BC.OnAppUnregistered in case HMI close an app with RESOURCE_CONSTRAINT reason.

##### Occurrences
~0.5%

##### Reproduction Steps
1. SDL and HMI are started
2. App is registered on default mobile connection
3. App is activated
4. HMI sends `BC.OnExitApplication` with reason: `RESOURCE_CONSTRAINT` related to App to SDL

##### Expected Behavior
SDL sends `BC.OnAppUnregistered` notification to HMI

##### Observed Behavior
SDL doesn't send notification to HMI

##### OS & Version Information
* OS/Version: Ubuntu 18.04
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/tree/release/7.0.0 (80973f4)
* Testing Against: ATF

##### Test Case, Sample Code, and / or Example App
 - ATF Script: [025_OnExitApplication_RESOURCE_CONSTRAINT_one_app](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/WebEngine/WebEngineProjection/025_OnExitApplication_RESOURCE_CONSTRAINT_one_app.lua) - needs to me run 1000 times
 - Report and Logs: [2020-10-29_22-43-00_3561.tar.gz](https://github.com/smartdevicelink/sdl_core/files/5467012/2020-10-29_22-43-00_3561.tar.gz)

**Comment by AKalinich-Luxoft** [comment]
@theresalech please notice this is not a regression issue related to wrong behavior of TCP transport with a pretty low occurrence.
PR with fix is linked and ready for Livio review

**Comment by theresalech** [comment]
@AKalinich-Luxoft, thank you for letting us know! If Luxoft would like to make this issue a priority for the next Core release (planned for April 2021), please make sure it is raised to the SDLC Steering Committee as such.

**Comment by ShobhitAd** [comment]
Closed via https://github.com/smartdevicelink/sdl_core/pull/3566
