### ISSUE TITLE
SDL sometimes sends 2 requests to HMI with the same id

### ISSUE THREAD

**Issue by dboltovskyi** [smartdevicelink/sdl_core#3564]
### Bug Report
SDL sometimes sends 2 requests to HMI with the same id. 
There is a requirement for SDL that each request should have unique Id.

##### Occurrences
~0.1% (very rare)

##### Reproduction Steps
1. Start SDL
2. Start HMI
3. Check Ids of requests from SDL to HMI

##### Expected Behavior
Ids are unique

##### Observed Behavior
Sometimes Ids may be the same for 2 different requests:
```
SDL->HMI [13-10-2020 17:04:39,433] {"id":1,"jsonrpc":"2.0","method":"BasicCommunication.UpdateDeviceList"}
SDL->HMI [13-10-2020 17:04:39,438] {"id":1,"jsonrpc":"2.0","method":"BasicCommunication.GetSystemInfo"}
```

##### OS & Version Information
* OS/Version: Ubuntu 18.04
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/tree/release/7.0.0 (80973f4)
* Testing Against: ATF

##### Test Case, Sample Code, and / or Example App
 - ATF Script: Any
 - Report and Logs: [2020-11-05_10-54-34.681_3564.tar.gz](https://github.com/smartdevicelink/sdl_core/files/5495651/2020-11-05_10-54-34.681_3564.tar.gz)

**Comment by AKalinich-Luxoft** [comment]
@JackLivio @theresalech please notice this PR is ready for Livio review

**Comment by theresalech** [comment]
@AKalinich-Luxoft thank you for letting us know! This issue was not requested as priority for the next Core release, but we will try to review as time allows. If it's imperative this be included in the next release, please raise as priority to the SDLC Steering Committee. Thanks!

**Comment by jacobkeeler** [comment]
closing with the merge of #3567
