### ISSUE TITLE
[SDL4.0 - Question] How to build a SDL app which supports video streaming?

### ISSUE THREAD

**Issue by Manabu-GT** [smartdevicelink/sdl_core#357]
Hi,

I'm trying to test the video streaming feature via wifi connection based on https://github.com/smartdevicelink/sdl_core/wiki/Video-Streaming-Setup tutorial.

However, the MobileNavi app mentioned in the document is not available and it's not clear how to build such an app and test with SDL core.
Could you please provide a sample code snippet or app to test the video streaming functionality?

**Comment by Manabu-GT** [comment]
Figured it out by looking at the SDL Mobile library.

**Comment by jay-manikandan** [comment]
Hi Manabu,

Can u please share the details about Mobile Navi? I am looking at the sdl-android library and it is not present.

Thanks.

**Comment by moguli** [comment]
Hi @Manabu-GT 

I have the same problem in this wiki.
https://github.com/smartdevicelink/sdl_core/wiki/Video-Streaming-Setup
Could you share MobileNavi source code and APK?

**Comment by Manabu-GT** [comment]
Hi @moguli and @jay-manikandan,

Sorry, I no longer have access to the source/APK because I already left the company where I worked on SDL. Ideally, it should come from Livio. Maybe ask someone at Livio to add video streaming feature in their https://github.com/smartdevicelink/sdl_tester_android app.
