### ISSUE TITLE
Type defining without interface name in HMI_API.xml

### ISSUE THREAD

**Issue by GetmanetsIrina** [smartdevicelink/sdl_core#3570]
### Bug Report
Some types of parameters are defined without an interface name in HMI_API.xml

##### Reproduction Steps
1. Go to HMI_API.xml and check `type` value of parameters

##### Expected Behavior
All structures and enums are located in `Common` interface so all names of structures and enums should be used with the interface name like 
[`<param name="name" type="Common.TextFieldName" mandatory="true">`](https://github.com/smartdevicelink/sdl_core/blob/7af66962b29992166de8b2162a82db6aa3ebce80/src/components/interfaces/HMI_API.xml#L2678)

##### Observed Behavior
Some types of parameters are defined without the interface name
[`<param name="location" type="Grid" mandatory="false">`](https://github.com/smartdevicelink/sdl_core/blob/7af66962b29992166de8b2162a82db6aa3ebce80/src/components/interfaces/HMI_API.xml#L1781)
[`<param name="serviceArea" type="Grid" mandatory="false">`](https://github.com/smartdevicelink/sdl_core/blob/7af66962b29992166de8b2162a82db6aa3ebce80/src/components/interfaces/HMI_API.xml#L1784)
[`<param name="grid" type="Grid"  mandatory="false">`](https://github.com/smartdevicelink/sdl_core/blob/7af66962b29992166de8b2162a82db6aa3ebce80/src/components/interfaces/HMI_API.xml#L1794)
[`<param name="seats" type="SeatLocation" array="true" mandatory="false">`](https://github.com/smartdevicelink/sdl_core/blob/7af66962b29992166de8b2162a82db6aa3ebce80/src/components/interfaces/HMI_API.xml#L1804)
[`<param name="massageZone" type="MassageZone" mandatory="true"></param>`](https://github.com/smartdevicelink/sdl_core/blob/7af66962b29992166de8b2162a82db6aa3ebce80/src/components/interfaces/HMI_API.xml#L1837)
[`<param name="massageMode" type="MassageMode" mandatory="true"></param>`](https://github.com/smartdevicelink/sdl_core/blob/7af66962b29992166de8b2162a82db6aa3ebce80/src/components/interfaces/HMI_API.xml#L1838)
[`<param name="cushion" type="MassageCushion" mandatory="true"></param>`](https://github.com/smartdevicelink/sdl_core/blob/7af66962b29992166de8b2162a82db6aa3ebce80/src/components/interfaces/HMI_API.xml#L1852)
[`<param name="action" type="SeatMemoryActionType" mandatory="true"/>`](https://github.com/smartdevicelink/sdl_core/blob/7af66962b29992166de8b2162a82db6aa3ebce80/src/components/interfaces/HMI_API.xml#L1871)
[`<param name="id" type="SupportedSeat" mandatory="false"></param>`](https://github.com/smartdevicelink/sdl_core/blob/7af66962b29992166de8b2162a82db6aa3ebce80/src/components/interfaces/HMI_API.xml#L1882)
[`<param name="massageMode" type="MassageModeData" minsize="1" maxsize="2" array="true" mandatory="false"></param>`](https://github.com/smartdevicelink/sdl_core/blob/7af66962b29992166de8b2162a82db6aa3ebce80/src/components/interfaces/HMI_API.xml#L1898)
[`<param name="massageCushionFirmness" type="MassageCushionFirmness" minsize="1" maxsize="5" array="true" mandatory="false"></param>`](https://github.com/smartdevicelink/sdl_core/blob/7af66962b29992166de8b2162a82db6aa3ebce80/src/components/interfaces/HMI_API.xml#L1899)
[`<param name="memory" type="SeatMemoryAction" mandatory="false"></param>`](https://github.com/smartdevicelink/sdl_core/blob/7af66962b29992166de8b2162a82db6aa3ebce80/src/components/interfaces/HMI_API.xml#L1900)
[`<param name="moduleInfo" type="ModuleInfo" mandatory="false">`](https://github.com/smartdevicelink/sdl_core/blob/7af66962b29992166de8b2162a82db6aa3ebce80/src/components/interfaces/HMI_API.xml#L1910)
[`<param name="moduleInfo" type="ModuleInfo" mandatory="false">`](https://github.com/smartdevicelink/sdl_core/blob/7af66962b29992166de8b2162a82db6aa3ebce80/src/components/interfaces/HMI_API.xml#L2124)
[`<param name="moduleInfo" type="ModuleInfo" mandatory="false">`](https://github.com/smartdevicelink/sdl_core/blob/7af66962b29992166de8b2162a82db6aa3ebce80/src/components/interfaces/HMI_API.xml#L2279)
[`<param name="moduleInfo" type="ModuleInfo" mandatory="false">`](https://github.com/smartdevicelink/sdl_core/blob/7af66962b29992166de8b2162a82db6aa3ebce80/src/components/interfaces/HMI_API.xml#L2425)
[`<param name="moduleInfo" type="ModuleInfo" mandatory="false">`](https://github.com/smartdevicelink/sdl_core/blob/7af66962b29992166de8b2162a82db6aa3ebce80/src/components/interfaces/HMI_API.xml#L2587)
[`<param name="moduleInfo" type="ModuleInfo" mandatory="false">`](https://github.com/smartdevicelink/sdl_core/blob/7af66962b29992166de8b2162a82db6aa3ebce80/src/components/interfaces/HMI_API.xml#L2634)
[`<param name="moduleInfo" type="ModuleInfo" mandatory="false">`](https://github.com/smartdevicelink/sdl_core/blob/7af66962b29992166de8b2162a82db6aa3ebce80/src/components/interfaces/HMI_API.xml#L2701)
[`<param name="stationIDNumber" type="StationIDNumber"  mandatory="false">`](https://github.com/smartdevicelink/sdl_core/blob/7af66962b29992166de8b2162a82db6aa3ebce80/src/components/interfaces/HMI_API.xml#L2064)
[`<param name="stationLocation" type="GPSData" mandatory="false">`](https://github.com/smartdevicelink/sdl_core/blob/7af66962b29992166de8b2162a82db6aa3ebce80/src/components/interfaces/HMI_API.xml#L2070)
[`<param name="sisData" type="SisData" mandatory="false">`](https://github.com/smartdevicelink/sdl_core/blob/7af66962b29992166de8b2162a82db6aa3ebce80/src/components/interfaces/HMI_API.xml#L2114)
[`<param name="defrostZone" type="DefrostZone" mandatory="false">`](https://github.com/smartdevicelink/sdl_core/blob/7af66962b29992166de8b2162a82db6aa3ebce80/src/components/interfaces/HMI_API.xml#L2250)
[`<param name="source" type="PrimaryAudioSource" mandatory="false">`](https://github.com/smartdevicelink/sdl_core/blob/7af66962b29992166de8b2162a82db6aa3ebce80/src/components/interfaces/HMI_API.xml#L2394)
[`<param name="equalizerSettings" type="EqualizerSettings" minsize="1" maxsize="100" mandatory="false" array="true">`](https://github.com/smartdevicelink/sdl_core/blob/7af66962b29992166de8b2162a82db6aa3ebce80/src/components/interfaces/HMI_API.xml#L2413)
[`<param name="name" type="LightName" mandatory="true" />`](https://github.com/smartdevicelink/sdl_core/blob/7af66962b29992166de8b2162a82db6aa3ebce80/src/components/interfaces/HMI_API.xml#L2562)
[`<param name="id" type="LightName" mandatory="true">`](https://github.com/smartdevicelink/sdl_core/blob/7af66962b29992166de8b2162a82db6aa3ebce80/src/components/interfaces/HMI_API.xml#L2596)
[`<param name="supportedLights" type="LightCapabilities" minsize="1" maxsize="100" array="true" mandatory="true">`](https://github.com/smartdevicelink/sdl_core/blob/7af66962b29992166de8b2162a82db6aa3ebce80/src/components/interfaces/HMI_API.xml#L2590)
[`<param name="status" type="LightStatus" mandatory="true"/>`](https://github.com/smartdevicelink/sdl_core/blob/7af66962b29992166de8b2162a82db6aa3ebce80/src/components/interfaces/HMI_API.xml#L2599)
[`<param name="color" type="RGBColor" mandatory="false" />`](https://github.com/smartdevicelink/sdl_core/blob/7af66962b29992166de8b2162a82db6aa3ebce80/src/components/interfaces/HMI_API.xml#L2601)
[`<param name="lightState" type="LightState" mandatory="true" minsize="1" maxsize="100" array="true">`](https://github.com/smartdevicelink/sdl_core/blob/7af66962b29992166de8b2162a82db6aa3ebce80/src/components/interfaces/HMI_API.xml#L2605)
[`<param name="displayMode" type="DisplayMode" mandatory="false"></param>`](https://github.com/smartdevicelink/sdl_core/blob/7af66962b29992166de8b2162a82db6aa3ebce80/src/components/interfaces/HMI_API.xml#L2622)
[`<param name="temperatureUnit" type="TemperatureUnit" mandatory="false"></param>`](https://github.com/smartdevicelink/sdl_core/blob/7af66962b29992166de8b2162a82db6aa3ebce80/src/components/interfaces/HMI_API.xml#L2623)
[`<param name="distanceUnit" type="DistanceUnit" mandatory="false"></param>`](https://github.com/smartdevicelink/sdl_core/blob/7af66962b29992166de8b2162a82db6aa3ebce80/src/components/interfaces/HMI_API.xml#L2624)
[`<param name="seatControlData" type="SeatControlData" mandatory="false">`](https://github.com/smartdevicelink/sdl_core/blob/7af66962b29992166de8b2162a82db6aa3ebce80/src/components/interfaces/HMI_API.xml#L2659)
[`<param name="audioControlData" type="AudioControlData" mandatory="false">`](https://github.com/smartdevicelink/sdl_core/blob/7af66962b29992166de8b2162a82db6aa3ebce80/src/components/interfaces/HMI_API.xml#L2661)
[`<param name="lightControlData" type="LightControlData" mandatory="false">`](https://github.com/smartdevicelink/sdl_core/blob/7af66962b29992166de8b2162a82db6aa3ebce80/src/components/interfaces/HMI_API.xml#L2663)
[`<param name="hmiSettingsControlData" type="HMISettingsControlData" mandatory="false">`](https://github.com/smartdevicelink/sdl_core/blob/7af66962b29992166de8b2162a82db6aa3ebce80/src/components/interfaces/HMI_API.xml#L2665)
[`<param name="dayColorScheme" type="TemplateColorScheme" mandatory="false" />`](https://github.com/smartdevicelink/sdl_core/blob/7af66962b29992166de8b2162a82db6aa3ebce80/src/components/interfaces/HMI_API.xml#L2843)
[`<param name="nightColorScheme" type="TemplateColorScheme" mandatory="false" />`](https://github.com/smartdevicelink/sdl_core/blob/7af66962b29992166de8b2162a82db6aa3ebce80/src/components/interfaces/HMI_API.xml#L2844)
[`<param name="coordinate" type="Coordinate" mandatory="false">`](https://github.com/smartdevicelink/sdl_core/blob/7af66962b29992166de8b2162a82db6aa3ebce80/src/components/interfaces/HMI_API.xml#L3542)
[`<param name="locationImage" type="Image" mandatory="false">`](https://github.com/smartdevicelink/sdl_core/blob/7af66962b29992166de8b2162a82db6aa3ebce80/src/components/interfaces/HMI_API.xml#L3557)
[`<param name="searchAddress" type="OASISAddress" mandatory="false">`](https://github.com/smartdevicelink/sdl_core/blob/7af66962b29992166de8b2162a82db6aa3ebce80/src/components/interfaces/HMI_API.xml#L3560)
[`<param name="supportedDynamicImageFieldNames" type="ImageFieldName" array="true" mandatory="false" minsize="1">`](https://github.com/smartdevicelink/sdl_core/blob/7af66962b29992166de8b2162a82db6aa3ebce80/src/components/interfaces/HMI_API.xml#L3612)
[`<param name="textFields" type="TextField" minsize="1" maxsize="100" array="true" mandatory="false">`](https://github.com/smartdevicelink/sdl_core/blob/7af66962b29992166de8b2162a82db6aa3ebce80/src/components/interfaces/HMI_API.xml#L3633)
[`<param name="imageFields" type="ImageField" minsize="1" maxsize="100" array="true" mandatory="false">`](https://github.com/smartdevicelink/sdl_core/blob/7af66962b29992166de8b2162a82db6aa3ebce80/src/components/interfaces/HMI_API.xml#L3636)
[`<param name="imageTypeSupported" type="ImageType" array="true" minsize="0" maxsize="1000" mandatory="false">`](https://github.com/smartdevicelink/sdl_core/blob/7af66962b29992166de8b2162a82db6aa3ebce80/src/components/interfaces/HMI_API.xml#L3639)
[`<param name="buttonCapabilities" type="ButtonCapabilities" minsize="1" maxsize="100" array="true" mandatory="false">`](https://github.com/smartdevicelink/sdl_core/blob/7af66962b29992166de8b2162a82db6aa3ebce80/src/components/interfaces/HMI_API.xml#L3648)
[`<param name="softButtonCapabilities" type="SoftButtonCapabilities" minsize="1" maxsize="100" array="true" mandatory="false">`](https://github.com/smartdevicelink/sdl_core/blob/7af66962b29992166de8b2162a82db6aa3ebce80/src/components/interfaces/HMI_API.xml#L3651)
[`<param name="dynamicUpdateCapabilities" type="DynamicUpdateCapabilities" mandatory="false">`](https://github.com/smartdevicelink/sdl_core/blob/7af66962b29992166de8b2162a82db6aa3ebce80/src/components/interfaces/HMI_API.xml#L3657)
[`<param name="windowTypeSupported" type="WindowTypeCapabilities" array="true" minsize="1" mandatory="false">`](https://github.com/smartdevicelink/sdl_core/blob/7af66962b29992166de8b2162a82db6aa3ebce80/src/components/interfaces/HMI_API.xml#L3665)
[`<param name="windowCapabilities" type="WindowCapability" array="true" minsize="1" maxsize="1000" mandatory="false">`](https://github.com/smartdevicelink/sdl_core/blob/7af66962b29992166de8b2162a82db6aa3ebce80/src/components/interfaces/HMI_API.xml#L3670)
[`<param name="navigationCapability" type="NavigationCapability" mandatory="false">`](https://github.com/smartdevicelink/sdl_core/blob/7af66962b29992166de8b2162a82db6aa3ebce80/src/components/interfaces/HMI_API.xml#L3695)
[`<param name="phoneCapability" type="PhoneCapability" mandatory="false">`](https://github.com/smartdevicelink/sdl_core/blob/7af66962b29992166de8b2162a82db6aa3ebce80/src/components/interfaces/HMI_API.xml#L3697)
[`<param name="videoStreamingCapability" type="VideoStreamingCapability" mandatory="false">`](https://github.com/smartdevicelink/sdl_core/blob/7af66962b29992166de8b2162a82db6aa3ebce80/src/components/interfaces/HMI_API.xml#L3699)
[`<param name="driverDistractionCapability" type="DriverDistractionCapability" mandatory="false">`](https://github.com/smartdevicelink/sdl_core/blob/7af66962b29992166de8b2162a82db6aa3ebce80/src/components/interfaces/HMI_API.xml#L3701)
[`<param name="driverDistractionCapability" type="DriverDistractionCapability" mandatory="false">`](https://github.com/smartdevicelink/sdl_core/blob/7af66962b29992166de8b2162a82db6aa3ebce80/src/components/interfaces/HMI_API.xml#L4263)
[`<param name="climateControlCapabilities" type="ClimateControlCapabilities" mandatory="false" minsize="1" maxsize="100" array="true">`](https://github.com/smartdevicelink/sdl_core/blob/7af66962b29992166de8b2162a82db6aa3ebce80/src/components/interfaces/HMI_API.xml#L3707)
[`<param name="radioControlCapabilities" type="RadioControlCapabilities" mandatory="false" minsize="1" maxsize="100" array="true">`](https://github.com/smartdevicelink/sdl_core/blob/7af66962b29992166de8b2162a82db6aa3ebce80/src/components/interfaces/HMI_API.xml#L3710)
[`<param name="buttonCapabilities" type="ButtonCapabilities"  mandatory="false" minsize="1" maxsize="100" array="true" >`](https://github.com/smartdevicelink/sdl_core/blob/7af66962b29992166de8b2162a82db6aa3ebce80/src/components/interfaces/HMI_API.xml#L3713)
[`<param name="seatControlCapabilities" type="SeatControlCapabilities" mandatory="false" minsize="1" maxsize="100" array="true">`](https://github.com/smartdevicelink/sdl_core/blob/7af66962b29992166de8b2162a82db6aa3ebce80/src/components/interfaces/HMI_API.xml#L3716)
[`<param name="audioControlCapabilities" type="AudioControlCapabilities" mandatory="false" minsize="1" maxsize="100" array="true">`](https://github.com/smartdevicelink/sdl_core/blob/7af66962b29992166de8b2162a82db6aa3ebce80/src/components/interfaces/HMI_API.xml#L3721)
[`<param name="hmiSettingsControlCapabilities" type="HMISettingsControlCapabilities" mandatory="false">`](https://github.com/smartdevicelink/sdl_core/blob/7af66962b29992166de8b2162a82db6aa3ebce80/src/components/interfaces/HMI_API.xml#L3724)
[`<param name="lightControlCapabilities" type="LightControlCapabilities" mandatory="false">`](https://github.com/smartdevicelink/sdl_core/blob/7af66962b29992166de8b2162a82db6aa3ebce80/src/components/interfaces/HMI_API.xml#L3727)
[`<param name="seatLocationCapability" type="SeatLocationCapability" mandatory="false">`](https://github.com/smartdevicelink/sdl_core/blob/7af66962b29992166de8b2162a82db6aa3ebce80/src/components/interfaces/HMI_API.xml#L4260)

##### OS & Version Information
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/tree/develop (7af66962b29992166de8b2162a82db6aa3ebce80)

**Comment by iCollin** [comment]
Closed via https://github.com/smartdevicelink/sdl_core/pull/3742
