### ISSUE TITLE
SDL allows starting Video service for 2nd version of SDL protocol

### ISSUE THREAD

**Issue by dboltovskyi** [smartdevicelink/sdl_core#3576]
### Bug Report
SDL allows starting Auido/Video service for 2nd version of SDL protocol

##### Reproduction Steps
1. Register Navi app with 2nd version of SDL protocol
2. Start Video service

##### Expected Behavior
SDL responds with `StartServiceNACK`

##### Observed Behavior
SDL responds with `StartServiceACK`

##### OS & Version Information
* OS/Version: Ubuntu 18.04
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/tree/develop (7871541)
* Testing Against: ATF

##### Test Case, Sample Code, and / or Example App
 - ATF Script: [1912_Video_service_start_via_2_protocol](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Defects/4_5/1912_Video_service_start_via_2_protocol.lua)
 - Report and Logs: [2020-11-17_12-11-49.667_3576.tar.gz](https://github.com/smartdevicelink/sdl_core/files/5555039/2020-11-17_12-11-49.667_3576.tar.gz)

**Comment by dboltovskyi** [comment]
Issue is not reproduced at [7.0.0](https://github.com/smartdevicelink/sdl_core/tree/7.0.0) and seems introduced by https://github.com/smartdevicelink/sdl_core/pull/3572

**Comment by dboltovskyi** [comment]
Scripts affected:
```
./test_scripts/Defects/4_5/1912_Video_service_start_via_2_protocol.lua
./test_scripts/MobileProjection/Phase1/009_Rejecting_audio_video_service_in_FULL_2_protocol.lua
./test_scripts/MobileProjection/Phase1/010_Rejecting_audio_video_service_in_LIMITED_2_protocol.lua
./test_scripts/TheSameApp/Protocol/005_Protocol_StartService_from_2_apps_with_same_appName_diff_appID_DIFF_devices.lua
./test_scripts/TheSameApp/Protocol/006_Protocol_StartService_from_2_apps_with_same_appName_same_appID_DIFF_devices.lua
```

**Comment by jacobkeeler** [comment]
Closing with the merge of #3600
