### ISSUE TITLE
Revoked app can be activated via device consent in EXTERNAL_PROPRIETARY

### ISSUE THREAD

**Issue by jacobkeeler** [smartdevicelink/sdl_core#3580]
### Bug Report
In EXTERNAL_PROPRIETARY policy mode, if an app is revoked, it can still be activated by providing consent for the device. This activation results in the app being brought to the foreground whenever it is reconnected as well.

##### Reproduction Steps
Using SDL HMI
1. app1 is revoked and connected, but device is not consented
2. Select app1 from the app list, accept consent prompt for device, HMI sends `SDL.OnAllowSDLFunctionality(true)`

##### Expected Behavior
app1 is not activated via `BC.ActivateApp` from SDL Core

##### Observed Behavior
SDL Core sends `BC.ActivateApp` to HMI, HMI brings app to foreground (although app1 still has `hmiLevel: NONE`). `BC.ActivateApp` is also sent to the HMI when the app reconnects.

##### OS & Version Information
* OS/Version: Ubuntu 18.04
* SDL Core Version: 7.0.0
* Testing Against: Android Test Suite app

**Comment by aderiabin** [comment]
Current issue is not regression one. It can be reproduced on SDL versions less than 7.0.

**Comment by ShobhitAd** [comment]
Closed via https://github.com/smartdevicelink/sdl_core/pull/3592
