### ISSUE TITLE
[SDL 0285] ShowConstantTBT Description Update

### ISSUE THREAD

**Issue by jordynmackool** [smartdevicelink/sdl_core#3589]
Proposal: [ShowConstantTBT Description Update](https://github.com/smartdevicelink/sdl_evolution/edit/master/proposals/0285-ConstantTBT-Update.md)

> This proposal is to update the descriptions of `ShowConstantTBT`'s parameters `distanceToManeuver` and `distanceToManeuverScale` so we get consistent use of them across all OEMs and Navigation apps.

Review: https://github.com/smartdevicelink/sdl_evolution/issues/955

**Comment by jacobkeeler** [comment]
closing with the merge of #3596
