### ISSUE TITLE
SDL responds with ABORTED result code and success=true to PerformInteraction request with KEYBOARD layout and BOTH mode

### ISSUE THREAD

**Issue by GetmanetsIrina** [smartdevicelink/sdl_core#3611]
### Bug Report
SDL responds with `ABORTED` result code and `success=true` to PerformInteraction request with `KEYBOARD` layout and `BOTH` mode

##### Precondition
1. SDL and HMI are started
2. App is registered and activated
3. ChoiceSet is added with `vrCommands`

##### Reproduction Steps
1. Mobile app requests PerformInteraction`(interactionMode=BOTH, InteractionLayout=KEYBOARD or LIST_WITH_SERCH or ICON_WITH_SEARCH)`
2. SDL sends `VR.PerformInteraction` and `UI.PerformInteraction` requests to HMI
3. Abort `VR` part of `PI` request(Press `Back` button when HMI shows `vrCommands`)
4. HMI shows keyboard after aborting `VR` part of `PI`(with `LIST_WITH_SERCH`, `ICON_WITH_SEARCH` modes user should tap on the `Search` text field)
4. Enter some text using the keyboard and press the `Search` button

##### Expected Behavior
1. SDL receives `ABORTED` result for `VR.PerformInteraction` request and `SUCCESS` result for `UI.PerformInteraction` with `manualTextEntry`
2. SDL sends response PerformInteraction`(resultCode=SUCCESS, success=true, manualTextEntry = <value_received_from_HMI>, Info = <info_received_in_VR_PerformInteraction_response>)` to mobile app

##### Observed Behavior
SDL sends response PerformInteraction`(resultCode=ABORTED, success=true, manualTextEntry = <value_received_from_HMI>, Info = <info_received_in_VR_PerformInteraction_response>)` to mobile app

##### OS & Version Information
* OS/Version:  Ubuntu 18.04
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/tree/develop (98c367d182327ae3433a16183847a034ad103467)
* Testing Against: HMI: https://github.com/smartdevicelink/sdl_hmi/tree/develop (ff013b1) , mobile app version: 20201223

##### SDL log
[SmartDeviceLinkCore.zip](https://github.com/smartdevicelink/sdl_core/files/5753650/SmartDeviceLinkCore.zip)

**Comment by VjKlepikov** [comment]
Issue is not reproduced on:

SDL: https://github.com/smartdevicelink/sdl_core/tree/7.1.0-RC1
HMI: https://github.com/smartdevicelink/sdl_hmi/tree/develop (cc9c740)
SPT: SPT: 20210305-Android (1076)
