### ISSUE TITLE
Rare crash during UnsubscribeVehicleData

### ISSUE THREAD

**Issue by jacobkeeler** [smartdevicelink/sdl_core#3618]
### Bug Report
Occasionally, unsubscribing from vehicle data can cause a SIGSEGV crash

##### Reproduction Steps
1. Run [001_UnsubscribeVD_Success.lua](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/API/VehicleData/UnsubscribeVehicleData/001_UnsubscribeVD_Success.lua)

##### Expected Behavior
The test finishes with SUCCESS result code

##### Observed Behavior
The test sometimes finishes with ABORTED result code

##### OS & Version Information
* OS/Version: Ubuntu 18.04.5 LTS
* SDL Core Version: develop
* Testing Against: ATF (develop branch)

##### Test Case, Sample Code, and / or Example App
[001_UnsubscribeVD_Success.lua](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/API/VehicleData/UnsubscribeVehicleData/001_UnsubscribeVD_Success.lua)

**Comment by jacobkeeler** [comment]
Per https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/2488#issuecomment-756867744, this issue seems to appear only on the latest updates of Ubuntu 18.04, it does not a appear to be reproducible in 16.04 or earlier versions of 18.04

**Comment by dboltovskyi** [comment]
@jacobkeeler Please advise is there plan for PMs to fix this issue?

**Comment by jacobkeeler** [comment]
@dboltovskyi Just submitted a fix, see #3619

**Comment by dboltovskyi** [comment]
@jacobkeeler Thank you for the fix

**Comment by jacobkeeler** [comment]
closed via #3619
