### ISSUE TITLE
SDL does not respond with NACK to start RPC service request with invalid data

### ISSUE THREAD

**Issue by dboltovskyi** [smartdevicelink/sdl_core#3620]
### Bug Report
SDL does not respond with NACK to start RPC service request with invalid data

##### Reproduction Steps
1. Start SDL, HMI, connect mobile device
2. App tries to start RPC service over 5th SDL protocol with invalid data in bson payload

##### Expected Behavior
SDL does:
 - send 'OnServiceUpdate' notification to HMI with 'REQUEST_REJECTED'
 - respond with `NACK` to start service request with appropriate `reason`

##### Observed Behavior
SDL does:
 - send 'OnServiceUpdate' notification to HMI with 'REQUEST_REJECTED'
 - not send `StartServiceNack` to mobile app

##### OS & Version Information
* OS/Version: Ubuntu 18.04
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/tree/develop (61ea4ef)
* Testing Against: ATF

##### Test Case, Sample Code, and / or Example App
 - ATF Script: [3620.lua.tar.gz](https://github.com/smartdevicelink/sdl_core/files/5870776/3620.lua.tar.gz)
 - Report and Logs: [2021-01-25_21-30-42.461_3620.tar.gz](https://github.com/smartdevicelink/sdl_core/files/5870777/2021-01-25_21-30-42.461_3620.tar.gz)

**Comment by LitvinenkoIra** [comment]
@VladSemenyuk is working on it

**Comment by iCollin** [comment]
Closed via https://github.com/smartdevicelink/sdl_core/pull/3647
