### ISSUE TITLE
why define "MAXIMUM_FRAME_DATA_V2_SIZE " as 1488?

### ISSUE THREAD

**Issue by chenbd** [smartdevicelink/sdl_core#363]
when using usb transport (and we did mainly using usb transport for product),can we increase this size, maybe for better performance?

**Comment by JackLivio** [comment]
That is the max frame size used for protocol version 2. 

There is protocol version 4 that uses MaximumPayloadSize = 131072.

MaximumPayloadSize is defined in the smartdevicelink.ini configuration file.

https://github.com/smartdevicelink/sdl_core/blob/master/src/appMain/smartDeviceLink.ini

**Comment by chenbd** [comment]
@JackLivio  Is there any document which shows the changes of protocol between versions?
