### ISSUE TITLE
SDL crashes while sending OnSystemRequest in case if RPC service is protected and SDL protocol version is 3rd and greater

### ISSUE THREAD

**Issue by dboltovskyi** [smartdevicelink/sdl_core#3640]
### Bug Report
This is a continuation of original issue which is described in https://github.com/smartdevicelink/sdl_core/issues/2922 and had been fixed in scope of Release 6.0.
Current issue addresses the same scenario but version of SDL protocol is >= 3

##### Reproduction Steps
1. Register new app with SDL protocol version >= 3
=> Policy Update is started
2. Switch RPC service to protected mode
=> SDL continues PTU sequence
=> SDL->App: OnSystemRequest(with snapshot)

##### Expected Behavior
SDL proceed with OnSystemRequest notification successfully

##### Observed Behavior
SDL crashes with error:
```
smartDeviceLinkCore: /home/developer/sdl/sdl_core/src/components/security_manager/src/ssl_context_impl.cc:470:
virtual bool security_manager::CryptoManagerImpl::SSLContextImpl::Encrypt(const uint8_t*, size_t, const uint8_t**, size_t*):
Assertion `(len == static_cast<size_t>(read_size))' failed.
```

##### OS & Version Information
* OS/Version: Ubuntu 20.04
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/tree/develop (d8cd806)
* Testing Against: ATF

##### Test Case, Sample Code, and / or Example App
 - ATF Script: [003_PTU_all_flows_Protected_Mode_v3.lua.tar.gz](https://github.com/smartdevicelink/sdl_core/files/6076555/003_PTU_all_flows_Protected_Mode_v3.lua.tar.gz)
 - Report and Logs: [2021-02-25_14-39-18.239_3640.tar.gz](https://github.com/smartdevicelink/sdl_core/files/6045404/2021-02-25_14-39-18.239_3640.tar.gz)

**Comment by dboltovskyi** [comment]
SDL needs to follow maximum size of protected records. According to spec this is 16384 bytes:
https://tools.ietf.org/id/draft-ietf-tls-record-limit-01.html#:~:text=TLS%20versions%201.2%20and%20earlier,expansion%20is%20only%2016%20octets

**Comment by jacobkeeler** [comment]
Closing with the merge of #3652
