### ISSUE TITLE
SDL protocol_handler_test failed with -DBUILD_TESTS=ON -DENABLE_SECURITY=OFF

### ISSUE THREAD

**Issue by dboltovskyi** [smartdevicelink/sdl_core#3643]
### Bug Report
Within fix https://github.com/smartdevicelink/sdl_core/issues/3614 is it became possible to build SDL with `-DBUILD_TESTS=ON` `-DENABLE_SECURITY=OFF` flags
However `protocol_handler_test` failed in this configuration.

##### Reproduction Steps
1. git checkout develop
2. cmake ../sdl_core -DBUILD_TESTS=ON -DENABLE_SECURITY=OFF -DBUILD_TESTS=ON 
3. make install
4. make test

##### Expected Behavior
All UTs passed

##### Observed Behavior
protocol_handler_test failed with error:
```
unknown file: Failure
Uninteresting mock function call - returning default value.
    Function call: SendMessageToDevice(16-byte object <60-AD 17-9C D3-55 00-00 20-2E 50-9B D3-55 00-00>)
          Returns: 0
[  FAILED  ] ProtocolHandlerImplTest.OnTMMessageSend_ReadyToCloseConnection_Disconnect (1 ms)
```

##### OS & Version Information
* OS/Version: Ubuntu 18.04 (Ubuntu 20.04)
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/tree/develop (e68933c)
* Testing Against: N/A

**Comment by jacobkeeler** [comment]
Closing with the merge of #3655
