### ISSUE TITLE
Unable to build SDL with -DCMAKE_BUILD_TYPE=Release on Ubuntu 20.04

### ISSUE THREAD

**Issue by dboltovskyi** [smartdevicelink/sdl_core#3644]
### Bug Report
Unable to build SDL with `-DCMAKE_BUILD_TYPE=Release` for Ubuntu 20.04
However SDL in such configuration is built successfully on Ubuntu 18.04

##### Reproduction Steps
1. git checkout develop
2. cmake ../sdl_core -DCMAKE_BUILD_TYPE=Release
3. make install

##### Expected Behavior
SDL is built successfully

##### Observed Behavior
SDL build fails with errors:
```
/home/developer/sdl/sdl_core/src/components/include/utils/semantic_version.h:49:20: error: ‘*((void*)(& signature)+10).utils::SemanticVersion::patch_version_’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
   49 |     patch_version_ = other.patch_version_;
```

##### OS & Version Information
* OS/Version: Ubuntu 20.04
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/tree/develop (e68933c)
* Testing Against: N/A

##### Test Case, Sample Code, and / or Example App
 - Build log: [build.log.tar.gz](https://github.com/smartdevicelink/sdl_core/files/6070314/build.log.tar.gz)

**Comment by iCollin** [comment]
Thank you for reporting, closed via https://github.com/smartdevicelink/sdl_core/pull/3650
