### ISSUE TITLE
SDL encrypts payload of 1st frame of multi-frame message

### ISSUE THREAD

**Issue by dboltovskyi** [smartdevicelink/sdl_core#3659]
### Bug Report
In case if RPC service has switched to protected mode and SDL sends multi-frame message payload of 1st frame is encrypted. However it shouldn't be encrypted and it's size should always be 8 bytes. (See https://github.com/smartdevicelink/sdl_core/issues/2384)

##### Reproduction Steps
1. Start SDL, HMI, connect mobile device
2. Register new App
3. Switch RPC service to protected mode
=> SDL starts PTU through protected channel and sends encrypted `OnSystemRequest` notification to mobile with Policy Table Snapshot (PTS). In case if PTS is >16kb it would be split into a few frames.
4. Check content of the 1st frame

##### Expected Behavior
 - Payload is non-encrypted
 - Size is 8 bytes

##### Observed Behavior
 - Payload is encrypted
 - Size is greater than 8 bytes (30-50 bytes)

##### OS & Version Information
* OS/Version: Ubuntu 20.04
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/tree/develop (fed2ae4)
* Testing Against: ATF

##### Test Case, Sample Code, and / or Example App
 - ATF Script: [3640_PTU_all_flows_Protected_Mode_v3](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Defects/7_1/3640_PTU_all_flows_Protected_Mode_v3.lua)
 - Report and Logs: [2021-03-11_09-22-49.555_3659.tar.gz](https://github.com/smartdevicelink/sdl_core/files/6123631/2021-03-11_09-22-49.555_3659.tar.gz)
 - Snippet from extended console log:
```
Decode:	2	true	45	8	20522	2
[14:23:00,243] SDL->MOB:  N:	OnSystemRequest (encrypted)

`2` - first frame
`true` - encryption flag
`45` - size of the payload
```

**Comment by LitvinenkoIra** [comment]
Luxoft team is going to provide a fix.
