### ISSUE TITLE
Unable to establish secure connection on Ubuntu 20.04

### ISSUE THREAD

**Issue by dboltovskyi** [smartdevicelink/sdl_core#3664]
### Bug Report
Unable to establish secure connection on Ubuntu 20.04. Though it can be done successfully on Ubuntu 18.04.
Same SDL commit, SPT version, settings and certificates.

OpenSSL version:
- Ubuntu 20.04: `1.1.1f`
- Ubuntu 18.04: `1.1.1`

##### Reproduction Steps
1. Make sure all required certificates are defined properly
2. Start SDL, HMI, connect mobile device, start SPT
3. Register new App
4. Enable secure RPC service

##### Expected Behavior
Handshake sequence is finished successfully and RPC service is switched to protected mode

##### Observed Behavior
Handshake sequence has failed and RPC service hasn't switched to protected mode

##### OS & Version Information
* OS/Version: Ubuntu 20.04
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/tree/develop (0df6608)
* Testing Against: SPT

##### Test Case, Sample Code, and / or Example App
 - Ubuntu 20.04 SDL log: [u20_SmartDeviceLinkCore.log.tar.gz](https://github.com/smartdevicelink/sdl_core/files/6153888/u20_SmartDeviceLinkCore.log.tar.gz) (FAIL)
 - Ubuntu 18.04 SDL log: [u18_SmartDeviceLinkCore.log.tar.gz](https://github.com/smartdevicelink/sdl_core/files/6153887/u18_SmartDeviceLinkCore.log.tar.gz) (SUCCESS), provided for comparison

**Comment by LitvinenkoIra** [comment]
Luxoft team is going to provide a fix.

**Comment by jordynmackool** [comment]
@LitvinenkoIra please advise when the fix for this issue will be ready for Livio review?

**Comment by dboltovskyi** [comment]
@jordynmackool Please notice fix for this issue is in our internal team review. There is a plan to publish it for PM review until tomorrow.

**Comment by jacobkeeler** [comment]
closing with the merge of #3681
