### ISSUE TITLE
Incorrect behavior during processing of erroneous Slider responsive with `sliderPosition` parameter

### ISSUE THREAD

**Issue by GetmanetsIrina** [smartdevicelink/sdl_core#3676]
### Bug Report
Incorrect behavior during processing of erroneous Slider responsive with `sliderPosition` parameter

##### Precondition
1. HMI and SDL are started
2. Mobile app is registered and activated

##### Reproduction Steps
1. Mobile app requests `Slider` with default params and values
2. Press `Back`  button or wait until a timeout is expired

##### Expected Behavior
[Mobile API says](https://github.com/smartdevicelink/rpc_spec/blob/8b8c996c738711c4235c8574c179354cbf8982e2/MOBILE_API.xml#L7175)
```
<param name="sliderPosition" type="Integer" minvalue="1" maxvalue="26" mandatory="false">
    <description>
        Current slider value returned when saved or canceled (aborted)
        This value is only returned for resultCodes "SAVED" or "ABORTED"
    </description>
</param>
```
[HMI API says](https://github.com/smartdevicelink/sdl_core/blob/0df66080512cbe76ee5d4872910a54adf3ca1f36/src/components/interfaces/HMI_API.xml#L5962)
```
<param name="sliderPosition" type="Integer" minvalue="1" maxvalue="26" mandatory="false">
  <description>Current slider position. Must be returned when the user has clicked the ‘Save’ or ‘Canceled’ button or by the timeout </description>
</param>
```

According to the information above HMI should send `sliderPosition` parameter also in erroneous response, but according to HMI specification, HMI can not provide custom parameters in the erroneous response. All faced custom parameters will be treated as fake parameters and will be removed from the message.
So we were thinking that the summary in API's should be updated and should say that `sliderPosition` parameter should be provided only in a successful response.
SDL should not provide `sliderPosition` parameter in erroneous response.

**Note:** 
HMI issue should be created to remove `sliderPosition` parameter from the erroneous responses in case this solution will be applied.

##### Observed Behavior
1. HMI sends `sliderPosition` parameter with actual value in erroneous responses(ABORTED and TIMED_OUT)
2. SDL sends `sliderPosition=0` in the response to the mobile side because can not process the `sliderPosition` received in erroneous response from HMI

##### OS & Version Information
* OS/Version: Ubuntu 18.04
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/tree/7.1.0-RC1 (0df66080512cbe76ee5d4872910a54adf3ca1f36)
* Testing Against: HMI: https://github.com/smartdevicelink/sdl_hmi/tree/develop (7fad546)
SPT: 20210305-Android (1076) 

##### Logs
[slider_sdl_log.zip](https://github.com/smartdevicelink/sdl_core/files/6204024/slider_sdl_log.zip)

**Comment by jacobkeeler** [comment]
@GetmanetsIrina It seems to me that this is at least partially an HMI issue as well. The HMI can send an ABORTED or TIMED_OUT response with the `sliderPosition` parameter, but it needs to use the normal response format rather than the error one.
```
       {
          'jsonrpc': '2.0',
          'id': sliderRequestID,
          'result': {
            'code': 5,
            'method': 'UI.Slider',
            'sliderPosition': 8
          }
        }
``` 
Unfortunately when using this format, the HMI is not able send a `message` field, but sending `sliderPosition` is possible.

The main issue on Core's end is that it sends a `sliderPosition` of `0` if the HMI doesn't send this value properly, which is not valid in the Mobile API since `minvalue="1"`. I don't believe that the Mobile API description needs to be changed in this case.

**Comment by jacobkeeler** [comment]
Closing with the merge of #3697
