### ISSUE TITLE
`NONE` HMI level is missed for RPCs in "WidgetSupport" policy group

### ISSUE THREAD

**Issue by GetmanetsIrina** [smartdevicelink/sdl_core#3677]
### Bug Report
`sdl_preloaded_pt.json` does not contain "NONE" HMI level for RPCs in "WidgetSupport" group

##### Reproduction Steps
1. Open `sdl_preloaded_pt.json` and check HMI levels for `CreateWindow` and `DeleteWindow` RPCs in "WidgetSupport" group

##### Expected Behavior
`CreateWindow` and `DeleteWindow` RPCs should be allowed in `NONE` HMI level according to ["Widget support proposal"](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0216-widget-support.md)
```
"WidgetSupport" : {
      "rpcs":{
          "CreateWindow":{
              "hmi_levels":["NONE","BACKGROUND","LIMITED","FULL"]
          }, 
          "DeleteWindow":{
              "hmi_levels":["NONE","BACKGROUND","LIMITED","FULL"]
          }
      }
...
```
##### Observed Behavior
[sdl_preloaded_pt.json](https://github.com/smartdevicelink/sdl_core/blob/0df66080512cbe76ee5d4872910a54adf3ca1f36/src/appMain/sdl_preloaded_pt.json#L1660) does not contain "NONE" HMI level for `CreateWindow` and `DeleteWindow` RPCs in "WidgetSupport" group
```
"WidgetSupport": {
    "rpcs": {
        "CreateWindow": {
            "hmi_levels": ["BACKGROUND", "FULL", "LIMITED"]
        },
        "DeleteWindow": {
            "hmi_levels": ["BACKGROUND", "FULL", "LIMITED"]
        }
...
```

##### OS & Version Information
* OS/Version: Ubuntu 18.04
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/tree/7.1.0-RC1 (0df6608)

**Comment by JackLivio** [comment]
Fixed in 7.1 rc
