### ISSUE TITLE
SDL starts PTU sequence by Days trigger on second ignition cycle 

### ISSUE THREAD

**Issue by VjKlepikov** [smartdevicelink/sdl_core#3685]
### Bug Report
SDL starts PTU sequence by Days trigger on second ignition cycle

##### Reproduction Steps
0. "exchange_after_x_days": 30 in sdl_preloaded_pt.json
1. Start HMI and Core
2. Shut down Core and HMI via IGNITION_OFF signal
    Start HMI and Core again

##### Expected Behavior
1. SDL does not start PTU sequence

##### Observed Behavior
1. The PTU sequence is started by Days trigger before the previous UpdatedPollicyTable is successfully applied. 

/policy/policy_regular/src/policy_manager_impl.cc:1266 PolicyManagerImpl::ExceededDays: Enter
TRACE [02 Apr 2021 15:18:59,545][140210323048192][Policy] /home/slava/Work/SmartDeviceLink/sdl_core/src/components/policy/policy_regular/src/cache_manager.cc:661 CacheManager::DaysBeforeExchange: Enter
DEBUG [02 Apr 2021 15:18:59,545][140210323048192][Policy] /home/slava/Work/SmartDeviceLink/sdl_core/src/components/policy/policy_regular/src/cache_manager.cc:673 CacheManager::DaysBeforeExchange: Exchange after: 30 days
DEBUG [02 Apr 2021 15:18:59,545][140210323048192][Policy] /home/slava/Work/SmartDeviceLink/sdl_core/src/components/policy/policy_regular/src/cache_manager.cc:675 CacheManager::DaysBeforeExchange: Epoch since last update: 0
TRACE [02 Apr 2021 15:18:59,545][140210967283456][JsoncppReaderWrapper] /home/slava/Work/SmartDeviceLink/sdl_core/src/components/utils/src/jsoncpp_reader_wrapper.cc:45 JsonReader::parse: Enter
DEBUG [02 Apr 2021 15:18:59,545][140210323048192][Policy] /home/slava/Work/SmartDeviceLink/sdl_core/src/components/policy/policy_regular/src/cache_manager.cc:679 CacheManager::DaysBeforeExchange: The days since last update: 18719
TRACE [02 Apr 2021 15:18:59,545][140210323048192][Policy] /home/slava/Work/SmartDeviceLink/sdl_core/src/components/policy/policy_regular/src/cache_manager.cc:661 CacheManager::DaysBeforeExchange: Exit
TRACE [02 Apr 2021 15:18:59,545][140210323048192][Policy] /home/slava/Work/SmartDeviceLink/sdl_core/src/components/policy/policy_regular/src/policy_manager_impl.cc:1266 PolicyManagerImpl::ExceededDays: Exit
DEBUG [02 Apr 2021 15:18:59,545][140210323048192][Policy] /home/slava/Work/SmartDeviceLink/sdl_core/src/components/policy/policy_regular/src/policy_manager_impl.cc:136 PolicyManagerImpl::CheckTriggers: 
Days exceeded: true
Ignition cycles exceeded: false

##### OS & Version Information
* OS/Version: Ubuntu 18.04
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/tree/7.1.0-RC1 (0df6608)

**Comment by VjKlepikov** [comment]
Please notice issue is reproduced on release_7.0.0

**Comment by jacobkeeler** [comment]
@VjKlepikov Could you clarify what is wrong with the current behavior? My understanding was that this trigger should fire if Core has never done a Policy Table exchange before. Generally it's expected that on a clean install, Core will attempt to perform a PTU on startup until at least one has been performed

**Comment by dboltovskyi** [comment]
@jacobkeeler It looks like this is not a "bug", but a "feature".
SDL may start PTU sequence on a very first start (due to Days trigger). But this change may have a huge impact on existing ATF scripts.
Some scripts do not expect PTU start and would fail in that case.

I propose to leave SDL logic as is and to create a new ATF script to cover this specific sequence as a normal behavior.

**Comment by jacobkeeler** [comment]
@dboltovskyi are there any tests that are failing due to this behavior at the moment?

**Comment by dboltovskyi** [comment]
@jacobkeeler There are no such tests as of now
