### ISSUE TITLE
[SDL 0334] Transform SetDisplayLayout requests into UI.Show for HMIs

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_core#3706]
Proposal: [Transform SetDisplayLayout requests into UI.Show for HMIs](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0334-transform-setdisplaylayout-requests-to-ui-show.md)

> This proposal is to make modifications in sdl_core to transform incoming `SetDisplayLayout` requests from applications into `UI.Show` requests to send to the HMI.

Review: https://github.com/smartdevicelink/sdl_evolution/issues/1141

Steering Committee Decision:
>The Steering Committee agreed to accept this proposal with the revision of removing `SetDisplayLayout` from HMI_API.

>The proposal .md file was updated to reflect these revisions on 5/19/21

**Comment by ShobhitAd** [comment]
Closed via https://github.com/smartdevicelink/sdl_core/pull/3849
