### ISSUE TITLE
[SDL 0337] Reject PROPRIETARY/HTTP SystemRequests when PTU is not in progress

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_core#3715]
Proposal: [Reject PROPRIETARY/HTTP SystemRequests when PTU is not in progress](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0337-reject-proprietary-http-systemrequests-when-ptu-not-in-progress.md)

> This proposal is to make modifications in sdl_core to reject incoming `PROPRIETARY`/`HTTP` SystemRequests if there is no policy table update (PTU) in progress.

Review: https://github.com/smartdevicelink/sdl_evolution/issues/1149

**Comment by iCollin** [comment]
Closed via https://github.com/smartdevicelink/sdl_core/pull/3853
