### ISSUE TITLE
Remove unnecessary default_timeout_ adjustments after 0189

### ISSUE THREAD

**Issue by iCollin** [smartdevicelink/sdl_core#3759]
Many of the interaction RPCs currently have their HMI timeout adjusted by Core; that ​is no longer necessary after the implementation of [0189](https://github.com/smartdevicelink/sdl_core/pull/3726). This affects Alert, SubtleAlert, Slider, and ScrollableMessage.

Lines such as the following are no longer necessary:

https://github.com/smartdevicelink/sdl_core/blob/042872f24b2cf7d9c1b18cab81d502071de4b5a7/src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/hmi/ui_alert_request.cc#L55

**Comment by jacobkeeler** [comment]
Closing, see https://github.com/smartdevicelink/sdl_core/pull/3760#issuecomment-902868563
