### ISSUE TITLE
SDL core dump on IGNITION_OFF

### ISSUE THREAD

**Issue by VjKlepikov** [smartdevicelink/sdl_core#3774]
### Bug Report
SDL core dump on IGNITION_OFF

##### Reproduction Steps
1. SDL and HMI are started
2. Mobile App is registered
3. Perform ignition Off:
On "HMI" go to → Click the "Exit Application" button → Select “IGNITION_OFF” in “Exit Application reason” → Click the `Send state` button
SDL->HMI: BasicCommunication.OnExitAllApplications:{"reason":"IGNITION_OFF"}}

##### Expected Behavior
SDL starts the ignition off sequence
1. SDL sends to HMI OnSDLClose and stops working
SDL->HMI: BasicCommunication.OnSDLClose:{}

##### Observed Behavior
SDL starts the ignition off sequence
1. SDL sends to HMI OnSDLClose and stops working
SDL->HMI: BasicCommunication.OnSDLClose:{}
**Core dump is observed**

##### OS & Version Information
* OS/Version: [Ubuntu 18]
* SDL Core Version: [ https://github.com/smartdevicelink/sdl_core/tree/develop (35f5a06 )]
* HMI: [https://github.com/smartdevicelink/sdl_hmi/tree/develop (d2c882a)]
* SPT: 20210729-Android

**Comment by VjKlepikov** [comment]
Please note Luxoft team is going to prepare a fix

**Comment by iCollin** [comment]
Hello @VjKlepikov, I have followed these steps many times but have not seen a core dump.

Can you please provide any additional steps or details required to trigger this bug? Were you able to consistently reproduce it?

**Comment by iCollin** [comment]
Hello I was able to reproduce by streaming before sending IGNITION_OFF. Thank you

**Comment by iCollin** [comment]
Closed via https://github.com/smartdevicelink/sdl_core/pull/3781
