### ISSUE TITLE
SDL copies MOBILE_API.xml from 'rpc_spec' submodule during build process

### ISSUE THREAD

**Issue by dboltovskyi** [smartdevicelink/sdl_core#3779]
### Bug Report
According to https://github.com/smartdevicelink/sdl_core/pull/3270 Core build process performs redundant copy operation of `MOBILE_API.xml` file from submodule `rpc_spec`  to `sdl_core sources` (`/tools/rpc_spec` -> `src/components/interfaces`)

##### Reproduction Steps
1. Try to build SDL Core
2. Check content of `src/components/interfaces` folder

##### Expected Behavior
There is no `MOBILE_API.xml` file 

##### Observed Behavior
There is redundant `MOBILE_API.xml` file 

##### OS & Version Information
* OS/Version: Ubuntu 18.04/20.04
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/tree/release/8.0.0 (de58a41)

**Comment by iCollin** [comment]
Closed via https://github.com/smartdevicelink/sdl_core/pull/3778
