### ISSUE TITLE
Core dump during language change

### ISSUE THREAD

**Issue by GetmanetsIrina** [smartdevicelink/sdl_core#3783]
### Bug Report
Core dump during language change for several apps

### Occurrences
2/5

##### Reproduction Steps
1. SDL and HMI are started
2. 2-10 apps are registered (depends on a test environment)
3. apps are activated one by one
4. Go to Apps menu
5. Change VR language to ES-MX (maybe update UI HMI language to some another value before )

##### Expected Behavior
All apps are reregistered successfully 

##### Observed Behavior
core dump

##### OS & Version Information
* OS/Version: Ubuntu 18.04
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/releases/tag/8.0.0-RC1
* HMI: https://github.com/smartdevicelink/sdl_hmi/tree/release/5.6.0 (1fb8b6b)
* SPT: 20210729-Android

[logs_dump.zip](https://github.com/smartdevicelink/sdl_core/files/7285648/logs_dump.zip)
[logs_dump_2.zip](https://github.com/smartdevicelink/sdl_core/files/7285652/logs_dump_2.zip)

**Comment by dboltovskyi** [comment]
@theresalech Please notice fix for this issue is under development by Luxoft team. We are planning to submit a PR tomorrow.

**Comment by iCollin** [comment]
Closed via https://github.com/smartdevicelink/sdl_core/pull/3796
