### ISSUE TITLE
Invalid data in BC.UpdateAppList for WebEngine app

### ISSUE THREAD

**Issue by GetmanetsIrina** [smartdevicelink/sdl_core#3797]
### Bug Report
Invalid data in BC.UpdateAppList for WebEngine app

##### Reproduction Steps

1. Core is built with DWEBSOCKET_SERVER_TRANSPORT_SUPPORT set to `true`
2. In sdl_preloaded_pt.json default app_policies groups: ["Base-4" ]
3. SDL and HMI are started
4. Run deploy_server.sh file in HMI directory
5. On HMI → Apps →Apps Store → Set Apps Properties → Set

##### Expected Behavior
```
HMI → SDL: SetAppProperties ( properties:
{nicknames:{ "Hello JS" } ,
policyAppID:"hello-js",
enabled: true,
transportType:"ws",
hybridAppPreference: "BOTH"})
SDL → HMI: SetAppProperties ( { success:true, resultCode: "SUCCESS" } )
SDL → HMI: UpdateAppList request {"applications":[{"appID":1251837608,"appName":"Hello JS","deviceInfo":"id":"558302f84258903819b64191998d9c8b8ce613e5b4d0153ca93343c09553792e","isSDLAllowed":true,"name":"Web Engine","transportType":"WEBENGINE_WEBSOCKET"},"greyOut":false,"isCloudApplication":false,"policyAppID":"hello-js","requestSubType":[],"requestType":[]}]}}
HMI → SDL: UpdateAppList response{SUCCESS}
```

##### Observed Behavior
```
SDL -> HMI [17:53:37:477]: {"id":2,"jsonrpc":"2.0","method":"BasicCommunication.UpdateAppList","params":{"applications":[{"appID":38803992,"appName":"Hello JS","deviceInfo":{"id":"558302f84258903819b64191998d9c8b8ce613e5b4d0153ca93343c09553792e","isSDLAllowed":true,"name":"Web Engine","transportType":"WEBENGINE_WEBSOCKET"},"hmiDisplayLanguageDesired":-1,"isCloudApplication":false,"isMediaApplication":false,"policyAppID":"hello-js","requestSubType":[],"requestType":[]}]}}
```
SDL sends invalid value for `hmiDisplayLanguageDesired`, redundant `isMediaApplication` and does not send `greyOut` parameters.

##### OS & Version Information
* OS/Version:Ubuntu 18.04
* HMI: https://github.com/smartdevicelink/sdl_hmi/tree/release/5.6.0 (4d7c0b5)
* Core: https://github.com/smartdevicelink/sdl_core/tree/release/8.0.0 (e44e292)
* Mobile app: SPT 20210729

**Comment by dboltovskyi** [comment]
@theresalech Please notice this is a regression issue which is likely introduced by https://github.com/smartdevicelink/sdl_core/pull/3796.
Luxoft team is going to prepare a fix.

**Comment by dboltovskyi** [comment]
@theresalech Please notice following PRs are ready for Livio team review:
- https://github.com/smartdevicelink/sdl_core/pull/3799
- https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/2599
