### ISSUE TITLE
SDL sends RegisterAppInterface response with the incorrect value of "hmiCapabilities" parameters if HMICapabilitiesCacheFile exists

### ISSUE THREAD

**Issue by VjKlepikov** [smartdevicelink/sdl_core#3804]
### Bug Report
SDL sends RegisterAppInterface response with the incorrect value of "hmiCapabilities" parameters if HMICapabilitiesCacheFile exists

##### Reproduction Steps
1. HMICapabilitiesCacheFile parameter has a value with name the file ( e.g. hmi_capabilities_cache.json) in SmartDeviceLink.ini
2. HMICapabilitiesCacheFile file is present in AppStorageFolder (Perform Ignition cycle) with
"hmiCapabilities" : 
  {
    "navigation" : true,
    "phoneCall" : true,
    "videoStreaming": true
  }
3. SDL and HMI are started
4.  Mobile App sends RegisterAppInterface request to SDL

##### Expected Behavior
SDL→App: SDL sends RegisterAppInterface response with capabilities (stored in hmi_capabilities_cache.json) to Mobile

"hmiCapabilities" : 
  {
    "navigation" : true,
    "phoneCall" : true,
    "videoStreaming": true
  }

##### Observed Behavior
SDL sends RegisterAppInterface response with the incorrect value of "hmiCapabilities" parameters
"hmiCapabilities" : 
  {
    "navigation" : false,
    "phoneCall" : false,
    "videoStreaming": false
  }

##### OS & Version Information
* OS/Version: Ubuntu 18.04
* SDL Core Version: 7.1 RC 2/ https://github.com/smartdevicelink/sdl_core/releases/tag/8.0.0-RC1
* HMI: https://github.com/smartdevicelink/sdl_hmi/tree/release/5.6.0 (1fb8b6b)
* SPT: 20210729-Android

**Comment by ShobhitAd** [comment]
Closed via https://github.com/smartdevicelink/sdl_core/pull/3820
