### ISSUE TITLE
Sometimes application_manager_test may fail with core crash

### ISSUE THREAD

**Issue by dboltovskyi** [smartdevicelink/sdl_core#3808]
### Bug Report
Sometimes application_manager_test may fail with core crash

##### Reproduction Steps
1. Build SDL core with `-DBUILD_TESTS=ON` and `-DENABLE_SECURITY=OFF` cmake options
2. Run `application_manager_test` with command:
```
./application_manager_test --gtest_filter=PolicyHandlerTest.OnAppPermissionConsentInternal_ExistAppsPreviouslyStored_SUCCESS --gtest_repeat=10000
```

##### Expected Behavior
Test passed

##### Observed Behavior
Test failed and core crash observed

##### OS & Version Information
* OS/Version: Ubuntu 18.04
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/tree/develop (31324d5)
* Testing Against: N/A

##### Test Case, Sample Code, and / or Example App
 - [backtrace.txt](https://github.com/smartdevicelink/sdl_core/files/7443668/backtrace.txt)

**Comment by JackLivio** [comment]
@dboltovskyi Is Luxoft going to submit a pr for this issue?

**Comment by dboltovskyi** [comment]
@JackLivio Yes, Luxoft teams is going to submit a fix for this issue.

**Comment by ShobhitAd** [comment]
Closed via https://github.com/smartdevicelink/sdl_core/pull/3810
