### ISSUE TITLE
Core sometimes sends redundant OnAudioDataStreaming(true/false) notifications

### ISSUE THREAD

**Issue by dboltovskyi** [smartdevicelink/sdl_core#3811]
### Bug Report
Core sometimes sends redundant `OnAudioDataStreaming(true/false)` notifications to HMI

##### Occurrences
Rare (~0.1%)

##### Reproduction Steps
1. App starts Video and Audio streaming at the same time
2. Core sends requests to HMI:
a) `Navigation.StartStream`
b) `Navigation.StartAudioStream`
3. HMI responds to a) and doesn't respond to b)
4. Core sends 3 more b) requests
5. HMI still doesn't respond

##### Expected Behavior
Core does:
- stop Audio service
- not stop Video service
- continue Video streaming from App
- not unregister App with `PROTOCOL_VIOLATION` reason
- not send redundant `Navi.OnAudioDataStreaming` messages to HMI

##### Observed Behavior
Core does:
- send redundant Navi.OnAudioDataStreaming messages to HMI

##### OS & Version Information
* OS/Version: Ubuntu 20.04
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/tree/develop (31324d5)
* Testing Against: ATF

##### Test Case, Sample Code, and / or Example App
- Impacted scripts:
    - https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Defects/8_0/3479_1_Audio-Video_streaming_same_time_no_response_from_HMI_for_Audio.lua
    - https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Defects/8_0/3479_2_Audio-Video_streaming_same_time_no_response_from_HMI_for_Video.lua
- Report and Logs:
    - [3811_Audio.zip](https://github.com/smartdevicelink/sdl_core/files/7470545/3811_Audio.zip)
    - [3811_Video.zip](https://github.com/smartdevicelink/sdl_core/files/7470546/3811_Video.zip)

**Comment by iCollin** [comment]
Closed via https://github.com/smartdevicelink/sdl_core/pull/3816
