### ISSUE TITLE
Core doesn't restore app's HMI level during resumption

### ISSUE THREAD

**Issue by dboltovskyi** [smartdevicelink/sdl_core#3821]
### Bug Report
Core doesn't restore app's HMI level during resumption

##### Occurrences
Rare

##### Reproduction Steps
1. App registered and activated (HMI level is `FULL`)
2. App adds `Command1`, `Command2`, `Command3` commands with `vrCommands` parameter
3. Perform disconnect and reconnect

##### Expected Behavior
SDL restore app's HMI level to `FULL`

##### Observed Behavior
SDL doesn't restore app's HMI level

##### OS & Version Information
* OS/Version: Ubuntu 20.04
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/tree/develop (31324d5)
* Testing Against: ATF

##### Test Case, Sample Code, and / or Example App
- Impacted script: https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/SDL5_0/Handling_VR_help_requests/023_SetGlobalProp_custom_vrHelp_only_by_resumption.lua 
- Reports and logs: [3821.zip](https://github.com/smartdevicelink/sdl_core/files/7498648/3821.zip)

**Comment by dboltovskyi** [comment]
@theresalech Please notice Luxoft team is planning to provide a fix

**Comment by iCollin** [comment]
Closed via https://github.com/smartdevicelink/sdl_core/pull/3836
