### ISSUE TITLE
SDL sends redundant UI.ClosePopUp request

### ISSUE THREAD

**Issue by VjKlepikov** [smartdevicelink/sdl_core#3838]
### Bug Report
SDL sends redundant UI.ClosePopUp request in several cases

Issue is also relevant for cases:
  - SDL sends redundant UI.ClosePopUp request in case mobile App sends PerformInteraction request with BOTH interaction mode to SDL and HMI responds with 'SUCCESS' to VR.PerformInteraction request without choiceID
  - SDL sends redundant UI.ClosePopUp request in case mobile App sends two PerformInteraction requests with VR_ONLY interaction mode to SDL

##### Reproduction Steps
1. SDL and HMI are started
2. Mobile app is registered and activated
3. CreateInteractionChoiceSet is added
4.  App sends PerformInteraction request with VR_ONLY interaction mode to SDL
5. HMI responds with 'SUCCESS' to UI.PerformInteraction request
6. HMI responds with 'TIMED_OUT' to VR.PerformInteraction request

##### Expected Behavior
SDL does not send UI.ClosePopUp request to HMI 

##### Observed Behavior
SDL sends UI.ClosePopUp request to HMI

##### OS & Version Information
* OS/Version: Ubuntu 18.04
* SDL Core Version: [https://github.com/smartdevicelink/sdl_core/tree/develop](https://github.com/smartdevicelink/sdl_core/tree/develop)

SDL logs: [Logs_SDL.zip](https://github.com/smartdevicelink/sdl_core/files/7734637/Logs_SDL.zip)

**Comment by VjKlepikov** [comment]
@theresalech Please notice Luxoft team is going to prepare a fix and ATF script(s) to verify it.

**Comment by jacobkeeler** [comment]
closed via #3844
