### ISSUE TITLE
Driver Distraction Notification does not include Lock Screen Dismissal information when state=DD_OFF

### ISSUE THREAD

**Issue by joeljfischer** [smartdevicelink/sdl_core#3841]
### Bug Report
When connecting to the Generic_HMI, an initial driver distraction notification is sent, but that DD notification doesn't include the lock screen dismissal enabled parameter, nor lock screen text. This information should be included so that lock screen dismissal is enabled before a second DD notification is received.

##### Reproduction Steps
1. Watch for the first DD notification
2. Connect to Core + generic_hmi
3. View the DD notification
4. Toggle DD
5. View the second DD notification

##### Expected Behavior
The initial DD notification should include lock screen dismissal information

##### Observed Behavior
The initial DD notification does not include lock screen dismissal information, but the second DD notification does

##### Browser & Version Information
* Browser and Version: Chromium 95.0
* RPC Sent: n/a
* Output Received: n/a
* Generic HMI Version: v0.11.0 / v0.10.0
* Testing Against: Core v8.0.0 / Manticore (Core v7.1.1)

##### Test Case, Sample Code, and / or Example App
n/a

**Comment by jacobkeeler** [comment]
Closed via #3842
