### ISSUE TITLE
SDL removes the current "consumer_friendly_messages" section in Local PT in case the Updated PT omits "consumer_friendly_messages" section

### ISSUE THREAD

**Issue by VjKlepikov** [smartdevicelink/sdl_core#3846]
### Bug Report
SDL removes the current "consumer_friendly_messages" section in Local PT in case the Updated PT omits "consumer_friendly_messages" section

##### Reproduction Steps
1. Make sure SDL is built with HTTP flow
2. Register new application => PTU is triggered
3. PTU omits "consumer_friendly_messages" section

##### Expected Behavior
SDL maintains the current "consumer_friendly_messages" section in Local PT

##### Observed Behavior
SDL removes the current "consumer_friendly_messages" section in Local PT in case the Updated PT omits "consumer_friendly_messages" section

##### OS & Version Information
* OS/Version: Ubuntu 18
* SDL Core Version:  https://github.com/smartdevicelink/sdl_core/tree/develop (6ca6961)

##### Test Case, Sample Code, and / or Example App
* Tests scripts: *./test_scripts/Policies/build_options/070_ATF_PTU_Merge_Into_Local_PT_ConsumerFriendlyMessages_Omitted_HTTP.lua

**Comment by VjKlepikov** [comment]
Please notice this is a regression issue that became reproducible after merge of [#3842](https://github.com/smartdevicelink/sdl_core/pull/3842)
@theresalech  Can you please advise if the Livio team is planning on submitting a PR to fix?

**Comment by theresalech** [comment]
@VjKlepikov our team will review the issue and advise.

**Comment by jacobkeeler** [comment]
@VjKlepikov can you confirm if this issue only occurs in HTTP mode?

**Comment by jacobkeeler** [comment]
After testing, it appears that this issue is reproducible in master if `OnDriverDistraction(DD_ON)` is sent prior to registering the app. It seems likely that the issue lies in [this section of code](https://github.com/smartdevicelink/sdl_core/blob/develop/src/components/application_manager/src/application_manager_impl.cc#L4663-L4678)

**Comment by jacobkeeler** [comment]
closed via #3852
