### ISSUE TITLE
SDL core dump on Ignition OFF during registering Apps

### ISSUE THREAD

**Issue by VjKlepikov** [smartdevicelink/sdl_core#3857]
## Bug Report
SDL core dump on Ignition OFF during registering Apps

##### Occurrences:
~10%

##### Reproduction Steps
1. SDL and HMI are started
2. Connect mobile device via USB transport.
3. Perform ignition Off during registering Apps (25 Apps)
On "HMI" go to → Click the "Exit Application" button → Select “IGNITION_OFF” in “Exit Application reason” → Click the `Send state` button

##### Expected Behavior
SDL starts the ignition off sequence
1. SDL sends to HMI OnSDLClose and stops working
SDL->HMI: BasicCommunication.OnSDLClose:{}

##### Observed Behavior
SDL starts the ignition off sequence
1. SDL sends to HMI OnSDLClose and stops working
SDL->HMI: BasicCommunication.OnSDLClose:{}
Core dump is observed
SIGSEGV caught
DEBUG [139969695552064][SDLMain] /home/jenkins/workspace/Develop_SDL_NoUT_P/src/appMain/life_cycle_impl.cc:241 {anonymous}::sig_handler: SIGSEGV signal has been caught

##### OS & Version Information
* OS/Version: Ubuntu 18
* SDL Core Version:  https://github.com/smartdevicelink/sdl_core/tree/develop (7a4a4e0)

##### Logs:
[Logs.zip](https://github.com/smartdevicelink/sdl_core/files/8061975/Logs.zip)

**Comment by VjKlepikov** [comment]
Please notice this is a non-regression issue. It's also reproduced on 8.0

**Comment by VjKlepikov** [comment]
@theresalech Please notice Luxoft team is going to prepare a fix

**Comment by ShobhitAd** [comment]
@VjKlepikov I was able to reproduce this issue on my end manually but might need an ATF tests PR to more easily test the fix PR.

**Comment by VjKlepikov** [comment]
@ShobhitAd Please find PR with  the script in https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/2694

**Comment by ShobhitAd** [comment]
Closed via https://github.com/smartdevicelink/sdl_core/pull/3939
