### ISSUE TITLE
SDL rejects SystemRequest from mobile App during PTU in case HMI sends BC.OnSystemRequest with 'url' parameter

### ISSUE THREAD

**Issue by VjKlepikov** [smartdevicelink/sdl_core#3881]
### Bug Report
SDL rejects SystemRequest from mobile App during PTU in case HMI sends BC.OnSystemRequest with url parameter

##### Reproduction Steps
SDL is built in PROPRIETARY policy mode
Core and HMI are started
App is registered
SDL sends OnStatusUpdate(UPDATING)
HMI sends OnSystemRequest with 'url' parameter
SDL send OnSystemRequest to App
App sends SystemRequest(PROPRIETARY) to SDL 

##### Expected Behavior
SDL sends SystemRequest(SUCCESS) response to mobile App

##### Observed Behavior
SDL rejects SystemRequest from mobile App

##### OS & Version Information
* OS/Version: Ubuntu 18
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/tree/release/8.1.0 (25e47c7)

##### Logs:
[Logs_P.zip](https://github.com/smartdevicelink/sdl_core/files/8323477/Logs_P.zip)

**Comment by VjKlepikov** [comment]
@theresalech  Please notice this is a regression issue that became reproducible after merge of https://github.com/smartdevicelink/sdl_core/pull/3853

**Comment by JackLivio** [comment]
@VjKlepikov Can you provide the test you were using for this issue please?

**Comment by VjKlepikov** [comment]
@JackLivio Issue has been found during manual testing with enable External Policies option  on Web-HMI 
Also please find draft script to check the issue https://github.com/smartdevicelink/sdl_atf_test_scripts/commit/c87e1a0fa1abadd46573b046d523e572d58923bd

**Comment by JackLivio** [comment]
@VjKlepikov I confirmed my pr fixes the issue for both external and proprietary policy builds. Could you please open a pr with those atf changes?

**Comment by VjKlepikov** [comment]
@JackLivio Yes, Luxoft team is going to prepare ATF script(s) to verify it

**Comment by VjKlepikov** [comment]
@JackLivio Please find PR with ATF script(s) to check the issue
Please note SDL rejects SystemRequest from mobile App during PTU for several apps in case HMI sends BC.OnSystemRequest with 'url' parameter
Sometimes test script is FAILED 
https://github.com/LuxoftSDL/sdl_atf_test_scripts/blob/defects/3881/test_scripts/Policies/Policy_Table_Update/177_PTU_is_performed_for_several_Apps_if_HMI_sends_BC_OnSystemRequest_with_url_parameter.lua
logs: 
[Logs.zip](https://github.com/smartdevicelink/sdl_core/files/8342330/Logs.zip)
SDL: fix/issue_3881 (bf9e4e4d)
