### ISSUE TITLE
SDL requests invalid VR.AddCommand during CreateInteractionChoiceSet resumption without VR part

### ISSUE THREAD

**Issue by GetmanetsIrina** [smartdevicelink/sdl_core#3888]
### Bug Report
SDL requests invalid `VR.AddCommand` during `CreateInteractionChoice` resumption without `VR` part

##### Precondition
1. SDL and HMI are started
2. Mobile app is registered and activated

##### Reproduction Steps
1. Mobile app requests `CreateInteractionChoiceSet` without `VR Command`
2. Perform transport reconnect  
5. Mobile app is registered with actual hash id

##### Expected Behavior
SDL does not request `VR.AddCommand` for  the `CreateInteractionChoiceSet` resumption without `VR Command` and resumes `CreateInteractionChoiceSet` internally

##### Observed Behavior
SDL request invalid `VR.AddCommand` message during resumption
```
SDL -> HMI [16:36:20:329]: {"id":96,"jsonrpc":"2.0","method":"VR.AddCommand","params":{"appID":856255661,"cmdID":4,"grammarID":0,"type":"Choice","vrCommands":null}}

VRRPC.js:295 FFW.VR.AddCommandResponse
RPCClient.js:323 HMI -> SDL [16:36:20:330]: {"jsonrpc":"2.0","id":96,"error":{"code":11,"message":"Parameter 'vrCommands' does not exists!","data":{"method":"VR.AddCommand"}}}
```

##### Note:
In case of deleting such `CreateInteractionChoiceSet`(without `VR` part) after it adding ( step 1 from ) SDL also requests invalid `VR.DeleteCommand`
```
{"id":70,"jsonrpc":"2.0","method":"VR.DeleteCommand","params":{"appID":1326361392,"cmdID":1,"grammarID":null,"type":"Choice"}}
```

##### OS & Version Information
* OS/Version: Ubuntu 18.04
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/tree/8.1-RC1 ([25e47c7](https://github.com/smartdevicelink/sdl_core/commit/25e47c7f34f90f5393958f998c1861efa966d702))
* Testing Against: HMI: https://github.com/smartdevicelink/sdl_hmi/tree/release/5.7.0 ([cd2d250](https://github.com/smartdevicelink/sdl_hmi/commit/cd2d250cba100d1e0dd354172d2e24c0bd3449fc)), SyncProxyTester: 20210729-Android

##### Logs
[SmartDeviceLinkCore.zip](https://github.com/smartdevicelink/sdl_core/files/8333946/SmartDeviceLinkCore.zip)

**Comment by LitvinenkoIra** [comment]
Luxoft team is going to fix this issue

**Comment by ShobhitAd** [comment]
Closed via https://github.com/smartdevicelink/sdl_core/pull/3938
