### ISSUE TITLE
Remove optional argument in MessageBroker Thread::Join

### ISSUE THREAD

**Issue by nk0leg** [smartdevicelink/sdl_core#389]
Investigate is possible remove optional argument for `Thread::Join(void** ret)`
for `pthread_join` we can use  `pthread_join(thread, NULL);`

For OS Windows:
`GetExitCodeThread(m_id, &val);`
`CloseHandle(m_id);`
`m_id = NULL;`
`*ret = (void*)val;` <-- ASSERT

**Comment by JackLivio** [comment]
Closing since issue is outdated and non descriptive. The "Message broker" has been replaced replaced by a boost web sockets library.
