### ISSUE TITLE
SDL sends BasicCommunication.PolicyUpdate(sdl_snapshot.json) twice

### ISSUE THREAD

**Issue by VjKlepikov** [smartdevicelink/sdl_core#3895]
### Bug Report
SDL sends BasicCommunication.PolicyUpdate(sdl_snapshot.json) twice

##### Reproduction Steps
1. SDL and HMI are started
2. HMI sends SDL.OnPolicyUpdate notification during triggered PTU by register App
 HMI->SDL: HMI sends SDL.OnPolicyUpdate

##### Expected Behavior
SDL->HMI: SDL.OnStatusUpdate("UPDATE_NEEDED")
SDL->HMI: BasicCommunication.PolicyUpdate(sdl_snapshot.json)

##### Observed Behavior
SDL->HMI: SDL.OnStatusUpdate("UPDATE_NEEDED")
SDL->HMI: SDL sends BasicCommunication.PolicyUpdate(sdl_snapshot.json) request twice

##### OS & Version Information
* OS/Version: Ubuntu 18
* SDL Core Version:  https://github.com/smartdevicelink/sdl_core/tree/release/8.1.0 (b30f0125) (also reproduced in 8.0.0)

##### Test Case, Sample Code, and / or Example App
./test_scripts/Policies/App_Permissions/005_ATF_DISALLOWED_app_Id_policies_And_RequestType_Validation.lua

**Comment by LitvinenkoIra** [comment]
Luxoft team is going to fix this issue

**Comment by ShobhitAd** [comment]
Closed via https://github.com/smartdevicelink/sdl_core/pull/3921
