### ISSUE TITLE
Generated vrHelp is not properly resumed after ResetGlobalProperties

### ISSUE THREAD

**Issue by jacobkeeler** [smartdevicelink/sdl_core#3909]
### Bug Report
Autogenerated vrHelp is not resumed of ResetGlobalProperties was sent previously

##### Reproduction Steps
1. Register app
2. Send AddCommand
3. Send SetGlobalProperties with vrHelp & vrHelpTitle
4. Send ResetGlobalProperties with VRHELPTITLE and VRHELPITEMS (HMI receives autogenerated vrHelp and vrHelpTitle)
5. Disconnect and reconnect app with correct resumption hash ID

##### Expected Behavior
HMI receives autogenerated vrHelp and vrHelpTitle based on commands

##### Observed Behavior
Core resumes vrHelpTitle, but does not provide generated vrHelp

##### OS & Version Information
* OS/Version: Ubuntu 20.04
* SDL Core Version: master (8.1.0)
* Testing Against: RPC Builder App JS and Generic HMI (master)

**Comment by ShobhitAd** [comment]
Closed via https://github.com/smartdevicelink/sdl_core/pull/3916
