### ISSUE TITLE
Core crash during fails resumption

### ISSUE THREAD

**Issue by VjKlepikov** [smartdevicelink/sdl_core#3910]
### Bug Report
Core crash during fails resumption

##### Reproduction Steps
1. App is registered
2. App added some resumption data
3. Ignition On/Off
4. App re-connected
5. During resumption SDL sends requests to HMI
6. HMI responds with late response to one of the requests

##### Expected Behavior
Core fails resumption and send RegisterAppInterfaceResponse(success=true,result_code=RESUME_FAILED) to mobile application

##### Observed Behavior
 Core crash
src/appMain/life_cycle_impl.cc:241 {anonymous}::sig_handler: SIGSEGV signal has been caught

##### OS & Version Information
* OS/Version: Ubuntu 18.04
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/tree/develop (65947fd), release_8.0

##### Test Case, Sample Code, and / or Example App
./test_scripts/Resumption/Handling_errors_from_HMI/014_resume_one_rpc_late_response_ign_off.lua

##### Logs: 
[2022-04-21_11-10-13.135_failed.tar.gz](https://github.com/smartdevicelink/sdl_core/files/8538374/2022-04-21_11-10-13.135_failed.tar.gz)

**Comment by ShobhitAd** [comment]
Closed via https://github.com/smartdevicelink/sdl_core/pull/3919
