### ISSUE TITLE
Multiple APP support on iOS

### ISSUE THREAD

**Issue by jinujose50** [smartdevicelink/sdl_core#393]
Can you please provide the documentation or reference regarding the usage of "com.smartdevicelink.prot" protocol to support multiple APPs on iOS? In which version of SDL this feature is added?

**Comment by chenbd** [comment]
@jinujose50  Is there any update on this issue?

**Comment by JackLivio** [comment]
Sorry but IAP is not currently supported in the open source version of SDL Core.
