### ISSUE TITLE
Core stops generating vrHelp and helpPrompt after ResetGlobalProperties

### ISSUE THREAD

**Issue by jacobkeeler** [smartdevicelink/sdl_core#3931]
### Bug Report
If ResetGlobalProperties is sent for VRHELP, VRHELPTITLE, and HELPPROMPT, an auto-generated value for each of these fields is sent initially, but these auto-generated values no longer update after this. 

##### Reproduction Steps
1. Register App
2. Send AddCommand, verify UI.SetGlobalProperties + TTS.SetGlobalProperties are sent with info for this command
3. Send SetGlobalProperties with vrHelp + vrHelpTitle + helpPrompt
4. Send ResetGlobalProperties with VR_HELP, VR_HELP_TITLE, verify UI.SetGlobalProperties + TTS.SetGlobalProperties matches step 1
5. Send another AddCommand

##### Expected Behavior
UI.SetGlobalProperties  + TTS.SetGlobalProperties are sent with data for both commands

##### Observed Behavior
UI.SetGlobalProperties  + TTS.SetGlobalProperties are not sent

##### OS & Version Information
* OS/Version: Ubuntu 20.04
* SDL Core Version: master (Release 8.1)
* Testing Against: RPC Builder JS

**Comment by jacobkeeler** [comment]
Seems this is because the `sending_type_` is never updated when ResetGlobalProperties is sent, see https://github.com/smartdevicelink/sdl_core/blob/master/src/components/application_manager/src/help_prompt_manager_impl.cc#L340

**Comment by ShobhitAd** [comment]
Closed via https://github.com/smartdevicelink/sdl_core/pull/3937
