### ISSUE TITLE
CheckButtonName check not working for module types other than CLIMATE and RADIO

### ISSUE THREAD

**Issue by ShobhitAd** [smartdevicelink/sdl_core#3945]
### Bug Report
Currently, core only checks if a button name is compatible with the module type (in CheckButtonName) if the module type in the request is CLIMATE or RADIO. 

If the user were to send a ButtonPress request with a different type, core would currently not send the "Request module type and button name mismatch!" response and forward the invalid request to the HMI

##### Reproduction Steps
1. Add RemoteControl permissions in preloaded_pt
```json
"app_policies": {
            "default": {
                "keep_context": false,
                "steal_focus": false,
                "priority": "NONE",
                "default_hmi": "NONE",
                "groups": [
                    "Base-4",
+                    "RemoteControl"
                ],
+                "moduleType": [],
                "RequestType": [],
                "RequestSubType": []
            },
```
3. Start core and HMI
4. Register and activate RPC Builder app with appHMIType REMOTE_CONTROL
5. Send ButtonPress with params `{"moduleType":"HMI_SETTINGS","buttonName":"FAN_UP","buttonPressMode":"LONG"}`

##### Expected Behavior
App receives INVALID_DATA response with info "Request module type and button name mismatch!"

##### Observed Behavior
App receives SUCCESS response

##### OS & Version Information
* OS/Version: Ubuntu 20.04
* SDL Core Version: release/8.2.0
* Testing Against: RPC Builder

**Comment by jacobkeeler** [comment]
Closed via #3944
