### ISSUE TITLE
Resumption timestamps are limited to 32 bits

### ISSUE THREAD

**Issue by jacobkeeler** [smartdevicelink/sdl_core#3948]
### Bug Report
Detected by Coverity (CIDs 277332 and 277353).

The `timestamp` and `last_ign_off_time` parameters in the resumption data storage are currently written to and read as `uint32_t`, which could be shorter than `time_t`. These parameters should be stored as `int64_t` to prevent narrowing conversions. See [here](https://github.com/smartdevicelink/sdl_core/blob/master/src/components/application_manager/src/resumption/resumption_data_json.cc#L65)

##### Reproduction Steps
1. Set clock so that the timestamp goes past the unsigned 32 bit limit (year=2200 should work)
2. Start Core
3. Connect app
4. Stop Core and check `app_info.dat`

##### Expected Behavior
`timestamp` should match up with system clock

##### Observed Behavior
`timestamp` does not match up with system clock due to narrowing conversion

##### OS & Version Information
* OS/Version: Ubuntu 20.04
* SDL Core Version: master

**Comment by ShobhitAd** [comment]
Closed via https://github.com/smartdevicelink/sdl_core/pull/3946
