### ISSUE TITLE
How to connect to other Apps besides Livio SDL tester

### ISSUE THREAD

**Issue by tulip0425** [smartdevicelink/sdl_core#403]
Hi,
Besides Livio SDL tester, How can i test connecting with other Apps which support Applink?
For example,  those apps officially announced supporting Applink on Ford Website, like spotify, glympse, or others.
thanks.

**Comment by JackLivio** [comment]
What transport method are you using to connect to sdl core? If you are using android, most production apps require you to connect via bluetooth/usb. If you are connecting via a tcp connection then apps like Spotify will not connect to core.

**Comment by tulip0425** [comment]
Yes, I was using Android and WiFi/TCP connection to connect to core.
I have read through the mailing list that USB connection was not supported yet, right?
So does sdl core support connecting production apps via bluetooth?

thanks.

**Comment by jacobkeeler** [comment]
Yes, all production Android apps use bluetooth as their transport.
