### ISSUE TITLE
enable PLAY/PAUSE functionality 

### ISSUE THREAD

**Issue by madhuy** [smartdevicelink/sdl_core#406]
As per HMI spec 7.29.3.16 ButtonName. there is PLAY/PAUSE button but not added in SDL core.
Please check this.

**Comment by justinjdickow** [comment]
The HMI spec is updated with some features that will be done in develop, and for this it was unfortunately updated in advance. For now, and for all media apps using current mobile proxies, the button they will subscribe to for play/pause events is called OK
