### ISSUE TITLE
Web HMI code present in core repository and in separate repository

### ISSUE THREAD

**Issue by JackLivio** [smartdevicelink/sdl_core#411]
[Web HMI directory in core](https://github.com/smartdevicelink/sdl_core/tree/master/src/components/HMI)

[Web HMI Repository](https://github.com/smartdevicelink/sdl_hmi)

Can we strip the web hmi code from the sdl_core repository if we are going to keep the web hmi code maintained in a separate repository?

**Comment by jacobkeeler** [comment]
@LuxoftAKutsan Is there any reason that this code is still included in this repository, or can it be safely removed?

**Comment by jacobkeeler** [comment]
or @AnastasiyaBritanova
