### ISSUE TITLE
SDL is core is allowing 'TextField' text  more than  Max value(500)

### ISSUE THREAD

**Issue by madhuy** [smartdevicelink/sdl_core#418]
The Max value  is 500 for textfield . but SDL core is sending to HMI even mobile app sends more than 500.
https://github.com/smartdevicelink/sdl_core/blob/master/src/components/interfaces/MOBILE_API.xml#L1614

I am not sure who should control it . is it HMI or is it SDL core? 

Please clarify.

**Comment by JackLivio** [comment]
I think that value is for 500 character per row.

```
  <description>The number of characters in one row of this field.</description>
```

Is sdl sending a line more than 500 chars long in a single row?

**Comment by madhuy** [comment]
Yes. mobile app sending more than 500 chars for each line. SDL core sending to HMI.

**Comment by madhuy** [comment]
It is our Mobile app issue. Sorry for confusion.
