### ISSUE TITLE
GENIVI would like to use SDL mirror repo here: https://github.com/genivi

### ISSUE THREAD

**Issue by jeremiah** [smartdevicelink/sdl_core#421]
Hi,

I believe some folks from the SDL project setup a GitHub repo called genivi: https://github.com/genivi
GENIVI is hoping to move some, if not all, their repos to a mirror on GitHub and would like to use the above named repo to do so. Is it possible to grant ownership to GENIVI of that repo? Of course we would change anything with SDL repos.

Thanks!

Jeremiah

**Comment by justinjdickow** [comment]
Sent you a private email
