### ISSUE TITLE
SDL demo with Bluetooth and Pandora question?

### ISSUE THREAD

**Issue by chrisarney** [smartdevicelink/sdl_core#44]
I'm trying to get a demo up and running using SDL, Bluetooth, and Pandora on Android. I've got SDL core up and running on an Ubuntu laptop with these options enabled: EXTENDED_MEDIA_MODE, BUILD_BT_SUPPORT, and BUILD_USB_SUPPORT. I've tried connecting using the SDL helper app on Android, but it doesn't see the SDL over Bluetooth. Do I need to enable something different? How do I get this up and running using Bluetooth?

**Comment by genivi** [comment]
Hey Chris,

I have a few questions regarding your issue.

What phone are you using?

Can you confirm that the phone is paired to the laptop?

What branch of SDL did you build?

Are you able to connect via tcp?

best,

justin


justin dickow, product development project manager

justin@livio.io

cell: 248-842-2836

office: 248-591-0333, ext 889.

skype: justin.dickow.livio


3136 Hilton, Ferndale, MI 48220
