### ISSUE TITLE
How to send data from sdl-core to mobile app

### ISSUE THREAD

**Issue by surabhiz** [smartdevicelink/sdl_core#458]
I have made an app which will interact with the SDL-core. The app basically has to send a request to the sdl-core asking for data. I expect the sdl-core to provide the requested data back to the application only when requested. The sdl-core should send data continuously after a request  is recieved. 
The only RPC which came close to doing the above task was OnSystemRequest but I am not entirely sure about it. 

The data to the SDL-core comes from some other device and not from mobile application.

**Comment by JackLivio** [comment]
What kind of data are you looking for? If you subscribe to certain data like button presses or vehicle data, core will constantly send you those subscribed messages until your app unsubscribes from them. Please refer follow up questions to the SDL slack http://slack.smartdevicelink.com
