### ISSUE TITLE
DialNumber Disallowed 

### ISSUE THREAD

**Issue by JackLivio** [smartdevicelink/sdl_core#488]
When performing a Dial Number Request, Core is returning Disallowed.

Dial number is not included in the "Base-4" functional grouping  and therefore permission for DialNumber is not given to apps by default.

Now that DialNumber is implemented, do we want to include this RPC as a default permission for app policies?

**Comment by chinlin0924** [comment]
@JackLivio I think it is necessary.

**Comment by JackLivio** [comment]
Not an issue, where DialNumber is included in the policy table is technically a configuration option.
