### ISSUE TITLE
Microphone format not set, settings from PerformAudioPassThru request ignored by OnAudioPassThru notification

### ISSUE THREAD

**Issue by chrisdrehernuance** [smartdevicelink/sdl_core#491]
The OnAudioPassThru notification sends microphone audio data from the headunit to the mobile device as binary PCM data (preceded by a wav file header).  Unfortunately, this data does not match the PCM format requested in the preceding PerformAudioPassThru request from the phone.

For example, PerformAudioPassThru can request microphone audio data in a format of 8-bit PCM at 22KHz but OnAudioPassThru will return data in the OS's default format (ex: 16-bit 44KHz).

Recommend updating the file from_mic_to_file_recorder_thread.cc to set the sampling Hz, the bits-per-sample, and number of channels.

**Comment by LitvinenkoIra** [comment]
Priority Low.
Offer for enhancement, not a defect.

**Comment by JackLivio** [comment]
@chrisdrehernuance That audio format might not be supported by the head unit. Please check the audioPassThruCapabilities struct in the Register App Interface response. Also having multiple supported audioPassThruCapabilities is an accepted proposal. Please refer to this proposal which will be implemented into core in the future. https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0138-hmi-audiopassthru-capability.md

**Comment by ShobhitAd** [comment]
Closed via #2184
