### ISSUE TITLE
Changes to better support non-VR head units

### ISSUE THREAD

**Issue by justinjdickow** [smartdevicelink/sdl_core#561]
#### Steps to Reproduce
- SDL receives `VR.IsReady(available:false)` and `UI.IsReady(available:true)` from HMI
- SDL receives a command which has optional params that can trigger messages to VR and UI (AddCommand, PerformInteraction, etc.) from an app
#### Current Behavior
- SDL returns `GENERIC_ERROR` to the app
#### Expected Behavior
- SDL returns success with warning info describing the unsupported VR portion
#### Other Corner Cases
- If SDL receives a command which is VR ONLY and previously received VR.IsReady(available:false), SDL should return GENERIC_ERROR
#### Justification

This is better behavior because it takes the burden off of the app developer to determine whether VR is supported by the connected head unit before building their RPCs which have vrSynonyms (or similar) params.

**Comment by JackLivio** [comment]
Now supported from the 4.2 release
