### ISSUE TITLE
Cannot download documentations from appbox

### ISSUE THREAD

**Issue by BrandonHe** [smartdevicelink/sdl_core#563]
@justinjdickow 
Several developers said they can't download SDL documentations in yesterday. I just now verified, can open the link and review the documents successfully. But click **DOWNLOAD** button on app.box.com is no response.

Thanks!

**Comment by justinjdickow** [comment]
Thanks @BrandonHe. I've got a ticket internally to update all of the READMEs to point to smartdevicelink.com for documentation now.

**Comment by BrandonHe** [comment]
@justinjdickow Yes, that's why I closed this issue. Thanks.
