### ISSUE TITLE
V4 Tester application cannot be downloaded

### ISSUE THREAD

**Issue by dustinrwh** [smartdevicelink/sdl_core#590]
The README.md links to an application that can be used for testing called V4 Tester application. This file is host at box.com here: 
[https://app.box.com/s/eeloquc0fhqfmxjjubw7kousf12f3pzg](https://app.box.com/s/eeloquc0fhqfmxjjubw7kousf12f3pzg)

Unfortunately, the file cannot be downloaded. I tried in Safari, Chrome and Firefox.

Is there any alternate link or something I'm missing?

Thanks!

**Comment by amiramo3** [comment]
I too have this issue.

**Comment by pankaj2590** [comment]
I am also facing same issue.
Is there any alternate link or alternate application for same.

Thanks,

**Comment by jacobkeeler** [comment]
Appears to have been fixed
