### ISSUE TITLE
Generic DisplayType

### ISSUE THREAD

**Issue by MprenticeUIE** [smartdevicelink/sdl_core#626]
Current DisplayType is based on Ford head units.  This needs to be changed to generic enums.  Example Video_Ht_Wt or Text_#lines_Lines. 

To this end, implement Video_800_480 included in the next SDL Core and Proxy Drop

**Comment by MprenticeUIE** [comment]
quick clarification we want Video_480_800

**Comment by goelgoldi** [comment]
@joeygrover, Any update on this request?

**Comment by joeygrover** [comment]
This was discussed on a while back, but not finally decision has been reached. 

I believe an evolution proposal is needed here. I think the change will be more than adding an enum for a specific resolution. We might be able to add a generic enum like "SDL_Generic". Then I believe we want to add things like resolution/screen size/etc into the display capabilities. 

@tpulatha Can you comment? I know we talked about this. I think the quick answer is to add SDL_Generic as a Display_Type and then using the evolution process to add the other parameters.

**Comment by goelgoldi** [comment]
@tpulatha Please let us know when its doable?

**Comment by joeygrover** [comment]
@goelgoldi There is now a pull request open that should address the addition of the enum. #884

**Comment by joeygrover** [comment]
Fixed with merge of #884
