### ISSUE TITLE
Policy update is been triggered Continiously if we enable  flag ENABLE_EXTENDED_POLICY

### ISSUE THREAD

**Issue by madhuy** [smartdevicelink/sdl_core#636]
1) Enabled ENABLE_EXTENDED_POLICY in SDL core.
2) Policy update been triggered continuously 

Please look for "BasicCommunication.PolicyUpdate" in logs. 

[SmartDeviceLinkCore.txt](https://github.com/smartdevicelink/sdl_core/files/328778/SmartDeviceLinkCore.txt)

**Comment by JackLivio** [comment]
@madhuy looking into this

**Comment by JackLivio** [comment]
@madhuy Do you see this behavior every time? 

I am unable to replicate this behavior at the moment. Using recent versions of SPT, Core, and the web hmi I only see the initial policy update.

**Comment by JackLivio** [comment]
I also do not see BasicCommunication.OnSystemRequest in your logs. I think you might have something hooked up wrong in your HMI?

**Comment by madhuy** [comment]
@JackLivio 
with ENABLE_EXTENDED_POLICY it calls the  "BasicCommunication.PolicyUpdate" NOT "BasicCommunication.OnSystemRequest" for policy update

I think I know the reason . We need to call 
 policy::PolicyHandler::instance()->OnUpdateRequestSentToMobile(); to reset update_required_ value.

in [SendPolicyUpdate](https://github.com/smartdevicelink/sdl_core/blob/master/src/components/application_manager/src/message_helper.cc#L1580)()

With this fix it is working I will create PULL request.

**Comment by madhuy** [comment]
@JackLivio  Please review change https://github.com/smartdevicelink/sdl_core/pull/644/files

**Comment by AnastasiyaBritanova** [comment]
Hi Guys!

Please - it seems you'll break the expected flow of events with these fixes :)

Correct flow for ENABLE_EXTENDED_POLICY: **ON**

1. policies update is triggered: SDL -> HMI: PolicyUpdate (with Snapshot of current policies)
2. HMI **must request** the policices urls via GetURLs RPC 
3. Afterwards, **HMI must generate OnSystemRequest** through SDL to mobile app.

You should not fix SDL to generate OnSystemRequest - in this case, it's HMI's responsibility.

**Comment by AnastasiyaBritanova** [comment]
Please see the attached diagram for details.
![policies_proprietary_flow](https://cloud.githubusercontent.com/assets/11644716/16690788/3d946dde-4532-11e6-976c-f4a20d7d5318.png)

**Comment by JackLivio** [comment]
@madhuy see proper flow above

**Comment by JackLivio** [comment]
@madhuy After the HMI sends an OnSystemRequest to Core, [the application manager will call](https://github.com/smartdevicelink/sdl_core/blob/master/src/components/application_manager/src/application_manager_impl.cc#L1269) 
```
OnUpdateRequestSentToMobile();
``` 
when processing the OnSystemRequest message from the HMI before passing along the message to the mobile side.

**Comment by madhuy** [comment]
@JackLivio  I understand the Flow.  in our HMI, HMI does not create BC.OnSystemRequest to get Policy data from server.  we get Policy data with different mechanism(secure channel), store into the file and directly call the SDL.OnRecievedPolicyUpdate() .  

my question , where the right place to set s 'update_required_' to 'false' in this case.

**Comment by justinjdickow** [comment]
@madhuy Will test with using `set_update_required(false);` in `UpdateStatusManager::OnValidUpdateReceived()`

**Comment by joeygrover** [comment]
Current PR open and being discussed on #644

**Comment by jacobkeeler** [comment]
New PR: #865

**Comment by theresalech** [comment]
Pull request #865 was merged to fix this issue.
