### ISSUE TITLE
USB Device is detected but apps are not listed

### ISSUE THREAD

**Issue by MayilrajC** [smartdevicelink/sdl_core#665]
I have compiled the SDL core with Qt.
When i connect using USB, I was able see device name listed, but apps are not listed.
When is debug i found the code below in usb_device.h,

```
virtual ApplicationList GetApplicationList() const {
    ApplicationList app_list;
    app_list.push_back(1);
    return app_list;
  }
```

**Comment by justinjdickow** [comment]
@MayilrajC What SDL applications are on the device which support USB?

**Comment by MayilrajC** [comment]
I have Pandora and iHeartRadio installed in the phone.

**Comment by MayilrajC** [comment]
Can anyone tell me list of iPhone apps, which supports smartdevicelink.

**Comment by BrandonHe** [comment]
@MayilrajC You can try download app **Ford App Catalog** from App Store, in this app, all support SDL apps are listed, and it will keep update if new apps are added.

**Comment by raspeeyan** [comment]
@justinjdickow 

I am also experiencing the same problem. I have created a sample application which SDL Core detects via Bluetooth, but cannot through USB. SDL can detect the Android device, however.

I have added the needed permissions for Android Accessory in the manifest file. What else do I have to set up?

Much thanks!

**Comment by JackLivio** [comment]
I will reopen if people are still having this issue

**Comment by ashokvasarla** [comment]
USB Device is detected and connected but apps are not listed.
I have registered a test APP with new SdlProxyALM(this, "testapp", false, usbtransport);
I observed this issue is still exists and i see the same code MayilrajC commented on Jul 2, 2016.
