### ISSUE TITLE
Fix misspellings of "subscription"

### ISSUE THREAD

**Issue by asm09fsu** [smartdevicelink/sdl_core#736]
It appears that we have many misspellings of the word "subscription", which is spelt as "subscribtions". The following files are affected:
- src/components/application_manager/src/resume_ctrl.cpp 
- src/components/application_manager/include/application_manager/smart_object_keys.h 
- src/components/application_manager/test/resumption/resume_ctrl_test.cc 
- src/components/application_manager/test/resumption/resumption_data_db_test.cc 
- src/components/application_manager/test/resumption/resumption_data_test.cc

**Comment by jacobkeeler** [comment]
Fixed with the merge of #2044
