### ISSUE TITLE
PredefinedLayout isn't actually used by any RPC

### ISSUE THREAD

**Issue by justinjdickow** [smartdevicelink/sdl_core#75]
Instead the SetDisplayType RPC takes a string for the display type, claiming that it can either be a string defined in the PredefinedLayout enum or some other string.

Is there a reason that the PredefinedLayouts aren't used or a situation in which an app would know about a layout that isn't defined by the RPC Specification implemented on a head unit that it's connected to?

**Comment by stefanek22** [comment]
The PredefinedLayout enum was not explicitly used, allowing the capability for an headunit / app to reference a special layout outside the defined SDL list.  The layout would *still* have to be in the list provided from the head unit (via templatesAvailable).  However, there is no known integration that strays outside the PredefinedLayout list.
