### ISSUE TITLE
Compiling Error for "lock_taken_" is not defined.

### ISSUE THREAD

**Issue by yifili09** [smartdevicelink/sdl_core#751]
@justinjdickow 

I found there was no issue reported for that topic.

At least, a missing header file named **"lock.h"** messed up my compiling process on Ubuntu, **_codebase from latest Develop branch**_

where the header is included from **_"sdl_core/src/components/utils/src/lock_posix.cc"**_

**_The weird file path**_
- [**sdl_core/src/components/utils/include/utils/**](https://github.com/smartdevicelink/sdl_core/tree/develop/src/components/utils/include/utils)
- [**sdl_core/src/components/include/utils/**](https://github.com/smartdevicelink/sdl_core/tree/develop/src/components/include/utils/)

![image](https://cloud.githubusercontent.com/assets/1016943/17549418/ae699fe8-5f22-11e6-82b9-2ab6c5b1c191.png)

![image](https://cloud.githubusercontent.com/assets/1016943/17549425/b163a16c-5f22-11e6-9f0f-c944b31745a6.png)

Snapshoot for GCC

![image](https://cloud.githubusercontent.com/assets/1016943/17549849/d2b79268-5f24-11e6-9510-c40404e400a5.png)

**Comment by jacobkeeler** [comment]
Closing because this comment is based on a version of develop which no longer exists
