### ISSUE TITLE
sh: line 1: bt-device: command not found

### ISSUE THREAD

**Issue by TaoheGit** [smartdevicelink/sdl_core#755]
when i test sdl via bluetooth,i found  the message "sh: line 1: bt-device: command not found" in shell.
i  use bluez4.95,and i dont know what is bt-device

**Comment by jacobkeeler** [comment]
It sounds like you just don't have the `bluez-tools` package installed, this should be easily fixed by just running:

```
sudo apt-get install bluez-tools
```

**Comment by jacobkeeler** [comment]
@TaoheGit Did this fix your issue?

**Comment by durandaltheta** [comment]
I know this is a dead thread, but because the author didn't respond:
'sudo apt-get install bluez-tools'   *did* fix my very similar issue
