### ISSUE TITLE
How is a putfile stream supposed to work?

### ISSUE THREAD

**Issue by justinjdickow** [smartdevicelink/sdl_core#78]
Is there a document describing how the putfile stream concept works using putFiles?

@stefanek22 @mrapitis

**Comment by mrapitis** [comment]
Although you have probably already reviewed it, the best description may be in the pull request on Android here:
https://github.com/smartdevicelink/sdl_android/pull/74
The next best reference may be the mobile API xml specification

**Comment by joeljfischer** [comment]
See this issue as well  https://github.com/smartdevicelink/sdl_core/issues/78
