### ISSUE TITLE
Code is not fallowing Spec (13.1.4.2 SDL.ActivateApp for the application registered and this application was unauthorized by the latest PT Update.)

### ISSUE THREAD

**Issue by madhuy** [smartdevicelink/sdl_core#798]
the sequence diagram 13.1.4.2 in SDL_Intgreation says SDL should send onAppUnregistered to HMI.

HMI never gets onAppUnregistered notification.

in case of Apprevoked , SDL sends
1. SDL.OnAppPermissionChanged with "Apprevoked" is true
2. BasicCommunication.ActivateApp with "Apprevoked" is true

as per SDL core [code](https://github.com/smartdevicelink/sdl_core/blob/master/src/components/application_manager/src/policies/policy_handler.cc#L761),  Function return after sending above 2 notification . Never send [appUnregistered](https://github.com/smartdevicelink/sdl_core/blob/master/src/components/application_manager/src/policies/policy_handler.cc#L798)

Please check flow and let me know your thoughts.

**Comment by AnastasiyaBritanova** [comment]
@madhuy it's the documentation defect (description left from the older implementation). 
Will be fixed in the referenced defect.

If the app gets revoked by Policies update - SDL should notify HMI about the event, keep such app registered and in NONE level and disallow its activation.
