### ISSUE TITLE
Loss of communication on Ubuntu 14.04.1

### ISSUE THREAD

**Issue by MikaylaRay44** [smartdevicelink/sdl_core#8]
While running SDL Core on Ubuntu 14.04.1 (64-bit) through VMWare 7 there is a loss of communication that occurs randomly while testing connected apps. Buttons on the emulator and phone may be pressed, but the communication from the emulator to the phone does not occur despite seeing a connected status and the current screen on the emulator is unnavigable.

Closing the app on the phone does not update the connection status on the emulator, so to fix this issue it requires restarting VMWare 7 and the phone being used for debugging. Doing one or the other does not seem to solve the issue.

**Comment by justinjdickow** [comment]
Closing this issue as something that only happens in debug builds of SDL core running on computers rather than head units
