### ISSUE TITLE
SendLocation uses Doubles instead of Floats

### ISSUE THREAD

**Issue by joeygrover** [smartdevicelink/sdl_core#823]
The lat and long params are of type Double when they should be floats in the MOBILE_API for the struct Coordinate and in the SendLocation RPC. The lat and long params of SendLocation are also not mandatory which is incorrect.

[See here for Coordinate](https://github.com/smartdevicelink/sdl_core/blob/master/src/components/interfaces/MOBILE_API.xml#L2293)

[See here for SendLocation](https://github.com/smartdevicelink/sdl_core/blob/master/src/components/interfaces/MOBILE_API.xml#L4792)

**Comment by joeygrover** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;qTbl1j66&#x2F;93-sendlocation-uses-doubles-not-floats"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> SendLocation uses doubles not floats</a>

**Comment by sandeepf184** [comment]
Yeah Even I noticed that.

**Comment by TMelnyk** [comment]
Hello @joeygrover 
1. "Double" type is **_correct type_** for _"latitudeDegrees"_ and _"longtitudeDegrees"_ params per existing requirements for SDL - as result, type will not be changed

2.  The mandatory of _"latitudeDegrees"_ and _"longtitudeDegrees"_ params of _SendLocation_ is planned to be changed from 'false' to 'true' in the next releases

**Comment by jacobkeeler** [comment]
@TMelnyk Is there any reason why both of these parameters are "Float" type in [GPSData](https://github.com/smartdevicelink/sdl_core/blob/master/src/components/interfaces/MOBILE_API.xml#L1537-L1542)?

**Comment by joeygrover** [comment]
I don't believe that's a correct requirement. We don't use doubles anywhere else in the Mobile_Api.

@stefanek22 @tpulatha Can you comment?

Also, changing from not required to required will introduce extra corner cases between versions and would require the RPC API version to be increased.

**Comment by TMelnyk** [comment]
Hello @jacobkeeler , @joeygrover ,
Per discussion with Ford team the type of "_latitudeDegrees_" and "_lotitudeDegrees_" will be changed to **Float** at SendLocation_request and Coordinate struct
GPSData struct will remain without changes

**Comment by jacobkeeler** [comment]
PR: #837
