### ISSUE TITLE
[SDLcore 4.1 release] onPhoneCall notification is removed ?

### ISSUE THREAD

**Issue by madhuy** [smartdevicelink/sdl_core#831]
if onPhoneCall is removed what is the best way to notify phone call status? it fails this flow(6.26.2.1 OnPhoneCall) in HMI spec

**Comment by madhuy** [comment]
All these files are removed
on_emergency_event_notification.cc
on_play_tone_notification.cc
on_phone_call_notification.cc

**Comment by joeygrover** [comment]
@AnastasiyaBritanova can you comment?

**Comment by AnastasiyaBritanova** [comment]
@joeygrover yes, it was replaced with [OnEventChanged](https://github.com/smartdevicelink/sdl_core/blob/master/src/components/interfaces/HMI_API.xml#L2468)
It also replaces OnEmergencyEvent, OnDeactivateHMI - when sent with the appropriate eventTypes.

**Comment by joeygrover** [comment]
[EventTypeEnums](https://github.com/smartdevicelink/sdl_core/blob/master/src/components/interfaces/HMI_API.xml#L1182)

@madhuy Does this satisfy your issue?

**Comment by madhuy** [comment]
@joeygrover Could you please provide me updated sequence diagrams or updated SDL_integration guidlines?

**Comment by joeygrover** [comment]
@AnastasiyaBritanova are there updated diagrams for this new flow?

**Comment by madhuy** [comment]
@joeygrover @AnastasiyaBritanova Could you please let us know if any API's removed or added in 4.1 release. I know Playtone Notification removed and added the param("Playtone") in TTS.Speak .

**Comment by AnastasiyaBritanova** [comment]
@madhuy @joeygrover 
1. the diagrams are attached
2. will prepare the list of changes and update you here
![oneventchanged deactivate_hmi](https://cloud.githubusercontent.com/assets/11644716/18742810/cbe270c8-80be-11e6-8d98-7d9b83da9b9b.png)
![oneventchanged emergency_event](https://cloud.githubusercontent.com/assets/11644716/18742809/cbdfc5ee-80be-11e6-91cf-71f1aa75ea66.png)
![oneventchanged phone_call](https://cloud.githubusercontent.com/assets/11644716/18742808/cbddd658-80be-11e6-8b89-45d787f75a21.png)

**Comment by madhuy** [comment]
@AnastasiyaBritanova 

Could you please provide me list of changes in 4.1?

**Comment by AnastasiyaBritanova** [comment]
hi @madhuy 
attached providing the diff of HMI_APIs between releases 4.0.12 and 4.1.0 (excel file).
Will get back a bit later with the list of related functional changes.

[HMI_API_diff_release4.0.12_vs_release4.1.0.xlsx](https://github.com/smartdevicelink/sdl_core/files/495541/HMI_API_diff_release4.0.12_vs_release4.1.0.xlsx)
