### ISSUE TITLE
Web SDL HMI doesn't follow the HMI flow 

### ISSUE THREAD

**Issue by sandeepf184** [smartdevicelink/sdl_core#838]
According to the HMI flow, when we send messages like dialnumber it should check for high priority events like Alert and Emergency Call etc. But I have seen in web hmi that when alert message is displayed and made a request for dialnumber , the dialnumber popup is displayed over alert message.  Can anyone please check with it and help me with that.

**Comment by JackLivio** [comment]
@sandeepf184 Here's a fix
https://github.com/smartdevicelink/sdl_hmi/pull/5

**Comment by joeygrover** [comment]
Can you reference which guide you found this information?

**Comment by sandeepf184** [comment]
https://smartdevicelink.com/en/docs/hmi/master/basiccommunication/dialnumber/

Refer the sequence diagrams

**Comment by jacobkeeler** [comment]
Closing, issue moved to sdl_hmi repository (smartdevicelink/sdl_hmi#18)
