### ISSUE TITLE
App does not activate when policies are disabled

### ISSUE THREAD

**Issue by JackLivio** [smartdevicelink/sdl_core#842]
Using the web hmi, after activating an app, the alert shows "Activating App..." and nothing follows.

Same effect if built using extended policy or not.

**Comment by JackLivio** [comment]
[This is the line crashing the policy thread when policies are disabled, causing the activate message to be lost](https://github.com/smartdevicelink/sdl_core/blob/master/src/components/application_manager/src/policies/policy_handler.cc#L962)

**Comment by LitvinenkoIra** [comment]
Priority Medium.
Related to general activation app behavior

**Comment by jacobkeeler** [comment]
Closing with the merge of #2204
