### ISSUE TITLE
The reference of wild pointer cause to memory leak

### ISSUE THREAD

**Issue by wzhhnet** [smartdevicelink/sdl_core#860]
https://github.com/smartdevicelink/sdl_core/blob/master/src/components/dbus/src/dbus_adapter.cc
`bool DBusAdapter::SetValue(...
...
    case ford_message_descriptions::ParameterType::String:
      type = DBUS_TYPE_STRING;
      stringValue = param.asString().c_str();
`
temporary string object was returned, but it was not copied, it's internal pointer member was copied by stringValue. after this, the temporary string object was destroyed and stringValue become a wild pointer.

**Comment by chenbd** [comment]
is this a problem which param.asString() return a temp string, after c_str() call, pointer is returned from temp string after temp string is destructed?
which means use a pointer from string.c_str() after string is destructed.

**Comment by LitvinenkoIra** [comment]
Priority Medium.
Related to memory leak, but there is no defined use-case and behavior.

**Comment by jacobkeeler** [comment]
Fixed with the merge of #2051
