### ISSUE TITLE
Add SDL version info in BasicCommunication.GetSystemInfo Response

### ISSUE THREAD

**Issue by henry-fan** [smartdevicelink/sdl_core#9]
Head unit wants to show SDL version in system diagnosis. Suggest we add SDL version in HMI protocol GetSystemInfo.

**Comment by genivi** [comment]
I'll write an issue against core so we can discuss during our next meeting.
The versioning for SDL is moving to semantic versioning (semver.org) so the
field would most likely contain something like "4.0.0"

justin


justin dickow, product development project manager

justin@livioconnect.com

cell: 248-842-2836

office: 248-591-0333, ext 889.

skype: justin.dickow.livio


3136 Hilton, Ferndale, MI 48220

**Comment by justinjdickow** [comment]
Oops, I didn't realize this was already an issue. I would suggest we also add a new field alongside syncMsgVersion so we can eventually deprecate that field which will indicate the version in the register app interface response.

**Comment by justinjdickow** [comment]
Some feedback on this issue I got via email

>There is a constant string(kApplicationVersion) to define the SDL Core version but isn’t exposed to HMI protocol.
![unnamed](https://cloud.githubusercontent.com/assets/3627664/6130007/57e864f4-b110-11e4-829e-ddd65ddb212e.jpg)
Considering there are variants HMI implementations near future, that should be an enhancement

**Comment by justinjdickow** [comment]
We added sdl version and system software version to register app interface response to communicate this information. It sounds like the proposal is to also add this information to be sent to the HMI.

**Comment by justinjdickow** [comment]
@henry-fan Can you let us know if that information in the register app interface being communicated to the application is enough for your system diagnosis purposes or whether it needs to be on the hmi?

**Comment by henry-fan** [comment]
@justinjdickow 
we need SDL version string to be exposed to HMI. Thanks.

**Comment by justinjdickow** [comment]
@henry-fan Do you know if this was ever resolved?

**Comment by BrandonHe** [comment]
@justinjdickow 
As far as we know, neither sdl_version nor kApplicationVersion exposed to HMI. Thanks.

**Comment by JackLivio** [comment]
@henry-fan I think this is partly covered by https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0096-deliver-build-configuration.md

If this solution does not satisfy your needs please consider submitting a proposal to the sdl evolution repository.

https://github.com/smartdevicelink/sdl_evolution
