### ISSUE TITLE
[Policy] "EXTERNAL_PROPRIETARY" flow: Validation of PolicyTables

### ISSUE THREAD

**Issue by TMelnyk** [smartdevicelink/sdl_core#938]

**Comment by DrachenkoAnastasiia** [comment]
_**Description:**_
To "switch on" the extended Policies -> SDL should be built with ***-DEXTENDED_POLICY: EXTERNAL_PROPRIETARY*** flag

_**Impact:**_
SDL 
HTML5 HMI 
SPT 
TestCases 
Requirements

**Comment by jacobkeeler** [comment]
Closing due to being a requirement rather than an issue
