### ISSUE TITLE
[Policy] "EXTERNAL_PROPRIETARY" flow: user-consent in terms of Policies

### ISSUE THREAD

**Issue by TMelnyk** [smartdevicelink/sdl_core#939]

**Comment by DrachenkoAnastasiia** [comment]
_**Description:**_
_High-level idea:_
After device was successfully connected to the HU, user will be prompted to allow/disallow device data usage. Device data will be used for further connection with the Cloud in PTUpdate sequence.
Based on user consent PolicyManager stores appropriate records in PolicyTable and assigns corresponding permissions to app.

To "switch on" the extended Policies -> SDL should be built with ***-DEXTENDED_POLICY: EXTERNAL_PROPRIETARY*** flag.

_**Impact:**_
SDL 
HTML5 HMI 
SPT 
TestCases 
Requirements

**Comment by jacobkeeler** [comment]
Closing due to being a requirement rather than an issue
