### ISSUE TITLE
 [Policy] "Proprietary" flow: SDL must be build with "-DEXTENDED_POLICY: PROPRIETARY"

### ISSUE THREAD

**Issue by TMelnyk** [smartdevicelink/sdl_core#940]

**Comment by DrachenkoAnastasiia** [comment]
_**Description:**_
High-level idea:
To "switch on" the "Proprietary" flow of PolicyTableUpdate feature -> SDL should be built with ***-DEXTENDED_POLICY: PROPRIETARY*** flag

_**Impact:**_
SDL 
HTML5 HMI 
SPT 
TestCases 
Requirements

**Comment by jacobkeeler** [comment]
Closing due to being a requirement rather than an issue
