### ISSUE TITLE
[Policy] "EXTERNAL_PROPRIETARY" flow: SDL must be build with "-DEXTENDED_POLICY: EXTERNAL_PROPRIETARY"

### ISSUE THREAD

**Issue by TMelnyk** [smartdevicelink/sdl_core#942]

**Comment by DrachenkoAnastasiia** [comment]
_**Description:**_
To "switch on" the "Premium" (extended) Policies feature -> SDL should be built with ***-DEXTENDED_POLICY: EXTERNAL_PROPRIETARY*** flag

_**Impact:**_
SDL 
HTML5 HMI 
SPT 
TestCases 
Requirements

**Comment by jacobkeeler** [comment]
Closing due to being a requirement rather than an issue
