### ISSUE TITLE
[SDL-RC Merge] Requirements cloning

### ISSUE THREAD

**Issue by Itileda** [smartdevicelink/sdl_core#947]
RA(BA): 
- Analysis of existing req-s
- Clone SDL-RC requirements to OpenSDL
- Adjust cloned requirements to OpenSDL "standards"
- Resolve requirements conflicts (if any)
- Meeting with Customers
- Questions from team

**Comment by DrachenkoAnastasiia** [comment]
1. [RC_PolicyTable_example.pdf](https://github.com/smartdevicelink/sdl_core/files/878829/RC_PolicyTable_example.pdf)

2. [ReverseSDL_Policy_Table_Data_Dictionary_003.pdf](https://github.com/smartdevicelink/sdl_core/files/878859/ReverseSDL_Policy_Table_Data_Dictionary_003.pdf)

3. [Uploading RSDL_Equipment_configuration_v.2.pdf…]()

4. [RSDL_HMI_Guidelines_v1.1.pdf](https://github.com/smartdevicelink/sdl_core/files/878879/RSDL_HMI_Guidelines_v1.1.pdf)

5. [RSDL_Mobile_API_Guidelines_v1.0.pdf](https://github.com/smartdevicelink/sdl_core/files/878880/RSDL_Mobile_API_Guidelines_v1.0.pdf)

6. [SDL_RC_HMI_API.pdf](https://github.com/smartdevicelink/sdl_core/files/878881/SDL_RC_HMI_API.pdf)

7. [SDL_RC_MOBILE_API.pdf](https://github.com/smartdevicelink/sdl_core/files/878882/SDL_RC_MOBILE_API.pdf)
