### ISSUE TITLE
putFile does not copy file with .\\ before the name to AppStorageFolder

### ISSUE THREAD

**Issue by DrachenkoAnastasiia** [smartdevicelink/sdl_core#956]
**Occurrence:**
Always

**Preconditions:**
1. SDL and HMI are started
2. App is registered("Set app icon" after registration checkbox is unchecked)
3. App HMIlevel=FULL
**Steps to reproduce:**
1. Send PutFile (choose any file from sdcard on mobile), specify Sync File Name - .
syncFileName (dot two backslashes before the name) 
**Actual result:**
the SPT displays PutFile(response):SUCESS, but chosen file didn't appear in AppStorageFolder

**Environment:**
Verified on release SDL_RB_B3.37.
Failed
SDL repo: https://github.com/smartdevicelink/sdl_core/
SDL branch: a6c32b45832653d6b851be9b19355fa35f377e07
HMI: HTML5
ATF version: -
ATF repo: -
ATF branch: -
Scripts repo: -
Scripts branch: -
OS: Ubuntu 14.04.01
Transport: Wi-Fi
Mobile device: Lenovo P1ma40
Mobile OS: Android V5.1
Mobile App version: Luxoft SPT
Mobile App type (media/non-media/navi/any): any
Virtual Machine using (yes/no): no

**Attachments:**
[att_issue#956.zip](https://github.com/smartdevicelink/sdl_core/files/575486/att_issue.956.zip)

**Comment by LitvinenkoIra** [comment]
Priority Low.
Specific use-case related to used file name

**Comment by robinmk** [comment]
As long as the file is not copied (to prevent file traversal issue), agree that it is a lower priority bug. However, if the file is copied to another folder it should be fixed as a high priority item.

**Comment by ValeriiMalkov** [comment]
### The bug isn't reproduced. 
### Note:warning: 
In Unix-like operating systems, any file or folder that starts with a dot character (for example, /home/user/.config), commonly called a dot file or dotfile, is to be treated as hidden – that is, the `ls` command does not display them unless the `-a` flag `ls -a` is used.

**Comment by AStasiuk** [comment]
Closed as not reproducible.
