### ISSUE TITLE
[Policy]: SDL does not send RequestType:HTTP in OnSystemRequest to app

### ISSUE THREAD

**Issue by KhrystynaDubovyk** [smartdevicelink/sdl_core#958]
**Occurrence:**
Always

**Preconditions:**
1. SDL built with DEXTENDED_POLICY: *OFF*
2. Core, HMI started.
3. First SDL life cycle.
4. Policy autoreplay checkbox is unchecked on app.

**Steps to reproduce:**
1. Register App 

**Actual result:**
SDL send OnSystemRequest with requestType:PROPRIETARY and fileType:Json to app.

**Expected result:**
SDL should send OnSystemRequest with requestType:HTTP and fileType:BINARY to app.

**Comment by LitvinenkoIra** [comment]
Priority Medium.
Loss of functionality on SDL side with standard use-case.

**Comment by JackLivio** [comment]
Issue outdated. Run with HTTP policies and onSystemRequest sends HTTP and binary. Not sure where the issue was fixed but it no longer exists on master or develop.
