### ISSUE TITLE
SDL retry send StartStream/StartAudioStream less on one time than configured in .ini file

### ISSUE THREAD

**Issue by DrachenkoAnastasiia** [smartdevicelink/sdl_core#960]
**Occurrence:**
Always

**Preconditions:**
1. Core, HMI started.
2. StartStreamRetry = 3, 3 in .ini file.
3. Navi app registered and activated on HMI.

**Steps to reproduce:**
1. Start Audio/Video service.
2. Press cancel on HTML5 HMI (emulate REJECT from HMI) => SDL start retry sequence.
3. Press Cancel on all appeared pop-ups. 

**Actual result:**
After unsuccessful StartStream/StartAudioStream (first REJECT) SDL retry to start 2 times instead 3 times.

**Expected result:**
The counting of retries should be started after first unsuccessfuly response.

**Environment:**
Reproduces
Release: 4.2.0 (master marge)
Repository: https://github.com/smartdevicelink/sdl_core
Commit: a6c32b45832653d6b851be9b19355fa35f377e07
OS: Ubuntu 14.04
Transport: WiFi
App type: navi
App: Luxoft SPT
Device: HTC One 
**Attachments:**
[att_issue#960.zip](https://github.com/smartdevicelink/sdl_core/files/575509/att_issue.960.zip)

**Comment by AStasiuk** [comment]
Reopened - because fix is ready and PR should be reviewed by project maintainer.

**Comment by jacobkeeler** [comment]
Closing with the merge of #2553
