### ISSUE TITLE
[Policy]: SDL dos not select url from PT for specified appID during GetURLs request.

### ISSUE THREAD

**Issue by KhrystynaDubovyk** [smartdevicelink/sdl_core#961]
## Occurrence
Always.

## Preconditions
1. Move IsReady_Template folder into sdl_atf\user_modules
2. SubscribeVehicleData and UnSubscribeVehicleData are allowed in PT

## Steps to reproduce
Or: (Go to atf folder -> Run command: ./start.sh ../ATF_VehicleInfo_IsReady_available_false_SingleRPC.lua)
1. RegisterApp incase HMI does not respond
2. Activate app
3. Send SubscribeVehicleData with gps = true
4. Send UnSubscribeVehicleData with gps = true

## Actual result
    SDL respond "
    {success = true, resultCode = "IGNORED", info = "Already subscribed on some provided VehicleData."}
    ".
## Expected result
    SDL should respond "
    {success = false, resultCode = "IGNORED", info = "Some provided VehicleData was not subscribed."}
    " code to mobile app.

# Environment
Branch: (https://github.com/smartdevicelink/sdl_core/)
branch: "release/4.2.0"
commit id: a6c32b45832653d6b851be9b19355fa35f377e07
HMI: HTML5
ATF version: 2.2
ATF repo: https://github.com/smartdevicelink/sdl_atf/
ATF branch: 962e1eff8664d97af5e59ec4e22f39b9ea76f5eb
Scripts repo: https://github.com/CustomSDL/sdl_atf_test_scripts/tree/OS_DRAFT
Scripts branch: 18cce42
OS: Ubuntu 14.04.01
Transport: Wi-Fi
Mobile device: -
Mobile OS: -
Mobile App version: -
Mobile App type (media/non-media/navi/any): any
Virtual Machine using (yes/no): no

# Attachments
[att_issue#961.zip](https://github.com/smartdevicelink/sdl_core/files/575775/att_issue.961.zip)

# Expected delivery   
- [ ] Source code updates 
- [ ] Code comments 
- [ ] UTs add/update 
- [x] ATF tests add/update ***(not required)***  
- [x] Manual tests ***(not required)*** 
- [x] Add/update CI plans/jobs ***(not required)***  
- [x] SDD updates ***(not required)***  
- [x] Guidelines update ([sdl_core_guides](https://github.com/smartdevicelink/sdl_core_guides)) ***(not required)***  
- [x] Guidelines update ([sdl_hmi_integration_guidelines](https://github.com/smartdevicelink/sdl_hmi_integration_guidelines))  ***(not required)***

**Comment by theresalech** [comment]
Per Luxoft, this is addressed via PR #1539

**Comment by JackLivio** [comment]
@KhrystynaDubovyk The content of this issue does not match the title or the pr associated with it.

**Comment by JackLivio** [comment]
fix is merged
