### ISSUE TITLE
SDL sends to mobile "APPLICATION_NOT_REGISTRED" in setAppIcon responce if HMI responds with "INVALID_DATA"

### ISSUE THREAD

**Issue by KhrystynaDubovyk** [smartdevicelink/sdl_core#964]
**Occurrence:**
Always

**Precondition:**
SDL Core and HMI are started. App is registered, HMI level = FULL

**Steps:**
1. Send PutFile with file name =\syncFileName
SDL returns SUCCESS result, success:true
2. Send SetAppIcon with file name =\syncFileName
3. Send from HMI INVALID_DATA to SDL.

**Actual result:**
-SDL returns "APPLICATION_NOT_REGISTRED" to mobile 

**Expected result:**
-SDL should send to mobile result code which was sent to SDL by HMI

**Environment:**
SDL branch: a6c32b45832653d6b851be9b19355fa35f377e07
HMI: HTML5
ATF version: -
ATF repo: -
ATF branch: -
Scripts repo: -
Scripts branch: -
OS: Ubuntu 14.04.01
Transport: Wi-Fi
Mobile device: Lenovo P1ma40
Mobile OS: Android V5.1
Mobile App version: Luxoft SPT
Mobile App type (media/non-media/navi/any): any
Virtual Machine using (yes/no): no

**Attachments:**
[att_issue#964.zip](https://github.com/smartdevicelink/sdl_core/files/575784/att_issue.964.zip)

**Comment by vvvakulenko** [comment]
PASSED
was verified on:
SDL repo: https://github.com/smartdevicelink/sdl_core/
SDL branch: a6c32b45832653d6b851be9b19355fa35f377e07
HMI: HTML5
ATF version: -
ATF repo: - 
ATF branch: - 
Scripts repo: - 
Scripts branch: -
OS: Ubuntu 14.04
Transport: Wi-Fi
Mobile device: Huawei U9200
Mobile OS: Android V4.0.3
Mobile App version: Luxoft SPT
Mobile App type (media/non-media/navi/any): any
Virtual Machine using (yes/no): yes

**Comment by jacobkeeler** [comment]
@vvvakulenko Does your comment mean that this issue is already fixed in 4.2?

**Comment by LitvinenkoIra** [comment]
Priority Medium.
Unregistration app in standard use case.

**Comment by HSavynetska** [comment]
The defect is not reproduced
sdl_core: branch develop
commit: 65c1e7eb77fa949cce9c07f229e2cf747f297e14
Verified with script:
Script is under review
https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/1897

**Comment by HSavynetska** [comment]
The defect is not reproduced
sdl_core: branch develop
commit: 65c1e7e
Verified with script:
Script is under review
https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/1903

**Comment by AStasiuk** [comment]
Closed as not reproducible.

**Comment by GetmanetsIrina** [comment]
Script for reproducing https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Defects/5_0/964_SDL_sends_to_mobile_APPLICATION_NOT_REGISTRED_in_setAppIcon_responce_if_HMI_responds_with_INVALID_DATA.lua
