### ISSUE TITLE
[SDL4.0]SDL does not send OnSystemRequest to app on second device

### ISSUE THREAD

**Issue by DrachenkoAnastasiia** [smartdevicelink/sdl_core#966]
## Occurrence
always

## Preconditions
SDL4.0 feature is enabled in .ini file, SDL and HMI are started. App app_1 is registered via 4th on first device,has already received OnSystemRequest(Query_apps)and sent query json.

## Steps to reproduce
1. Register app via 4th protocol on second device.

## Expected result
After app is registered and sends to SDL OnHMIStatus(FULL) SDL sends OnSystermRequest(Query_apps) notification to mobile app on second device.

## Actual result
SDL does not send OnSystermRequest(Query_apps) notification to mobile app on second device.
**Note:** For reproducing defect using ATF extract files from files_for_script_execution_onSysterm_request_on_second_device.tar.gz to ATF_build and execute script Expecting_OnSystermrequest_query_apps_onSecond_device.lua.

# Environment
SDL:
sdl_repository = "https://github.com/smartdevicelink/sdl_core/"
sdl_branch = "release/4.2.0", commit fc832c7a7ae
ATF:
Repository: https://github.com/smartdevicelink/sdl_atf/
Commit: 962e1eff8664d97af5e59ec4e22f39b9ea76f5eb
Please see attached ATF_logs.zip at Attachments.

# Attachments
[att_issue#966.zip](https://github.com/smartdevicelink/sdl_core/files/575605/att_issue.966.zip)

# Expected delivery   
- [ ] Source code updates 
- [ ] Code comments 
- [ ] UTs add/update 
- [x] ATF tests add/update ***(not required)***  
- [x] Manual tests ***(not required)*** 
- [x] Add/update CI plans/jobs ***(not required)***  
- [x] SDD updates ***(not required)***  
- [x] Guidelines update ([sdl_core_guides](https://github.com/smartdevicelink/sdl_core_guides)) ***(not required)***  
- [x] Guidelines update ([sdl_hmi_integration_guidelines](https://github.com/smartdevicelink/sdl_hmi_integration_guidelines))  ***(not required)***

**Comment by LitvinenkoIra** [comment]
Priority High.
Feature is unable for second device in standard use-case.

**Comment by HSavynetska** [comment]
The issue is relevant on the current develop branch
Environment:
test script: https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/2101
SDL build: https://github.com/smartdevicelink/sdl_core/tree/develop ( 891497b )
ATF: develop branch

**Comment by ShobhitAd** [comment]
Unable to reproduce the issue on the latest develop commit (https://github.com/smartdevicelink/sdl_core/commit/ca0cdaf10bae555a7bb5bdec0026adcc5f317eb6)
