### ISSUE TITLE
CCB: SDL forw OnButtonEvent of CUSTOM_BTN to BACKGROUND

### ISSUE THREAD

**Issue by KhrystynaDubovyk** [smartdevicelink/sdl_core#967]
### Bug Report
SDL not forwards OnButtonEvent notification of CUSTOM_BUTTON to BACKGROUND App

##### Reproduction Steps
1. Make sure app is in BACKGROUND HMI level
2. Send OnButtonEvent(CUSTOM_BUTTON, SHORT/LONG) from HMI

##### Expected Behavior
Notification is re-sent to App

##### Observed Behavior
SDL didn't resend notification to App

##### OS & Version Information
commit: 
* OS/Version: Ubuntu 16.04
* SDL Core Version: a4c2702
* Testing Against: ATF

##### Test Case, Sample Code, and / or Example App
* [att_issue#967.zip](https://github.com/smartdevicelink/sdl_core/files/575677/att_issue.967.zip)
* Updated script: [967_OnButtonPress_OnButtonEvent_in_background.lua.zip](https://github.com/smartdevicelink/sdl_core/files/2572423/967_OnButtonPress_OnButtonEvent_in_background.lua.zip)

**Comment by LitvinenkoIra** [comment]
Priority Medium.
Loss of functionality on SDL side with standard use-case.

**Comment by robinmk** [comment]
We do not think the same requirement should apply to CUSTOM-BUTTON and hence think this bug is invalid.
Eg: Lets say we provide the ability for apps to populate softbuttons on the app list (like a short cut to the most widely used buttons). Then we would not want to limit the button presses being sent to the app in BACKGROUND.

**Comment by GetmanetsIrina** [comment]
@robinmk , please confirm the Expected result:

**Expected result:**
In case  OnButtonEvent(CUSTOM_BUTTON, SHORT/LONG) is allowed by Policy SDL must resend it to BACKGROUND App.

Requirement 
>In case there is a media application in FULL HMILevel and several other media applications in BACKGROUND and-or NONE HMILevel connected to SDL and subscribed for Tune Up/Down, Seek Right/Left HW buttons, SDL must transfer the OnButtonEvent notification from HMI to the media application in FULL only.

will be still actual for Tune Up/Down, Seek Right/Left HW buttons.

**Comment by robinmk** [comment]
@GetmanetsIrina @AStasiuk 

> Requirement
In case there is a media application in FULL HMILevel and several other media applications in BACKGROUND and-or NONE HMILevel connected to SDL and subscribed for Tune Up/Down, Seek Right/Left HW buttons, SDL must transfer the OnButtonEvent notification from HMI to the media application in FULL only.
will be still actual for Tune Up/Down, Seek Right/Left HW buttons

This still holds true for Tune Up/Down, Seek Left/Right buttons. The rule should be expanded to include Media applications that are in LIMITED as well. The behavior for LIMITED should be similar to applications in FULL.

Regarding CUSTOM_BUTTON, I would like to refer you to the description provided in HMI_API for the OnButtonEvent RPC. The description states rules that define the correct behavior.
[OnButtonEvent](https://github.com/smartdevicelink/sdl_core/blob/7f7fcbb998fb17f2954fd103349af67ea9b71a3f/src/components/interfaces/HMI_API.xml#L2704)

**Comment by GetmanetsIrina** [comment]
Defect is reproduced.
SDL branch: develop(af97446)
ATF: develop
Script: https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/1921

**Comment by ValeriiMalkov** [comment]
The next link to PR which provided fix this issue:
[Pull request](https://github.com/smartdevicelink/sdl_core/pull/2365)

**Comment by KrupenichOleg** [comment]
1) Description and summary updated according to comments written by @robinmk, this defect is valid now
2) Uploaded fresh script to reproducing this case (updated script from [PR#1921](https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/1921))

**Comment by KrupenichOleg** [comment]
Defect is reproduced.
SDL branch: develop ([d363167](https://github.com/smartdevicelink/sdl_core/commit/d36316738785c96dab2ee892762ed08c059fffde))
ATF: develop
Script: smartdevicelink/sdl_atf_test_scripts#1921

**Comment by KrupenichOleg** [comment]
Defect is not reprodused 
SDL branch:  Bugfix `SDL forwards OnButtonEvent notification` ([3db5b52](https://github.com/smartdevicelink/sdl_core/pull/2365/commits/3db5b5237ee6e6f7b876182b3675213d43fe70fe))
ATF: develop
Script: [smartdevicelink/sdl_atf_test_scripts#1921](https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/1921)

**Comment by LitvinenkoIra** [comment]
Defect is reproduced.
SDL branch: develop([e137556](https://github.com/smartdevicelink/sdl_core/commit/e137556512215ded94228e33d21ab4c3e1af3017))
ATF: develop
Script: smartdevicelink/sdl_atf_test_scripts#1921

**Comment by LitvinenkoIra** [comment]
https://github.com/smartdevicelink/sdl_core/pull/2365 - rebased to the latest develop 
Fix is valid

**Comment by LitvinenkoIra** [comment]
Full regression successfully passed
SDL: fix/sdl_forwards_onbuttoneven c1b6be3a
Scripts: develop 6f43bfd
ATF: develop 37da7aba

**Comment by LitvinenkoIra** [comment]
@theresalech Please triage this issue

**Comment by theresalech** [comment]
@LitvinenkoIra thank you. We are currently working on finalizing the roadmap with the Steering Committee, so will keep this PR in consideration for upcoming Core releases.

**Comment by iCollin** [comment]
Closed via #2365
