### ISSUE TITLE
[Policy] PM doesn't validate required section/key in case it is invalid and SDL continue running.

### ISSUE THREAD

**Issue by DrachenkoAnastasiia** [smartdevicelink/sdl_core#969]
## Occurrence
Always

## Preconditions
- Change "exchange_after_x_ignition_cycles": "abc" in sdl_preloaded_pt.json;
- SDL is the first life cycle.

## Steps to reproduce
1. Start SDL.

## Actual result
PM sets "exchange_after_x_ignition_cycles": 0 and SDL continue working.

## Expected result
PM should shut SDL down and log an error internally. 

# Environment
SDL repo: https://github.com/smartdevicelink/sdl_core.git
SDL branch: master
SDL commit: a6c32b4
HMI: https://github.com/LuxoftSDL/sdl_hmi: 01cb5b49883ed6288e34fcf7db24fd0439d08312
OS: Ubuntu 14.04 LTS

# Attachments
[att_issue#969.zip](https://github.com/smartdevicelink/sdl_core/files/575633/att_issue.969.zip)

# Expected delivery   
- [ ] Source code updates 
- [ ] Code comments 
- [ ] UTs add/update 
- [x] ATF tests add/update ***(not required)***  
- [x] Manual tests ***(not required)*** 
- [x] Add/update CI plans/jobs ***(not required)***  
- [x] SDD updates ***(not required)***  
- [x] Guidelines update ([sdl_core_guides](https://github.com/smartdevicelink/sdl_core_guides)) ***(not required)***  
- [x] Guidelines update ([sdl_hmi_integration_guidelines](https://github.com/smartdevicelink/sdl_hmi_integration_guidelines))  ***(not required)***

**Comment by pold500** [comment]
@DrachenkoAnastasiia any link to requirements?
