### ISSUE TITLE
[IVSU] SDL doesn't reject SystemRequest with filenam=IVSU but w/o binary data.

### ISSUE THREAD

**Issue by DrachenkoAnastasiia** [smartdevicelink/sdl_core#976]
## Occurrence
Always

## Preconditions
1. Core, HMI started.
2. App is registered and activated on HMI.

## Steps to reproduce
1. Send systemRequest. specify name IVSU, don't select a file on sdcard.

## Actual result
SDL replies with SUCCESS and resend this SystemRequest to HMI.

## Expected result
SDL should reject such request.

# Environment
SDL repo: https://github.com/smartdevicelink/sdl_core.git
SDL branch: master
SDL commit: a6c32b4
HMI: https://github.com/LuxoftSDL/sdl_hmi: 01cb5b49883ed6288e34fcf7db24fd0439d08312
OS: Ubuntu 14.04 LTS

# Expected delivery   
- [ ] Source code updates 
- [ ] Code comments 
- [ ] UTs add/update 
- [x] ATF tests add/update ***(not required)***  
- [x] Manual tests ***(not required)*** 
- [x] Add/update CI plans/jobs ***(not required)***  
- [x] SDD updates ***(not required)***  
- [x] Guidelines update ([sdl_core_guides](https://github.com/smartdevicelink/sdl_core_guides)) ***(not required)***  
- [x] Guidelines update ([sdl_hmi_integration_guidelines](https://github.com/smartdevicelink/sdl_hmi_integration_guidelines))  ***(not required)***

**Comment by jacobkeeler** [comment]
Closing with the merge of #1625
