### ISSUE TITLE
[SDL4.0]SDL sends appName in vrSynonyms and ttsName in case of lower and upper bound values of params in json file

### ISSUE THREAD

**Issue by KhrystynaDubovyk** [smartdevicelink/sdl_core#977]
## Occurrence
Always.

## Preconditions
SDL4.0 feature is enabled in .ini file, SDL and HMI are started.

## Steps to reproduce
1. Register app via 4th protocol.
2. App sends via SystemRequest json file JSONWithLanguageDefaultVrTtsLowerBound.json
JSONWithLanguageDefaultVrTtsUpperBound.json

## Expected result
SDL sends in BC.UpdateAppList values of vrSynonyms and ttsName from json file

## Actual result
SDL sends in BC.UpdateAppList in vrSynonyms and ttsName value of appName
Notes: To reproduce defect using ATF extract attached files in 'ATF_build/' folder and execute TtsNameVrSyn_lower_bound_language.lua.

# Environment
Tag: 4.2.0
commit: a6c32b45832653d6b851be9b19355fa35f377e07
ATF version: 2.2 / 962e1eff8664d97a 

# Attachments
[att_issue#977.zip](https://github.com/smartdevicelink/sdl_core/files/575852/att_issue.977.zip)

# Expected delivery   
- [ ] Source code updates 
- [ ] Code comments 
- [ ] UTs add/update 
- [x] ATF tests add/update ***(not required)***  
- [x] Manual tests ***(not required)*** 
- [x] Add/update CI plans/jobs ***(not required)***  
- [x] SDD updates ***(not required)***  
- [x] Guidelines update ([sdl_core_guides](https://github.com/smartdevicelink/sdl_core_guides)) ***(not required)***  
- [x] Guidelines update ([sdl_hmi_integration_guidelines](https://github.com/smartdevicelink/sdl_hmi_integration_guidelines))  ***(not required)***

**Comment by LitvinenkoIra** [comment]
Priority Low.
Defect is related to processing values of lower and upper bound.

**Comment by ShobhitAd** [comment]
Closed via https://github.com/smartdevicelink/sdl_core/pull/2705
