### ISSUE TITLE
[APIs] AlertManeuver: SDL responds GENERIC_ERROR instead of INVALID_DATA when soft button has Type is Image or Both and Text is whitespace or \t or \n or empty

### ISSUE THREAD

**Issue by DrachenkoAnastasiia** [smartdevicelink/sdl_core#980]
## Occurrence
 Always

## Preconditions
- AlertManeuver is allowed by policy for "default" group.
- SDL core and HMI are started.
- App is connected and at the FULL.

## Steps to reproduce
1. Send AlertManeuver sure that soft button has Type is Image or Both and Text is whitespace or \t or \n or empty.
_**Note:**_ Should you the attached lua file and reproduce this defect automatically.

## Actual result
SDL responds with resultCode "GENERIC_ERROR" and success:"false". 

## Expected result
SDL must respond with resultCode "INVALID_DATA" and success:"false".

# Environment
SDL: https://github.com/smartdevicelink/sdl_core.git: a6c32b45832653d6b851be9b19355fa35f377e07
ATF: https://github.com/smartdevicelink/sdl_atf.git: 962e1eff8664d97af5e59ec4e22f39b9ea76f5eb
OS: Ubuntu 14.04 LTS

# Attachments
[att_issue#980.zip](https://github.com/smartdevicelink/sdl_core/files/575882/att_issue.980.zip).

# Expected delivery   
- [ ] Source code updates 
- [ ] Code comments 
- [ ] UTs add/update 
- [x] ATF tests add/update ***(not required)***  
- [x] Manual tests ***(not required)*** 
- [x] Add/update CI plans/jobs ***(not required)***  
- [x] SDD updates ***(not required)***  
- [x] Guidelines update ([sdl_core_guides](https://github.com/smartdevicelink/sdl_core_guides)) ***(not required)***  
- [x] Guidelines update ([sdl_hmi_integration_guidelines](https://github.com/smartdevicelink/sdl_hmi_integration_guidelines))  ***(not required)***

**Comment by jacobkeeler** [comment]
Closing with the merge of #1627
