### ISSUE TITLE
 SDL responds "resultCode: SUCCESS" while dataType:VEHICLEDATA_EXTERNTEMP is VEHICLE_DATA_NOT_AVAILABLE and not in subscribed list store

### ISSUE THREAD

**Issue by DrachenkoAnastasiia** [smartdevicelink/sdl_core#982]
## Occurrence
Always

## Preconditions
1. Core and HMI are started.
2. SubscribeVehicleData (speed, externalTemperature), OnVehicleData is allowed by policy for app_1 and app_2.
3. Navi App1 and navi app2 are registered and activated.

## Steps to reproduce
1. Send SubscribeVehicleData (speed, externalTemperature) from app_1
=> SDL responds SubscribeVehicleData ((speed:success),(externalTemperature:VEHICLE_DATA_NOT_AVAILABLE), SUCCESS).
2. Send SubscribeVehicleData (speed, externalTemperature) from app_2.
3. Observe the result.

## Actual result
SDL sends "resultCode: SUCCESS, success:true" to mobile app2.

## Expected result
SDL should send "SUCCESS, (speed: SUCCESS),
(externalTemperature: VEHICLE_DATA_NOT_AVAILABLE)" to mobile app2.

# Environment
SDL repo: https://github.com/smartdevicelink/sdl_core.git
SDL branch: master
SDL commit: a6c32b4
HMI: HTML5
OS: Ubuntu 14.04 LTS
Transport: WiFi
Mobile device: HTC One
Mobile OS: Android 4.3
Mobile App version: SPT v.2.1.81 Code: 239
Mobile App type (media/non-media/navi/any): any

# Attachments
[att_issue#982.zip](https://github.com/smartdevicelink/sdl_core/files/575906/att_issue.982.zip).

# Expected delivery   
- [ ] Source code updates 
- [ ] Code comments 
- [ ] UTs add/update 
- [x] ATF tests add/update ***(not required)***  
- [x] Manual tests ***(not required)*** 
- [x] Add/update CI plans/jobs ***(not required)***  
- [x] SDD updates ***(not required)***  
- [x] Guidelines update ([sdl_core_guides](https://github.com/smartdevicelink/sdl_core_guides)) ***(not required)***  
- [x] Guidelines update ([sdl_hmi_integration_guidelines](https://github.com/smartdevicelink/sdl_hmi_integration_guidelines))  ***(not required)***

**Comment by JackLivio** [comment]
Issue is reproducible when App2 sends SubscribeVehicle data Speed:True and externTemp:True in the same RPC request.

**Comment by jacobkeeler** [comment]
Closing with the merge of #1929
