### ISSUE TITLE
[Policy]: SDL does not apply url from PT for specified appID for OnSystemRequest

### ISSUE THREAD

**Issue by DrachenkoAnastasiia** [smartdevicelink/sdl_core#985]
## Occurrence
Always

## Preconditions
1. SDL built with DEXTENDED_POLICY: OFF.
2. Core, HMI started using attached sdl_preloaded_pt.json.
3. SPT is configured to send attached PTU - PTFromCloud_smoke%20test__2.json.

## Steps to reproduce
1. Register App with appID "584421907" - PTU trigered successfully.
2. Register app "Base", appID = 12345.

## Actual result
After Registration second app SDL triger PTU. SDL sends OnSystemRequest with url: http://policies.telematics.*.com/api/policies.

## Expected result
SDL send http://policifffffffffffff.com/api/policies url in OnSystemRequest notification to mobile.

# Environment
Release: 4.2.0 (master marge)
Repository: https://github.com/smartdevicelink/sdl_core
Commit: a6c32b45832653d6b851be9b19355fa35f377e07
OS: Ubuntu 14.04 
Transport: WiFi 
App type: navi
App: Luxoft SPT
Device: HTC One 

# Attachments
[att_issue#985.zip](https://github.com/smartdevicelink/sdl_core/files/575941/att_issue.985.zip)

# Expected delivery   
- [ ] Source code updates 
- [ ] Code comments 
- [ ] UTs add/update 
- [x] ATF tests add/update ***(not required)***  
- [x] Manual tests ***(not required)*** 
- [x] Add/update CI plans/jobs ***(not required)***  
- [x] SDD updates ***(not required)***  
- [x] Guidelines update ([sdl_core_guides](https://github.com/smartdevicelink/sdl_core_guides)) ***(not required)***  
- [x] Guidelines update ([sdl_hmi_integration_guidelines](https://github.com/smartdevicelink/sdl_hmi_integration_guidelines))  ***(not required)***

**Comment by JackLivio** [comment]
@DrachenkoAnastasiia Was this issue addressed in the 4.3 code at all?

**Comment by JackLivio** [comment]
fix is merged
