### ISSUE TITLE
INVALID_DATA received in case wayPointType with correct parameter was sent

### ISSUE THREAD

**Issue by DrachenkoAnastasiia** [smartdevicelink/sdl_core#987]
## Occurrence
Always.

## Actions
GetWayPoints with valid param (ALL or DESTINATION) was sent. resultCode: INVALID_DATA was received in responce (script_001.lua in attachment could be used to reproduce this step).

## Actual result
GetWayPoints_wayPointType_IsExistentValues_ALL_SUCCESS and GetWayPoints_wayPointType_IsExistentValues_DESTINATION_SUCCESS are failed; INVALID_DATA is received.

## Expected result
SUCCESS should be received.

# Environment
Release: 4.2.0 (master marge)
Repository: https://github.com/smartdevicelink/sdl_core
Commit: a6c32b45832653d6b851be9b19355fa35f377e07
OS: Ubuntu 14.04 
Transport: WiFi 
App type: navi
App: Luxoft SPT
Device: HTC One 

# Attachments
[att_issue#987.zip](https://github.com/smartdevicelink/sdl_core/files/575959/att_issue.987.zip).

# Expected delivery   
- [ ] Source code updates 
- [ ] Code comments 
- [ ] UTs add/update 
- [x] ATF tests add/update ***(not required)***  
- [x] Manual tests ***(not required)*** 
- [x] Add/update CI plans/jobs ***(not required)***  
- [x] SDD updates ***(not required)***  
- [x] Guidelines update ([sdl_core_guides](https://github.com/smartdevicelink/sdl_core_guides)) ***(not required)***  
- [x] Guidelines update ([sdl_hmi_integration_guidelines](https://github.com/smartdevicelink/sdl_hmi_integration_guidelines))  ***(not required)***

**Comment by jacobkeeler** [comment]
@DrachenkoAnastasiia The same occurs with `SubscribeWayPoints` and `UnsubscribeWayPoints`. I've found that part of the reason for this is that [CSmartFactory.h](https://github.com/smartdevicelink/sdl_core/blob/aff7f09a4ec07becfb64dc78992580061d3342ff/src/components/formatters/include/formatters/CSmartFactory.h#L289) is unable to find the Schema for these three RPCs, but I do not know why they are missing from the list.

**Comment by jacobkeeler** [comment]
Despite there being several issues with the SDL HMI regarding this RPC (missing `code` and `appID` parameters in the `Navigation.GetWayPoints` response), this issue does not appear to be caused by anything in Core.
