### ISSUE TITLE
[Navigation] SDL does not respond info message in case GENERIC_ERROR watchdog timeout from HMI

### ISSUE THREAD

**Issue by DrachenkoAnastasiia** [smartdevicelink/sdl_core#990]
**Occurrence:**
Always

**Preconditions:**
1. Core and HMI started
2. SendLocation, ShowConstantTBT, UpdateTurnList, GetWayPoints, SubscribeWayPoints are allowed in Policy.

**Steps to reproduce:**
**Or:** (Go to atf folder -> Run command: ./start.sh ../ATF_Navigation_IsReady_no_response_single_RPC_no_response.lua)

1. Stop then start SDL
2. Init HMI, Send Navigation.IsReady from SDL to HMI
SDL->HMI(09:02:52) : {"id":5,"jsonrpc":"2.0","method":"Navigation.IsReady"}
3. HMI does not respond for Navigation during watchdog timeout
4. Connect mobile, start session, register app
5. Activate app
6. Send SendLocation request
{"appID":689314620,"latitudeDegrees":1.10,"longitudeDegrees":1.10}
7. Wait till watchdog timeout expried from HMI

**Actual result:**
SDL send
{"resultCode":"GENERIC_ERROR","success":false} 

**Expected result:**
SDL should send
{"resultCode":"GENERIC_ERROR","success":false, "info": Navigation component does not respond}
to mobile app.

**Environment:**
SDL repo: https://github.com/smartdevicelink/sdl_core.git
SDL branch: master
SDL commit: a6c32b4
HMI: https://github.com/LuxoftSDL/sdl_hmi: 01cb5b49883ed6288e34fcf7db24fd0439d08312
OS: Ubuntu 14.04 LTS

**Attachments:**
[Uploading att_issue#990.zip…]()

**Comment by jacobkeeler** [comment]
@DrachenkoAnastasiia It doesn't appear that the attachment that was supposed to be included in this issue was fully uploaded, the link is empty

**Comment by jacobkeeler** [comment]
Fixed with the merge of #1640
