### ISSUE TITLE
GetWayPoints: SDL does not reset the default watchdog timeout of GetWayPoints request if HMI sends OnResetTimeout notification for this request

### ISSUE THREAD

**Issue by DrachenkoAnastasiia** [smartdevicelink/sdl_core#991]
## Occurrence
Always

## Preconditions
ATF is configured to execute tests.
All related files are present in ATF directiry.

## Steps to reproduce
1. Execute ATF_GetWayPoints_OnResettimeout.lua (attached):
HMI sends OnResetTimeout after 8s aftyer GetWayPoints request from SDL (see "GetWayPoints_OnResetTimeout" test case).
==============>>>>

## Actual result
SDL does not reset watchdog timeout for GetWayPoints after receiving OnResetTimeout.

## Expected result
SDL should reset watchdog timeout for GetWayPoints after receiving OnResetTimeout.

# Environment
Release: 4.2.0 (master marge)
Repository: https://github.com/smartdevicelink/sdl_core
Commit: a6c32b45832653d6b851be9b19355fa35f377e07
ATF: 962e1eff8664d97af5e59ec4e22f39b9ea76f5eb

# Attachments
[att_issue#991.zip](https://github.com/smartdevicelink/sdl_core/files/576015/att_issue.991.zip)

# Expected delivery   
- [ ] Source code updates 
- [ ] Code comments 
- [ ] UTs add/update 
- [x] ATF tests add/update ***(not required)***  
- [x] Manual tests ***(not required)*** 
- [x] Add/update CI plans/jobs ***(not required)***  
- [x] SDD updates ***(not required)***  
- [x] Guidelines update ([sdl_core_guides](https://github.com/smartdevicelink/sdl_core_guides)) ***(not required)***  
- [x] Guidelines update ([sdl_hmi_integration_guidelines](https://github.com/smartdevicelink/sdl_hmi_integration_guidelines))  ***(not required)***

**Comment by jacobkeeler** [comment]
Fixed with the merge of #1633
