### ISSUE TITLE
CCB: Fix sdl sends query apps to the app

### ISSUE THREAD

**Issue by KhrystynaDubovyk** [smartdevicelink/sdl_core#995]
### Bug Report
SDL sends OnSystemRequest (QUERY_APPS) to the app after unsuccessful attempt 

##### Reproduction Steps
1. Make sure SDL4.0 feature is enabled in .ini file
2. Register app via 4th protocol.
3. App sends incorrect json on SystemRequest and receives error code in response.
4. Bring app to background and then to foreground again or register new app via 4th protocol.

##### Expected Behavior
SDL does not send OnSystemRequest(QUERY_APPS) to the same app after bringing it to foreground and also to new registered app after unsuccessful attempt to send query json.

##### Observed Behavior
SDL sends OnSystemRequest(QUERY_APPS) to the same app after bringing it to foreground and also to new registered app after unsuccessful attempt to send query json.

##### OS & Version Information
* OS/Version: Ubuntu 16.04
* SDL Core Version: 
* Testing Against: ATF

##### Test Case, Sample Code, and / or Example App
* [att_issue#995.zip](https://github.com/smartdevicelink/sdl_core/files/576054/att_issue.995.zip)

**Comment by vvvakulenko** [comment]
**Reproducible**
SDL: HEAD of https://github.com/smartdevicelink/sdl_core/tree/feature/extended_policy_functionality
(commit d5f63b4f66d9ab945d452dfb1c07bf7ee3ca781e)
ATF: HEAD of https://github.com/smartdevicelink/sdl_atf/tree/develop
(commit aa5beae6ab1726a9b43ed2fa15f66c20d7f7883f)

**Comment by LitvinenkoIra** [comment]
Priority Medium.
Loss of functionality on SDL side with standard use-case.

**Comment by GetmanetsIrina** [comment]
Defect is reproduced.
SDL branch: develop(2ec732c56e3f06b7043cf02cf98109720d6ff38a)
ATF: develop
Script: https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/1929

**Comment by Ypostolov** [comment]
@GetmanetsIrina 
Please update script for reproducing this issue (SLD considers invalid json from test script as a valid one).

**Comment by Ypostolov** [comment]
> @GetmanetsIrina
> Please update script for reproducing this issue (SLD considers invalid json from test script as a valid one).

Comment above not actual.

**Comment by LitvinenkoIra** [comment]
Defect is reproduced.
SDL branch: develop(e137556)
ATF: develop
Script: smartdevicelink/sdl_atf_test_scripts#1929

**Comment by LitvinenkoIra** [comment]
#2335 - rebased to the latest develop
Fix is partially valid

**Comment by LitvinenkoIra** [comment]
There was an atf test script issue,
After https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/1929/commits/3d0e1748ee3b99064a92a3b3c5c02819a99f64cb - script passed successfully, so the **fix from #2335 - is valid**

**Comment by LitvinenkoIra** [comment]
Full regression successfully passed
SDL: fix_sdl_sends_query_apps_to_t 15253302
Scripts: develop 6f43bfd
ATF: develop 37da7aba

**Comment by LitvinenkoIra** [comment]
@theresalech Please triage this issue

**Comment by theresalech** [comment]
@LitvinenkoIra We are currently working on finalizing the roadmap with the Steering Committee, so will keep this PR in consideration for upcoming Core releases.

**Comment by iCollin** [comment]
Closed via #2335
