### ISSUE TITLE
SDL returns IGNORED instead of UNSUPPORTED_RESOURCE for UnsubscribeButton

### ISSUE THREAD

**Issue by KhrystynaDubovyk** [smartdevicelink/sdl_core#998]
## Occurrence
Always.

## Preconditions
1. In file hmi_capabilities.json "SEARCH" button exists in capabilities.
2. Core, HMI are started.
3. SDL receives Buttons.GetCapabilities response. "SEARCH" button is not in list for supported buttons.

## Steps to reproduce
1. Send RPC UnsubscribeButton with buttonName = "SEARCH".

## Expected result
SDL shall return result_code: UNSUPPORTED_RESOURCE, success: false

## Actual result
SDL returns result_code: IGNORED, success: false.

**Note:**
Behaviour of SDL for RPC SubscribeButton in case not supported button is correct.

# Environment
Release: 4.2.0 (master marge)
Commit: a6c32b45832653d6b851be9b19355fa35f377e07
OS: Ubuntu 14.04 
Transport: WiFi 
App type: navi
App: Luxoft SPT
Device: HTC One 

# Attachments
[att_issue#998.zip](https://github.com/smartdevicelink/sdl_core/files/576080/att_issue.998.zip)

# Expected delivery   
- [ ] Source code updates 
- [ ] Code comments 
- [ ] UTs add/update 
- [x] ATF tests add/update ***(not required)***  
- [x] Manual tests ***(not required)*** 
- [x] Add/update CI plans/jobs ***(not required)***  
- [x] SDD updates ***(not required)***  
- [x] Guidelines update ([sdl_core_guides](https://github.com/smartdevicelink/sdl_core_guides)) ***(not required)***  
- [x] Guidelines update ([sdl_hmi_integration_guidelines](https://github.com/smartdevicelink/sdl_hmi_integration_guidelines))  ***(not required)***

**Comment by LevchenkoS** [comment]
Issue should be resolved after merge of PR #1358

**Comment by LevchenkoS** [comment]
#1358 Merged
